In [2]:
# !pip install yfinance
# !pip install TA-Lib 
# !pip install numpy
# !pip install pandas
# !pip install vectorbt
# !pip install scipy

In [3]:
import yfinance as yf
import talib
import numpy as np
import pandas as pd
import vectorbt as vbt
import warnings
from scipy import stats
import matplotlib.pyplot as plt

In [4]:
# DOWNLOAD STOCK DATA FROM 2018 USING YFINANCE

# Configuration - Change these variables as needed
TICKER = 'TQQQ'  # Any ticker symbol (e.g., 'AAPL', 'MSFT', 'GOOGL')
START_DATE = '2018-01-01'  # Any start date in YYYY-MM-DD format

# Download data from start date onwards
stock_data = yf.download(TICKER, start=START_DATE, interval='1d')

if not stock_data.empty:
    print(f"Successfully downloaded {len(stock_data)} records for {TICKER} from {START_DATE}")
    print(f"Data range: {stock_data.index.min().date()} to {stock_data.index.max().date()}")
    print("\nFirst 5 rows:")
    print(stock_data.head())
else:
    print(f"Failed to download {TICKER} data from yfinance")

# Display the downloaded data
stock_data

[*********************100%***********************]  1 of 1 completed

Successfully downloaded 2167 records for TQQQ from 2018-01-01
Data range: 2018-01-02 to 2026-08-17

First 5 rows:
Price          Close      High       Low      Open    Volume
Ticker          TQQQ      TQQQ      TQQQ      TQQQ      TQQQ
Date
2018-01-02  5.778714  5.790602  5.542953  5.582973  91735200
2018-01-03  5.947908  5.969702  5.801302  5.802094  85224000
2018-01-04  5.982775  6.039041  5.961775  6.017644  70024800
2018-01-05  6.163460  6.176536  6.035080  6.066383  82380000
2018-01-08  6.232009  6.244689  6.156725  6.162668  72252000

Price           Close       High        Low       Open    Volume
Ticker           TQQQ       TQQQ       TQQQ       TQQQ      TQQQ
Date
2018-01-02   5.778714   5.790602   5.542953   5.582973  91735200
2018-01-03   5.947908   5.969702   5.801302   5.802094  85224000
2018-01-04   5.982775   6.039041   5.961775   6.017644  70024800
2018-01-05   6.163460   6.176536   6.035080   6.066383  82380000
2018-01-08   6.232009   6.244689   6.156725   6.162668  72252000
...               ...        ...        ...        ...       ...
2026-08-11  73.059998  74.540001  72.239998  74.540001  43674100
2026-08-12  74.599998  75.690002  74.379997  75.620003  46867300
2026-08-13  77.150002  77.769997  74.709999  75.040001  49822600
2026-08-14  76.790001  77.849998  75.940002  77.570000  36616800
2026-08-17        NaN        NaN        NaN        NaN  39282074

[2167 rows x 5 columns]

In [5]:
# TECHNICAL ANALYSIS INDICATORS USING TA-LIB

# Make sure stock_data is available from the previous cell
if "stock_data" not in locals():
    raise ValueError("Please run the stock data download cell first")

# Extract OHLCV data (handling multi-level columns from yfinance)
if isinstance(stock_data.columns, pd.MultiIndex):
    close = stock_data[("Close", TICKER)].values
    high = stock_data[("High", TICKER)].values
    low = stock_data[("Low", TICKER)].values
    open_ = stock_data[("Open", TICKER)].values
    volume = stock_data[("Volume", TICKER)].values
else:
    close = stock_data["Close"].values
    high = stock_data["High"].values
    low = stock_data["Low"].values
    open_ = stock_data["Open"].values
    volume = stock_data["Volume"].values

print(f"Calculating technical indicators for {TICKER}...")

# Simple Moving Averages
sma_20 = talib.SMA(close, timeperiod=20)
sma_50 = talib.SMA(close, timeperiod=50)

# Exponential Moving Averages
ema_12 = talib.EMA(close, timeperiod=12)
ema_26 = talib.EMA(close, timeperiod=26)

# MACD
macd, macdsignal, macdhist = talib.MACD(close, fastperiod=12, slowperiod=26, signalperiod=9)

# RSI
rsi = talib.RSI(close, timeperiod=14)

# Stochastic RSI
stochrsi_k, stochrsi_d = talib.STOCHRSI(close, timeperiod=14, fastk_period=3, fastd_period=3, fastd_matype=0)

# VWAP (manual calculation)
typical_price = (high + low + close) / 3
price_volume = typical_price * volume
cumulative_price_volume = np.cumsum(price_volume)
cumulative_volume = np.cumsum(volume)
vwap = cumulative_price_volume / cumulative_volume

# Schaff Trend Cycle (defaults: EMA 23/50, stochastic cycle 10)
STC_EMA_SHORT = 23
STC_EMA_LONG = 50
STC_CYCLE_PERIOD = 10

stc_ema_short = talib.EMA(close, timeperiod=STC_EMA_SHORT)
stc_ema_long = talib.EMA(close, timeperiod=STC_EMA_LONG)
stc_macd = stc_ema_short - stc_ema_long

stc_macd_highest = talib.MAX(stc_macd, timeperiod=STC_CYCLE_PERIOD)
stc_macd_lowest = talib.MIN(stc_macd, timeperiod=STC_CYCLE_PERIOD)
stc_macd_denom = stc_macd_highest - stc_macd_lowest
with np.errstate(divide="ignore", invalid="ignore"):
    stc_k_macd = np.where(np.abs(stc_macd_denom) > 0, 100.0 * (stc_macd - stc_macd_lowest) / stc_macd_denom, 0.0)
stc_d_macd = talib.EMA(stc_k_macd, timeperiod=STC_CYCLE_PERIOD)

stc_d_highest = talib.MAX(stc_d_macd, timeperiod=STC_CYCLE_PERIOD)
stc_d_lowest = talib.MIN(stc_d_macd, timeperiod=STC_CYCLE_PERIOD)
stc_d_denom = stc_d_highest - stc_d_lowest
with np.errstate(divide="ignore", invalid="ignore"):
    stc_k = np.where(np.abs(stc_d_denom) > 0, 100.0 * (stc_d_macd - stc_d_lowest) / stc_d_denom, 0.0)
stc_d = talib.EMA(stc_k, timeperiod=STC_CYCLE_PERIOD)

# AROON
AROON_PERIOD = 14
if len(high) != len(close) or len(low) != len(close):
    raise ValueError("High, Low, and Close arrays must have the same length for AROON")
if len(close) <= AROON_PERIOD:
    raise ValueError(f"AROON requires more than {AROON_PERIOD} rows of OHLC data")
aroon_down, aroon_up = talib.AROON(
    high.astype(float, copy=False),
    low.astype(float, copy=False),
    timeperiod=AROON_PERIOD,
)

# KAMA (Kaufman Adaptive Moving Average — custom implementation for full parameter control)
KAMA_PERIOD = 10
KAMA_FAST_EMA_CONSTANT = 2
KAMA_SLOW_EMA_CONSTANT = 30


def validate_kama_params(period, fast_ema_constant, slow_ema_constant):
    try:
        period = int(period)
        fast_ema_constant = int(fast_ema_constant)
        slow_ema_constant = int(slow_ema_constant)
    except (TypeError, ValueError) as exc:
        raise ValueError(
            "KAMA parameters must be integers; "
            f"got period={period!r}, fast={fast_ema_constant!r}, slow={slow_ema_constant!r}"
        ) from exc
    if period <= 0 or fast_ema_constant <= 0 or slow_ema_constant <= 0:
        raise ValueError("KAMA parameters must be positive integers.")
    if fast_ema_constant >= slow_ema_constant:
        raise ValueError("KAMA fastest EMA constant must be less than slowest EMA constant.")
    return period, fast_ema_constant, slow_ema_constant


def _compute_kama_core(close, period, fast_ema_constant, slow_ema_constant):
    if close.dropna().shape[0] <= period:
        raise ValueError(f"KAMA requires more than {period} rows of close data")

    change = (close - close.shift(period)).abs()
    volatility = close.diff().abs().rolling(window=period).sum()
    er = change / (volatility + 1e-9)
    sc = (
        (er * (2 / (fast_ema_constant + 1) - 2 / (slow_ema_constant + 1)))
        + 2 / (slow_ema_constant + 1)
    ) ** 2
    sc = sc.clip(0, 1).fillna(0)

    kama_values = np.full(len(close), np.nan)
    seed = close.iloc[period]
    if pd.isna(seed):
        return pd.Series(kama_values, index=close.index)

    kama_values[period] = seed
    sc_values = sc.to_numpy(dtype=float)
    close_values = close.to_numpy(dtype=float)
    for i in range(period + 1, len(close)):
        if np.isnan(close_values[i]):
            kama_values[i] = np.nan
            continue
        prev = kama_values[i - 1]
        if np.isnan(prev):
            kama_values[i] = np.nan
            continue
        kama_values[i] = prev + sc_values[i] * (close_values[i] - prev)

    kama_values[:period] = np.nan
    return pd.Series(kama_values, index=close.index)


def compute_kama_series(close, period, fast_ema_constant, slow_ema_constant, index=None):
    period, fast_ema_constant, slow_ema_constant = validate_kama_params(
        period,
        fast_ema_constant,
        slow_ema_constant,
    )
    if not isinstance(close, pd.Series):
        if index is None:
            raise ValueError("index is required when close is not a Series")
        close = pd.Series(close, index=index)
    close = close.astype(float)
    return _compute_kama_core(close, period, fast_ema_constant, slow_ema_constant)


kama = compute_kama_series(
    close,
    KAMA_PERIOD,
    KAMA_FAST_EMA_CONSTANT,
    KAMA_SLOW_EMA_CONSTANT,
    index=stock_data.index,
).values

# SUPERTREND (ATR from TA-Lib + SuperTrend band/direction logic)
SUPERTREND_ATR_LENGTH = 10
SUPERTREND_FACTOR = 3


def validate_supertrend_params(atr_length, factor):
    try:
        atr_length_num = float(atr_length)
        factor_num = float(factor)
    except (TypeError, ValueError) as exc:
        raise ValueError(
            "SUPERTREND parameters must be numeric; "
            f"got atr_length={atr_length!r}, factor={factor!r}"
        ) from exc
    if not np.isfinite(atr_length_num) or not np.isfinite(factor_num):
        raise ValueError("SUPERTREND ATR length and factor must be finite numbers.")
    if atr_length_num != int(atr_length_num):
        raise ValueError(
            f"SUPERTREND ATR length must be an integer; got atr_length={atr_length!r}"
        )
    atr_length = int(atr_length_num)
    # Reject silent float truncation (e.g. 2.7 -> 2) while still allowing 3.0
    if factor_num != int(factor_num):
        raise ValueError(
            "SUPERTREND factor must be a whole number for this grid "
            f"(sensitivity uses int grids); got factor={factor!r}"
        )
    factor = int(factor_num)
    if atr_length <= 0 or factor <= 0:
        raise ValueError("SUPERTREND ATR length and factor must be positive integers.")
    return atr_length, factor


def _compute_supertrend_core(high, low, close, atr_length, factor):
    if len(high) != len(close) or len(low) != len(close):
        raise ValueError("High, Low, and Close arrays must have the same length for SUPERTREND")
    if len(close) == 0:
        raise ValueError("SUPERTREND requires a non-empty OHLC series")
    if len(close) <= atr_length:
        raise ValueError(f"SUPERTREND requires more than {atr_length} rows of OHLC data")

    high_arr = np.asarray(high, dtype=float)
    low_arr = np.asarray(low, dtype=float)
    close_arr = np.asarray(close, dtype=float)

    finite_mask = np.isfinite(high_arr) & np.isfinite(low_arr) & np.isfinite(close_arr)
    if not finite_mask.any():
        raise ValueError("SUPERTREND requires at least one finite OHLC row")
    if np.any(high_arr[finite_mask] < low_arr[finite_mask]):
        raise ValueError("SUPERTREND requires High >= Low on all finite rows")

    atr = talib.ATR(high_arr, low_arr, close_arr, timeperiod=atr_length)
    hl2 = (high_arr + low_arr) / 2.0
    basic_upper = hl2 + factor * atr
    basic_lower = hl2 - factor * atr

    final_upper = np.full(len(close_arr), np.nan)
    final_lower = np.full(len(close_arr), np.nan)
    supertrend = np.full(len(close_arr), np.nan)
    direction = np.full(len(close_arr), np.nan)

    for i in range(len(close_arr)):
        # Gap / bad bar: carry prior state forward so trend memory is not reset
        if (
            np.isnan(atr[i])
            or not np.isfinite(close_arr[i])
            or not np.isfinite(high_arr[i])
            or not np.isfinite(low_arr[i])
        ):
            if i > 0:
                final_upper[i] = final_upper[i - 1]
                final_lower[i] = final_lower[i - 1]
                direction[i] = direction[i - 1]
                supertrend[i] = supertrend[i - 1]
            continue

        if i == 0 or np.isnan(final_lower[i - 1]):
            final_lower[i] = basic_lower[i]
        elif basic_lower[i] > final_lower[i - 1] or close_arr[i - 1] < final_lower[i - 1]:
            final_lower[i] = basic_lower[i]
        else:
            final_lower[i] = final_lower[i - 1]

        if i == 0 or np.isnan(final_upper[i - 1]):
            final_upper[i] = basic_upper[i]
        elif basic_upper[i] < final_upper[i - 1] or close_arr[i - 1] > final_upper[i - 1]:
            final_upper[i] = basic_upper[i]
        else:
            final_upper[i] = final_upper[i - 1]

        # Seed first direction from bands, then prior-close momentum (avoid hl2 tie -> always +1)
        if i == 0 or np.isnan(direction[i - 1]):
            if close_arr[i] > final_upper[i]:
                direction[i] = 1.0
            elif close_arr[i] < final_lower[i]:
                direction[i] = -1.0
            elif i > 0 and np.isfinite(close_arr[i - 1]):
                direction[i] = 1.0 if close_arr[i] >= close_arr[i - 1] else -1.0
            else:
                direction[i] = 1.0 if close_arr[i] > hl2[i] else -1.0
        elif direction[i - 1] == 1.0:
            direction[i] = -1.0 if close_arr[i] < final_lower[i] else 1.0
        else:
            direction[i] = 1.0 if close_arr[i] > final_upper[i] else -1.0

        supertrend[i] = final_lower[i] if direction[i] == 1.0 else final_upper[i]

    return supertrend, direction


def compute_supertrend_series(high, low, close, atr_length, factor, index=None):
    atr_length, factor = validate_supertrend_params(atr_length, factor)
    if index is None:
        if isinstance(close, pd.Series):
            index = close.index
        else:
            raise ValueError("index is required when close is not a Series")
    if len(index) != len(np.asarray(close)):
        raise ValueError("SUPERTREND index length must match close length")
    supertrend, direction = _compute_supertrend_core(high, low, close, atr_length, factor)
    return (
        pd.Series(supertrend, index=index),
        pd.Series(direction, index=index),
    )


supertrend, supertrend_direction = compute_supertrend_series(
    high,
    low,
    close,
    SUPERTREND_ATR_LENGTH,
    SUPERTREND_FACTOR,
    index=stock_data.index,
)
supertrend = supertrend.values
supertrend_direction = supertrend_direction.values

# KALMAN (1D Kalman filter — custom implementation; Q=process noise, R=measurement noise)
KALMAN_PROCESS_NOISE = 1
KALMAN_MEASUREMENT_NOISE = 10


def validate_kalman_params(process_noise, measurement_noise):
    try:
        process_noise_num = float(process_noise)
        measurement_noise_num = float(measurement_noise)
    except (TypeError, ValueError) as exc:
        raise ValueError(
            "KALMAN parameters must be numeric; "
            f"got process_noise={process_noise!r}, measurement_noise={measurement_noise!r}"
        ) from exc
    if not np.isfinite(process_noise_num) or not np.isfinite(measurement_noise_num):
        raise ValueError("KALMAN process noise (Q) and measurement noise (R) must be finite numbers.")
    if process_noise_num != int(process_noise_num):
        raise ValueError(
            "KALMAN process noise (Q) must be a whole number for this grid "
            f"(sensitivity uses int grids); got process_noise={process_noise!r}"
        )
    if measurement_noise_num != int(measurement_noise_num):
        raise ValueError(
            "KALMAN measurement noise (R) must be a whole number for this grid "
            f"(sensitivity uses int grids); got measurement_noise={measurement_noise!r}"
        )
    process_noise = int(process_noise_num)
    measurement_noise = int(measurement_noise_num)
    if process_noise <= 0 or measurement_noise <= 0:
        raise ValueError("KALMAN process noise (Q) and measurement noise (R) must be positive integers.")
    return process_noise, measurement_noise


def _compute_kalman_core(close, process_noise, measurement_noise):
    close_arr = np.asarray(close, dtype=float)
    if close_arr.size == 0:
        raise ValueError("KALMAN requires a non-empty close series")
    if not np.isfinite(close_arr).any():
        raise ValueError("KALMAN requires at least one finite close price")

    kalman = np.full(close_arr.size, np.nan)
    q = float(process_noise)
    r = float(measurement_noise)

    first_idx = int(np.flatnonzero(np.isfinite(close_arr))[0])
    x = close_arr[first_idx]
    # Seed uncertainty from R so the first updates are not artificially overconfident
    p = float(measurement_noise)
    kalman[first_idx] = x

    for i in range(first_idx + 1, close_arr.size):
        z = close_arr[i]
        # Predict every bar (including gaps) so multi-bar holes inflate uncertainty
        p = p + q
        if not np.isfinite(z):
            # Carry estimate forward across gaps; do not update with bad measurements
            kalman[i] = x
            continue
        # Update: higher R trusts the filter prediction over noisy measurements
        k = p / (p + r)
        x = x + k * (z - x)
        p = (1.0 - k) * p
        kalman[i] = x

    return kalman


def compute_kalman_series(close, process_noise, measurement_noise, index=None):
    process_noise, measurement_noise = validate_kalman_params(process_noise, measurement_noise)
    if index is None:
        if isinstance(close, pd.Series):
            index = close.index
        else:
            raise ValueError("index is required when close is not a Series")
    if len(index) != len(np.asarray(close)):
        raise ValueError("KALMAN index length must match close length")
    kalman = _compute_kalman_core(close, process_noise, measurement_noise)
    return pd.Series(kalman, index=index)


kalman = compute_kalman_series(
    close,
    KALMAN_PROCESS_NOISE,
    KALMAN_MEASUREMENT_NOISE,
    index=stock_data.index,
).values

# ALMA (Arnaud Legoux Moving Average — custom implementation; TA-Lib has no ALMA)
# Offset is stored as hundredths (85 = 0.85) so sensitivity int-grids stay coherent.
ALMA_LENGTH = 9
ALMA_OFFSET = 85
ALMA_SIGMA = 6


def validate_alma_params(length, offset, sigma):
    try:
        length_num = float(length)
        offset_num = float(offset)
        sigma_num = float(sigma)
    except (TypeError, ValueError) as exc:
        raise ValueError(
            "ALMA parameters must be numeric; "
            f"got length={length!r}, offset={offset!r}, sigma={sigma!r}"
        ) from exc
    if not np.isfinite(length_num) or not np.isfinite(offset_num) or not np.isfinite(sigma_num):
        raise ValueError("ALMA length, offset, and sigma must be finite numbers.")
    if length_num != int(length_num):
        raise ValueError(
            "ALMA length must be a whole number for this grid "
            f"(sensitivity uses int grids); got length={length!r}"
        )
    if offset_num != int(offset_num):
        raise ValueError(
            "ALMA offset must be a whole number for this grid "
            f"(sensitivity uses int grids; offset is hundredths, e.g. 85 = 0.85); "
            f"got offset={offset!r}"
        )
    if sigma_num != int(sigma_num):
        raise ValueError(
            "ALMA sigma must be a whole number for this grid "
            f"(sensitivity uses int grids); got sigma={sigma!r}"
        )
    length = int(length_num)
    offset = int(offset_num)
    sigma = int(sigma_num)
    if length <= 1:
        raise ValueError("ALMA length must be an integer greater than 1.")
    # 0..100 hundredths maps to classic ALMA distribution offset [0.0, 1.0]
    if offset < 0 or offset > 100:
        raise ValueError("ALMA offset must be an integer in 0..100 (hundredths of the distribution offset).")
    if sigma <= 0:
        raise ValueError("ALMA sigma must be a positive integer.")
    return length, offset, sigma


def _compute_alma_core(close, length, offset, sigma):
    # Defensive guards so direct callers cannot hit ZeroDivisionError / bad shapes.
    if length <= 1:
        raise ValueError("ALMA length must be an integer greater than 1.")
    if sigma <= 0:
        raise ValueError("ALMA sigma must be a positive integer.")
    if offset < 0 or offset > 100:
        raise ValueError("ALMA offset must be an integer in 0..100 (hundredths of the distribution offset).")

    close_arr = np.asarray(close, dtype=float)
    if close_arr.size == 0:
        raise ValueError("ALMA requires a non-empty close series")
    if close_arr.size < length:
        raise ValueError(f"ALMA requires at least {length} rows of close data")
    if not np.isfinite(close_arr).any():
        raise ValueError("ALMA requires at least one finite close price")

    offset_f = offset / 100.0
    m = int(np.floor(offset_f * (length - 1)))
    s = length / float(sigma)
    idxs = np.arange(length, dtype=float)
    weights = np.exp(-((idxs - m) ** 2) / (2.0 * s * s))
    norm = weights.sum()
    if not np.isfinite(norm) or norm <= 0:
        raise ValueError("ALMA weights are degenerate for the selected parameters")

    # Vectorized weighted window (avoids Python per-bar loop on large grids).
    alma = np.full(close_arr.size, np.nan)
    windows = np.lib.stride_tricks.sliding_window_view(close_arr, window_shape=length)
    finite_mask = np.isfinite(windows).all(axis=1)
    if finite_mask.any():
        alma_vals = np.full(windows.shape[0], np.nan)
        alma_vals[finite_mask] = windows[finite_mask] @ weights / norm
        alma[length - 1:] = alma_vals

    return alma


def compute_alma_series(close, length, offset, sigma, index=None):
    length, offset, sigma = validate_alma_params(length, offset, sigma)
    if index is None:
        if isinstance(close, pd.Series):
            index = close.index
        else:
            raise ValueError("index is required when close is not a Series")
    if len(index) != len(np.asarray(close)):
        raise ValueError("ALMA index length must match close length")
    alma = _compute_alma_core(close, length, offset, sigma)
    return pd.Series(alma, index=index)


alma = compute_alma_series(
    close,
    ALMA_LENGTH,
    ALMA_OFFSET,
    ALMA_SIGMA,
    index=stock_data.index,
).values

# Create indicators dataframe
indicators_df = pd.DataFrame({
    "Date": stock_data.index,
    "Close": close,
    "SMA_20": sma_20,
    "SMA_50": sma_50,
    "EMA_12": ema_12,
    "EMA_26": ema_26,
    "MACD": macd,
    "MACD_Signal": macdsignal,
    "MACD_Hist": macdhist,
    "RSI": rsi,
    "StochRSI_K": stochrsi_k,
    "StochRSI_D": stochrsi_d,
    "VWAP": vwap,
    "STC_K": stc_k,
    "STC_D": stc_d,
    "AROON_Down": aroon_down,
    "AROON_Up": aroon_up,
    "KAMA": kama,
    "SUPERTREND": supertrend,
    "SUPERTREND_Direction": supertrend_direction,
    "KALMAN": kalman,
    "ALMA": alma,
})

print("All technical indicators calculated!")
print(f"Data shape: {indicators_df.shape}")
indicators_df.tail(5)

Calculating technical indicators for TQQQ...
All technical indicators calculated!
Data shape: (2167, 22)

,Date,Close,SMA_20,SMA_50,EMA_12,EMA_26,MACD,MACD_Signal,MACD_Hist,RSI,...,VWAP,STC_K,STC_D,AROON_Down,AROON_Up,KAMA,SUPERTREND,SUPERTREND_Direction,KALMAN,ALMA
2162,2026-08-11,73.059998,68.5960,73.866122,70.731378,70.720027,0.011350,-1.244960,1.256311,53.487632,...,19.075846,100.0,75.465535,35.714286,71.428571,69.372624,62.194070,1.0,72.138205,73.378488
2163,2026-08-12,74.599998,68.6040,73.641275,71.326550,71.007432,0.319118,-0.932145,1.251262,55.566428,...,19.082335,100.0,79.926347,28.571429,64.285714,70.509471,63.811093,1.0,72.803274,73.638167
2164,2026-08-13,77.150002,68.9245,73.443882,72.222466,71.462438,0.760028,-0.593710,1.353738,58.846298,...,19.089436,100.0,83.576102,21.428571,100.000000,71.791211,65.187482,1.0,73.977569,74.158672
2165,2026-08-14,76.790001,69.3875,73.252459,72.925163,71.857072,1.068091,-0.261350,1.329441,58.193220,...,19.094683,100.0,86.562265,14.285714,100.000000,72.626282,66.374738,1.0,74.737365,74.957050
2166,2026-08-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,7.142857,92.857143,NaN,66.374738,1.0,74.737365,NaN

In [6]:
# PREPARE PRICE SERIES

warnings.filterwarnings("ignore", message="Degrees of freedom <= 0 for slice", category=RuntimeWarning)
warnings.filterwarnings("ignore", message="invalid value encountered in scalar divide", category=RuntimeWarning)

# Expect stock_data and TICKER already exist
def select_close_series(df, ticker):
    if isinstance(df.columns, pd.MultiIndex):
        if ('Close', ticker) in df.columns:
            s = df[('Close', ticker)]
        else:
            cols = [c for c in df.columns if 'Close' in str(c)]
            if not cols:
                raise KeyError("Close not found")
            s = df[cols[0]]
    else:
        s = df['Close']
    return s.astype(float).squeeze()

close = select_close_series(stock_data, TICKER)
close.name = 'price'

# Simple split
TRAIN_RATIO = 0.60 
split_idx = int(len(close) * TRAIN_RATIO)
train_close = close.iloc[:split_idx].copy()
val_close   = close.iloc[split_idx:].copy()

print(f"Data ready: train={train_close.index[0].date()} → {train_close.index[-1].date()} | val={val_close.index[0].date()} → {val_close.index[-1].date()}")

# Auto-detect market calendar from actual bars/year in the data
_calendar_days = max((close.index[-1] - close.index[0]).days, 1)
_bars_per_year = len(close) / (_calendar_days / 365.25)
IS_24_7_MARKET = _bars_per_year > 330
TRADING_DAYS_PER_YEAR = 365 if IS_24_7_MARKET else 252
YEAR_FREQ = f"{TRADING_DAYS_PER_YEAR}D"
FREQ = "1D"


def sample_years(price_series):
    return max(len(price_series) / TRADING_DAYS_PER_YEAR, 1e-9)


market_label = 'crypto (365-day)' if IS_24_7_MARKET else 'stock (252-day)'
print(f"Bars/year: {_bars_per_year:.0f} → FREQ='{FREQ}', YEAR_FREQ='{YEAR_FREQ}' ({market_label})")

Data ready: train=2018-01-02 → 2023-03-02 | val=2023-03-03 → 2026-08-17
Bars/year: 251 → FREQ='1D', YEAR_FREQ='252D' (stock (252-day))

MULTI-INDICATOR GRID SEARCH - TRAINING SET
------------------------------------------

This section performs grid search optimization for multiple technical indicators using only the **training data**.

The existing **Triple EMA Crossover Strategy** remains active, and this notebook adds **MACD Crossover Strategy**, **AROON Crossover Strategy**, **STC Trend Strategy**, **KAMA Crossover Strategy**, **SUPERTREND Strategy**, **KALMAN Strategy**, **RSI Strategy**, **ADX Strategy**, **DONCHIAN Strategy**, **TRIX Strategy**, **VORTEX Strategy**, and **ALMA Crossover Strategy** as separate grids. Each indicator owns its own parameter grid and signal builder, so Triple EMA, MACD, AROON, STC, KAMA, SUPERTREND, KALMAN, RSI, ADX, DONCHIAN, TRIX, VORTEX, and ALMA parameters are never combined into one search grid.

**Triple EMA Strategy Logic**: Buy when any EMA crosses above another (EMA1 > EMA2, EMA1 > EMA3, or EMA2 > EMA3). Sell when any EMA crosses below another.

**MACD Strategy Logic**: Buy when the MACD line crosses above the MACD signal line. Sell when the MACD line crosses below the MACD signal line.

**AROON Strategy Logic**: Aroon via TA-Lib (`talib.AROON`, timeperiod). Buy when Aroon Up crosses above Aroon Down and Aroon Up is strictly above `AROON_ENTRY_LEVEL`. Sell when Aroon Down crosses above Aroon Up. Grid search optimizes the AROON timeperiod independently.

**STC Strategy Logic**: Schaff Trend Cycle uses a custom MACD (fast EMA minus slow EMA) with a double-smoothed stochastic over the cycle period. Buy when the STC line crosses above 50. Sell when the STC line crosses below 50. Grid search optimizes the fast EMA length, slow EMA length, and cycle period.

**KAMA Strategy Logic**: Kaufman Adaptive Moving Average via a custom implementation (period, fastest EMA constant, slowest EMA constant). Buy when price crosses from below to above the KAMA line (shift into a new uptrend). Sell when price crosses from above to below the KAMA line (shift into a new downtrend). Grid search optimizes all three parameters independently.

**SUPERTREND Strategy Logic**: SuperTrend built from TA-Lib ATR (ATR length and factor/multiplier). Buy when price closes above a red SuperTrend line (line flips below price and turns green). Sell when price closes below a green SuperTrend line (line flips above price and turns red). Grid search optimizes ATR length and factor independently.

**KALMAN Strategy Logic**: 1D Kalman filter (process noise Q, measurement noise R). Higher Q makes the filter more responsive to price changes; higher R trusts the filter prediction over noisy measurements. Buy when price crosses from below to above the Kalman filter line. Sell when price crosses from above to below the Kalman filter line. Grid search optimizes Q and R independently.

**RSI Strategy Logic**: Relative Strength Index via TA-Lib (`talib.RSI`, timeperiod). Buy when the RSI crosses above 50, confirming rising bullish momentum. Sell when the RSI crosses below 50, confirming increasing bearish momentum. Grid search optimizes the RSI timeperiod independently.

**ADX Strategy Logic**: Directional Movement via TA-Lib (`talib.PLUS_DI`, `talib.MINUS_DI` for DI length) with ADX as Wilder-smoothed DX over the ADX smoothing timeperiod (so both parameters stay coherent). Buy when +DI crosses above -DI while ADX is above `ADX_TREND_LEVEL` (25, confirming a strong uptrend). Sell when -DI crosses above +DI while ADX is above `ADX_TREND_LEVEL` (confirming a strong downtrend). Grid search optimizes DI length and ADX smoothing independently.

**DONCHIAN Strategy Logic**: Donchian Channel built from TA-Lib (`talib.MAX` / `talib.MIN` over timeperiod for upper/lower bands; middle = average of the two — TA-Lib has no dedicated Donchian function). Buy when close crosses above the prior upper band (breakout to ride an upward trend). Sell when close crosses below the prior middle band (trailing stop to lock in profits). Grid search optimizes the Donchian timeperiod independently.

**TRIX Strategy Logic**: Triple Exponential Average via TA-Lib (`talib.TRIX`, timeperiod). Buy when the TRIX line crosses above zero, indicating bullish momentum and a potential buy signal. Sell when the TRIX line crosses below zero, suggesting bearish momentum and a potential sell signal. Grid search optimizes the TRIX timeperiod independently.

**VORTEX Strategy Logic**: Vortex Indicator built from TA-Lib helpers (`talib.TRANGE` / `talib.SUM` over timeperiod for VI+ and VI- — TA-Lib has no dedicated Vortex function). Buy when the VI+ line crosses upward from below the VI- line. Sell when the VI- line crosses upward from below the VI+ line. Grid search optimizes the VORTEX timeperiod independently.

**ALMA Strategy Logic**: Arnaud Legoux Moving Average via a custom implementation (TA-Lib has no ALMA; fast length, slow length, offset, sigma). Offset is stored as hundredths of the distribution offset in 0..100 (e.g. 85 = 0.85) so sensitivity int-grids stay coherent. Buy when the fast ALMA crosses above the slow ALMA, indicating an emerging bullish trend. Sell when the fast ALMA crosses below the slow ALMA, indicating a shifting bearish trend. Grid search optimizes fast length, slow length, offset, and sigma independently.

---

In [7]:
# Define Indicator Grids

# Existing Triple EMA grid. MACD, AROON, STC, KAMA, SUPERTREND, KALMAN, RSI, ADX, DONCHIAN, TRIX, VORTEX, and ALMA are added below as separate grids; parameters are not mixed.
ema1_periods = list(range(4, 10, 1))    # Fast EMA (shortest-term)
ema2_periods = list(range(90, 200, 1))  # Medium EMA
ema3_periods = list(range(120, 250, 1)) # Slow EMA

# MACD periods for crossover strategy
macd_fast_periods = list(range(10, 50, 1))
macd_slow_periods = list(range(60, 100, 1))
macd_signal_periods = list(range(40, 120, 1))

# AROON timeperiods for Up/Down crossover strategy
aroon_timeperiods = list(range(4, 80, 1))
AROON_ENTRY_LEVEL = 49

# STC EMA and cycle periods for Schaff Trend Cycle strategy
stc_ema_short_periods = list(range(10, 50, 1))
stc_ema_long_periods = list(range(60, 100, 1))
stc_cycle_periods = list(range(20, 100, 1))
STC_BUY_LEVEL = 50
STC_SELL_LEVEL = 50

# KAMA periods and EMA constants for price crossover strategy
kama_periods = list(range(5, 30, 5))
kama_fast_ema_constants = list(range(2, 40, 1))
kama_slow_ema_constants = list(range(60, 100, 1))

# SUPERTREND ATR length and factor/multiplier for trend-flip strategy
supertrend_atr_lengths = list(range(4, 112, 1))
supertrend_factors = list(range(1, 60, 1))

# KALMAN process noise (Q) and measurement noise (R) for price vs filter strategy
kalman_process_noise_values = list(range(1, 5, 1))
kalman_measurement_noise_values = list(range(100, 160, 1))

# RSI timeperiods for midline crossover strategy
rsi_timeperiods = list(range(40, 80, 1))
RSI_CROSS_LEVEL = 50

# ADX DI length and smoothing timeperiods for +DI/-DI crossover with trend-strength filter
adx_di_lengths = list(range(4, 60, 1))
adx_smoothing_timeperiods = list(range(20, 80, 1))
ADX_TREND_LEVEL = 20

# DONCHIAN timeperiods for upper-band breakout / middle-band trailing-stop strategy
donchian_timeperiods = list(range(10, 60, 1))

# TRIX timeperiods for zero-line crossover strategy
trix_timeperiods = list(range(4, 80, 1))
TRIX_CROSS_LEVEL = 0

# VORTEX timeperiods for VI+/VI- crossover strategy
vortex_timeperiods = list(range(40, 140, 1))

# ALMA fast/slow lengths / offset (hundredths) / sigma for ALMA crossover strategy
alma_fast_lengths = list(range(2, 40, 1))
alma_slow_lengths = list(range(60, 100, 1))
alma_offsets = list(range(10, 20, 2))
alma_sigmas = list(range(1, 10, 2))


def validate_triple_ema_params(ema1_period, ema2_period, ema3_period):
    ema1_period = int(ema1_period)
    ema2_period = int(ema2_period)
    ema3_period = int(ema3_period)
    if ema1_period <= 0 or ema2_period <= 0 or ema3_period <= 0:
        raise ValueError("EMA periods must be positive integers.")
    if not (ema1_period <= ema2_period <= ema3_period):
        raise ValueError("EMA periods must be ordered as EMA1 <= EMA2 <= EMA3.")
    return ema1_period, ema2_period, ema3_period


_ema_series_cache = {}


def get_ema_series(close_series, period):
    cache_key = (id(close_series), int(period))
    if cache_key not in _ema_series_cache:
        ema = vbt.MA.run(close_series, int(period), ewm=True).ma
        _ema_series_cache[cache_key] = pd.Series(ema.values.flatten(), index=close_series.index)
    return _ema_series_cache[cache_key]


def build_triple_ema_signals(close_series, params, shift_signals=True):
    ema1_period, ema2_period, ema3_period = validate_triple_ema_params(
        params["ema1_period"],
        params["ema2_period"],
        params["ema3_period"]
    )
    ema1 = get_ema_series(close_series, ema1_period)
    ema2 = get_ema_series(close_series, ema2_period)
    ema3 = get_ema_series(close_series, ema3_period)

    entries = (
        ema1.vbt.crossed_above(ema2) |
        ema1.vbt.crossed_above(ema3) |
        ema2.vbt.crossed_above(ema3)
    ).reindex(close_series.index).fillna(False)
    exits = (
        ema1.vbt.crossed_below(ema2) |
        ema1.vbt.crossed_below(ema3) |
        ema2.vbt.crossed_below(ema3)
    ).reindex(close_series.index).fillna(False)

    if shift_signals:
        entries = entries.shift(1).fillna(False)
        exits = exits.shift(1).fillna(False)

    return (
        pd.Series(entries.to_numpy(dtype=bool), index=close_series.index, dtype=bool),
        pd.Series(exits.to_numpy(dtype=bool), index=close_series.index, dtype=bool)
    )


def format_triple_ema_params(params):
    return f"EMA({params['ema1_period']},{params['ema2_period']},{params['ema3_period']})"


def validate_macd_params(fast_period, slow_period, signal_period):
    fast_period = int(fast_period)
    slow_period = int(slow_period)
    signal_period = int(signal_period)
    if fast_period <= 0 or slow_period <= 0 or signal_period <= 0:
        raise ValueError("MACD periods must be positive integers.")
    if fast_period >= slow_period:
        raise ValueError("MACD fast period must be less than slow period.")
    return fast_period, slow_period, signal_period


def compute_macd(close_series, fast_period, slow_period, signal_period):
    fast_period, slow_period, signal_period = validate_macd_params(
        fast_period,
        slow_period,
        signal_period
    )
    close_series = pd.Series(close_series, index=close_series.index).astype(float)
    if close_series.dropna().shape[0] < slow_period + signal_period:
        raise ValueError("Not enough price bars to compute MACD for the selected periods.")

    macd_line_arr, macd_signal_arr, macd_hist_arr = talib.MACD(
        close_series.to_numpy(dtype=float),
        fastperiod=fast_period,
        slowperiod=slow_period,
        signalperiod=signal_period
    )
    return (
        pd.Series(macd_line_arr, index=close_series.index),
        pd.Series(macd_signal_arr, index=close_series.index),
        pd.Series(macd_hist_arr, index=close_series.index)
    )


def build_macd_signals(close_series, params, shift_signals=True):
    macd_line, macd_signal_line, macd_hist = compute_macd(
        close_series,
        params["macd_fast_period"],
        params["macd_slow_period"],
        params["macd_signal_period"]
    )
    entries = macd_line.vbt.crossed_above(macd_signal_line).reindex(close_series.index).fillna(False)
    exits = macd_line.vbt.crossed_below(macd_signal_line).reindex(close_series.index).fillna(False)

    if shift_signals:
        entries = entries.shift(1).fillna(False)
        exits = exits.shift(1).fillna(False)

    return (
        pd.Series(entries.to_numpy(dtype=bool), index=close_series.index, dtype=bool),
        pd.Series(exits.to_numpy(dtype=bool), index=close_series.index, dtype=bool)
    )


def format_macd_params(params):
    return (
        f"MACD({params['macd_fast_period']},"
        f"{params['macd_slow_period']},"
        f"{params['macd_signal_period']})"
    )


# AROON Up/Down crossover strategy (TA-Lib AROON timeperiod)
def validate_aroon_params(timeperiod):
    try:
        timeperiod_num = float(timeperiod)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"AROON timeperiod must be numeric; got timeperiod={timeperiod!r}") from exc
    if not np.isfinite(timeperiod_num):
        raise ValueError("AROON timeperiod must be a finite number.")
    if timeperiod_num != int(timeperiod_num):
        raise ValueError(
            "AROON timeperiod must be a whole number for this grid "
            f"(sensitivity uses int grids); got timeperiod={timeperiod!r}"
        )
    timeperiod = int(timeperiod_num)
    if timeperiod <= 0:
        raise ValueError("AROON timeperiod must be a positive integer.")
    return timeperiod


def validate_aroon_entry_level(level):
    try:
        level_num = float(level)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"AROON entry level must be numeric; got level={level!r}") from exc
    if not np.isfinite(level_num):
        raise ValueError("AROON entry level must be a finite number.")
    if not 0.0 <= level_num <= 100.0:
        raise ValueError(
            f"AROON entry level must be between 0 and 100 (Aroon scale); got {level_num}."
        )
    return level_num


AROON_ENTRY_LEVEL = validate_aroon_entry_level(AROON_ENTRY_LEVEL)


_aroon_ohlc_cache = {}
_aroon_series_cache = {}


def get_aroon_ohlc(close_series):
    if "stock_data" not in globals() or "TICKER" not in globals():
        raise ValueError("stock_data/TICKER are missing. Run the download and prepare cells first.")
    if "_select_ohlc_column" not in globals():
        raise ValueError(
            "Shared OHLC helper `_select_ohlc_column` is missing. "
            "Run the full Define Indicator Grids cell (SUPERTREND section included)."
        )
    if close_series is None or len(close_series) == 0:
        raise ValueError("AROON close_series is empty.")

    cache_key = id(close_series)
    if cache_key in _aroon_ohlc_cache:
        return _aroon_ohlc_cache[cache_key]

    price_index = pd.DatetimeIndex(close_series.index)
    if price_index.tz is not None:
        price_index = price_index.tz_localize(None)

    high = _select_ohlc_column(stock_data, TICKER, "High")
    low = _select_ohlc_column(stock_data, TICKER, "Low")
    if isinstance(high.index, pd.DatetimeIndex) and high.index.tz is not None:
        high = high.copy()
        high.index = high.index.tz_localize(None)
    if isinstance(low.index, pd.DatetimeIndex) and low.index.tz is not None:
        low = low.copy()
        low.index = low.index.tz_localize(None)

    high = high.reindex(price_index)
    low = low.reindex(price_index)
    close = pd.Series(
        pd.Series(close_series).astype(float).to_numpy(),
        index=price_index,
        name=getattr(close_series, "name", None),
    )

    finite_close = np.isfinite(close.to_numpy(dtype=float))
    if not finite_close.any():
        raise ValueError("AROON close_series contains no finite prices.")
    valid_mask = pd.Series(finite_close, index=close.index)
    high_vals = high.loc[valid_mask].to_numpy(dtype=float)
    low_vals = low.loc[valid_mask].to_numpy(dtype=float)
    if (not np.isfinite(high_vals).all()) or (not np.isfinite(low_vals).all()):
        raise ValueError(
            "High/Low data is missing or non-finite for one or more dates in the selected price series."
        )
    if (high_vals < low_vals).any():
        raise ValueError("AROON requires High >= Low on all valid close dates.")

    _aroon_ohlc_cache[cache_key] = (high, low, close)
    return _aroon_ohlc_cache[cache_key]


def compute_aroon(close_series, timeperiod):
    timeperiod = validate_aroon_params(timeperiod)
    if close_series is None or len(close_series) == 0:
        raise ValueError("AROON close_series is empty.")
    cache_key = (id(close_series), timeperiod)
    if cache_key in _aroon_series_cache:
        return _aroon_series_cache[cache_key]

    high, low, close = get_aroon_ohlc(close_series)
    finite_bars = int(np.isfinite(close.to_numpy(dtype=float)).sum())
    if finite_bars <= timeperiod:
        raise ValueError("Not enough price bars to compute AROON for the selected timeperiod.")

    try:
        aroon_down_arr, aroon_up_arr = talib.AROON(
            high.to_numpy(dtype=float),
            low.to_numpy(dtype=float),
            timeperiod=timeperiod,
        )
    except Exception as exc:
        raise ValueError(
            f"talib.AROON failed for timeperiod={timeperiod}: {type(exc).__name__}: {exc}"
        ) from exc

    aroon_up = pd.Series(aroon_up_arr, index=close.index)
    aroon_down = pd.Series(aroon_down_arr, index=close.index)
    if (~(aroon_up.isna() | aroon_down.isna())).sum() == 0:
        raise ValueError("AROON could not be computed for the selected parameter combination.")

    _aroon_series_cache[cache_key] = (aroon_up, aroon_down)
    return _aroon_series_cache[cache_key]


def build_aroon_signals(close_series, params, shift_signals=True):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for AROON, got {type(params).__name__}.")
    missing_keys = [key for key in ("aroon_timeperiod",) if key not in params]
    if missing_keys:
        raise KeyError(f"AROON params missing keys: {missing_keys}")
    if "AROON_ENTRY_LEVEL" not in globals():
        raise ValueError("AROON_ENTRY_LEVEL is missing. Re-run the Define Indicator Grids cell.")
    entry_level = validate_aroon_entry_level(AROON_ENTRY_LEVEL)

    aroon_up, aroon_down = compute_aroon(close_series, params["aroon_timeperiod"])
    # Require both lines valid on this bar and the prior bar so TA-Lib warmup NaNs
    # do not register as false Up/Down crosses (same pattern as KAMA/RSI).
    valid = aroon_up.notna() & aroon_down.notna()
    valid_cross = valid & valid.shift(1).fillna(False)
    # Entry trigger: Up crosses above Down, and Up is strictly above the entry level.
    entries = (
        aroon_up.vbt.crossed_above(aroon_down)
        & (aroon_up > entry_level)
        & valid_cross
    ).fillna(False)
    exits = (aroon_down.vbt.crossed_above(aroon_up) & valid_cross).fillna(False)

    if shift_signals:
        entries = entries.shift(1).fillna(False)
        exits = exits.shift(1).fillna(False)

    return (
        pd.Series(entries.to_numpy(dtype=bool), index=close_series.index, dtype=bool),
        pd.Series(exits.to_numpy(dtype=bool), index=close_series.index, dtype=bool),
    )


def format_aroon_params(params):
    return f"AROON({params['aroon_timeperiod']})"


def validate_aroon_sensitivity_params(timeperiod, timeperiod_anchor_a, timeperiod_anchor_b):
    timeperiod = validate_aroon_params(timeperiod)
    try:
        anchor_a = int(timeperiod_anchor_a)
        anchor_b = int(timeperiod_anchor_b)
    except (TypeError, ValueError) as exc:
        raise ValueError(
            "AROON sensitivity anchors must be integers matching the timeperiod."
        ) from exc
    if anchor_a != timeperiod or anchor_b != timeperiod:
        raise ValueError("AROON sensitivity anchors must match the timeperiod.")
    return timeperiod, timeperiod, timeperiod


# STC Schaff Trend Cycle strategy (EMA short/long + cycle period)
def validate_stc_params(ema_short, ema_long, cycle_period):
    ema_short = int(ema_short)
    ema_long = int(ema_long)
    cycle_period = int(cycle_period)
    if ema_short <= 0 or ema_long <= 0 or cycle_period <= 0:
        raise ValueError("STC periods must be positive integers.")
    if ema_short >= ema_long:
        raise ValueError("STC short EMA period must be less than long EMA period.")
    return ema_short, ema_long, cycle_period


def compute_stc(close_series, ema_short, ema_long, cycle_period):
    ema_short, ema_long, cycle_period = validate_stc_params(ema_short, ema_long, cycle_period)
    close = np.asarray(close_series, dtype=float)
    stc_ema_short = talib.EMA(close, timeperiod=ema_short)
    stc_ema_long = talib.EMA(close, timeperiod=ema_long)
    stc_macd = stc_ema_short - stc_ema_long

    stc_macd_highest = talib.MAX(stc_macd, timeperiod=cycle_period)
    stc_macd_lowest = talib.MIN(stc_macd, timeperiod=cycle_period)
    stc_macd_denom = stc_macd_highest - stc_macd_lowest
    with np.errstate(divide="ignore", invalid="ignore"):
        stc_k_macd = np.where(
            np.abs(stc_macd_denom) > 0,
            100.0 * (stc_macd - stc_macd_lowest) / stc_macd_denom,
            0.0,
        )
    stc_d_macd = talib.EMA(stc_k_macd, timeperiod=cycle_period)

    stc_d_highest = talib.MAX(stc_d_macd, timeperiod=cycle_period)
    stc_d_lowest = talib.MIN(stc_d_macd, timeperiod=cycle_period)
    stc_d_denom = stc_d_highest - stc_d_lowest
    with np.errstate(divide="ignore", invalid="ignore"):
        stc = np.where(
            np.abs(stc_d_denom) > 0,
            100.0 * (stc_d_macd - stc_d_lowest) / stc_d_denom,
            0.0,
        )
    stc = pd.Series(stc, index=close_series.index).replace([np.inf, -np.inf], np.nan)
    return stc


def build_stc_signals_from_series(
    stc,
    buy_level=STC_BUY_LEVEL,
    sell_level=STC_SELL_LEVEL,
    shift_signals=True,
):
    entries = (stc > buy_level) & (stc.shift(1) <= buy_level)
    exits = (stc < sell_level) & (stc.shift(1) >= sell_level)

    if shift_signals:
        entries = entries.shift(1).fillna(False)
        exits = exits.shift(1).fillna(False)

    return (
        pd.Series(entries.to_numpy(dtype=bool), index=stc.index, dtype=bool),
        pd.Series(exits.to_numpy(dtype=bool), index=stc.index, dtype=bool),
    )


def build_stc_signals(close_series, params, shift_signals=True):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for STC, got {type(params).__name__}.")
    missing_keys = [
        key
        for key in ("stc_ema_short_period", "stc_ema_long_period", "stc_cycle_period")
        if key not in params
    ]
    if missing_keys:
        raise KeyError(f"STC params missing keys: {missing_keys}")

    ema_short, ema_long, cycle_period = validate_stc_params(
        params["stc_ema_short_period"],
        params["stc_ema_long_period"],
        params["stc_cycle_period"],
    )
    stc = compute_stc(close_series, ema_short, ema_long, cycle_period)
    if stc.notna().sum() == 0:
        raise ValueError("STC could not be computed for the selected parameter combination.")
    return build_stc_signals_from_series(stc, shift_signals=shift_signals)


def format_stc_params(params):
    return (
        f"STC({params['stc_ema_short_period']},"
        f"{params['stc_ema_long_period']},"
        f"{params['stc_cycle_period']})"
    )


# KAMA price crossover strategy (custom KAMA: period + fastest/slowest EMA constants)
if (
    "validate_kama_params" not in globals()
    or "_compute_kama_core" not in globals()
):
    raise ValueError("KAMA helpers are missing. Run the TA-Lib indicator cell first.")


_kama_series_cache = {}


def get_kama_series(close_series, period, fast_ema_constant, slow_ema_constant):
    period, fast_ema_constant, slow_ema_constant = validate_kama_params(
        period,
        fast_ema_constant,
        slow_ema_constant,
    )
    cache_key = (id(close_series), period, fast_ema_constant, slow_ema_constant)
    if cache_key not in _kama_series_cache:
        close = pd.Series(close_series, index=close_series.index).astype(float)
        kama_line = _compute_kama_core(
            close,
            period,
            fast_ema_constant,
            slow_ema_constant,
        )
        if kama_line.notna().sum() == 0:
            raise ValueError("KAMA could not be computed for the selected parameter combination.")
        _kama_series_cache[cache_key] = (close, kama_line)
    return _kama_series_cache[cache_key]


def build_kama_signals(close_series, params, shift_signals=True):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for KAMA, got {type(params).__name__}.")
    missing_keys = [
        key
        for key in ("kama_period", "kama_fast_ema_constant", "kama_slow_ema_constant")
        if key not in params
    ]
    if missing_keys:
        raise KeyError(f"KAMA params missing keys: {missing_keys}")

    close, kama_line = get_kama_series(
        close_series,
        params["kama_period"],
        params["kama_fast_ema_constant"],
        params["kama_slow_ema_constant"],
    )
    valid_kama = kama_line.notna()
    valid_cross = valid_kama & valid_kama.shift(1).fillna(False)
    entries = (close.vbt.crossed_above(kama_line) & valid_cross).fillna(False)
    exits = (close.vbt.crossed_below(kama_line) & valid_cross).fillna(False)

    if shift_signals:
        entries = entries.shift(1).fillna(False)
        exits = exits.shift(1).fillna(False)

    return (
        pd.Series(entries.to_numpy(dtype=bool), index=close.index, dtype=bool),
        pd.Series(exits.to_numpy(dtype=bool), index=close.index, dtype=bool),
    )


def format_kama_params(params):
    return (
        f"KAMA({params['kama_period']},"
        f"{params['kama_fast_ema_constant']},"
        f"{params['kama_slow_ema_constant']})"
    )


# SUPERTREND trend-flip strategy (ATR length + factor/multiplier via TA-Lib ATR)
if (
    "validate_supertrend_params" not in globals()
    or "_compute_supertrend_core" not in globals()
):
    raise ValueError("SUPERTREND helpers are missing. Run the TA-Lib indicator cell first.")


_supertrend_ohlc_cache = {}
_supertrend_series_cache = {}


def _select_ohlc_column(df, ticker, column_name):
    if isinstance(df.columns, pd.MultiIndex):
        key = (column_name, ticker)
        if key in df.columns:
            series = df[key]
        else:
            # Exact level match only — avoid substring false positives like "HigherHigh"
            cols = [
                c for c in df.columns
                if isinstance(c, tuple) and len(c) >= 1 and c[0] == column_name
            ]
            if not cols:
                raise KeyError(f"{column_name} not found for ticker {ticker!r}")
            series = df[cols[0]]
    else:
        if column_name not in df.columns:
            raise KeyError(f"{column_name} not found in stock_data columns")
        series = df[column_name]
    return pd.Series(series.astype(float).to_numpy(), index=series.index, name=column_name)


def get_supertrend_ohlc(close_series):
    if "stock_data" not in globals() or "TICKER" not in globals():
        raise ValueError("stock_data/TICKER are missing. Run the download and prepare cells first.")
    if close_series is None or len(close_series) == 0:
        raise ValueError("SUPERTREND close_series is empty.")

    cache_key = id(close_series)
    if cache_key in _supertrend_ohlc_cache:
        return _supertrend_ohlc_cache[cache_key]

    high = _select_ohlc_column(stock_data, TICKER, "High").reindex(close_series.index)
    low = _select_ohlc_column(stock_data, TICKER, "Low").reindex(close_series.index)
    close = pd.Series(close_series, index=close_series.index).astype(float)

    valid_close = close.notna()
    if not valid_close.any():
        raise ValueError("SUPERTREND close_series contains no finite prices.")
    if high.loc[valid_close].isna().any() or low.loc[valid_close].isna().any():
        raise ValueError(
            "High/Low data is missing for one or more dates in the selected price series."
        )
    if (high.loc[valid_close] < low.loc[valid_close]).any():
        raise ValueError("SUPERTREND requires High >= Low on all valid close dates.")

    _supertrend_ohlc_cache[cache_key] = (high, low, close)
    return _supertrend_ohlc_cache[cache_key]


def get_supertrend_series(close_series, atr_length, factor):
    atr_length, factor = validate_supertrend_params(atr_length, factor)
    cache_key = (id(close_series), atr_length, factor)
    if cache_key not in _supertrend_series_cache:
        high, low, close = get_supertrend_ohlc(close_series)
        supertrend_line, direction = _compute_supertrend_core(
            high.to_numpy(dtype=float),
            low.to_numpy(dtype=float),
            close.to_numpy(dtype=float),
            atr_length,
            factor,
        )
        supertrend_line = pd.Series(supertrend_line, index=close.index)
        direction = pd.Series(direction, index=close.index)
        if direction.notna().sum() == 0:
            raise ValueError("SUPERTREND could not be computed for the selected parameter combination.")
        _supertrend_series_cache[cache_key] = (close, supertrend_line, direction)
    return _supertrend_series_cache[cache_key]


def build_supertrend_signals(close_series, params, shift_signals=True):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for SUPERTREND, got {type(params).__name__}.")
    missing_keys = [
        key
        for key in ("supertrend_atr_length", "supertrend_factor")
        if key not in params
    ]
    if missing_keys:
        raise KeyError(f"SUPERTREND params missing keys: {missing_keys}")

    close, _supertrend_line, direction = get_supertrend_series(
        close_series,
        params["supertrend_atr_length"],
        params["supertrend_factor"],
    )
    valid_dir = direction.notna()
    valid_flip = valid_dir & valid_dir.shift(1).fillna(False)
    # Buy: close above red line → direction flips to green (+1)
    entries = ((direction == 1.0) & (direction.shift(1) == -1.0) & valid_flip).fillna(False)
    # Sell: close below green line → direction flips to red (-1)
    exits = ((direction == -1.0) & (direction.shift(1) == 1.0) & valid_flip).fillna(False)

    if shift_signals:
        entries = entries.shift(1).fillna(False)
        exits = exits.shift(1).fillna(False)

    return (
        pd.Series(entries.to_numpy(dtype=bool), index=close.index, dtype=bool),
        pd.Series(exits.to_numpy(dtype=bool), index=close.index, dtype=bool),
    )


def format_supertrend_params(params):
    return (
        f"SUPERTREND(ATR={params['supertrend_atr_length']},"
        f"Factor={params['supertrend_factor']})"
    )


def validate_supertrend_sensitivity_params(atr_length, factor, factor_anchor):
    atr_length, factor = validate_supertrend_params(atr_length, factor)
    if int(factor_anchor) != factor:
        raise ValueError("SUPERTREND sensitivity anchor must match the factor.")
    return atr_length, factor, factor


# KALMAN price vs filter strategy (Q=process noise, R=measurement noise)
if (
    "validate_kalman_params" not in globals()
    or "_compute_kalman_core" not in globals()
):
    raise ValueError("KALMAN helpers are missing. Run the TA-Lib indicator cell first.")


_kalman_series_cache = {}


def get_kalman_series(close_series, process_noise, measurement_noise):
    process_noise, measurement_noise = validate_kalman_params(process_noise, measurement_noise)
    if close_series is None or len(close_series) == 0:
        raise ValueError("KALMAN close_series is empty.")
    cache_key = (id(close_series), process_noise, measurement_noise)
    if cache_key not in _kalman_series_cache:
        close = pd.Series(close_series, index=close_series.index).astype(float)
        close_values = close.to_numpy(dtype=float)
        if not np.isfinite(close_values).any():
            raise ValueError("KALMAN close_series contains no finite prices.")
        kalman_line = pd.Series(
            _compute_kalman_core(close_values, process_noise, measurement_noise),
            index=close.index,
        )
        if kalman_line.notna().sum() == 0:
            raise ValueError("KALMAN could not be computed for the selected parameter combination.")
        _kalman_series_cache[cache_key] = (close, kalman_line)
    return _kalman_series_cache[cache_key]


def build_kalman_signals(close_series, params, shift_signals=True):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for KALMAN, got {type(params).__name__}.")
    missing_keys = [
        key
        for key in ("kalman_process_noise", "kalman_measurement_noise")
        if key not in params
    ]
    if missing_keys:
        raise KeyError(f"KALMAN params missing keys: {missing_keys}")

    close, kalman_line = get_kalman_series(
        close_series,
        params["kalman_process_noise"],
        params["kalman_measurement_noise"],
    )
    valid = kalman_line.notna() & close.notna()
    valid_cross = valid & valid.shift(1).fillna(False)
    # Buy: price closes above the Kalman filter line (cross into above)
    entries = (close.vbt.crossed_above(kalman_line) & valid_cross).fillna(False)
    # Sell: price closes below the Kalman filter line (cross into below)
    exits = (close.vbt.crossed_below(kalman_line) & valid_cross).fillna(False)

    if shift_signals:
        entries = entries.shift(1).fillna(False)
        exits = exits.shift(1).fillna(False)

    return (
        pd.Series(entries.to_numpy(dtype=bool), index=close.index, dtype=bool),
        pd.Series(exits.to_numpy(dtype=bool), index=close.index, dtype=bool),
    )


def format_kalman_params(params):
    return (
        f"KALMAN(Q={params['kalman_process_noise']},"
        f"R={params['kalman_measurement_noise']})"
    )


def validate_kalman_sensitivity_params(process_noise, measurement_noise, measurement_noise_anchor):
    process_noise, measurement_noise = validate_kalman_params(process_noise, measurement_noise)
    if int(measurement_noise_anchor) != measurement_noise:
        raise ValueError("KALMAN sensitivity anchor must match the measurement noise (R).")
    return process_noise, measurement_noise, measurement_noise


# RSI midline crossover strategy (TA-Lib RSI timeperiod; buy/sell on cross of 50)
def validate_rsi_params(timeperiod):
    try:
        timeperiod_num = float(timeperiod)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"RSI timeperiod must be numeric; got timeperiod={timeperiod!r}") from exc
    if not np.isfinite(timeperiod_num):
        raise ValueError("RSI timeperiod must be a finite number.")
    if timeperiod_num != int(timeperiod_num):
        raise ValueError(
            "RSI timeperiod must be a whole number for this grid "
            f"(sensitivity uses int grids); got timeperiod={timeperiod!r}"
        )
    timeperiod = int(timeperiod_num)
    if timeperiod <= 0:
        raise ValueError("RSI timeperiod must be a positive integer.")
    return timeperiod


_rsi_series_cache = {}


def compute_rsi(close_series, timeperiod):
    timeperiod = validate_rsi_params(timeperiod)
    if close_series is None or len(close_series) == 0:
        raise ValueError("RSI close_series is empty.")
    cache_key = (id(close_series), timeperiod)
    if cache_key in _rsi_series_cache:
        return _rsi_series_cache[cache_key]

    close = pd.Series(close_series, index=close_series.index).astype(float)
    close_values = close.to_numpy(dtype=float)
    if not np.isfinite(close_values).any():
        raise ValueError("RSI close_series contains no finite prices.")
    if np.isfinite(close_values).sum() < timeperiod + 1:
        raise ValueError("Not enough price bars to compute RSI for the selected timeperiod.")

    rsi = pd.Series(
        talib.RSI(close_values, timeperiod=timeperiod),
        index=close.index,
    )
    if rsi.notna().sum() == 0:
        raise ValueError("RSI could not be computed for the selected parameter combination.")
    _rsi_series_cache[cache_key] = rsi
    return rsi


def build_rsi_signals(close_series, params, shift_signals=True):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for RSI, got {type(params).__name__}.")
    missing_keys = [key for key in ("rsi_timeperiod",) if key not in params]
    if missing_keys:
        raise KeyError(f"RSI params missing keys: {missing_keys}")

    rsi = compute_rsi(close_series, params["rsi_timeperiod"])
    valid = rsi.notna()
    valid_cross = valid & valid.shift(1).fillna(False)
    # Buy: RSI crosses above 50 (rising bullish momentum)
    entries = (
        (rsi > RSI_CROSS_LEVEL) & (rsi.shift(1) <= RSI_CROSS_LEVEL) & valid_cross
    ).fillna(False)
    # Sell: RSI crosses below 50 (increasing bearish momentum)
    exits = (
        (rsi < RSI_CROSS_LEVEL) & (rsi.shift(1) >= RSI_CROSS_LEVEL) & valid_cross
    ).fillna(False)

    if shift_signals:
        entries = entries.shift(1).fillna(False)
        exits = exits.shift(1).fillna(False)

    return (
        pd.Series(entries.to_numpy(dtype=bool), index=rsi.index, dtype=bool),
        pd.Series(exits.to_numpy(dtype=bool), index=rsi.index, dtype=bool),
    )


def format_rsi_params(params):
    return f"RSI({params['rsi_timeperiod']})"


def validate_rsi_sensitivity_params(timeperiod, timeperiod_anchor_a, timeperiod_anchor_b):
    timeperiod = validate_rsi_params(timeperiod)
    if int(timeperiod_anchor_a) != timeperiod or int(timeperiod_anchor_b) != timeperiod:
        raise ValueError("RSI sensitivity anchors must match the timeperiod.")
    return timeperiod, timeperiod, timeperiod



# ADX +DI/-DI crossover strategy (TA-Lib PLUS_DI / MINUS_DI; ADX = Wilder-smoothed DX)
def validate_adx_params(di_length, adx_smoothing):
    try:
        di_length_num = float(di_length)
        adx_smoothing_num = float(adx_smoothing)
    except (TypeError, ValueError) as exc:
        raise ValueError(
            f"ADX params must be numeric; got di_length={di_length!r}, "
            f"adx_smoothing={adx_smoothing!r}"
        ) from exc
    if not np.isfinite(di_length_num) or not np.isfinite(adx_smoothing_num):
        raise ValueError("ADX DI length and ADX smoothing must be finite numbers.")
    if di_length_num != int(di_length_num):
        raise ValueError(
            "ADX DI length must be a whole number for this grid "
            f"(sensitivity uses int grids); got di_length={di_length!r}"
        )
    if adx_smoothing_num != int(adx_smoothing_num):
        raise ValueError(
            "ADX smoothing timeperiod must be a whole number for this grid "
            f"(sensitivity uses int grids); got adx_smoothing={adx_smoothing!r}"
        )
    di_length = int(di_length_num)
    adx_smoothing = int(adx_smoothing_num)
    if di_length <= 0 or adx_smoothing <= 0:
        raise ValueError("ADX DI length and ADX smoothing must be positive integers.")
    return di_length, adx_smoothing


def validate_adx_trend_level(level):
    try:
        level_num = float(level)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"ADX trend level must be numeric; got level={level!r}") from exc
    if not np.isfinite(level_num):
        raise ValueError("ADX trend level must be a finite number.")
    if not 0.0 <= level_num <= 100.0:
        raise ValueError(
            f"ADX trend level must be between 0 and 100 (ADX scale); got {level_num}."
        )
    return level_num


ADX_TREND_LEVEL = validate_adx_trend_level(ADX_TREND_LEVEL)


_adx_ohlc_cache = {}
_adx_di_cache = {}
_adx_series_cache = {}


def get_adx_ohlc(close_series):
    if "stock_data" not in globals() or "TICKER" not in globals():
        raise ValueError("stock_data/TICKER are missing. Run the download and prepare cells first.")
    if "_select_ohlc_column" not in globals():
        raise ValueError(
            "Shared OHLC helper `_select_ohlc_column` is missing. "
            "Run the full Define Indicator Grids cell (SUPERTREND section included)."
        )
    if close_series is None or len(close_series) == 0:
        raise ValueError("ADX close_series is empty.")

    cache_key = id(close_series)
    if cache_key in _adx_ohlc_cache:
        return _adx_ohlc_cache[cache_key]

    price_index = pd.DatetimeIndex(close_series.index)
    if price_index.tz is not None:
        price_index = price_index.tz_localize(None)

    high = _select_ohlc_column(stock_data, TICKER, "High")
    low = _select_ohlc_column(stock_data, TICKER, "Low")
    if isinstance(high.index, pd.DatetimeIndex) and high.index.tz is not None:
        high = high.copy()
        high.index = high.index.tz_localize(None)
    if isinstance(low.index, pd.DatetimeIndex) and low.index.tz is not None:
        low = low.copy()
        low.index = low.index.tz_localize(None)

    high = high.reindex(price_index)
    low = low.reindex(price_index)
    close = pd.Series(
        pd.Series(close_series).astype(float).to_numpy(),
        index=price_index,
        name=getattr(close_series, "name", None),
    )

    finite_close = np.isfinite(close.to_numpy(dtype=float))
    if not finite_close.any():
        raise ValueError("ADX close_series contains no finite prices.")
    valid_mask = pd.Series(finite_close, index=close.index)
    high_vals = high.loc[valid_mask].to_numpy(dtype=float)
    low_vals = low.loc[valid_mask].to_numpy(dtype=float)
    if (not np.isfinite(high_vals).all()) or (not np.isfinite(low_vals).all()):
        raise ValueError(
            "High/Low data is missing or non-finite for one or more dates in the selected price series."
        )
    if (high_vals < low_vals).any():
        raise ValueError("ADX requires High >= Low on all valid close dates.")

    _adx_ohlc_cache[cache_key] = (high, low, close)
    return _adx_ohlc_cache[cache_key]


def _compute_adx_di_lines(close_series, di_length):
    """TA-Lib +DI/-DI for a DI length; cached so each length is computed once per series."""
    di_length = validate_adx_params(di_length, di_length)[0]
    if close_series is None or len(close_series) == 0:
        raise ValueError("ADX close_series is empty.")
    cache_key = (id(close_series), di_length)
    if cache_key in _adx_di_cache:
        return _adx_di_cache[cache_key]

    high, low, close = get_adx_ohlc(close_series)
    finite_bars = int(np.isfinite(close.to_numpy(dtype=float)).sum())
    if finite_bars <= di_length:
        raise ValueError("Not enough price bars to compute ADX DI lines for the selected DI length.")

    high_vals = high.to_numpy(dtype=float)
    low_vals = low.to_numpy(dtype=float)
    close_vals = close.to_numpy(dtype=float)
    try:
        plus_di_arr = talib.PLUS_DI(high_vals, low_vals, close_vals, timeperiod=di_length)
        minus_di_arr = talib.MINUS_DI(high_vals, low_vals, close_vals, timeperiod=di_length)
    except Exception as exc:
        raise ValueError(
            f"talib PLUS_DI/MINUS_DI failed for di_length={di_length}: "
            f"{type(exc).__name__}: {exc}"
        ) from exc

    plus_di = pd.Series(plus_di_arr, index=close.index)
    minus_di = pd.Series(minus_di_arr, index=close.index)
    if (~(plus_di.isna() | minus_di.isna())).sum() == 0:
        raise ValueError("ADX DI lines could not be computed for the selected DI length.")

    _adx_di_cache[cache_key] = (plus_di, minus_di, close)
    return _adx_di_cache[cache_key]


def _wilder_smooth_dx(dx_values, adx_smoothing):
    """Wilder/RMA smooth of DX -> ADX (same DI lines for any DI length / smoothing pair)."""
    dx = np.asarray(dx_values, dtype=float)
    adx = np.full(dx.shape, np.nan, dtype=float)
    if adx_smoothing <= 0:
        raise ValueError("ADX smoothing must be a positive integer.")
    n = int(dx.size)
    if n == 0:
        return adx

    # Seed with SMA of the first contiguous `adx_smoothing` finite DX values,
    # then Wilder-smooth — common ADX / TA-Lib-style initialization.
    run = 0
    seed_end = None
    for i in range(n):
        if np.isfinite(dx[i]):
            run += 1
            if run == adx_smoothing:
                seed_end = i
                break
        else:
            run = 0
    if seed_end is None:
        return adx

    seed_start = seed_end - adx_smoothing + 1
    prev = float(np.mean(dx[seed_start : seed_end + 1]))
    adx[seed_end] = prev
    for i in range(seed_end + 1, n):
        if not np.isfinite(dx[i]):
            adx[i] = np.nan
            continue
        prev = ((prev * (adx_smoothing - 1)) + float(dx[i])) / adx_smoothing
        adx[i] = prev
    return adx


def compute_adx(close_series, di_length, adx_smoothing):
    di_length, adx_smoothing = validate_adx_params(di_length, adx_smoothing)
    if close_series is None or len(close_series) == 0:
        raise ValueError("ADX close_series is empty.")
    cache_key = (id(close_series), di_length, adx_smoothing)
    if cache_key in _adx_series_cache:
        return _adx_series_cache[cache_key]

    plus_di, minus_di, close = _compute_adx_di_lines(close_series, di_length)
    finite_bars = int(np.isfinite(close.to_numpy(dtype=float)).sum())
    # DI warmup + ADX seed window
    min_bars = di_length + adx_smoothing
    if finite_bars < min_bars:
        raise ValueError(
            "Not enough price bars to compute ADX for the selected parameter combination "
            f"(need at least di_length + adx_smoothing = {min_bars} finite bars)."
        )

    plus_vals = plus_di.to_numpy(dtype=float)
    minus_vals = minus_di.to_numpy(dtype=float)
    with np.errstate(divide="ignore", invalid="ignore"):
        denom = plus_vals + minus_vals
        dx_vals = np.where(
            np.isfinite(denom) & (denom != 0.0),
            100.0 * np.abs(plus_vals - minus_vals) / denom,
            np.nan,
        )
    if not np.isfinite(dx_vals).any():
        raise ValueError("ADX DX could not be computed for the selected parameter combination.")

    try:
        adx_arr = _wilder_smooth_dx(dx_vals, adx_smoothing)
    except Exception as exc:
        raise ValueError(
            f"ADX smoothing failed for di_length={di_length}, "
            f"adx_smoothing={adx_smoothing}: {type(exc).__name__}: {exc}"
        ) from exc

    adx = pd.Series(adx_arr, index=close.index)
    if (~(plus_di.isna() | minus_di.isna() | adx.isna())).sum() == 0:
        raise ValueError("ADX could not be computed for the selected parameter combination.")

    _adx_series_cache[cache_key] = (plus_di, minus_di, adx)
    return _adx_series_cache[cache_key]


def build_adx_signals(close_series, params, shift_signals=True):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for ADX, got {type(params).__name__}.")
    missing_keys = [
        key
        for key in ("adx_di_length", "adx_smoothing_timeperiod")
        if key not in params
    ]
    if missing_keys:
        raise KeyError(f"ADX params missing keys: {missing_keys}")
    if "ADX_TREND_LEVEL" not in globals():
        raise ValueError("ADX_TREND_LEVEL is missing. Re-run the Define Indicator Grids cell.")
    trend_level = validate_adx_trend_level(ADX_TREND_LEVEL)

    plus_di, minus_di, adx = compute_adx(
        close_series,
        params["adx_di_length"],
        params["adx_smoothing_timeperiod"],
    )
    if len(plus_di) != len(close_series):
        raise ValueError(
            "ADX output length does not match close_series; check OHLC alignment."
        )
    # Require DI lines and ADX valid on this bar and the prior bar so warmup NaNs
    # do not register as false +DI/-DI crosses (same pattern as AROON/KAMA/RSI).
    valid = plus_di.notna() & minus_di.notna() & adx.notna()
    valid_cross = valid & valid.shift(1).fillna(False)
    # Buy: +DI crosses above -DI while ADX confirms a strong uptrend
    entries = (
        plus_di.vbt.crossed_above(minus_di)
        & (adx > trend_level)
        & valid_cross
    ).fillna(False)
    # Sell: -DI crosses above +DI while ADX confirms a strong downtrend
    exits = (
        minus_di.vbt.crossed_above(plus_di)
        & (adx > trend_level)
        & valid_cross
    ).fillna(False)

    if shift_signals:
        entries = entries.shift(1).fillna(False)
        exits = exits.shift(1).fillna(False)

    return (
        pd.Series(entries.to_numpy(dtype=bool), index=close_series.index, dtype=bool),
        pd.Series(exits.to_numpy(dtype=bool), index=close_series.index, dtype=bool),
    )


def format_adx_params(params):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for ADX, got {type(params).__name__}.")
    missing_keys = [
        key
        for key in ("adx_di_length", "adx_smoothing_timeperiod")
        if key not in params
    ]
    if missing_keys:
        raise KeyError(f"ADX params missing keys: {missing_keys}")
    return (
        f"ADX(DI={params['adx_di_length']},"
        f"Smooth={params['adx_smoothing_timeperiod']})"
    )


def validate_adx_sensitivity_params(di_length, adx_smoothing, adx_smoothing_anchor):
    di_length, adx_smoothing = validate_adx_params(di_length, adx_smoothing)
    try:
        anchor = int(adx_smoothing_anchor)
    except (TypeError, ValueError) as exc:
        raise ValueError(
            "ADX sensitivity anchor must be an integer matching the ADX smoothing timeperiod."
        ) from exc
    if anchor != adx_smoothing:
        raise ValueError("ADX sensitivity anchor must match the ADX smoothing timeperiod.")
    return di_length, adx_smoothing, adx_smoothing


# DONCHIAN upper-band breakout strategy (TA-Lib MAX/MIN timeperiod; sell on middle-band cross)
def validate_donchian_params(timeperiod):
    try:
        timeperiod_num = float(timeperiod)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"DONCHIAN timeperiod must be numeric; got timeperiod={timeperiod!r}") from exc
    if not np.isfinite(timeperiod_num):
        raise ValueError("DONCHIAN timeperiod must be a finite number.")
    if timeperiod_num != int(timeperiod_num):
        raise ValueError(
            "DONCHIAN timeperiod must be a whole number for this grid "
            f"(sensitivity uses int grids); got timeperiod={timeperiod!r}"
        )
    timeperiod = int(timeperiod_num)
    if timeperiod <= 0:
        raise ValueError("DONCHIAN timeperiod must be a positive integer.")
    return timeperiod


_donchian_series_cache = {}


def get_donchian_ohlc(close_series):
    """Reuse AROON's High/Low alignment cache — same extract, no second OHLC pass."""
    if "get_aroon_ohlc" not in globals():
        raise ValueError(
            "Shared OHLC helper get_aroon_ohlc is missing. "
            "Run the full Define Indicator Grids cell (AROON section included)."
        )
    if close_series is None or len(close_series) == 0:
        raise ValueError("DONCHIAN close_series is empty.")
    try:
        return get_aroon_ohlc(close_series)
    except ValueError as exc:
        msg = str(exc)
        if msg.startswith("AROON "):
            raise ValueError("DONCHIAN " + msg[len("AROON "):]) from exc
        if "AROON requires" in msg:
            raise ValueError(msg.replace("AROON requires", "DONCHIAN requires", 1)) from exc
        raise


def compute_donchian(close_series, timeperiod):
    timeperiod = validate_donchian_params(timeperiod)
    if close_series is None or len(close_series) == 0:
        raise ValueError("DONCHIAN close_series is empty.")
    cache_key = (id(close_series), timeperiod)
    if cache_key in _donchian_series_cache:
        return _donchian_series_cache[cache_key]

    high, low, close = get_donchian_ohlc(close_series)
    finite_bars = int(np.isfinite(close.to_numpy(dtype=float)).sum())
    if finite_bars <= timeperiod:
        raise ValueError("Not enough price bars to compute DONCHIAN for the selected timeperiod.")

    high_vals = high.to_numpy(dtype=float)
    low_vals = low.to_numpy(dtype=float)
    try:
        # TA-Lib has no DONCHIAN; upper/lower from MAX/MIN over High/Low.
        upper_arr = talib.MAX(high_vals, timeperiod=timeperiod)
        lower_arr = talib.MIN(low_vals, timeperiod=timeperiod)
    except Exception as exc:
        raise ValueError(
            f"talib MAX/MIN failed for DONCHIAN timeperiod={timeperiod}: "
            f"{type(exc).__name__}: {exc}"
        ) from exc

    upper = pd.Series(upper_arr, index=close.index)
    lower = pd.Series(lower_arr, index=close.index)
    middle = (upper + lower) / 2.0
    if (~(upper.isna() | lower.isna() | middle.isna())).sum() == 0:
        raise ValueError("DONCHIAN could not be computed for the selected parameter combination.")

    _donchian_series_cache[cache_key] = (close, upper, middle, lower)
    return _donchian_series_cache[cache_key]


def build_donchian_signals(close_series, params, shift_signals=True):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for DONCHIAN, got {type(params).__name__}.")
    missing_keys = [key for key in ("donchian_timeperiod",) if key not in params]
    if missing_keys:
        raise KeyError(f"DONCHIAN params missing keys: {missing_keys}")

    close, upper, middle, _lower = compute_donchian(
        close_series, params["donchian_timeperiod"]
    )
    if len(close) != len(close_series):
        raise ValueError(
            "DONCHIAN output length does not match close_series; check OHLC alignment."
        )
    # Use prior bar's channel so close can break above upper (same-bar MAX(High)
    # embeds today's high and makes close > upper impossible).
    prior_upper = upper.shift(1)
    prior_middle = middle.shift(1)
    valid = prior_upper.notna() & prior_middle.notna()
    valid_cross = valid & valid.shift(1).fillna(False)
    # Buy: close crosses above the prior upper band (uptrend breakout)
    entries = (close.vbt.crossed_above(prior_upper) & valid_cross).fillna(False)
    # Sell: close crosses below the prior middle band (trailing stop)
    exits = (close.vbt.crossed_below(prior_middle) & valid_cross).fillna(False)

    if shift_signals:
        entries = entries.shift(1).fillna(False)
        exits = exits.shift(1).fillna(False)

    # Return on the caller's index (AROON/ADX pattern). close.index may be
    # tz-stripped inside get_aroon_ohlc and would mis-align the backtest.
    return (
        pd.Series(entries.to_numpy(dtype=bool), index=close_series.index, dtype=bool),
        pd.Series(exits.to_numpy(dtype=bool), index=close_series.index, dtype=bool),
    )


def format_donchian_params(params):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for DONCHIAN, got {type(params).__name__}.")
    missing_keys = [key for key in ("donchian_timeperiod",) if key not in params]
    if missing_keys:
        raise KeyError(f"DONCHIAN params missing keys: {missing_keys}")
    return f"DONCHIAN({params['donchian_timeperiod']})"


def validate_donchian_sensitivity_params(timeperiod, timeperiod_anchor_a, timeperiod_anchor_b):
    timeperiod = validate_donchian_params(timeperiod)
    try:
        anchor_a = int(timeperiod_anchor_a)
        anchor_b = int(timeperiod_anchor_b)
    except (TypeError, ValueError) as exc:
        raise ValueError(
            "DONCHIAN sensitivity anchors must be integers matching the timeperiod."
        ) from exc
    if anchor_a != timeperiod or anchor_b != timeperiod:
        raise ValueError("DONCHIAN sensitivity anchors must match the timeperiod.")
    return timeperiod, timeperiod, timeperiod


# TRIX zero-line crossover strategy (TA-Lib TRIX timeperiod; buy/sell on cross of 0)
def validate_trix_params(timeperiod):
    try:
        timeperiod_num = float(timeperiod)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"TRIX timeperiod must be numeric; got timeperiod={timeperiod!r}") from exc
    if not np.isfinite(timeperiod_num):
        raise ValueError("TRIX timeperiod must be a finite number.")
    if timeperiod_num != int(timeperiod_num):
        raise ValueError(
            "TRIX timeperiod must be a whole number for this grid "
            f"(sensitivity uses int grids); got timeperiod={timeperiod!r}"
        )
    timeperiod = int(timeperiod_num)
    if timeperiod <= 0:
        raise ValueError("TRIX timeperiod must be a positive integer.")
    return timeperiod


_trix_series_cache = {}


def compute_trix(close_series, timeperiod):
    timeperiod = validate_trix_params(timeperiod)
    if close_series is None or len(close_series) == 0:
        raise ValueError("TRIX close_series is empty.")
    cache_key = (id(close_series), timeperiod)
    if cache_key in _trix_series_cache:
        return _trix_series_cache[cache_key]

    close = pd.Series(close_series, index=close_series.index).astype(float)
    close_values = close.to_numpy(dtype=float)
    if not np.isfinite(close_values).any():
        raise ValueError("TRIX close_series contains no finite prices.")

    # TRIX is ROC of a triple EMA; needs far more warmup than timeperiod+1.
    # TA-Lib TRIX lookback is 3*(timeperiod-1)+1; need one more bar for a usable value.
    min_bars = 3 * (timeperiod - 1) + 2
    if np.isfinite(close_values).sum() < min_bars:
        raise ValueError(
            "Not enough price bars to compute TRIX for the selected timeperiod "
            f"(need >= {min_bars} finite bars for timeperiod={timeperiod})."
        )

    try:
        trix_arr = talib.TRIX(close_values, timeperiod=timeperiod)
    except Exception as exc:
        raise ValueError(
            f"talib.TRIX failed for timeperiod={timeperiod}: "
            f"{type(exc).__name__}: {exc}"
        ) from exc

    trix = pd.Series(trix_arr, index=close.index)
    if trix.notna().sum() == 0:
        raise ValueError("TRIX could not be computed for the selected parameter combination.")
    _trix_series_cache[cache_key] = trix
    return trix


def build_trix_signals(close_series, params, shift_signals=True):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for TRIX, got {type(params).__name__}.")
    missing_keys = [key for key in ("trix_timeperiod",) if key not in params]
    if missing_keys:
        raise KeyError(f"TRIX params missing keys: {missing_keys}")
    if "TRIX_CROSS_LEVEL" not in globals():
        raise ValueError("TRIX_CROSS_LEVEL is missing. Re-run the Define Indicator Grids cell.")

    trix = compute_trix(close_series, params["trix_timeperiod"])
    valid = trix.notna()
    valid_cross = valid & valid.shift(1).fillna(False)
    # Buy: TRIX crosses above 0 (bullish momentum)
    entries = (
        (trix > TRIX_CROSS_LEVEL) & (trix.shift(1) <= TRIX_CROSS_LEVEL) & valid_cross
    ).fillna(False)
    # Sell: TRIX crosses below 0 (bearish momentum)
    exits = (
        (trix < TRIX_CROSS_LEVEL) & (trix.shift(1) >= TRIX_CROSS_LEVEL) & valid_cross
    ).fillna(False)

    if shift_signals:
        entries = entries.shift(1).fillna(False)
        exits = exits.shift(1).fillna(False)

    # Return on the caller's index (AROON/ADX/DONCHIAN pattern).
    return (
        pd.Series(entries.to_numpy(dtype=bool), index=close_series.index, dtype=bool),
        pd.Series(exits.to_numpy(dtype=bool), index=close_series.index, dtype=bool),
    )


def format_trix_params(params):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for TRIX, got {type(params).__name__}.")
    missing_keys = [key for key in ("trix_timeperiod",) if key not in params]
    if missing_keys:
        raise KeyError(f"TRIX params missing keys: {missing_keys}")
    return f"TRIX({params['trix_timeperiod']})"


def validate_trix_sensitivity_params(timeperiod, timeperiod_anchor_a, timeperiod_anchor_b):
    timeperiod = validate_trix_params(timeperiod)
    try:
        anchor_a = int(timeperiod_anchor_a)
        anchor_b = int(timeperiod_anchor_b)
    except (TypeError, ValueError) as exc:
        raise ValueError(
            "TRIX sensitivity anchors must be integers matching the timeperiod."
        ) from exc
    if anchor_a != timeperiod or anchor_b != timeperiod:
        raise ValueError("TRIX sensitivity anchors must match the timeperiod.")
    return timeperiod, timeperiod, timeperiod


# VORTEX VI+/VI- crossover strategy (TA-Lib has no VORTEX; TRANGE/SUM over timeperiod)
def validate_vortex_params(timeperiod):
    try:
        timeperiod_num = float(timeperiod)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"VORTEX timeperiod must be numeric; got timeperiod={timeperiod!r}") from exc
    if not np.isfinite(timeperiod_num):
        raise ValueError("VORTEX timeperiod must be a finite number.")
    if timeperiod_num != int(timeperiod_num):
        raise ValueError(
            "VORTEX timeperiod must be a whole number for this grid "
            f"(sensitivity uses int grids); got timeperiod={timeperiod!r}"
        )
    timeperiod = int(timeperiod_num)
    if timeperiod <= 0:
        raise ValueError("VORTEX timeperiod must be a positive integer.")
    return timeperiod


_vortex_series_cache = {}
_vortex_base_cache = {}


def get_vortex_ohlc(close_series):
    """Reuse AROON's High/Low alignment cache — same extract, no second OHLC pass."""
    if "get_aroon_ohlc" not in globals():
        raise ValueError(
            "Shared OHLC helper get_aroon_ohlc is missing. "
            "Run the full Define Indicator Grids cell (AROON section included)."
        )
    if close_series is None or len(close_series) == 0:
        raise ValueError("VORTEX close_series is empty.")
    try:
        return get_aroon_ohlc(close_series)
    except ValueError as exc:
        msg = str(exc)
        if msg.startswith("AROON "):
            raise ValueError("VORTEX " + msg[len("AROON "):]) from exc
        if "AROON requires" in msg:
            raise ValueError(msg.replace("AROON requires", "VORTEX requires", 1)) from exc
        raise


def _get_vortex_base_arrays(close_series):
    """Cache TRANGE and VM+/- once per price series (independent of timeperiod)."""
    if close_series is None or len(close_series) == 0:
        raise ValueError("VORTEX close_series is empty.")
    cache_key = id(close_series)
    if cache_key in _vortex_base_cache:
        return _vortex_base_cache[cache_key]

    high, low, close = get_vortex_ohlc(close_series)
    high_vals = high.to_numpy(dtype=float)
    low_vals = low.to_numpy(dtype=float)
    close_vals = close.to_numpy(dtype=float)
    if not (len(high_vals) == len(low_vals) == len(close_vals)):
        raise ValueError("VORTEX High/Low/Close lengths do not match after OHLC alignment.")

    try:
        # TA-Lib has no VORTEX; VI+/VI- from vortex movement vs true range.
        tr_arr = talib.TRANGE(high_vals, low_vals, close_vals)
    except Exception as exc:
        raise ValueError(
            f"talib.TRANGE failed for VORTEX: {type(exc).__name__}: {exc}"
        ) from exc

    # First bar has no prior High/Low; leave VM undefined (NaN), not 0.
    vm_plus = np.full(len(high_vals), np.nan, dtype=float)
    vm_minus = np.full(len(high_vals), np.nan, dtype=float)
    vm_plus[1:] = np.abs(high_vals[1:] - low_vals[:-1])
    vm_minus[1:] = np.abs(low_vals[1:] - high_vals[:-1])

    _vortex_base_cache[cache_key] = (tr_arr, vm_plus, vm_minus, close)
    return _vortex_base_cache[cache_key]


def compute_vortex(close_series, timeperiod):
    timeperiod = validate_vortex_params(timeperiod)
    if close_series is None or len(close_series) == 0:
        raise ValueError("VORTEX close_series is empty.")
    cache_key = (id(close_series), timeperiod)
    if cache_key in _vortex_series_cache:
        return _vortex_series_cache[cache_key]

    tr_arr, vm_plus, vm_minus, close = _get_vortex_base_arrays(close_series)
    finite_bars = int(np.isfinite(close.to_numpy(dtype=float)).sum())
    # First VI needs a prior bar for VM+/- and `timeperiod` finite TR/VM values.
    min_bars = timeperiod + 1
    if finite_bars < min_bars:
        raise ValueError(
            "Not enough price bars to compute VORTEX for the selected timeperiod "
            f"(need >= {min_bars} finite bars for timeperiod={timeperiod})."
        )

    try:
        sum_vm_plus = talib.SUM(vm_plus, timeperiod=timeperiod)
        sum_vm_minus = talib.SUM(vm_minus, timeperiod=timeperiod)
        sum_tr = talib.SUM(tr_arr, timeperiod=timeperiod)
    except Exception as exc:
        raise ValueError(
            f"talib.SUM failed for VORTEX timeperiod={timeperiod}: "
            f"{type(exc).__name__}: {exc}"
        ) from exc

    vi_plus_arr = np.full(len(sum_tr), np.nan, dtype=float)
    vi_minus_arr = np.full(len(sum_tr), np.nan, dtype=float)
    valid_tr = np.isfinite(sum_tr) & (sum_tr != 0)
    # Only divide where the TR sum is finite and non-zero.
    vi_plus_arr[valid_tr] = sum_vm_plus[valid_tr] / sum_tr[valid_tr]
    vi_minus_arr[valid_tr] = sum_vm_minus[valid_tr] / sum_tr[valid_tr]

    vi_plus = pd.Series(vi_plus_arr, index=close.index)
    vi_minus = pd.Series(vi_minus_arr, index=close.index)
    if (~(vi_plus.isna() | vi_minus.isna())).sum() == 0:
        raise ValueError("VORTEX could not be computed for the selected parameter combination.")

    _vortex_series_cache[cache_key] = (vi_plus, vi_minus)
    return _vortex_series_cache[cache_key]


def build_vortex_signals(close_series, params, shift_signals=True):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for VORTEX, got {type(params).__name__}.")
    missing_keys = [key for key in ("vortex_timeperiod",) if key not in params]
    if missing_keys:
        raise KeyError(f"VORTEX params missing keys: {missing_keys}")

    vi_plus, vi_minus = compute_vortex(close_series, params["vortex_timeperiod"])
    if len(vi_plus) != len(close_series) or len(vi_minus) != len(close_series):
        raise ValueError(
            "VORTEX output length does not match close_series; check OHLC alignment."
        )
    # Require both lines valid on this bar and the prior bar so warmup NaNs
    # do not register as false VI+/VI- crosses (same pattern as AROON/KAMA/RSI).
    valid = vi_plus.notna() & vi_minus.notna()
    valid_cross = valid & valid.shift(1).fillna(False)
    # Buy: VI+ crosses upward from below VI-
    entries = (vi_plus.vbt.crossed_above(vi_minus) & valid_cross).fillna(False)
    # Sell: VI- crosses upward from below VI+
    exits = (vi_minus.vbt.crossed_above(vi_plus) & valid_cross).fillna(False)

    if shift_signals:
        entries = entries.shift(1).fillna(False)
        exits = exits.shift(1).fillna(False)

    # Return on the caller's index (AROON/ADX/DONCHIAN pattern).
    return (
        pd.Series(entries.to_numpy(dtype=bool), index=close_series.index, dtype=bool),
        pd.Series(exits.to_numpy(dtype=bool), index=close_series.index, dtype=bool),
    )

def format_vortex_params(params):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for VORTEX, got {type(params).__name__}.")
    missing_keys = [key for key in ("vortex_timeperiod",) if key not in params]
    if missing_keys:
        raise KeyError(f"VORTEX params missing keys: {missing_keys}")
    return f"VORTEX({params['vortex_timeperiod']})"


def validate_vortex_sensitivity_params(timeperiod, timeperiod_anchor_a, timeperiod_anchor_b):
    timeperiod = validate_vortex_params(timeperiod)
    try:
        anchor_a = int(timeperiod_anchor_a)
        anchor_b = int(timeperiod_anchor_b)
    except (TypeError, ValueError) as exc:
        raise ValueError(
            "VORTEX sensitivity anchors must be integers matching the timeperiod."
        ) from exc
    if anchor_a != timeperiod or anchor_b != timeperiod:
        raise ValueError("VORTEX sensitivity anchors must match the timeperiod.")
    return timeperiod, timeperiod, timeperiod


# ALMA crossover strategy (custom ALMA: fast/slow length + offset hundredths + sigma)
if (
    "validate_alma_params" not in globals()
    or "_compute_alma_core" not in globals()
):
    raise ValueError("ALMA helpers are missing. Run the TA-Lib indicator cell first.")


_alma_series_cache = {}


def validate_alma_crossover_params(fast_length, slow_length, offset, sigma):
    fast_length, offset, sigma = validate_alma_params(fast_length, offset, sigma)
    slow_length, offset, sigma = validate_alma_params(slow_length, offset, sigma)
    if fast_length >= slow_length:
        raise ValueError("ALMA fast length must be less than slow length.")
    return fast_length, slow_length, offset, sigma


def get_alma_series(close_series, length, offset, sigma):
    length, offset, sigma = validate_alma_params(length, offset, sigma)
    if close_series is None or len(close_series) == 0:
        raise ValueError("ALMA close_series is empty.")
    if not hasattr(close_series, "index"):
        raise TypeError(
            f"ALMA close_series must be a pandas Series; got {type(close_series).__name__}."
        )
    cache_key = (id(close_series), length, offset, sigma)
    if cache_key not in _alma_series_cache:
        close = pd.Series(close_series, index=close_series.index).astype(float)
        close_values = close.to_numpy(dtype=float)
        if not np.isfinite(close_values).any():
            raise ValueError("ALMA close_series contains no finite prices.")
        try:
            alma_line = pd.Series(
                _compute_alma_core(close_values, length, offset, sigma),
                index=close.index,
            )
        except ValueError as exc:
            raise ValueError(
                f"ALMA could not be computed for length={length}, offset={offset}, "
                f"sigma={sigma}: {exc}"
            ) from exc
        if alma_line.notna().sum() == 0:
            raise ValueError("ALMA could not be computed for the selected parameter combination.")
        _alma_series_cache[cache_key] = (close, alma_line)
    return _alma_series_cache[cache_key]


def build_alma_signals(close_series, params, shift_signals=True):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for ALMA, got {type(params).__name__}.")
    missing_keys = [
        key
        for key in ("alma_fast_length", "alma_slow_length", "alma_offset", "alma_sigma")
        if key not in params
    ]
    if missing_keys:
        raise KeyError(f"ALMA params missing keys: {missing_keys}")

    fast_length, slow_length, offset, sigma = validate_alma_crossover_params(
        params["alma_fast_length"],
        params["alma_slow_length"],
        params["alma_offset"],
        params["alma_sigma"],
    )

    close, alma_fast = get_alma_series(close_series, fast_length, offset, sigma)
    _, alma_slow = get_alma_series(close_series, slow_length, offset, sigma)
    if len(alma_fast) != len(close_series) or len(alma_slow) != len(close_series):
        raise ValueError(
            "ALMA output length does not match close_series; check close alignment."
        )
    # Require both ALMAs and close valid on this bar and the prior bar so warmup NaNs
    # do not register as false fast/slow crosses (same pattern as AROON/KAMA/RSI).
    valid = alma_fast.notna() & alma_slow.notna() & close.notna()
    valid_cross = valid & valid.shift(1).fillna(False)
    # Buy: fast ALMA crosses above slow ALMA
    entries = (alma_fast.vbt.crossed_above(alma_slow) & valid_cross).fillna(False)
    # Sell: fast ALMA crosses below slow ALMA
    exits = (alma_fast.vbt.crossed_below(alma_slow) & valid_cross).fillna(False)

    if shift_signals:
        entries = entries.shift(1).fillna(False)
        exits = exits.shift(1).fillna(False)

    # Return on the caller's index (AROON/ADX/DONCHIAN pattern).
    return (
        pd.Series(entries.to_numpy(dtype=bool), index=close_series.index, dtype=bool),
        pd.Series(exits.to_numpy(dtype=bool), index=close_series.index, dtype=bool),
    )


def format_alma_params(params):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for ALMA, got {type(params).__name__}.")
    missing_keys = [
        key
        for key in ("alma_fast_length", "alma_slow_length", "alma_offset", "alma_sigma")
        if key not in params
    ]
    if missing_keys:
        raise KeyError(f"ALMA params missing keys: {missing_keys}")
    fast_length, slow_length, offset, sigma = validate_alma_crossover_params(
        params["alma_fast_length"],
        params["alma_slow_length"],
        params["alma_offset"],
        params["alma_sigma"],
    )
    return f"ALMA({fast_length},{slow_length},{offset / 100:.2f},{sigma})"


ema_combinations = []
for ema1 in ema1_periods:
    for ema2 in ema2_periods:
        for ema3 in ema3_periods:
            try:
                ema1, ema2, ema3 = validate_triple_ema_params(ema1, ema2, ema3)
                ema_combinations.append({
                    "ema1_period": ema1,
                    "ema2_period": ema2,
                    "ema3_period": ema3
                })
            except ValueError:
                pass

if not ema_combinations:
    raise ValueError("No valid Triple EMA parameter combinations were generated.")

macd_combinations = []
for fast_period in macd_fast_periods:
    for slow_period in macd_slow_periods:
        for signal_period in macd_signal_periods:
            try:
                fast_period, slow_period, signal_period = validate_macd_params(
                    fast_period,
                    slow_period,
                    signal_period
                )
                macd_combinations.append({
                    "macd_fast_period": fast_period,
                    "macd_slow_period": slow_period,
                    "macd_signal_period": signal_period
                })
            except ValueError:
                pass

if not macd_combinations:
    raise ValueError("No valid MACD parameter combinations were generated.")

aroon_combinations = []
for timeperiod in aroon_timeperiods:
    try:
        timeperiod = validate_aroon_params(timeperiod)
        aroon_combinations.append({
            "aroon_timeperiod": timeperiod,
        })
    except ValueError:
        pass

if not aroon_combinations:
    raise ValueError("No valid AROON parameter combinations were generated.")

stc_combinations = []
for ema_short in stc_ema_short_periods:
    for ema_long in stc_ema_long_periods:
        for cycle_period in stc_cycle_periods:
            try:
                ema_short, ema_long, cycle_period = validate_stc_params(
                    ema_short,
                    ema_long,
                    cycle_period,
                )
                stc_combinations.append({
                    "stc_ema_short_period": ema_short,
                    "stc_ema_long_period": ema_long,
                    "stc_cycle_period": cycle_period,
                })
            except ValueError:
                pass

if not stc_combinations:
    raise ValueError("No valid STC parameter combinations were generated.")

kama_combinations = []
for period in kama_periods:
    for fast_ema_constant in kama_fast_ema_constants:
        for slow_ema_constant in kama_slow_ema_constants:
            try:
                period, fast_ema_constant, slow_ema_constant = validate_kama_params(
                    period,
                    fast_ema_constant,
                    slow_ema_constant,
                )
                kama_combinations.append({
                    "kama_period": period,
                    "kama_fast_ema_constant": fast_ema_constant,
                    "kama_slow_ema_constant": slow_ema_constant,
                })
            except ValueError:
                pass

if not kama_combinations:
    raise ValueError("No valid KAMA parameter combinations were generated.")

supertrend_combinations = []
for atr_length in supertrend_atr_lengths:
    for factor in supertrend_factors:
        try:
            atr_length, factor = validate_supertrend_params(atr_length, factor)
            supertrend_combinations.append({
                "supertrend_atr_length": atr_length,
                "supertrend_factor": factor,
            })
        except ValueError:
            pass

if not supertrend_combinations:
    raise ValueError("No valid SUPERTREND parameter combinations were generated.")

kalman_combinations = []
for process_noise in kalman_process_noise_values:
    for measurement_noise in kalman_measurement_noise_values:
        try:
            process_noise, measurement_noise = validate_kalman_params(
                process_noise,
                measurement_noise,
            )
            kalman_combinations.append({
                "kalman_process_noise": process_noise,
                "kalman_measurement_noise": measurement_noise,
            })
        except ValueError:
            pass

if not kalman_combinations:
    raise ValueError("No valid KALMAN parameter combinations were generated.")

rsi_combinations = []
for timeperiod in rsi_timeperiods:
    try:
        timeperiod = validate_rsi_params(timeperiod)
        rsi_combinations.append({
            "rsi_timeperiod": timeperiod,
        })
    except ValueError:
        pass

if not rsi_combinations:
    raise ValueError("No valid RSI parameter combinations were generated.")

adx_combinations = []
for di_length in adx_di_lengths:
    for adx_smoothing in adx_smoothing_timeperiods:
        try:
            di_length, adx_smoothing = validate_adx_params(di_length, adx_smoothing)
            adx_combinations.append({
                "adx_di_length": di_length,
                "adx_smoothing_timeperiod": adx_smoothing,
            })
        except ValueError:
            pass

if not adx_combinations:
    raise ValueError("No valid ADX parameter combinations were generated.")

donchian_combinations = []
for timeperiod in donchian_timeperiods:
    try:
        timeperiod = validate_donchian_params(timeperiod)
        donchian_combinations.append({
            "donchian_timeperiod": timeperiod,
        })
    except ValueError:
        pass

if not donchian_combinations:
    raise ValueError("No valid DONCHIAN parameter combinations were generated.")

trix_combinations = []
for timeperiod in trix_timeperiods:
    try:
        timeperiod = validate_trix_params(timeperiod)
        trix_combinations.append({
            "trix_timeperiod": timeperiod,
        })
    except ValueError:
        pass

if not trix_combinations:
    raise ValueError("No valid TRIX parameter combinations were generated.")

vortex_combinations = []
for timeperiod in vortex_timeperiods:
    try:
        timeperiod = validate_vortex_params(timeperiod)
        vortex_combinations.append({
            "vortex_timeperiod": timeperiod,
        })
    except ValueError:
        pass

if not vortex_combinations:
    raise ValueError("No valid VORTEX parameter combinations were generated.")

alma_combinations = []
for fast_length in alma_fast_lengths:
    for slow_length in alma_slow_lengths:
        for offset in alma_offsets:
            for sigma in alma_sigmas:
                try:
                    fast_v, slow_v, offset_v, sigma_v = validate_alma_crossover_params(
                        fast_length, slow_length, offset, sigma
                    )
                    alma_combinations.append({
                        "alma_fast_length": fast_v,
                        "alma_slow_length": slow_v,
                        "alma_offset": offset_v,
                        "alma_sigma": sigma_v,
                    })
                except ValueError:
                    pass

if not alma_combinations:
    raise ValueError("No valid ALMA parameter combinations were generated.")

indicator_grids = {
    "Triple EMA": {
        "description": "Triple EMA crossover strategy",
        "params": ema_combinations,
        "build_signals": build_triple_ema_signals,
        "format_params": format_triple_ema_params
    },
    "MACD": {
        "description": "MACD line crossing its signal line",
        "params": macd_combinations,
        "build_signals": build_macd_signals,
        "format_params": format_macd_params
    },
    "AROON": {
        "description": "AROON Up/Down crossover: buy when Up crosses above Down and Up > entry level, sell when Down crosses above Up",
        "params": aroon_combinations,
        "build_signals": build_aroon_signals,
        "format_params": format_aroon_params
    },
    "STC": {
        "description": "Schaff Trend Cycle: buy on cross above 50, sell on cross below 50",
        "params": stc_combinations,
        "build_signals": build_stc_signals,
        "format_params": format_stc_params
    },
    "KAMA": {
        "description": "Price crossing KAMA line: buy on cross above, sell on cross below",
        "params": kama_combinations,
        "build_signals": build_kama_signals,
        "format_params": format_kama_params
    },
    "SUPERTREND": {
        "description": "SUPERTREND flip: buy when close above red line, sell when close below green line",
        "params": supertrend_combinations,
        "build_signals": build_supertrend_signals,
        "format_params": format_supertrend_params
    },
    "KALMAN": {
        "description": "Price crossing Kalman filter: buy on cross above, sell on cross below",
        "params": kalman_combinations,
        "build_signals": build_kalman_signals,
        "format_params": format_kalman_params
    },
    "RSI": {
        "description": "RSI crossing 50: buy on cross above, sell on cross below",
        "params": rsi_combinations,
        "build_signals": build_rsi_signals,
        "format_params": format_rsi_params
    },
    "ADX": {
        "description": "ADX +DI/-DI crossover: buy when +DI crosses above -DI with ADX > trend level, sell when -DI crosses above +DI with ADX > trend level",
        "params": adx_combinations,
        "build_signals": build_adx_signals,
        "format_params": format_adx_params
    },
    "DONCHIAN": {
        "description": "DONCHIAN breakout: buy when close crosses above prior upper band, sell when close crosses below prior middle band",
        "params": donchian_combinations,
        "build_signals": build_donchian_signals,
        "format_params": format_donchian_params
    },
    "TRIX": {
        "description": "TRIX crossing 0: buy on cross above, sell on cross below",
        "params": trix_combinations,
        "build_signals": build_trix_signals,
        "format_params": format_trix_params
    },
    "VORTEX": {
        "description": "VORTEX VI+/VI- crossover: buy when VI+ crosses above VI-, sell when VI- crosses above VI+",
        "params": vortex_combinations,
        "build_signals": build_vortex_signals,
        "format_params": format_vortex_params
    },
    "ALMA": {
        "description": "ALMA fast/slow crossover: buy when fast crosses above slow, sell when fast crosses below slow",
        "params": alma_combinations,
        "build_signals": build_alma_signals,
        "format_params": format_alma_params
    },
}

active_indicator_names = ["Triple EMA", "MACD", "AROON", "STC", "KAMA", "SUPERTREND", "KALMAN", "RSI", "ADX", "DONCHIAN", "TRIX", "VORTEX", "ALMA"]
missing_indicator_names = [
    name for name in active_indicator_names
    if name not in indicator_grids
]
if missing_indicator_names:
    raise KeyError(f"Active indicators are not defined: {missing_indicator_names}")

active_indicator_grids = {
    name: indicator_grids[name]
    for name in active_indicator_names
}


def get_active_indicator_spec(indicator_name):
    if indicator_name not in active_indicator_grids:
        available = ", ".join(active_indicator_grids.keys())
        raise KeyError(f"Unknown indicator '{indicator_name}'. Available indicators: {available}")
    return active_indicator_grids[indicator_name]


def require_params_dict(params, indicator_name):
    if not isinstance(params, dict):
        raise TypeError(f"Expected params dict for {indicator_name}, got {type(params).__name__}.")
    return params




INIT_CASH = 100_000
FEE_RATE = 0.0005
SLIPPAGE_RATE = 0.0005


def trade_stats_from_portfolio(pf):
    """Extract trade-level stats; safe when there are zero trades."""
    trades = pf.trades
    total_trades = len(trades)
    stats = {
        "total_trades": total_trades,
        "win_rate_pct": np.nan,
        "profit_factor": np.nan,
        "expectancy": np.nan,
        "avg_win": np.nan,
        "avg_loss": np.nan,
    }
    if total_trades <= 0:
        return stats

    tr = trades.returns.values if hasattr(trades.returns, "values") else np.asarray(trades.returns)
    if tr.size == 0:
        return stats

    pos = tr[tr > 0]
    neg = tr[tr < 0]
    stats["win_rate_pct"] = (len(pos) / len(tr)) * 100.0
    gains = float(pos.sum()) if len(pos) else 0.0
    losses = float(abs(neg.sum())) if len(neg) else 0.0
    stats["profit_factor"] = (gains / losses) if losses > 0 else (np.inf if gains > 0 else np.nan)
    stats["expectancy"] = float(tr.mean())
    stats["avg_win"] = float(pos.mean()) if len(pos) else np.nan
    stats["avg_loss"] = float(abs(neg.mean())) if len(neg) else np.nan
    return stats


def run_signal_backtest(price, entries, exits):
    """Shared Portfolio.from_signals wrapper used by OOS / full-sample cells."""
    close_arg = price.to_numpy(dtype=float) if hasattr(price, "to_numpy") else np.asarray(price, dtype=float)
    if hasattr(entries, "to_numpy"):
        entries = entries.to_numpy(dtype=bool)
    if hasattr(exits, "to_numpy"):
        exits = exits.to_numpy(dtype=bool)
    return vbt.Portfolio.from_signals(
        close=close_arg,
        entries=entries,
        exits=exits,
        init_cash=INIT_CASH,
        fees=FEE_RATE,
        slippage=SLIPPAGE_RATE,
        freq=FREQ,
    )


def fmt_metric(value, spec=".3f", suffix=""):
    """Format metrics without crashing on NaN/None/inf."""
    if value is None or (isinstance(value, float) and not np.isfinite(value)):
        return "n/a"
    try:
        return format(float(value), spec) + suffix
    except (TypeError, ValueError):
        return "n/a"


def safe_float(value, default=np.nan):
    """Convert to float; return default for missing/invalid/non-finite values."""
    try:
        out = float(value)
        return out if np.isfinite(out) else default
    except (TypeError, ValueError):
        return default


_tied_is_sharpe_notes_printed = set()


def displayed_is_top_n(indicator_results, top_n=5):
    """Top-N rows shown in the in-sample results table."""
    if "sharpe_ratio" not in indicator_results.columns:
        raise KeyError("indicator_results is missing required column: sharpe_ratio")
    return indicator_results.dropna(subset=["sharpe_ratio"]).nlargest(top_n, "sharpe_ratio")


def is_sharpe_tied_at_best(indicator_results, rtol=1e-9, atol=1e-12):
    valid = indicator_results.dropna(subset=["sharpe_ratio"])
    if valid.empty:
        return False
    best_sharpe = valid["sharpe_ratio"].max()
    tied_count = np.isclose(valid["sharpe_ratio"], best_sharpe, rtol=rtol, atol=atol).sum()
    return int(tied_count) > 1


def maybe_print_tied_is_sharpe_note(indicator_name, indicator_results, used_param_displays, context, top_n=5):
    if indicator_name in _tied_is_sharpe_notes_printed:
        return

    required_columns = {"sharpe_ratio", "param_display"}
    missing_columns = required_columns.difference(indicator_results.columns)
    if missing_columns:
        return

    used_labels = {
        str(label).strip()
        for label in used_param_displays
        if label is not None and pd.notna(label) and str(label).strip() and str(label).strip().lower() != "nan"
    }
    if not used_labels:
        return

    display_top = displayed_is_top_n(indicator_results, top_n)
    if display_top.empty:
        return

    display_labels = {
        str(label).strip()
        for label in display_top["param_display"].tolist()
        if label is not None and pd.notna(label) and str(label).strip() and str(label).strip().lower() != "nan"
    }
    outside_display = sorted(used_labels - display_labels)
    if not outside_display or not is_sharpe_tied_at_best(indicator_results):
        return

    best_sharpe = float(display_top["sharpe_ratio"].iloc[0])
    print(
        f"Note ({context}): {indicator_name} has multiple parameter sets tied at the "
        f"best in-sample Sharpe ({best_sharpe:.3f}). The in-sample top-{top_n} table shows one "
        f"valid tied set; this step used different tied equivalent(s): "
        f"{', '.join(outside_display)}"
    )
    _tied_is_sharpe_notes_printed.add(indicator_name)


def best_is_row(indicator_results):
    """Pick the single best in-sample row by Sharpe (matches the IS results table)."""
    ranked = displayed_is_top_n(indicator_results, 1)
    if ranked.empty:
        return None
    return ranked.iloc[0]


def best_oos_row(oos_results_df):
    """Pick the single best OOS row by Sharpe among validated IS top-N candidates."""
    valid = oos_results_df.dropna(subset=["OOS_Sharpe"])
    if valid.empty:
        return None
    return valid.loc[valid["OOS_Sharpe"].idxmax()]


total_grid_combinations = sum(len(spec["params"]) for spec in active_indicator_grids.values())

print("Active indicator grids:")
for indicator_name, spec in active_indicator_grids.items():
    combinations = spec["params"]
    print(f"\n{indicator_name}: {spec['description']}")
    print(f"Generated {len(combinations)} valid {indicator_name} combinations")
    print("First 10 combinations preview:")
    for i, params in enumerate(combinations[:10], 1):
        print(f"  {i:2d}. {spec['format_params'](params)}")
    if len(combinations) > 10:
        print(f"   ... and {len(combinations) - 10} more combinations")

print(f"\nTotal combinations across active grids: {total_grid_combinations}")
print("Ready to test each indicator grid separately on training data!")

Active indicator grids:

Triple EMA: Triple EMA crossover strategy
Generated 66840 valid Triple EMA combinations
First 10 combinations preview:
   1. EMA(4,90,120)
   2. EMA(4,90,121)
   3. EMA(4,90,122)
   4. EMA(4,90,123)
   5. EMA(4,90,124)
   6. EMA(4,90,125)
   7. EMA(4,90,126)
   8. EMA(4,90,127)
   9. EMA(4,90,128)
  10. EMA(4,90,129)
   ... and 66830 more combinations

MACD: MACD line crossing its signal line
Generated 128000 valid MACD combinations
First 10 combinations preview:
   1. MACD(10,60,40)
   2. MACD(10,60,41)
   3. MACD(10,60,42)
   4. MACD(10,60,43)
   5. MACD(10,60,44)
   6. MACD(10,60,45)
   7. MACD(10,60,46)
   8. MACD(10,60,47)
   9. MACD(10,60,48)
  10. MACD(10,60,49)
   ... and 127990 more combinations

AROON: AROON Up/Down crossover: buy when Up crosses above Down and Up > entry level, sell when Down crosses above Up
Generated 76 valid AROON combinations
First 10 combinations preview:
   1. AROON(4)
   2. AROON(5)
   3. AROON(6)
   4. AROON(7)
   5. AROON(8)
   6. AROON(9)
   7. AROON(10)
   8. AROON(11)
   9. AROON(12)
  10. AROON(13)
   ... and 66 more combinations

STC: Schaff Trend Cycle: buy on cross above 50, sell on cross below 50
Generated 128000 valid STC combinations
First 10 combinations preview:
   1. STC(10,60,20)
   2. STC(10,60,21)
   3. STC(10,60,22)
   4. STC(10,60,23)
   5. STC(10,60,24)
   6. STC(10,60,25)
   7. STC(10,60,26)
   8. STC(10,60,27)
   9. STC(10,60,28)
  10. STC(10,60,29)
   ... and 127990 more combinations

KAMA: Price crossing KAMA line: buy on cross above, sell on cross below
Generated 7600 valid KAMA combinations
First 10 combinations preview:
   1. KAMA(5,2,60)
   2. KAMA(5,2,61)
   3. KAMA(5,2,62)
   4. KAMA(5,2,63)
   5. KAMA(5,2,64)
   6. KAMA(5,2,65)
   7. KAMA(5,2,66)
   8. KAMA(5,2,67)
   9. KAMA(5,2,68)
  10. KAMA(5,2,69)
   ... and 7590 more combinations

SUPERTREND: SUPERTREND flip: buy when close above red line, sell when close below green line
Generated 6372 valid SUPERTREND combinations
First 10 combinations preview:
   1. SUPERTREND(ATR=4,Factor=1)
   2. SUPERTREND(ATR=4,Factor=2)
   3. SUPERTREND(ATR=4,Factor=3)
   4. SUPERTREND(ATR=4,Factor=4)
   5. SUPERTREND(ATR=4,Factor=5)
   6. SUPERTREND(ATR=4,Factor=6)
   7. SUPERTREND(ATR=4,Factor=7)
   8. SUPERTREND(ATR=4,Factor=8)
   9. SUPERTREND(ATR=4,Factor=9)
  10. SUPERTREND(ATR=4,Factor=10)
   ... and 6362 more combinations

KALMAN: Price crossing Kalman filter: buy on cross above, sell on cross below
Generated 240 valid KALMAN combinations
First 10 combinations preview:
   1. KALMAN(Q=1,R=100)
   2. KALMAN(Q=1,R=101)
   3. KALMAN(Q=1,R=102)
   4. KALMAN(Q=1,R=103)
   5. KALMAN(Q=1,R=104)
   6. KALMAN(Q=1,R=105)
   7. KALMAN(Q=1,R=106)
   8. KALMAN(Q=1,R=107)
   9. KALMAN(Q=1,R=108)
  10. KALMAN(Q=1,R=109)
   ... and 230 more combinations

RSI: RSI crossing 50: buy on cross above, sell on cross below
Generated 40 valid RSI combinations
First 10 combinations preview:
   1. RSI(40)
   2. RSI(41)
   3. RSI(42)
   4. RSI(43)
   5. RSI(44)
   6. RSI(45)
   7. RSI(46)
   8. RSI(47)
   9. RSI(48)
  10. RSI(49)
   ... and 30 more combinations

ADX: ADX +DI/-DI crossover: buy when +DI crosses above -DI with ADX > trend level, sell when -DI crosses above +DI with ADX > trend level
Generated 3360 valid ADX combinations
First 10 combinations preview:
   1. ADX(DI=4,Smooth=20)
   2. ADX(DI=4,Smooth=21)
   3. ADX(DI=4,Smooth=22)
   4. ADX(DI=4,Smooth=23)
   5. ADX(DI=4,Smooth=24)
   6. ADX(DI=4,Smooth=25)
   7. ADX(DI=4,Smooth=26)
   8. ADX(DI=4,Smooth=27)
   9. ADX(DI=4,Smooth=28)
  10. ADX(DI=4,Smooth=29)
   ... and 3350 more combinations

DONCHIAN: DONCHIAN breakout: buy when close crosses above prior upper band, sell when close crosses below prior middle band
Generated 50 valid DONCHIAN combinations
First 10 combinations preview:
   1. DONCHIAN(10)
   2. DONCHIAN(11)
   3. DONCHIAN(12)
   4. DONCHIAN(13)
   5. DONCHIAN(14)
   6. DONCHIAN(15)
   7. DONCHIAN(16)
   8. DONCHIAN(17)
   9. DONCHIAN(18)
  10. DONCHIAN(19)
   ... and 40 more combinations

TRIX: TRIX crossing 0: buy on cross above, sell on cross below
Generated 76 valid TRIX combinations
First 10 combinations preview:
   1. TRIX(4)
   2. TRIX(5)
   3. TRIX(6)
   4. TRIX(7)
   5. TRIX(8)
   6. TRIX(9)
   7. TRIX(10)
   8. TRIX(11)
   9. TRIX(12)
  10. TRIX(13)
   ... and 66 more combinations

VORTEX: VORTEX VI+/VI- crossover: buy when VI+ crosses above VI-, sell when VI- crosses above VI+
Generated 100 valid VORTEX combinations
First 10 combinations preview:
   1. VORTEX(40)
   2. VORTEX(41)
   3. VORTEX(42)
   4. VORTEX(43)
   5. VORTEX(44)
   6. VORTEX(45)
   7. VORTEX(46)
   8. VORTEX(47)
   9. VORTEX(48)
  10. VORTEX(49)
   ... and 90 more combinations

ALMA: ALMA fast/slow crossover: buy when fast crosses above slow, sell when fast crosses below slow
Generated 38000 valid ALMA combinations
First 10 combinations preview:
   1. ALMA(2,60,0.10,1)
   2. ALMA(2,60,0.10,3)
   3. ALMA(2,60,0.10,5)
   4. ALMA(2,60,0.10,7)
   5. ALMA(2,60,0.10,9)
   6. ALMA(2,60,0.12,1)
   7. ALMA(2,60,0.12,3)
   8. ALMA(2,60,0.12,5)
   9. ALMA(2,60,0.12,7)
  10. ALMA(2,60,0.12,9)
   ... and 37990 more combinations

Total combinations across active grids: 378754
Ready to test each indicator grid separately on training data!

In [8]:
# Initialize Multi-Indicator Results Collection System

# Create empty list to store all backtest results from every active indicator grid.
grid_search_results = []

print("Multi-Indicator Results Collection System Initialized")
print(f"   - Active indicators: {', '.join(active_indicator_grids.keys())}")
print(f"   - Will test {total_grid_combinations} total combinations")
print("   - Results will be stored in 'grid_search_results' list")

# Define what metrics we will collect (All TradingView-style metrics)
metrics_to_collect = [
    # Strategy Metadata
    "indicator",
    "strategy",
    "params",
    "param_display",
    "ema1_period",
    "ema2_period",
    "ema3_period",
    "macd_fast_period",
    "macd_slow_period",
    "macd_signal_period",
    "aroon_timeperiod",
    "stc_ema_short_period",
    "stc_ema_long_period",
    "stc_cycle_period",
    "supertrend_atr_length",
    "supertrend_factor",
    "kalman_process_noise",
    "kalman_measurement_noise",
    "rsi_timeperiod",
    "trix_timeperiod",
    "vortex_timeperiod",
    "alma_fast_length",
    "alma_slow_length",
    "alma_offset",
    "alma_sigma",
    
    # Return Metrics
    "total_return",
    "annualized_return",
    "total_profit",
    
    # Risk-Adjusted Return Metrics
    "sharpe_ratio",
    "sortino_ratio",
    "calmar_ratio",
    "omega_ratio",
    "information_ratio",
    "tail_ratio",
    "deflated_sharpe_ratio",
    
    # Risk Metrics
    "max_drawdown",
    "volatility",
    "ulcer_index",
    
    # Trade Performance Metrics
    "win_rate",
    "total_trades",
    "avg_trade_duration",
    "expectancy",
    "profit_factor", 
    "sqn",
    
    # Win/Loss Analysis
    "payoff_ratio",
    "largest_win",
    "largest_loss",
    "avg_win_amount",
    "avg_loss_amount",
    "winning_streak",
    "losing_streak",
    
    # Additional Ratios
    "recovery_factor",
    "gain_to_pain_ratio",
    "serenity_index"
]

print("Metrics to collect for each indicator combination:")
for i, metric in enumerate(metrics_to_collect, 1):
    print(f"  {i}. {metric.replace('_', ' ').title()}")

print("Ready to start the multi-indicator grid search!")

Multi-Indicator Results Collection System Initialized
   - Active indicators: Triple EMA, MACD, AROON, STC, KAMA, SUPERTREND, KALMAN, RSI, ADX, DONCHIAN, TRIX, VORTEX, ALMA
   - Will test 378754 total combinations
   - Results will be stored in 'grid_search_results' list
Metrics to collect for each indicator combination:
  1. Indicator
  2. Strategy
  3. Params
  4. Param Display
  5. Ema1 Period
  6. Ema2 Period
  7. Ema3 Period
  8. Macd Fast Period
  9. Macd Slow Period
  10. Macd Signal Period
  11. Aroon Timeperiod
  12. Stc Ema Short Period
  13. Stc Ema Long Period
  14. Stc Cycle Period
  15. Supertrend Atr Length
  16. Supertrend Factor
  17. Kalman Process Noise
  18. Kalman Measurement Noise
  19. Rsi Timeperiod
  20. Trix Timeperiod
  21. Vortex Timeperiod
  22. Alma Fast Length
  23. Alma Slow Length
  24. Alma Offset
  25. Alma Sigma
  26. Total Return
  27. Annualized Return
  28. Total Profit
  29. Sharpe Ratio
  30. Sortino Ratio
  31. Calmar Ratio
  32. Omega Ratio
  33. Information Ratio
  34. Tail Ratio
  35. Deflated Sharpe Ratio
  36. Max Drawdown
  37. Volatility
  38. Ulcer Index
  39. Win Rate
  40. Total Trades
  41. Avg Trade Duration
  42. Expectancy
  43. Profit Factor
  44. Sqn
  45. Payoff Ratio
  46. Largest Win
  47. Largest Loss
  48. Avg Win Amount
  49. Avg Loss Amount
  50. Winning Streak
  51. Losing Streak
  52. Recovery Factor
  53. Gain To Pain Ratio
  54. Serenity Index
Ready to start the multi-indicator grid search!

In [9]:
# VISUALIZE SIGNALS FOR ONE EXAMPLE

example_params = {
    "macd_fast_period": 12,
    "macd_slow_period": 26,
    "macd_signal_period": 9
}
entries, exits = build_macd_signals(train_close, example_params, shift_signals=False)
macd_line, macd_signal_line, macd_hist = compute_macd(
    train_close,
    example_params["macd_fast_period"],
    example_params["macd_slow_period"],
    example_params["macd_signal_period"]
)

signals_df = pd.DataFrame({
    'Close': train_close.values,
    'MACD': macd_line.values,
    'MACD_Signal': macd_signal_line.values,
    'MACD_Hist': macd_hist.values,
    'Buy': entries.values.astype(bool),
    'Sell': exits.values.astype(bool)
}, index=train_close.index)
signals_df.index.name = 'Date'

pos = 0
pos_list = []
for buy, sell in zip(signals_df['Buy'], signals_df['Sell']):
    if buy:
        pos = 1
    elif sell:
        pos = 0
    pos_list.append(pos)
signals_df['Position'] = pos_list

print(f"Example {format_macd_params(example_params)} signals:")
print(signals_df.head(500).to_string())

Example MACD(12,26,9) signals:
                Close      MACD  MACD_Signal  MACD_Hist    Buy   Sell  Position
Date
2018-01-02   5.778714       NaN          NaN        NaN  False  False         0
2018-01-03   5.947908       NaN          NaN        NaN  False  False         0
2018-01-04   5.982775       NaN          NaN        NaN  False  False         0
2018-01-05   6.163460       NaN          NaN        NaN  False  False         0
2018-01-08   6.232009       NaN          NaN        NaN  False  False         0
2018-01-09   6.236763       NaN          NaN        NaN  False  False         0
2018-01-10   6.192385       NaN          NaN        NaN  False  False         0
2018-01-11   6.316407       NaN          NaN        NaN  False  False         0
2018-01-12   6.450337       NaN          NaN        NaN  False  False         0
2018-01-16   6.400410       NaN          NaN        NaN  False  False         0
2018-01-17   6.602093       NaN          NaN        NaN  False  False         0
2018-01-18   6.608434       NaN          NaN        NaN  False  False         0
2018-01-19   6.671832       NaN          NaN        NaN  False  False         0
2018-01-22   6.880253       NaN          NaN        NaN  False  False         0
2018-01-23   7.054595       NaN          NaN        NaN  False  False         0
2018-01-24   6.911556       NaN          NaN        NaN  False  False         0
2018-01-25   6.902837       NaN          NaN        NaN  False  False         0
2018-01-26   7.211109       NaN          NaN        NaN  False  False         0
2018-01-29   7.115616       NaN          NaN        NaN  False  False         0
2018-01-30   6.933743       NaN          NaN        NaN  False  False         0
2018-01-31   7.019331       NaN          NaN        NaN  False  False         0
2018-02-01   6.843799       NaN          NaN        NaN  False  False         0
2018-02-02   6.425768       NaN          NaN        NaN  False  False         0
2018-02-05   5.684013       NaN          NaN        NaN  False  False         0
2018-02-06   6.122252       NaN          NaN        NaN  False  False         0
2018-02-07   5.880150       NaN          NaN        NaN  False  False         0
2018-02-08   5.151472       NaN          NaN        NaN  False  False         0
2018-02-09   5.393969       NaN          NaN        NaN  False  False         0
2018-02-12   5.695899       NaN          NaN        NaN  False  False         0
2018-02-13   5.765243       NaN          NaN        NaN  False  False         0
2018-02-14   6.102836       NaN          NaN        NaN  False  False         0
2018-02-15   6.421806       NaN          NaN        NaN  False  False         0
2018-02-16   6.350087       NaN          NaN        NaN  False  False         0
2018-02-20   6.381786 -0.028949    -0.022682  -0.006267  False  False         0
2018-02-21   6.324332 -0.018823    -0.021910   0.003088   True  False         1
2018-02-22   6.325521 -0.010579    -0.019644   0.009065  False  False         1
2018-02-23   6.702342  0.026059    -0.010503   0.036563  False  False         1
2018-02-26   6.971385  0.075930     0.006783   0.069147  False  False         1
2018-02-27   6.721756  0.094224     0.024271   0.069952  False  False         1
2018-02-28   6.586641  0.096704     0.038758   0.057946  False  False         1
2018-03-01   6.269650  0.072259     0.045458   0.026801  False  False         1
2018-03-02   6.442014  0.066033     0.049573   0.016460  False  False         1
2018-03-05   6.644096  0.076523     0.054963   0.021560  False  False         1
2018-03-06   6.728096  0.090570     0.062084   0.028486  False  False         1
2018-03-07   6.778419  0.104558     0.070579   0.033979  False  False         1
2018-03-08   6.879461  0.122386     0.080940   0.041446  False  False         1
2018-03-09   7.280055  0.166915     0.098135   0.068780  False  False         1
2018-03-12   7.389019  0.208593     0.120227   0.088366  False  False         1
2018-03-13   7.120768  0.217471     0.139676   0.077795  False  False         1
2018-03-14   7.096597  0.220019     0.155745   0.064275  False  False         1
2018-03-15   7.064900  0.216981     0.167992   0.048989  False  False         1
2018-03-16   7.018142  0.208397     0.176073   0.032324  False  False         1
2018-03-19   6.577527  0.164148     0.173688  -0.009540  False   True         0
2018-03-20   6.625868  0.131466     0.165243  -0.033777  False  False         0
2018-03-21   6.529979  0.096713     0.151537  -0.054824  False  False         0
2018-03-22   6.052910  0.030326     0.127295  -0.096969  False  False         0
2018-03-23   5.563953 -0.061038     0.089628  -0.150666  False  False         0
2018-03-26   6.190009 -0.081981     0.055306  -0.137288  False  False         0
2018-03-27   5.596445 -0.144806     0.015284  -0.160090  False  False         0
2018-03-28   5.403478 -0.207771    -0.029327  -0.178444  False  False         0
2018-03-29   5.702638 -0.230869    -0.069635  -0.161234  False  False         0
2018-04-02   5.196246 -0.286732    -0.113055  -0.173677  False  False         0
2018-04-03   5.370590 -0.313323    -0.153108  -0.160215  False  False         0
2018-04-04   5.624578 -0.310325    -0.184552  -0.125773  False  False         0
2018-04-05   5.712940 -0.297391    -0.207120  -0.090271  False  False         0
2018-04-06   5.286590 -0.317879    -0.229272  -0.088608  False  False         0
2018-04-09   5.392383 -0.321869    -0.247791  -0.074078  False  False         0
2018-04-10   5.748600 -0.292911    -0.256815  -0.036096  False  False         0
2018-04-11   5.651918 -0.274598    -0.260372  -0.014226  False  False         0
2018-04-12   5.850037 -0.241316    -0.256560   0.015245   True  False         1
2018-04-13   5.763261 -0.219413    -0.249131   0.029718  False  False         1
2018-04-16   5.890452 -0.189605    -0.237226   0.047621  False  False         1
2018-04-17   6.267274 -0.134031    -0.216587   0.082556  False  False         1
2018-04-18   6.310860 -0.085486    -0.190367   0.104881  False  False         1
2018-04-19   6.139289 -0.060164    -0.164326   0.104162  False  False         1
2018-04-20   5.844885 -0.063125    -0.144086   0.080961  False  False         1
2018-04-23   5.798923 -0.068392    -0.128947   0.060555  False  False         1
2018-04-24   5.429234 -0.101230    -0.123404   0.022174  False  False         1
2018-04-25   5.450630 -0.124097    -0.123542  -0.000555  False   True         0
2018-04-26   5.788619 -0.113636    -0.121561   0.007925   True  False         1
2018-04-27   5.802092 -0.103071    -0.117863   0.014792  False  False         1
2018-04-30   5.678466 -0.103481    -0.114987   0.011506  False  False         1
2018-05-01   5.863113 -0.087893    -0.109568   0.021675  False  False         1
2018-05-02   5.760883 -0.082834    -0.104221   0.021387  False  False         1
2018-05-03   5.761281 -0.077894    -0.098956   0.021062  False  False         1
2018-05-04   6.085402 -0.047281    -0.088621   0.041340  False  False         1
2018-05-07   6.230027 -0.011220    -0.073140   0.061921  False  False         1
2018-05-08   6.209424  0.015517    -0.055409   0.070926  False  False         1
2018-05-09   6.417448  0.052883    -0.033751   0.086633  False  False         1
2018-05-10   6.617151  0.097486    -0.007503   0.104989  False  False         1
2018-05-11   6.597339  0.129740     0.019945   0.109795  False  False         1
2018-05-14   6.626660  0.155871     0.047130   0.108740  False  False         1
2018-05-15   6.412297  0.157467     0.069198   0.088269  False  False         1
2018-05-16   6.530374  0.166342     0.088627   0.077716  False  False         1
2018-05-17   6.456676  0.165521     0.104006   0.061516  False  False         1
2018-05-18   6.353257  0.154742     0.114153   0.040589  False  False         1
2018-05-21   6.464203  0.153383     0.121999   0.031384  False  False         1
2018-05-22   6.430523  0.147884     0.127176   0.020708  False  False         1
2018-05-23   6.592187  0.154787     0.132698   0.022089  False  False         1
2018-05-24   6.586641  0.157989     0.137756   0.020232  False  False         1
2018-05-25   6.603282  0.160024     0.142210   0.017814  False  False         1
2018-05-29   6.518884  0.153063     0.144380   0.008682  False  False         1
2018-05-30   6.657963  0.156959     0.146896   0.010063  False  False         1
2018-05-31   6.643700  0.157085     0.148934   0.008151  False  False         1
2018-06-01   6.952764  0.180048     0.155157   0.024891  False  False         1
2018-06-04   7.131069  0.210211     0.166168   0.044044  False  False         1
2018-06-05   7.204770  0.237327     0.180399   0.056927  False  False         1
2018-06-06   7.323640  0.265349     0.197389   0.067960  False  False         1
2018-06-07   7.153656  0.270720     0.212056   0.058665  False  False         1
2018-06-08   7.148901  0.271464     0.223937   0.047527  False  False         1
2018-06-11   7.204770  0.273410     0.233832   0.039578  False  False         1
2018-06-12   7.318885  0.280922     0.243250   0.037672  False  False         1
2018-06-13   7.310565  0.282942     0.251188   0.031754  False  False         1
2018-06-14   7.532854  0.299033     0.260757   0.038276  False  False         1
2018-06-15   7.457965  0.302258     0.269057   0.033201  False  False         1
2018-06-18   7.441323  0.300013     0.275248   0.024764  False  False         1
2018-06-19   7.374754  0.289524     0.278104   0.011421  False  False         1
2018-06-20   7.529287  0.290335     0.280550   0.009785  False  False         1
2018-06-21   7.334338  0.272110     0.278862  -0.006752  False   True         0
2018-06-22   7.260640  0.248851     0.272859  -0.024009  False  False         0
2018-06-25   6.797042  0.190810     0.256450  -0.065640  False  False         0
2018-06-26   6.871932  0.149136     0.234987  -0.085851  False  False         0
2018-06-27   6.596150  0.092786     0.206547  -0.113761  False  False         0
2018-06-28   6.757815  0.060476     0.177332  -0.116856  False  False         0
2018-06-29   6.788721  0.036938     0.149254  -0.112315  False  False         0
2018-07-02   6.940876  0.030214     0.125446  -0.095232  False  False         0
2018-07-03   6.701945  0.005541     0.101465  -0.095924  False  False         0
2018-07-05   6.948009  0.005777     0.082327  -0.076551  False  False         0
2018-07-06   7.260640  0.030834     0.072029  -0.041194  False  False         0
2018-07-09   7.462720  0.066236     0.070870  -0.004634  False  False         0
2018-07-10   7.480550  0.094639     0.075624   0.019015   True  False         1
2018-07-11   7.371191  0.107090     0.081917   0.025173  False  False         1
2018-07-12   7.734935  0.144641     0.094462   0.050180  False  False         1
2018-07-13   7.757521  0.174215     0.110413   0.063803  False  False         1
2018-07-16   7.705217  0.191228     0.126576   0.064652  False  False         1
2018-07-17   7.847863  0.213757     0.144012   0.069745  False  False         1
2018-07-18   7.797935  0.224989     0.160207   0.064782  False  False         1
2018-07-19   7.682631  0.222027     0.172571   0.049456  False  False         1
2018-07-20   7.671933  0.216323     0.181322   0.035001  False  False         1
2018-07-23   7.738498  0.214699     0.187997   0.026702  False  False         1
2018-07-24   7.837165  0.218850     0.194168   0.024682  False  False         1
2018-07-25   8.164061  0.245686     0.204471   0.041215  False  False         1
2018-07-26   7.807446  0.235463     0.210670   0.024794  False  False         1
2018-07-27   7.481739  0.198789     0.208294  -0.009505  False   True         0
2018-07-30   7.159598  0.142092     0.195053  -0.052962  False  False         0
2018-07-31   7.302245  0.107431     0.177529  -0.070098  False  False         0
2018-08-01   7.402097  0.087016     0.159426  -0.072410  False  False         0
2018-08-02   7.696895  0.093546     0.146250  -0.052704  False  False         0
2018-08-03   7.765840  0.103097     0.137620  -0.034523  False  False         0
2018-08-06   7.908486  0.120784     0.134252  -0.013469  False  False         0
2018-08-07   7.985753  0.139428     0.135287   0.004141   True  False         1
2018-08-08   8.007148  0.154153     0.139061   0.015093  False  False         1
2018-08-09   8.000017  0.163365     0.143921   0.019443  False  False         1
2018-08-10   7.813390  0.153832     0.145904   0.007929  False  False         1
2018-08-13   7.790804  0.142809     0.145285  -0.002476  False   True         0
2018-08-14   7.934637  0.144019     0.145031  -0.001013  False  False         0
2018-08-15   7.645781  0.120283     0.140082  -0.019799  False  False         0
2018-08-16   7.715914  0.105910     0.133247  -0.027337  False  False         0
2018-08-17   7.714727  0.093348     0.125267  -0.031920  False  False         0
2018-08-20   7.699272  0.081209     0.116456  -0.035247  False  False         0
2018-08-21   7.778916  0.077126     0.108590  -0.031464  False  False         0
2018-08-22   7.869257  0.080256     0.102923  -0.022668  False  False         0
2018-08-23   7.830032  0.078663     0.098071  -0.019408  False  False         0
2018-08-24   8.047566  0.093873     0.097231  -0.003359  False  False         0
2018-08-27   8.290064  0.124064     0.102598   0.021466   True  False         1
2018-08-28   8.326914  0.149243     0.111927   0.037316  False  False         1
2018-08-29   8.618146  0.190502     0.127642   0.062860  False  False         1
2018-08-30   8.569407  0.216769     0.145467   0.071301  False  False         1
2018-08-31   8.594372  0.236869     0.163748   0.073121  False  False         1
2018-09-04   8.492142  0.241763     0.179351   0.062412  False  False         1
2018-09-05   8.154550  0.215911     0.186663   0.029248  False  False         1
2018-09-06   7.932261  0.175464     0.184423  -0.008959  False   True         0
2018-09-07   7.853803  0.135517     0.174642  -0.039125  False  False         0
2018-09-10   7.922750  0.108175     0.161349  -0.053174  False  False         0
2018-09-11   8.098679  0.099554     0.148990  -0.049436  False  False         0
2018-09-12   8.028544  0.086071     0.136406  -0.050335  False  False         0
2018-09-13   8.266287  0.093491     0.127823  -0.034332  False  False         0
2018-09-14   8.203288  0.093214     0.120901  -0.027687  False  False         0
2018-09-17   7.857371  0.064340     0.109589  -0.045249  False  False         0
2018-09-18   8.044001  0.055873     0.098846  -0.042973  False  False         0
2018-09-19   8.026168  0.047179     0.088513  -0.041333  False  False         0
2018-09-20   8.278175  0.059934     0.082797  -0.022863  False  False         0
2018-09-21   8.146228  0.058718     0.077981  -0.019263  False  False         0
2018-09-24   8.216361  0.062691     0.074923  -0.012232  False  False         0
2018-09-25   8.249646  0.067744     0.073487  -0.005743  False  False         0
2018-09-26   8.241325  0.070268     0.072843  -0.002576  False  False         0
2018-09-27   8.469559  0.089651     0.076205   0.013446   True  False         1
2018-09-28   8.456482  0.102772     0.081518   0.021254  False  False         1
2018-10-01   8.505219  0.115769     0.088369   0.027400  False  False         1
2018-10-02   8.456482  0.120745     0.094844   0.025901  False  False         1
2018-10-03   8.481444  0.125258     0.100927   0.024331  False  False         1
2018-10-04   7.997638  0.088773     0.098496  -0.009723  False   True         0
2018-10-05   7.696895  0.035185     0.085834  -0.050649  False  False         0
2018-10-08   7.559005 -0.018201     0.065027  -0.083228  False  False         0
2018-10-09   7.617252 -0.055173     0.040987  -0.096160  False  False         0
2018-10-10   6.629435 -0.162312     0.000327  -0.162639  False  False         0
2018-10-11   6.360786 -0.265833    -0.052905  -0.212928  False  False         0
2018-10-12   6.898084 -0.301049    -0.102534  -0.198515  False  False         0
2018-10-15   6.637755 -0.345976    -0.151222  -0.194754  False  False         0
2018-10-16   7.209526 -0.331621    -0.187302  -0.144319  False  False         0
2018-10-17   7.233299 -0.314699    -0.212781  -0.101917  False  False         0
2018-10-18   6.731663 -0.337870    -0.237799  -0.100071  False  False         0
2018-10-19   6.704324 -0.354356    -0.261110  -0.093245  False  False         0
2018-10-22   6.805363 -0.355173    -0.279923  -0.075250  False  False         0
2018-10-23   6.730474 -0.357740    -0.295486  -0.062254  False  False         0
2018-10-24   5.815167 -0.428690    -0.322127  -0.106563  False  False         0
2018-10-25   6.411900 -0.431790    -0.344060  -0.087730  False  False         0
2018-10-26   5.913830 -0.469030    -0.369054  -0.099976  False  False         0
2018-10-29   5.597634 -0.518085    -0.398860  -0.119225  False  False         0
2018-10-30   5.813979 -0.533356    -0.425759  -0.107597  False  False         0
2018-10-31   6.206254 -0.507950    -0.442198  -0.065753  False  False         0
2018-11-01   6.477280 -0.460636    -0.445885  -0.014751  False  False         0
2018-11-02   6.187234 -0.441455    -0.444999   0.003544   True  False         1
2018-11-05   6.126610 -0.426232    -0.441246   0.015014  False  False         1
2018-11-06   6.256179 -0.399112    -0.432819   0.033707  False  False         1
2018-11-07   6.831514 -0.327420    -0.411739   0.084319  False  False         1
2018-11-08   6.715022 -0.276813    -0.384754   0.107941  False  False         1
2018-11-09   6.373861 -0.261224    -0.360048   0.098824  False  False         1
2018-11-12   5.813979 -0.290697    -0.346178   0.055481  False  False         1
2018-11-13   5.811602 -0.310664    -0.339075   0.028411  False  False         1
2018-11-14   5.664202 -0.334527    -0.338165   0.003639  False  False         1
2018-11-15   5.967322 -0.325229    -0.335578   0.010349  False  False         1
2018-11-16   5.901944 -0.319454    -0.332353   0.012899  False  False         1
2018-11-19   5.336118 -0.356426    -0.337168  -0.019258  False   True         0
2018-11-20   5.040130 -0.404943    -0.350723  -0.054220  False  False         0
2018-11-21   5.153057 -0.429331    -0.366445  -0.062886  False  False         0
2018-11-23   5.038940 -0.452649    -0.383685  -0.068964  False  False         0
2018-11-26   5.384855 -0.438166    -0.394582  -0.043584  False  False         0
2018-11-27   5.440725 -0.417368    -0.399139  -0.018229  False  False         0
2018-11-28   5.956625 -0.355163    -0.390344   0.035181   True  False         1
2018-11-29   5.901944 -0.306741    -0.373623   0.066882  False  False         1
2018-11-30   6.025569 -0.255446    -0.349988   0.094541  False  False         1
2018-12-03   6.334633 -0.187693    -0.317529   0.129836  False  False         1
2018-12-04   5.638050 -0.188038    -0.291631   0.103593  False  False         1
2018-12-06   5.720072 -0.179623    -0.269229   0.089606  False  False         1
2018-12-07   5.160190 -0.215645    -0.258512   0.042867  False  False         1
2018-12-10   5.321854 -0.228515    -0.252513   0.023998  False  False         1
2018-12-11   5.378911 -0.231442    -0.248299   0.016857  False  False         1
2018-12-12   5.514425 -0.220287    -0.242696   0.022409  False  False         1
2018-12-13   5.515613 -0.208943    -0.235946   0.027003  False  False         1
2018-12-14   5.099564 -0.230863    -0.234929   0.004066  False  False         1
2018-12-17   4.770292 -0.271672    -0.242278  -0.029394  False   True         0
2018-12-18   4.849936 -0.294196    -0.252661  -0.041535  False  False         0
2018-12-19   4.499266 -0.336464    -0.269422  -0.067042  False  False         0
2018-12-20   4.318582 -0.380159    -0.291569  -0.088590  False  False         0
2018-12-21   3.901346 -0.443345    -0.321924  -0.121420  False  False         0
2018-12-24   3.612488 -0.510839    -0.359707  -0.151132  False  False         0
2018-12-26   4.268472 -0.505569    -0.388880  -0.116689  False  False         0

In [10]:
# MULTI-INDICATOR GRID SEARCH ON TRAINING DATA - BATCHED

print("INITIATING MULTI-INDICATOR GRID SEARCH OPTIMIZATION")
print("=" * 70)
print(f"Active Indicators: {', '.join(active_indicator_grids.keys())}")
print(f"Training Period: {train_close.index[0].date()} -> {train_close.index[-1].date()}")
print(f"Market Regime: {market_label}")
print(f"Annualization Basis: {TRADING_DAYS_PER_YEAR} bars/year ({YEAR_FREQ})")
print("Initial Capital: $100,000")
print("Transaction Costs: 0.05% per trade (fees + slippage)")
print("Optimization Metric: Sharpe Ratio (risk-adjusted returns)")
print("=" * 70)

# Configuration
BATCH_SIZE = 1000  # Process combinations in batches to manage memory
MIN_TRADES_PER_YEAR = 2
train_years = sample_years(train_close)
total_combinations = total_grid_combinations

print(f"Total combinations to test: {total_combinations}")
print(f"Batch size: {BATCH_SIZE}")
print(f"Minimum trade frequency filter: {MIN_TRADES_PER_YEAR}/year")
print("Each indicator grid is run separately.\n")

def metric_scalar(values, idx):
    """Return a scalar metric from vectorbt outputs that may be scalar, Series, or array-like."""
    if isinstance(values, pd.Series):
        return float(values.iloc[idx])
    if isinstance(values, pd.DataFrame):
        return float(values.iloc[:, idx].iloc[0])

    arr = np.asarray(values)
    if arr.ndim == 0:
        return float(arr)
    return float(arr.ravel()[idx])


# Process each active indicator grid independently.
grid_search_results = []
successful_tests = 0
filtered_tests = 0
failed_tests = 0
failure_details = []

print("Starting batched grid search...\n")

for indicator_name, spec in active_indicator_grids.items():
    indicator_params = spec["params"]
    indicator_total = len(indicator_params)
    indicator_successful = 0
    indicator_filtered = 0
    indicator_failed = 0
    batch_count = (indicator_total + BATCH_SIZE - 1) // BATCH_SIZE

    print("=" * 70)
    print(f"Running {indicator_name} grid: {indicator_total} combinations")
    print("=" * 70)

    for batch_start in range(0, indicator_total, BATCH_SIZE):
        batch_end = min(batch_start + BATCH_SIZE, indicator_total)
        batch_params = indicator_params[batch_start:batch_end]
        batch_size = len(batch_params)

        print(f"Processing {indicator_name} batch {batch_start // BATCH_SIZE + 1}/{batch_count}")
        print(f"  Combinations {batch_start + 1} to {batch_end}...")

        batch_entries = []
        batch_exits = []
        signal_ok = []

        for params in batch_params:
            try:
                entries, exits = spec["build_signals"](train_close, params, shift_signals=True)
                batch_entries.append(entries)
                batch_exits.append(exits)
                signal_ok.append(True)
            except Exception as exc:
                batch_entries.append(pd.Series(False, index=train_close.index, dtype=bool))
                batch_exits.append(pd.Series(False, index=train_close.index, dtype=bool))
                signal_ok.append(False)
                indicator_failed += 1
                failed_tests += 1
                if len(failure_details) < 10:
                    failure_details.append(f"{indicator_name} signal build failed for {spec['format_params'](params)}: {exc}")

        entries_df = pd.DataFrame(batch_entries).T
        exits_df = pd.DataFrame(batch_exits).T

        print(f"  Running vectorized backtest on {batch_size} {indicator_name} combinations...")
        try:
            portfolios = vbt.Portfolio.from_signals(
                close=train_close,
                entries=entries_df,
                exits=exits_df,
                init_cash=100_000,
                fees=0.0005,
                slippage=0.0005,
                freq=FREQ
            )

            total_returns = portfolios.total_return()
            annualized_returns = portfolios.annualized_return(freq=FREQ, year_freq=YEAR_FREQ)
            max_drawdowns = portfolios.max_drawdown()
            volatilities = portfolios.annualized_volatility(freq=FREQ, year_freq=YEAR_FREQ)
            sharpe_ratios = portfolios.sharpe_ratio(freq=FREQ, year_freq=YEAR_FREQ)
            sortino_ratios = portfolios.sortino_ratio(freq=FREQ, year_freq=YEAR_FREQ)
            portfolio_returns = portfolios.returns()

            for idx, params in enumerate(batch_params):
                if not signal_ok[idx]:
                    continue

                try:
                    total_return = metric_scalar(total_returns, idx)
                    annualized_return = metric_scalar(annualized_returns, idx)
                    max_drawdown = metric_scalar(max_drawdowns, idx)
                    volatility = metric_scalar(volatilities, idx)
                    sharpe_ratio = metric_scalar(sharpe_ratios, idx)
                    sortino_ratio = metric_scalar(sortino_ratios, idx)

                    trades = portfolios.trades if batch_size == 1 else portfolios[idx].trades
                    total_trades = len(trades)
                    trades_per_year = total_trades / train_years

                    if trades_per_year < MIN_TRADES_PER_YEAR:
                        filtered_tests += 1
                        indicator_filtered += 1
                        continue

                    win_rate_pct = np.nan
                    profit_factor = np.nan
                    expectancy = 0.0
                    avg_win_amount = 0.0
                    avg_loss_amount = 0.0
                    winning_streak = np.nan
                    losing_streak = np.nan

                    if total_trades > 0:
                        tr = trades.returns.values if hasattr(trades.returns, 'values') else np.array(trades.returns)
                        if tr.size > 0:
                            pos = tr[tr > 0]
                            neg = tr[tr < 0]
                            win_rate_pct = (len(pos) / len(tr)) * 100.0 if len(tr) > 0 else np.nan
                            gains = pos.sum() if len(pos) else 0.0
                            losses = abs(neg.sum()) if len(neg) else 0.0
                            profit_factor = gains / losses if losses > 0 else np.inf
                            expectancy = float(tr.mean())
                            avg_win_amount = float(pos.mean()) if len(pos) else 0.0
                            avg_loss_amount = float(abs(neg.mean())) if len(neg) else 0.0

                            try:
                                winning_streak = int(trades.winning_streak[idx] if batch_size > 1 else trades.winning_streak())
                                losing_streak = int(trades.losing_streak[idx] if batch_size > 1 else trades.losing_streak())
                            except Exception:
                                pass

                    returns = portfolio_returns.iloc[:, idx] if batch_size > 1 else portfolio_returns
                    cum = (1 + returns).cumprod()
                    peak = cum.cummax()
                    dd = (cum - peak) / peak
                    ulcer_index = float(np.sqrt((dd.pow(2)).mean())) if len(dd) > 0 else np.nan
                    payoff_ratio = (avg_win_amount / avg_loss_amount) if avg_loss_amount != 0.0 else np.inf

                    result = {
                        "indicator": indicator_name,
                        "strategy": spec["description"],
                        "params": params.copy(),
                        "param_display": spec["format_params"](params),
                        "total_return": total_return,
                        "annualized_return": annualized_return,
                        "total_profit": total_return * 100_000,
                        "max_drawdown": max_drawdown,
                        "volatility": volatility,
                        "sharpe_ratio": sharpe_ratio,
                        "sortino_ratio": sortino_ratio,
                        "calmar_ratio": np.nan,
                        "omega_ratio": np.nan,
                        "information_ratio": np.nan,
                        "tail_ratio": np.nan,
                        "deflated_sharpe_ratio": np.nan,
                        "ulcer_index": ulcer_index,
                        "total_trades": total_trades,
                        "win_rate": win_rate_pct,
                        "profit_factor": profit_factor,
                        "expectancy": expectancy,
                        "avg_win_amount": avg_win_amount,
                        "avg_loss_amount": avg_loss_amount,
                        "payoff_ratio": payoff_ratio,
                        "winning_streak": winning_streak,
                        "losing_streak": losing_streak,
                        "trades_per_year": trades_per_year
                    }
                    result.update(params)
                    grid_search_results.append(result)
                    successful_tests += 1
                    indicator_successful += 1

                except Exception as exc:
                    failed_tests += 1
                    indicator_failed += 1
                    if len(failure_details) < 10:
                        failure_details.append(f"{indicator_name} metric extraction failed for {spec['format_params'](params)}: {exc}")

        except Exception as exc:
            print(f"  Batch failed: {str(exc)[:100]}")
            backtestable_count = sum(signal_ok)
            failed_tests += backtestable_count
            indicator_failed += backtestable_count
            if len(failure_details) < 10:
                failure_details.append(f"{indicator_name} batch backtest failed: {exc}")

        progress_pct = (batch_end / indicator_total) * 100 if indicator_total else 100.0
        print(
            f"  {indicator_name} batch complete: "
            f"{indicator_successful} stored, {indicator_filtered} filtered, {indicator_failed} failed"
        )
        print(f"  {indicator_name} progress: {batch_end}/{indicator_total} ({progress_pct:.1f}%)\n")

# SUMMARY
print("=" * 70)
print("MULTI-INDICATOR GRID SEARCH COMPLETED!")
print("=" * 70)
print(f"Total combinations attempted: {total_combinations}")
print(f"Stored after filters: {successful_tests}")
print(f"Filtered by trade frequency: {filtered_tests}")
print(f"Failed: {failed_tests}")
if total_combinations > 0:
    print(f"Stored-result rate: {(successful_tests / total_combinations) * 100:.1f}%")
print(f"\nResults stored in 'grid_search_results' ({len(grid_search_results)} entries)")

if failure_details:
    print("\nFirst failure details:")
    for detail in failure_details[:5]:
        print(f"  - {detail}")

def print_top_in_sample_by_indicator(results, top_n=5, include_summary=False):
    required_columns = {
        'indicator',
        'param_display',
        'sharpe_ratio',
        'total_return',
        'annualized_return',
        'max_drawdown',
        'win_rate',
        'profit_factor',
        'total_trades',
        'trades_per_year'
    }
    missing_columns = sorted(required_columns - set(results.columns))
    if missing_columns:
        raise KeyError(f"Missing required result columns: {missing_columns}")

    if results.empty:
        print("No in-sample results to display.")
        return

    print("\n" + "=" * 70)
    print("TOP 5 IN-SAMPLE RESULTS BY INDICATOR")
    print("=" * 70)

    for indicator_name, indicator_results in results.groupby('indicator', sort=False):
        ranked = displayed_is_top_n(indicator_results, top_n)
        print(f"\n{indicator_name} - Top {top_n} by In-Sample Sharpe Ratio")
        print("-" * 70)

        if include_summary:
            print("In-sample summary:")
            print(f"   Stored combinations: {len(indicator_results)}")
            print(f"   Best Sharpe Ratio: {indicator_results['sharpe_ratio'].max():.3f}")
            print(f"   Best Total Return: {indicator_results['total_return'].max():.2%}")
            print(f"   Average Total Return: {indicator_results['total_return'].mean():.2%}")
            print(f"   Smallest Max Drawdown: {indicator_results['max_drawdown'].max():.2%}")
            print(f"   Best Profit Factor: {indicator_results['profit_factor'].max():.2f}")

        if ranked.empty:
            print("No valid Sharpe ratios for this indicator.")
            continue

        for rank, (_, row) in enumerate(ranked.iterrows(), 1):
            print(f"\n#{rank} - {row['param_display']}")
            print(f"   Sharpe Ratio:      {row['sharpe_ratio']:.3f}")
            print(f"   Total Return:      {row['total_return']:.2%}")
            print(f"   Annualized Return: {row['annualized_return']:.2%}")
            print(f"   Max Drawdown:      {row['max_drawdown']:.2%}")
            print(f"   Win Rate:          {row['win_rate']:.1f}%")
            print(f"   Profit Factor:     {row['profit_factor']:.2f}")
            print(f"   Total Trades:      {int(row['total_trades'])} ({row['trades_per_year']:.1f}/year)")

    print("\n" + "=" * 70)

if successful_tests > 0:
    results_df_preview = pd.DataFrame(grid_search_results)
    print_top_in_sample_by_indicator(results_df_preview, top_n=5, include_summary=False)

INITIATING MULTI-INDICATOR GRID SEARCH OPTIMIZATION
======================================================================
Active Indicators: Triple EMA, MACD, AROON, STC, KAMA, SUPERTREND, KALMAN, RSI, ADX, DONCHIAN, TRIX, VORTEX, ALMA
Training Period: 2018-01-02 -> 2023-03-02
Market Regime: stock (252-day)
Annualization Basis: 252 bars/year (252D)
Initial Capital: $100,000
Transaction Costs: 0.05% per trade (fees + slippage)
Optimization Metric: Sharpe Ratio (risk-adjusted returns)
======================================================================
Total combinations to test: 378754
Batch size: 1000
Minimum trade frequency filter: 2/year
Each indicator grid is run separately.

Starting batched grid search...

======================================================================
Running Triple EMA grid: 66840 combinations
======================================================================
Processing Triple EMA batch 1/67
  Combinations 1 to 1000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 1000 stored, 0 filtered, 0 failed
  Triple EMA progress: 1000/66840 (1.5%)

Processing Triple EMA batch 2/67
  Combinations 1001 to 2000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 2000 stored, 0 filtered, 0 failed
  Triple EMA progress: 2000/66840 (3.0%)

Processing Triple EMA batch 3/67
  Combinations 2001 to 3000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 3000 stored, 0 filtered, 0 failed
  Triple EMA progress: 3000/66840 (4.5%)

Processing Triple EMA batch 4/67
  Combinations 3001 to 4000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 4000 stored, 0 filtered, 0 failed
  Triple EMA progress: 4000/66840 (6.0%)

Processing Triple EMA batch 5/67
  Combinations 4001 to 5000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 5000 stored, 0 filtered, 0 failed
  Triple EMA progress: 5000/66840 (7.5%)

Processing Triple EMA batch 6/67
  Combinations 5001 to 6000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 6000 stored, 0 filtered, 0 failed
  Triple EMA progress: 6000/66840 (9.0%)

Processing Triple EMA batch 7/67
  Combinations 6001 to 7000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 7000 stored, 0 filtered, 0 failed
  Triple EMA progress: 7000/66840 (10.5%)

Processing Triple EMA batch 8/67
  Combinations 7001 to 8000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 7273 stored, 727 filtered, 0 failed
  Triple EMA progress: 8000/66840 (12.0%)

Processing Triple EMA batch 9/67
  Combinations 8001 to 9000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 7273 stored, 1727 filtered, 0 failed
  Triple EMA progress: 9000/66840 (13.5%)

Processing Triple EMA batch 10/67
  Combinations 9001 to 10000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 7273 stored, 2727 filtered, 0 failed
  Triple EMA progress: 10000/66840 (15.0%)

Processing Triple EMA batch 11/67
  Combinations 10001 to 11000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 7273 stored, 3727 filtered, 0 failed
  Triple EMA progress: 11000/66840 (16.5%)

Processing Triple EMA batch 12/67
  Combinations 11001 to 12000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 8133 stored, 3867 filtered, 0 failed
  Triple EMA progress: 12000/66840 (18.0%)

Processing Triple EMA batch 13/67
  Combinations 12001 to 13000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 9133 stored, 3867 filtered, 0 failed
  Triple EMA progress: 13000/66840 (19.4%)

Processing Triple EMA batch 14/67
  Combinations 13001 to 14000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 10133 stored, 3867 filtered, 0 failed
  Triple EMA progress: 14000/66840 (20.9%)

Processing Triple EMA batch 15/67
  Combinations 14001 to 15000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 11133 stored, 3867 filtered, 0 failed
  Triple EMA progress: 15000/66840 (22.4%)

Processing Triple EMA batch 16/67
  Combinations 15001 to 16000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 12001 stored, 3999 filtered, 0 failed
  Triple EMA progress: 16000/66840 (23.9%)

Processing Triple EMA batch 17/67
  Combinations 16001 to 17000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 12094 stored, 4906 filtered, 0 failed
  Triple EMA progress: 17000/66840 (25.4%)

Processing Triple EMA batch 18/67
  Combinations 17001 to 18000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 12272 stored, 5728 filtered, 0 failed
  Triple EMA progress: 18000/66840 (26.9%)

Processing Triple EMA batch 19/67
  Combinations 18001 to 19000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 12272 stored, 6728 filtered, 0 failed
  Triple EMA progress: 19000/66840 (28.4%)

Processing Triple EMA batch 20/67
  Combinations 19001 to 20000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 12272 stored, 7728 filtered, 0 failed
  Triple EMA progress: 20000/66840 (29.9%)

Processing Triple EMA batch 21/67
  Combinations 20001 to 21000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 12272 stored, 8728 filtered, 0 failed
  Triple EMA progress: 21000/66840 (31.4%)

Processing Triple EMA batch 22/67
  Combinations 21001 to 22000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 12272 stored, 9728 filtered, 0 failed
  Triple EMA progress: 22000/66840 (32.9%)

Processing Triple EMA batch 23/67
  Combinations 22001 to 23000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 12992 stored, 10008 filtered, 0 failed
  Triple EMA progress: 23000/66840 (34.4%)

Processing Triple EMA batch 24/67
  Combinations 23001 to 24000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 13992 stored, 10008 filtered, 0 failed
  Triple EMA progress: 24000/66840 (35.9%)

Processing Triple EMA batch 25/67
  Combinations 24001 to 25000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 14992 stored, 10008 filtered, 0 failed
  Triple EMA progress: 25000/66840 (37.4%)

Processing Triple EMA batch 26/67
  Combinations 25001 to 26000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 15488 stored, 10512 filtered, 0 failed
  Triple EMA progress: 26000/66840 (38.9%)

Processing Triple EMA batch 27/67
  Combinations 26001 to 27000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 15488 stored, 11512 filtered, 0 failed
  Triple EMA progress: 27000/66840 (40.4%)

Processing Triple EMA batch 28/67
  Combinations 27001 to 28000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 15503 stored, 12497 filtered, 0 failed
  Triple EMA progress: 28000/66840 (41.9%)

Processing Triple EMA batch 29/67
  Combinations 28001 to 29000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 15707 stored, 13293 filtered, 0 failed
  Triple EMA progress: 29000/66840 (43.4%)

Processing Triple EMA batch 30/67
  Combinations 29001 to 30000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 15707 stored, 14293 filtered, 0 failed
  Triple EMA progress: 30000/66840 (44.9%)

Processing Triple EMA batch 31/67
  Combinations 30001 to 31000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 15707 stored, 15293 filtered, 0 failed
  Triple EMA progress: 31000/66840 (46.4%)

Processing Triple EMA batch 32/67
  Combinations 31001 to 32000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 15707 stored, 16293 filtered, 0 failed
  Triple EMA progress: 32000/66840 (47.9%)

Processing Triple EMA batch 33/67
  Combinations 32001 to 33000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 15707 stored, 17293 filtered, 0 failed
  Triple EMA progress: 33000/66840 (49.4%)

Processing Triple EMA batch 34/67
  Combinations 33001 to 34000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 16287 stored, 17713 filtered, 0 failed
  Triple EMA progress: 34000/66840 (50.9%)

Processing Triple EMA batch 35/67
  Combinations 34001 to 35000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 17287 stored, 17713 filtered, 0 failed
  Triple EMA progress: 35000/66840 (52.4%)

Processing Triple EMA batch 36/67
  Combinations 35001 to 36000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 18086 stored, 17914 filtered, 0 failed
  Triple EMA progress: 36000/66840 (53.9%)

Processing Triple EMA batch 37/67
  Combinations 36001 to 37000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 18092 stored, 18908 filtered, 0 failed
  Triple EMA progress: 37000/66840 (55.4%)

Processing Triple EMA batch 38/67
  Combinations 37001 to 38000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 18092 stored, 19908 filtered, 0 failed
  Triple EMA progress: 38000/66840 (56.9%)

Processing Triple EMA batch 39/67
  Combinations 38001 to 39000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 18116 stored, 20884 filtered, 0 failed
  Triple EMA progress: 39000/66840 (58.3%)

Processing Triple EMA batch 40/67
  Combinations 39001 to 40000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 18316 stored, 21684 filtered, 0 failed
  Triple EMA progress: 40000/66840 (59.8%)

Processing Triple EMA batch 41/67
  Combinations 40001 to 41000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 18323 stored, 22677 filtered, 0 failed
  Triple EMA progress: 41000/66840 (61.3%)

Processing Triple EMA batch 42/67
  Combinations 41001 to 42000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 18323 stored, 23677 filtered, 0 failed
  Triple EMA progress: 42000/66840 (62.8%)

Processing Triple EMA batch 43/67
  Combinations 42001 to 43000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 18323 stored, 24677 filtered, 0 failed
  Triple EMA progress: 43000/66840 (64.3%)

Processing Triple EMA batch 44/67
  Combinations 43001 to 44000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 18323 stored, 25677 filtered, 0 failed
  Triple EMA progress: 44000/66840 (65.8%)

Processing Triple EMA batch 45/67
  Combinations 44001 to 45000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 18763 stored, 26237 filtered, 0 failed
  Triple EMA progress: 45000/66840 (67.3%)

Processing Triple EMA batch 46/67
  Combinations 45001 to 46000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 19763 stored, 26237 filtered, 0 failed
  Triple EMA progress: 46000/66840 (68.8%)

Processing Triple EMA batch 47/67
  Combinations 46001 to 47000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 20160 stored, 26840 filtered, 0 failed
  Triple EMA progress: 47000/66840 (70.3%)

Processing Triple EMA batch 48/67
  Combinations 47001 to 48000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 20160 stored, 27840 filtered, 0 failed
  Triple EMA progress: 48000/66840 (71.8%)

Processing Triple EMA batch 49/67
  Combinations 48001 to 49000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 20160 stored, 28840 filtered, 0 failed
  Triple EMA progress: 49000/66840 (73.3%)

Processing Triple EMA batch 50/67
  Combinations 49001 to 50000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 20163 stored, 29837 filtered, 0 failed
  Triple EMA progress: 50000/66840 (74.8%)

Processing Triple EMA batch 51/67
  Combinations 50001 to 51000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 20270 stored, 30730 filtered, 0 failed
  Triple EMA progress: 51000/66840 (76.3%)

Processing Triple EMA batch 52/67
  Combinations 51001 to 52000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 20270 stored, 31730 filtered, 0 failed
  Triple EMA progress: 52000/66840 (77.8%)

Processing Triple EMA batch 53/67
  Combinations 52001 to 53000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 20270 stored, 32730 filtered, 0 failed
  Triple EMA progress: 53000/66840 (79.3%)

Processing Triple EMA batch 54/67
  Combinations 53001 to 54000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 20270 stored, 33730 filtered, 0 failed
  Triple EMA progress: 54000/66840 (80.8%)

Processing Triple EMA batch 55/67
  Combinations 54001 to 55000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 20270 stored, 34730 filtered, 0 failed
  Triple EMA progress: 55000/66840 (82.3%)

Processing Triple EMA batch 56/67
  Combinations 55001 to 56000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 20570 stored, 35430 filtered, 0 failed
  Triple EMA progress: 56000/66840 (83.8%)

Processing Triple EMA batch 57/67
  Combinations 56001 to 57000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 21166 stored, 35834 filtered, 0 failed
  Triple EMA progress: 57000/66840 (85.3%)

Processing Triple EMA batch 58/67
  Combinations 57001 to 58000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 21360 stored, 36640 filtered, 0 failed
  Triple EMA progress: 58000/66840 (86.8%)

Processing Triple EMA batch 59/67
  Combinations 58001 to 59000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 21360 stored, 37640 filtered, 0 failed
  Triple EMA progress: 59000/66840 (88.3%)

Processing Triple EMA batch 60/67
  Combinations 59001 to 60000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 21392 stored, 38608 filtered, 0 failed
  Triple EMA progress: 60000/66840 (89.8%)

Processing Triple EMA batch 61/67
  Combinations 60001 to 61000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 21408 stored, 39592 filtered, 0 failed
  Triple EMA progress: 61000/66840 (91.3%)

Processing Triple EMA batch 62/67
  Combinations 61001 to 62000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 21455 stored, 40545 filtered, 0 failed
  Triple EMA progress: 62000/66840 (92.8%)

Processing Triple EMA batch 63/67
  Combinations 62001 to 63000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 21455 stored, 41545 filtered, 0 failed
  Triple EMA progress: 63000/66840 (94.3%)

Processing Triple EMA batch 64/67
  Combinations 63001 to 64000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 21455 stored, 42545 filtered, 0 failed
  Triple EMA progress: 64000/66840 (95.8%)

Processing Triple EMA batch 65/67
  Combinations 64001 to 65000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 21455 stored, 43545 filtered, 0 failed
  Triple EMA progress: 65000/66840 (97.2%)

Processing Triple EMA batch 66/67
  Combinations 65001 to 66000...

  Running vectorized backtest on 1000 Triple EMA combinations...

  Triple EMA batch complete: 21455 stored, 44545 filtered, 0 failed
  Triple EMA progress: 66000/66840 (98.7%)

Processing Triple EMA batch 67/67
  Combinations 66001 to 66840...

  Running vectorized backtest on 840 Triple EMA combinations...

  Triple EMA batch complete: 21455 stored, 45385 filtered, 0 failed
  Triple EMA progress: 66840/66840 (100.0%)

======================================================================
Running MACD grid: 128000 combinations
======================================================================
Processing MACD batch 1/128
  Combinations 1 to 1000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 1000 stored, 0 filtered, 0 failed
  MACD progress: 1000/128000 (0.8%)

Processing MACD batch 2/128
  Combinations 1001 to 2000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 2000 stored, 0 filtered, 0 failed
  MACD progress: 2000/128000 (1.6%)

Processing MACD batch 3/128
  Combinations 2001 to 3000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 3000 stored, 0 filtered, 0 failed
  MACD progress: 3000/128000 (2.3%)

Processing MACD batch 4/128
  Combinations 3001 to 4000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 4000 stored, 0 filtered, 0 failed
  MACD progress: 4000/128000 (3.1%)

Processing MACD batch 5/128
  Combinations 4001 to 5000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 5000 stored, 0 filtered, 0 failed
  MACD progress: 5000/128000 (3.9%)

Processing MACD batch 6/128
  Combinations 5001 to 6000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 6000 stored, 0 filtered, 0 failed
  MACD progress: 6000/128000 (4.7%)

Processing MACD batch 7/128
  Combinations 6001 to 7000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 7000 stored, 0 filtered, 0 failed
  MACD progress: 7000/128000 (5.5%)

Processing MACD batch 8/128
  Combinations 7001 to 8000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 8000 stored, 0 filtered, 0 failed
  MACD progress: 8000/128000 (6.2%)

Processing MACD batch 9/128
  Combinations 8001 to 9000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 9000 stored, 0 filtered, 0 failed
  MACD progress: 9000/128000 (7.0%)

Processing MACD batch 10/128
  Combinations 9001 to 10000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 10000 stored, 0 filtered, 0 failed
  MACD progress: 10000/128000 (7.8%)

Processing MACD batch 11/128
  Combinations 10001 to 11000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 11000 stored, 0 filtered, 0 failed
  MACD progress: 11000/128000 (8.6%)

Processing MACD batch 12/128
  Combinations 11001 to 12000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 12000 stored, 0 filtered, 0 failed
  MACD progress: 12000/128000 (9.4%)

Processing MACD batch 13/128
  Combinations 12001 to 13000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 13000 stored, 0 filtered, 0 failed
  MACD progress: 13000/128000 (10.2%)

Processing MACD batch 14/128
  Combinations 13001 to 14000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 14000 stored, 0 filtered, 0 failed
  MACD progress: 14000/128000 (10.9%)

Processing MACD batch 15/128
  Combinations 14001 to 15000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 15000 stored, 0 filtered, 0 failed
  MACD progress: 15000/128000 (11.7%)

Processing MACD batch 16/128
  Combinations 15001 to 16000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 16000 stored, 0 filtered, 0 failed
  MACD progress: 16000/128000 (12.5%)

Processing MACD batch 17/128
  Combinations 16001 to 17000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 17000 stored, 0 filtered, 0 failed
  MACD progress: 17000/128000 (13.3%)

Processing MACD batch 18/128
  Combinations 17001 to 18000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 18000 stored, 0 filtered, 0 failed
  MACD progress: 18000/128000 (14.1%)

Processing MACD batch 19/128
  Combinations 18001 to 19000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 19000 stored, 0 filtered, 0 failed
  MACD progress: 19000/128000 (14.8%)

Processing MACD batch 20/128
  Combinations 19001 to 20000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 20000 stored, 0 filtered, 0 failed
  MACD progress: 20000/128000 (15.6%)

Processing MACD batch 21/128
  Combinations 20001 to 21000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 21000 stored, 0 filtered, 0 failed
  MACD progress: 21000/128000 (16.4%)

Processing MACD batch 22/128
  Combinations 21001 to 22000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 22000 stored, 0 filtered, 0 failed
  MACD progress: 22000/128000 (17.2%)

Processing MACD batch 23/128
  Combinations 22001 to 23000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 23000 stored, 0 filtered, 0 failed
  MACD progress: 23000/128000 (18.0%)

Processing MACD batch 24/128
  Combinations 23001 to 24000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 24000 stored, 0 filtered, 0 failed
  MACD progress: 24000/128000 (18.8%)

Processing MACD batch 25/128
  Combinations 24001 to 25000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 25000 stored, 0 filtered, 0 failed
  MACD progress: 25000/128000 (19.5%)

Processing MACD batch 26/128
  Combinations 25001 to 26000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 26000 stored, 0 filtered, 0 failed
  MACD progress: 26000/128000 (20.3%)

Processing MACD batch 27/128
  Combinations 26001 to 27000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 27000 stored, 0 filtered, 0 failed
  MACD progress: 27000/128000 (21.1%)

Processing MACD batch 28/128
  Combinations 27001 to 28000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 28000 stored, 0 filtered, 0 failed
  MACD progress: 28000/128000 (21.9%)

Processing MACD batch 29/128
  Combinations 28001 to 29000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 29000 stored, 0 filtered, 0 failed
  MACD progress: 29000/128000 (22.7%)

Processing MACD batch 30/128
  Combinations 29001 to 30000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 30000 stored, 0 filtered, 0 failed
  MACD progress: 30000/128000 (23.4%)

Processing MACD batch 31/128
  Combinations 30001 to 31000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 31000 stored, 0 filtered, 0 failed
  MACD progress: 31000/128000 (24.2%)

Processing MACD batch 32/128
  Combinations 31001 to 32000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 32000 stored, 0 filtered, 0 failed
  MACD progress: 32000/128000 (25.0%)

Processing MACD batch 33/128
  Combinations 32001 to 33000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 33000 stored, 0 filtered, 0 failed
  MACD progress: 33000/128000 (25.8%)

Processing MACD batch 34/128
  Combinations 33001 to 34000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 34000 stored, 0 filtered, 0 failed
  MACD progress: 34000/128000 (26.6%)

Processing MACD batch 35/128
  Combinations 34001 to 35000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 35000 stored, 0 filtered, 0 failed
  MACD progress: 35000/128000 (27.3%)

Processing MACD batch 36/128
  Combinations 35001 to 36000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 36000 stored, 0 filtered, 0 failed
  MACD progress: 36000/128000 (28.1%)

Processing MACD batch 37/128
  Combinations 36001 to 37000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 37000 stored, 0 filtered, 0 failed
  MACD progress: 37000/128000 (28.9%)

Processing MACD batch 38/128
  Combinations 37001 to 38000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 38000 stored, 0 filtered, 0 failed
  MACD progress: 38000/128000 (29.7%)

Processing MACD batch 39/128
  Combinations 38001 to 39000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 39000 stored, 0 filtered, 0 failed
  MACD progress: 39000/128000 (30.5%)

Processing MACD batch 40/128
  Combinations 39001 to 40000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 40000 stored, 0 filtered, 0 failed
  MACD progress: 40000/128000 (31.2%)

Processing MACD batch 41/128
  Combinations 40001 to 41000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 41000 stored, 0 filtered, 0 failed
  MACD progress: 41000/128000 (32.0%)

Processing MACD batch 42/128
  Combinations 41001 to 42000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 42000 stored, 0 filtered, 0 failed
  MACD progress: 42000/128000 (32.8%)

Processing MACD batch 43/128
  Combinations 42001 to 43000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 42986 stored, 14 filtered, 0 failed
  MACD progress: 43000/128000 (33.6%)

Processing MACD batch 44/128
  Combinations 43001 to 44000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 43949 stored, 51 filtered, 0 failed
  MACD progress: 44000/128000 (34.4%)

Processing MACD batch 45/128
  Combinations 44001 to 45000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 44928 stored, 72 filtered, 0 failed
  MACD progress: 45000/128000 (35.2%)

Processing MACD batch 46/128
  Combinations 45001 to 46000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 45867 stored, 133 filtered, 0 failed
  MACD progress: 46000/128000 (35.9%)

Processing MACD batch 47/128
  Combinations 46001 to 47000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 46793 stored, 207 filtered, 0 failed
  MACD progress: 47000/128000 (36.7%)

Processing MACD batch 48/128
  Combinations 47001 to 48000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 47730 stored, 270 filtered, 0 failed
  MACD progress: 48000/128000 (37.5%)

Processing MACD batch 49/128
  Combinations 48001 to 49000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 48637 stored, 363 filtered, 0 failed
  MACD progress: 49000/128000 (38.3%)

Processing MACD batch 50/128
  Combinations 49001 to 50000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 49516 stored, 484 filtered, 0 failed
  MACD progress: 50000/128000 (39.1%)

Processing MACD batch 51/128
  Combinations 50001 to 51000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 50413 stored, 587 filtered, 0 failed
  MACD progress: 51000/128000 (39.8%)

Processing MACD batch 52/128
  Combinations 51001 to 52000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 51306 stored, 694 filtered, 0 failed
  MACD progress: 52000/128000 (40.6%)

Processing MACD batch 53/128
  Combinations 52001 to 53000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 52156 stored, 844 filtered, 0 failed
  MACD progress: 53000/128000 (41.4%)

Processing MACD batch 54/128
  Combinations 53001 to 54000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 53018 stored, 982 filtered, 0 failed
  MACD progress: 54000/128000 (42.2%)

Processing MACD batch 55/128
  Combinations 54001 to 55000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 53919 stored, 1081 filtered, 0 failed
  MACD progress: 55000/128000 (43.0%)

Processing MACD batch 56/128
  Combinations 55001 to 56000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 54748 stored, 1252 filtered, 0 failed
  MACD progress: 56000/128000 (43.8%)

Processing MACD batch 57/128
  Combinations 56001 to 57000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 55600 stored, 1400 filtered, 0 failed
  MACD progress: 57000/128000 (44.5%)

Processing MACD batch 58/128
  Combinations 57001 to 58000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 56505 stored, 1495 filtered, 0 failed
  MACD progress: 58000/128000 (45.3%)

Processing MACD batch 59/128
  Combinations 58001 to 59000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 57354 stored, 1646 filtered, 0 failed
  MACD progress: 59000/128000 (46.1%)

Processing MACD batch 60/128
  Combinations 59001 to 60000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 58195 stored, 1805 filtered, 0 failed
  MACD progress: 60000/128000 (46.9%)

Processing MACD batch 61/128
  Combinations 60001 to 61000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 59098 stored, 1902 filtered, 0 failed
  MACD progress: 61000/128000 (47.7%)

Processing MACD batch 62/128
  Combinations 61001 to 62000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 59944 stored, 2056 filtered, 0 failed
  MACD progress: 62000/128000 (48.4%)

Processing MACD batch 63/128
  Combinations 62001 to 63000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 60791 stored, 2209 filtered, 0 failed
  MACD progress: 63000/128000 (49.2%)

Processing MACD batch 64/128
  Combinations 63001 to 64000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 61678 stored, 2322 filtered, 0 failed
  MACD progress: 64000/128000 (50.0%)

Processing MACD batch 65/128
  Combinations 64001 to 65000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 62553 stored, 2447 filtered, 0 failed
  MACD progress: 65000/128000 (50.8%)

Processing MACD batch 66/128
  Combinations 65001 to 66000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 63394 stored, 2606 filtered, 0 failed
  MACD progress: 66000/128000 (51.6%)

Processing MACD batch 67/128
  Combinations 66001 to 67000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 64272 stored, 2728 filtered, 0 failed
  MACD progress: 67000/128000 (52.3%)

Processing MACD batch 68/128
  Combinations 67001 to 68000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 65155 stored, 2845 filtered, 0 failed
  MACD progress: 68000/128000 (53.1%)

Processing MACD batch 69/128
  Combinations 68001 to 69000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 65998 stored, 3002 filtered, 0 failed
  MACD progress: 69000/128000 (53.9%)

Processing MACD batch 70/128
  Combinations 69001 to 70000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 66872 stored, 3128 filtered, 0 failed
  MACD progress: 70000/128000 (54.7%)

Processing MACD batch 71/128
  Combinations 70001 to 71000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 67764 stored, 3236 filtered, 0 failed
  MACD progress: 71000/128000 (55.5%)

Processing MACD batch 72/128
  Combinations 71001 to 72000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 68601 stored, 3399 filtered, 0 failed
  MACD progress: 72000/128000 (56.2%)

Processing MACD batch 73/128
  Combinations 72001 to 73000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 69466 stored, 3534 filtered, 0 failed
  MACD progress: 73000/128000 (57.0%)

Processing MACD batch 74/128
  Combinations 73001 to 74000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 70360 stored, 3640 filtered, 0 failed
  MACD progress: 74000/128000 (57.8%)

Processing MACD batch 75/128
  Combinations 74001 to 75000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 71206 stored, 3794 filtered, 0 failed
  MACD progress: 75000/128000 (58.6%)

Processing MACD batch 76/128
  Combinations 75001 to 76000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 72066 stored, 3934 filtered, 0 failed
  MACD progress: 76000/128000 (59.4%)

Processing MACD batch 77/128
  Combinations 76001 to 77000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 72965 stored, 4035 filtered, 0 failed
  MACD progress: 77000/128000 (60.2%)

Processing MACD batch 78/128
  Combinations 77001 to 78000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 73802 stored, 4198 filtered, 0 failed
  MACD progress: 78000/128000 (60.9%)

Processing MACD batch 79/128
  Combinations 78001 to 79000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 74654 stored, 4346 filtered, 0 failed
  MACD progress: 79000/128000 (61.7%)

Processing MACD batch 80/128
  Combinations 79001 to 80000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 75553 stored, 4447 filtered, 0 failed
  MACD progress: 80000/128000 (62.5%)

Processing MACD batch 81/128
  Combinations 80001 to 81000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 76406 stored, 4594 filtered, 0 failed
  MACD progress: 81000/128000 (63.3%)

Processing MACD batch 82/128
  Combinations 81001 to 82000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 77255 stored, 4745 filtered, 0 failed
  MACD progress: 82000/128000 (64.1%)

Processing MACD batch 83/128
  Combinations 82001 to 83000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 78138 stored, 4862 filtered, 0 failed
  MACD progress: 83000/128000 (64.8%)

Processing MACD batch 84/128
  Combinations 83001 to 84000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 78990 stored, 5010 filtered, 0 failed
  MACD progress: 84000/128000 (65.6%)

Processing MACD batch 85/128
  Combinations 84001 to 85000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 79824 stored, 5176 filtered, 0 failed
  MACD progress: 85000/128000 (66.4%)

Processing MACD batch 86/128
  Combinations 85001 to 86000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 80705 stored, 5295 filtered, 0 failed
  MACD progress: 86000/128000 (67.2%)

Processing MACD batch 87/128
  Combinations 86001 to 87000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 81564 stored, 5436 filtered, 0 failed
  MACD progress: 87000/128000 (68.0%)

Processing MACD batch 88/128
  Combinations 87001 to 88000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 82381 stored, 5619 filtered, 0 failed
  MACD progress: 88000/128000 (68.8%)

Processing MACD batch 89/128
  Combinations 88001 to 89000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 83238 stored, 5762 filtered, 0 failed
  MACD progress: 89000/128000 (69.5%)

Processing MACD batch 90/128
  Combinations 89001 to 90000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 84101 stored, 5899 filtered, 0 failed
  MACD progress: 90000/128000 (70.3%)

Processing MACD batch 91/128
  Combinations 90001 to 91000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 84910 stored, 6090 filtered, 0 failed
  MACD progress: 91000/128000 (71.1%)

Processing MACD batch 92/128
  Combinations 91001 to 92000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 85758 stored, 6242 filtered, 0 failed
  MACD progress: 92000/128000 (71.9%)

Processing MACD batch 93/128
  Combinations 92001 to 93000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 86630 stored, 6370 filtered, 0 failed
  MACD progress: 93000/128000 (72.7%)

Processing MACD batch 94/128
  Combinations 93001 to 94000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 87422 stored, 6578 filtered, 0 failed
  MACD progress: 94000/128000 (73.4%)

Processing MACD batch 95/128
  Combinations 94001 to 95000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 88252 stored, 6748 filtered, 0 failed
  MACD progress: 95000/128000 (74.2%)

Processing MACD batch 96/128
  Combinations 95001 to 96000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 89135 stored, 6865 filtered, 0 failed
  MACD progress: 96000/128000 (75.0%)

Processing MACD batch 97/128
  Combinations 96001 to 97000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 89922 stored, 7078 filtered, 0 failed
  MACD progress: 97000/128000 (75.8%)

Processing MACD batch 98/128
  Combinations 97001 to 98000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 90748 stored, 7252 filtered, 0 failed
  MACD progress: 98000/128000 (76.6%)

Processing MACD batch 99/128
  Combinations 98001 to 99000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 91611 stored, 7389 filtered, 0 failed
  MACD progress: 99000/128000 (77.3%)

Processing MACD batch 100/128
  Combinations 99001 to 100000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 92410 stored, 7590 filtered, 0 failed
  MACD progress: 100000/128000 (78.1%)

Processing MACD batch 101/128
  Combinations 100001 to 101000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 93213 stored, 7787 filtered, 0 failed
  MACD progress: 101000/128000 (78.9%)

Processing MACD batch 102/128
  Combinations 101001 to 102000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 94070 stored, 7930 filtered, 0 failed
  MACD progress: 102000/128000 (79.7%)

Processing MACD batch 103/128
  Combinations 102001 to 103000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 94850 stored, 8150 filtered, 0 failed
  MACD progress: 103000/128000 (80.5%)

Processing MACD batch 104/128
  Combinations 103001 to 104000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 95649 stored, 8351 filtered, 0 failed
  MACD progress: 104000/128000 (81.2%)

Processing MACD batch 105/128
  Combinations 104001 to 105000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 96479 stored, 8521 filtered, 0 failed
  MACD progress: 105000/128000 (82.0%)

Processing MACD batch 106/128
  Combinations 105001 to 106000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 97238 stored, 8762 filtered, 0 failed
  MACD progress: 106000/128000 (82.8%)

Processing MACD batch 107/128
  Combinations 106001 to 107000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 98018 stored, 8982 filtered, 0 failed
  MACD progress: 107000/128000 (83.6%)

Processing MACD batch 108/128
  Combinations 107001 to 108000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 98848 stored, 9152 filtered, 0 failed
  MACD progress: 108000/128000 (84.4%)

Processing MACD batch 109/128
  Combinations 108001 to 109000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 99497 stored, 9503 filtered, 0 failed
  MACD progress: 109000/128000 (85.2%)

Processing MACD batch 110/128
  Combinations 109001 to 110000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 100276 stored, 9724 filtered, 0 failed
  MACD progress: 110000/128000 (85.9%)

Processing MACD batch 111/128
  Combinations 110001 to 111000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 101060 stored, 9940 filtered, 0 failed
  MACD progress: 111000/128000 (86.7%)

Processing MACD batch 112/128
  Combinations 111001 to 112000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 101555 stored, 10445 filtered, 0 failed
  MACD progress: 112000/128000 (87.5%)

Processing MACD batch 113/128
  Combinations 112001 to 113000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 102314 stored, 10686 filtered, 0 failed
  MACD progress: 113000/128000 (88.3%)

Processing MACD batch 114/128
  Combinations 113001 to 114000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 103048 stored, 10952 filtered, 0 failed
  MACD progress: 114000/128000 (89.1%)

Processing MACD batch 115/128
  Combinations 114001 to 115000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 103520 stored, 11480 filtered, 0 failed
  MACD progress: 115000/128000 (89.8%)

Processing MACD batch 116/128
  Combinations 115001 to 116000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 104204 stored, 11796 filtered, 0 failed
  MACD progress: 116000/128000 (90.6%)

Processing MACD batch 117/128
  Combinations 116001 to 117000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 104906 stored, 12094 filtered, 0 failed
  MACD progress: 117000/128000 (91.4%)

Processing MACD batch 118/128
  Combinations 117001 to 118000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 105357 stored, 12643 filtered, 0 failed
  MACD progress: 118000/128000 (92.2%)

Processing MACD batch 119/128
  Combinations 118001 to 119000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 105975 stored, 13025 filtered, 0 failed
  MACD progress: 119000/128000 (93.0%)

Processing MACD batch 120/128
  Combinations 119001 to 120000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 106666 stored, 13334 filtered, 0 failed
  MACD progress: 120000/128000 (93.8%)

Processing MACD batch 121/128
  Combinations 120001 to 121000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 107133 stored, 13867 filtered, 0 failed
  MACD progress: 121000/128000 (94.5%)

Processing MACD batch 122/128
  Combinations 121001 to 122000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 107660 stored, 14340 filtered, 0 failed
  MACD progress: 122000/128000 (95.3%)

Processing MACD batch 123/128
  Combinations 122001 to 123000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 108344 stored, 14656 filtered, 0 failed
  MACD progress: 123000/128000 (96.1%)

Processing MACD batch 124/128
  Combinations 123001 to 124000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 108796 stored, 15204 filtered, 0 failed
  MACD progress: 124000/128000 (96.9%)

Processing MACD batch 125/128
  Combinations 124001 to 125000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 109254 stored, 15746 filtered, 0 failed
  MACD progress: 125000/128000 (97.7%)

Processing MACD batch 126/128
  Combinations 125001 to 126000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 109949 stored, 16051 filtered, 0 failed
  MACD progress: 126000/128000 (98.4%)

Processing MACD batch 127/128
  Combinations 126001 to 127000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 110422 stored, 16578 filtered, 0 failed
  MACD progress: 127000/128000 (99.2%)

Processing MACD batch 128/128
  Combinations 127001 to 128000...

  Running vectorized backtest on 1000 MACD combinations...

  MACD batch complete: 110789 stored, 17211 filtered, 0 failed
  MACD progress: 128000/128000 (100.0%)

======================================================================
Running AROON grid: 76 combinations
======================================================================
Processing AROON batch 1/1
  Combinations 1 to 76...

  Running vectorized backtest on 76 AROON combinations...

  AROON batch complete: 59 stored, 17 filtered, 0 failed
  AROON progress: 76/76 (100.0%)

======================================================================
Running STC grid: 128000 combinations
======================================================================
Processing STC batch 1/128
  Combinations 1 to 1000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 586 stored, 414 filtered, 0 failed
  STC progress: 1000/128000 (0.8%)

Processing STC batch 2/128
  Combinations 1001 to 2000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 1127 stored, 873 filtered, 0 failed
  STC progress: 2000/128000 (1.6%)

Processing STC batch 3/128
  Combinations 2001 to 3000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 1679 stored, 1321 filtered, 0 failed
  STC progress: 3000/128000 (2.3%)

Processing STC batch 4/128
  Combinations 3001 to 4000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 2218 stored, 1782 filtered, 0 failed
  STC progress: 4000/128000 (3.1%)

Processing STC batch 5/128
  Combinations 4001 to 5000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 2787 stored, 2213 filtered, 0 failed
  STC progress: 5000/128000 (3.9%)

Processing STC batch 6/128
  Combinations 5001 to 6000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 3307 stored, 2693 filtered, 0 failed
  STC progress: 6000/128000 (4.7%)

Processing STC batch 7/128
  Combinations 6001 to 7000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 3871 stored, 3129 filtered, 0 failed
  STC progress: 7000/128000 (5.5%)

Processing STC batch 8/128
  Combinations 7001 to 8000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 4398 stored, 3602 filtered, 0 failed
  STC progress: 8000/128000 (6.2%)

Processing STC batch 9/128
  Combinations 8001 to 9000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 4956 stored, 4044 filtered, 0 failed
  STC progress: 9000/128000 (7.0%)

Processing STC batch 10/128
  Combinations 9001 to 10000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 5466 stored, 4534 filtered, 0 failed
  STC progress: 10000/128000 (7.8%)

Processing STC batch 11/128
  Combinations 10001 to 11000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 6027 stored, 4973 filtered, 0 failed
  STC progress: 11000/128000 (8.6%)

Processing STC batch 12/128
  Combinations 11001 to 12000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 6548 stored, 5452 filtered, 0 failed
  STC progress: 12000/128000 (9.4%)

Processing STC batch 13/128
  Combinations 12001 to 13000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 7086 stored, 5914 filtered, 0 failed
  STC progress: 13000/128000 (10.2%)

Processing STC batch 14/128
  Combinations 13001 to 14000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 7609 stored, 6391 filtered, 0 failed
  STC progress: 14000/128000 (10.9%)

Processing STC batch 15/128
  Combinations 14001 to 15000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 8160 stored, 6840 filtered, 0 failed
  STC progress: 15000/128000 (11.7%)

Processing STC batch 16/128
  Combinations 15001 to 16000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 8651 stored, 7349 filtered, 0 failed
  STC progress: 16000/128000 (12.5%)

Processing STC batch 17/128
  Combinations 16001 to 17000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 9207 stored, 7793 filtered, 0 failed
  STC progress: 17000/128000 (13.3%)

Processing STC batch 18/128
  Combinations 17001 to 18000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 9717 stored, 8283 filtered, 0 failed
  STC progress: 18000/128000 (14.1%)

Processing STC batch 19/128
  Combinations 18001 to 19000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 10241 stored, 8759 filtered, 0 failed
  STC progress: 19000/128000 (14.8%)

Processing STC batch 20/128
  Combinations 19001 to 20000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 10748 stored, 9252 filtered, 0 failed
  STC progress: 20000/128000 (15.6%)

Processing STC batch 21/128
  Combinations 20001 to 21000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 11287 stored, 9713 filtered, 0 failed
  STC progress: 21000/128000 (16.4%)

Processing STC batch 22/128
  Combinations 21001 to 22000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 11776 stored, 10224 filtered, 0 failed
  STC progress: 22000/128000 (17.2%)

Processing STC batch 23/128
  Combinations 22001 to 23000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 12309 stored, 10691 filtered, 0 failed
  STC progress: 23000/128000 (18.0%)

Processing STC batch 24/128
  Combinations 23001 to 24000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 12812 stored, 11188 filtered, 0 failed
  STC progress: 24000/128000 (18.8%)

Processing STC batch 25/128
  Combinations 24001 to 25000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 13335 stored, 11665 filtered, 0 failed
  STC progress: 25000/128000 (19.5%)

Processing STC batch 26/128
  Combinations 25001 to 26000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 13821 stored, 12179 filtered, 0 failed
  STC progress: 26000/128000 (20.3%)

Processing STC batch 27/128
  Combinations 26001 to 27000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 14355 stored, 12645 filtered, 0 failed
  STC progress: 27000/128000 (21.1%)

Processing STC batch 28/128
  Combinations 27001 to 28000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 14844 stored, 13156 filtered, 0 failed
  STC progress: 28000/128000 (21.9%)

Processing STC batch 29/128
  Combinations 28001 to 29000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 15353 stored, 13647 filtered, 0 failed
  STC progress: 29000/128000 (22.7%)

Processing STC batch 30/128
  Combinations 29001 to 30000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 15852 stored, 14148 filtered, 0 failed
  STC progress: 30000/128000 (23.4%)

Processing STC batch 31/128
  Combinations 30001 to 31000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 16374 stored, 14626 filtered, 0 failed
  STC progress: 31000/128000 (24.2%)

Processing STC batch 32/128
  Combinations 31001 to 32000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 16832 stored, 15168 filtered, 0 failed
  STC progress: 32000/128000 (25.0%)

Processing STC batch 33/128
  Combinations 32001 to 33000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 17364 stored, 15636 filtered, 0 failed
  STC progress: 33000/128000 (25.8%)

Processing STC batch 34/128
  Combinations 33001 to 34000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 17850 stored, 16150 filtered, 0 failed
  STC progress: 34000/128000 (26.6%)

Processing STC batch 35/128
  Combinations 34001 to 35000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 18342 stored, 16658 filtered, 0 failed
  STC progress: 35000/128000 (27.3%)

Processing STC batch 36/128
  Combinations 35001 to 36000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 18827 stored, 17173 filtered, 0 failed
  STC progress: 36000/128000 (28.1%)

Processing STC batch 37/128
  Combinations 36001 to 37000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 19344 stored, 17656 filtered, 0 failed
  STC progress: 37000/128000 (28.9%)

Processing STC batch 38/128
  Combinations 37001 to 38000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 19805 stored, 18195 filtered, 0 failed
  STC progress: 38000/128000 (29.7%)

Processing STC batch 39/128
  Combinations 38001 to 39000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 20312 stored, 18688 filtered, 0 failed
  STC progress: 39000/128000 (30.5%)

Processing STC batch 40/128
  Combinations 39001 to 40000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 20794 stored, 19206 filtered, 0 failed
  STC progress: 40000/128000 (31.2%)

Processing STC batch 41/128
  Combinations 40001 to 41000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 21290 stored, 19710 filtered, 0 failed
  STC progress: 41000/128000 (32.0%)

Processing STC batch 42/128
  Combinations 41001 to 42000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 21749 stored, 20251 filtered, 0 failed
  STC progress: 42000/128000 (32.8%)

Processing STC batch 43/128
  Combinations 42001 to 43000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 22262 stored, 20738 filtered, 0 failed
  STC progress: 43000/128000 (33.6%)

Processing STC batch 44/128
  Combinations 43001 to 44000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 22724 stored, 21276 filtered, 0 failed
  STC progress: 44000/128000 (34.4%)

Processing STC batch 45/128
  Combinations 44001 to 45000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 23205 stored, 21795 filtered, 0 failed
  STC progress: 45000/128000 (35.2%)

Processing STC batch 46/128
  Combinations 45001 to 46000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 23684 stored, 22316 filtered, 0 failed
  STC progress: 46000/128000 (35.9%)

Processing STC batch 47/128
  Combinations 46001 to 47000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 24177 stored, 22823 filtered, 0 failed
  STC progress: 47000/128000 (36.7%)

Processing STC batch 48/128
  Combinations 47001 to 48000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 24605 stored, 23395 filtered, 0 failed
  STC progress: 48000/128000 (37.5%)

Processing STC batch 49/128
  Combinations 48001 to 49000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 25125 stored, 23875 filtered, 0 failed
  STC progress: 49000/128000 (38.3%)

Processing STC batch 50/128
  Combinations 49001 to 50000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 25586 stored, 24414 filtered, 0 failed
  STC progress: 50000/128000 (39.1%)

Processing STC batch 51/128
  Combinations 50001 to 51000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 26050 stored, 24950 filtered, 0 failed
  STC progress: 51000/128000 (39.8%)

Processing STC batch 52/128
  Combinations 51001 to 52000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 26522 stored, 25478 filtered, 0 failed
  STC progress: 52000/128000 (40.6%)

Processing STC batch 53/128
  Combinations 52001 to 53000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 27016 stored, 25984 filtered, 0 failed
  STC progress: 53000/128000 (41.4%)

Processing STC batch 54/128
  Combinations 53001 to 54000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 27447 stored, 26553 filtered, 0 failed
  STC progress: 54000/128000 (42.2%)

Processing STC batch 55/128
  Combinations 54001 to 55000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 27933 stored, 27067 filtered, 0 failed
  STC progress: 55000/128000 (43.0%)

Processing STC batch 56/128
  Combinations 55001 to 56000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 28396 stored, 27604 filtered, 0 failed
  STC progress: 56000/128000 (43.8%)

Processing STC batch 57/128
  Combinations 56001 to 57000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 28854 stored, 28146 filtered, 0 failed
  STC progress: 57000/128000 (44.5%)

Processing STC batch 58/128
  Combinations 57001 to 58000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 29291 stored, 28709 filtered, 0 failed
  STC progress: 58000/128000 (45.3%)

Processing STC batch 59/128
  Combinations 58001 to 59000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 29787 stored, 29213 filtered, 0 failed
  STC progress: 59000/128000 (46.1%)

Processing STC batch 60/128
  Combinations 59001 to 60000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 30210 stored, 29790 filtered, 0 failed
  STC progress: 60000/128000 (46.9%)

Processing STC batch 61/128
  Combinations 60001 to 61000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 30665 stored, 30335 filtered, 0 failed
  STC progress: 61000/128000 (47.7%)

Processing STC batch 62/128
  Combinations 61001 to 62000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 31129 stored, 30871 filtered, 0 failed
  STC progress: 62000/128000 (48.4%)

Processing STC batch 63/128
  Combinations 62001 to 63000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 31586 stored, 31414 filtered, 0 failed
  STC progress: 63000/128000 (49.2%)

Processing STC batch 64/128
  Combinations 63001 to 64000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 31994 stored, 32006 filtered, 0 failed
  STC progress: 64000/128000 (50.0%)

Processing STC batch 65/128
  Combinations 64001 to 65000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 32487 stored, 32513 filtered, 0 failed
  STC progress: 65000/128000 (50.8%)

Processing STC batch 66/128
  Combinations 65001 to 66000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 32915 stored, 33085 filtered, 0 failed
  STC progress: 66000/128000 (51.6%)

Processing STC batch 67/128
  Combinations 66001 to 67000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 33357 stored, 33643 filtered, 0 failed
  STC progress: 67000/128000 (52.3%)

Processing STC batch 68/128
  Combinations 67001 to 68000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 33807 stored, 34193 filtered, 0 failed
  STC progress: 68000/128000 (53.1%)

Processing STC batch 69/128
  Combinations 68001 to 69000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 34270 stored, 34730 filtered, 0 failed
  STC progress: 69000/128000 (53.9%)

Processing STC batch 70/128
  Combinations 69001 to 70000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 34669 stored, 35331 filtered, 0 failed
  STC progress: 70000/128000 (54.7%)

Processing STC batch 71/128
  Combinations 70001 to 71000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 35135 stored, 35865 filtered, 0 failed
  STC progress: 71000/128000 (55.5%)

Processing STC batch 72/128
  Combinations 71001 to 72000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 35565 stored, 36435 filtered, 0 failed
  STC progress: 72000/128000 (56.2%)

Processing STC batch 73/128
  Combinations 72001 to 73000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 35994 stored, 37006 filtered, 0 failed
  STC progress: 73000/128000 (57.0%)

Processing STC batch 74/128
  Combinations 73001 to 74000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 36413 stored, 37587 filtered, 0 failed
  STC progress: 74000/128000 (57.8%)

Processing STC batch 75/128
  Combinations 74001 to 75000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 36876 stored, 38124 filtered, 0 failed
  STC progress: 75000/128000 (58.6%)

Processing STC batch 76/128
  Combinations 75001 to 76000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 37273 stored, 38727 filtered, 0 failed
  STC progress: 76000/128000 (59.4%)

Processing STC batch 77/128
  Combinations 76001 to 77000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 37712 stored, 39288 filtered, 0 failed
  STC progress: 77000/128000 (60.2%)

Processing STC batch 78/128
  Combinations 77001 to 78000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 38144 stored, 39856 filtered, 0 failed
  STC progress: 78000/128000 (60.9%)

Processing STC batch 79/128
  Combinations 78001 to 79000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 38574 stored, 40426 filtered, 0 failed
  STC progress: 79000/128000 (61.7%)

Processing STC batch 80/128
  Combinations 79001 to 80000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 38970 stored, 41030 filtered, 0 failed
  STC progress: 80000/128000 (62.5%)

Processing STC batch 81/128
  Combinations 80001 to 81000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 39435 stored, 41565 filtered, 0 failed
  STC progress: 81000/128000 (63.3%)

Processing STC batch 82/128
  Combinations 81001 to 82000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 39833 stored, 42167 filtered, 0 failed
  STC progress: 82000/128000 (64.1%)

Processing STC batch 83/128
  Combinations 82001 to 83000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 40262 stored, 42738 filtered, 0 failed
  STC progress: 83000/128000 (64.8%)

Processing STC batch 84/128
  Combinations 83001 to 84000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 40687 stored, 43313 filtered, 0 failed
  STC progress: 84000/128000 (65.6%)

Processing STC batch 85/128
  Combinations 84001 to 85000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 41119 stored, 43881 filtered, 0 failed
  STC progress: 85000/128000 (66.4%)

Processing STC batch 86/128
  Combinations 85001 to 86000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 41512 stored, 44488 filtered, 0 failed
  STC progress: 86000/128000 (67.2%)

Processing STC batch 87/128
  Combinations 86001 to 87000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 41961 stored, 45039 filtered, 0 failed
  STC progress: 87000/128000 (68.0%)

Processing STC batch 88/128
  Combinations 87001 to 88000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 42361 stored, 45639 filtered, 0 failed
  STC progress: 88000/128000 (68.8%)

Processing STC batch 89/128
  Combinations 88001 to 89000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 42777 stored, 46223 filtered, 0 failed
  STC progress: 89000/128000 (69.5%)

Processing STC batch 90/128
  Combinations 89001 to 90000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 43179 stored, 46821 filtered, 0 failed
  STC progress: 90000/128000 (70.3%)

Processing STC batch 91/128
  Combinations 90001 to 91000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 43611 stored, 47389 filtered, 0 failed
  STC progress: 91000/128000 (71.1%)

Processing STC batch 92/128
  Combinations 91001 to 92000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 43995 stored, 48005 filtered, 0 failed
  STC progress: 92000/128000 (71.9%)

Processing STC batch 93/128
  Combinations 92001 to 93000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 44420 stored, 48580 filtered, 0 failed
  STC progress: 93000/128000 (72.7%)

Processing STC batch 94/128
  Combinations 93001 to 94000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 44821 stored, 49179 filtered, 0 failed
  STC progress: 94000/128000 (73.4%)

Processing STC batch 95/128
  Combinations 94001 to 95000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 45237 stored, 49763 filtered, 0 failed
  STC progress: 95000/128000 (74.2%)

Processing STC batch 96/128
  Combinations 95001 to 96000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 45628 stored, 50372 filtered, 0 failed
  STC progress: 96000/128000 (75.0%)

Processing STC batch 97/128
  Combinations 96001 to 97000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 46063 stored, 50937 filtered, 0 failed
  STC progress: 97000/128000 (75.8%)

Processing STC batch 98/128
  Combinations 97001 to 98000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 46447 stored, 51553 filtered, 0 failed
  STC progress: 98000/128000 (76.6%)

Processing STC batch 99/128
  Combinations 98001 to 99000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 46863 stored, 52137 filtered, 0 failed
  STC progress: 99000/128000 (77.3%)

Processing STC batch 100/128
  Combinations 99001 to 100000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 47260 stored, 52740 filtered, 0 failed
  STC progress: 100000/128000 (78.1%)

Processing STC batch 101/128
  Combinations 100001 to 101000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 47676 stored, 53324 filtered, 0 failed
  STC progress: 101000/128000 (78.9%)

Processing STC batch 102/128
  Combinations 101001 to 102000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 48060 stored, 53940 filtered, 0 failed
  STC progress: 102000/128000 (79.7%)

Processing STC batch 103/128
  Combinations 102001 to 103000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 48483 stored, 54517 filtered, 0 failed
  STC progress: 103000/128000 (80.5%)

Processing STC batch 104/128
  Combinations 103001 to 104000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 48867 stored, 55133 filtered, 0 failed
  STC progress: 104000/128000 (81.2%)

Processing STC batch 105/128
  Combinations 104001 to 105000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 49283 stored, 55717 filtered, 0 failed
  STC progress: 105000/128000 (82.0%)

Processing STC batch 106/128
  Combinations 105001 to 106000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 49670 stored, 56330 filtered, 0 failed
  STC progress: 106000/128000 (82.8%)

Processing STC batch 107/128
  Combinations 106001 to 107000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 50086 stored, 56914 filtered, 0 failed
  STC progress: 107000/128000 (83.6%)

Processing STC batch 108/128
  Combinations 107001 to 108000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 50470 stored, 57530 filtered, 0 failed
  STC progress: 108000/128000 (84.4%)

Processing STC batch 109/128
  Combinations 108001 to 109000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 50888 stored, 58112 filtered, 0 failed
  STC progress: 109000/128000 (85.2%)

Processing STC batch 110/128
  Combinations 109001 to 110000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 51272 stored, 58728 filtered, 0 failed
  STC progress: 110000/128000 (85.9%)

Processing STC batch 111/128
  Combinations 110001 to 111000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 51679 stored, 59321 filtered, 0 failed
  STC progress: 111000/128000 (86.7%)

Processing STC batch 112/128
  Combinations 111001 to 112000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 52051 stored, 59949 filtered, 0 failed
  STC progress: 112000/128000 (87.5%)

Processing STC batch 113/128
  Combinations 112001 to 113000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 52470 stored, 60530 filtered, 0 failed
  STC progress: 113000/128000 (88.3%)

Processing STC batch 114/128
  Combinations 113001 to 114000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 52842 stored, 61158 filtered, 0 failed
  STC progress: 114000/128000 (89.1%)

Processing STC batch 115/128
  Combinations 114001 to 115000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 53245 stored, 61755 filtered, 0 failed
  STC progress: 115000/128000 (89.8%)

Processing STC batch 116/128
  Combinations 115001 to 116000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 53628 stored, 62372 filtered, 0 failed
  STC progress: 116000/128000 (90.6%)

Processing STC batch 117/128
  Combinations 116001 to 117000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 54031 stored, 62969 filtered, 0 failed
  STC progress: 117000/128000 (91.4%)

Processing STC batch 118/128
  Combinations 117001 to 118000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 54403 stored, 63597 filtered, 0 failed
  STC progress: 118000/128000 (92.2%)

Processing STC batch 119/128
  Combinations 118001 to 119000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 54814 stored, 64186 filtered, 0 failed
  STC progress: 119000/128000 (93.0%)

Processing STC batch 120/128
  Combinations 119001 to 120000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 55186 stored, 64814 filtered, 0 failed
  STC progress: 120000/128000 (93.8%)

Processing STC batch 121/128
  Combinations 120001 to 121000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 55589 stored, 65411 filtered, 0 failed
  STC progress: 121000/128000 (94.5%)

Processing STC batch 122/128
  Combinations 121001 to 122000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 55965 stored, 66035 filtered, 0 failed
  STC progress: 122000/128000 (95.3%)

Processing STC batch 123/128
  Combinations 122001 to 123000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 56368 stored, 66632 filtered, 0 failed
  STC progress: 123000/128000 (96.1%)

Processing STC batch 124/128
  Combinations 123001 to 124000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 56740 stored, 67260 filtered, 0 failed
  STC progress: 124000/128000 (96.9%)

Processing STC batch 125/128
  Combinations 124001 to 125000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 57146 stored, 67854 filtered, 0 failed
  STC progress: 125000/128000 (97.7%)

Processing STC batch 126/128
  Combinations 125001 to 126000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 57518 stored, 68482 filtered, 0 failed
  STC progress: 126000/128000 (98.4%)

Processing STC batch 127/128
  Combinations 126001 to 127000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 57921 stored, 69079 filtered, 0 failed
  STC progress: 127000/128000 (99.2%)

Processing STC batch 128/128
  Combinations 127001 to 128000...

  Running vectorized backtest on 1000 STC combinations...

  STC batch complete: 58293 stored, 69707 filtered, 0 failed
  STC progress: 128000/128000 (100.0%)

======================================================================
Running KAMA grid: 7600 combinations
======================================================================
Processing KAMA batch 1/8
  Combinations 1 to 1000...

  Running vectorized backtest on 1000 KAMA combinations...

  KAMA batch complete: 1000 stored, 0 filtered, 0 failed
  KAMA progress: 1000/7600 (13.2%)

Processing KAMA batch 2/8
  Combinations 1001 to 2000...

  Running vectorized backtest on 1000 KAMA combinations...

  KAMA batch complete: 2000 stored, 0 filtered, 0 failed
  KAMA progress: 2000/7600 (26.3%)

Processing KAMA batch 3/8
  Combinations 2001 to 3000...

  Running vectorized backtest on 1000 KAMA combinations...

  KAMA batch complete: 3000 stored, 0 filtered, 0 failed
  KAMA progress: 3000/7600 (39.5%)

Processing KAMA batch 4/8
  Combinations 3001 to 4000...

  Running vectorized backtest on 1000 KAMA combinations...

  KAMA batch complete: 4000 stored, 0 filtered, 0 failed
  KAMA progress: 4000/7600 (52.6%)

Processing KAMA batch 5/8
  Combinations 4001 to 5000...

  Running vectorized backtest on 1000 KAMA combinations...

  KAMA batch complete: 5000 stored, 0 filtered, 0 failed
  KAMA progress: 5000/7600 (65.8%)

Processing KAMA batch 6/8
  Combinations 5001 to 6000...

  Running vectorized backtest on 1000 KAMA combinations...

  KAMA batch complete: 6000 stored, 0 filtered, 0 failed
  KAMA progress: 6000/7600 (78.9%)

Processing KAMA batch 7/8
  Combinations 6001 to 7000...

  Running vectorized backtest on 1000 KAMA combinations...

  KAMA batch complete: 7000 stored, 0 filtered, 0 failed
  KAMA progress: 7000/7600 (92.1%)

Processing KAMA batch 8/8
  Combinations 7001 to 7600...

  Running vectorized backtest on 600 KAMA combinations...

  KAMA batch complete: 7600 stored, 0 filtered, 0 failed
  KAMA progress: 7600/7600 (100.0%)

======================================================================
Running SUPERTREND grid: 6372 combinations
======================================================================
Processing SUPERTREND batch 1/7
  Combinations 1 to 1000...

  Running vectorized backtest on 1000 SUPERTREND combinations...

  SUPERTREND batch complete: 90 stored, 910 filtered, 0 failed
  SUPERTREND progress: 1000/6372 (15.7%)

Processing SUPERTREND batch 2/7
  Combinations 1001 to 2000...

  Running vectorized backtest on 1000 SUPERTREND combinations...

  SUPERTREND batch complete: 163 stored, 1837 filtered, 0 failed
  SUPERTREND progress: 2000/6372 (31.4%)

Processing SUPERTREND batch 3/7
  Combinations 2001 to 3000...

  Running vectorized backtest on 1000 SUPERTREND combinations...

  SUPERTREND batch complete: 231 stored, 2769 filtered, 0 failed
  SUPERTREND progress: 3000/6372 (47.1%)

Processing SUPERTREND batch 4/7
  Combinations 3001 to 4000...

  Running vectorized backtest on 1000 SUPERTREND combinations...

  SUPERTREND batch complete: 299 stored, 3701 filtered, 0 failed
  SUPERTREND progress: 4000/6372 (62.8%)

Processing SUPERTREND batch 5/7
  Combinations 4001 to 5000...

  Running vectorized backtest on 1000 SUPERTREND combinations...

  SUPERTREND batch complete: 374 stored, 4626 filtered, 0 failed
  SUPERTREND progress: 5000/6372 (78.5%)

Processing SUPERTREND batch 6/7
  Combinations 5001 to 6000...

  Running vectorized backtest on 1000 SUPERTREND combinations...

  SUPERTREND batch complete: 455 stored, 5545 filtered, 0 failed
  SUPERTREND progress: 6000/6372 (94.2%)

Processing SUPERTREND batch 7/7
  Combinations 6001 to 6372...

  Running vectorized backtest on 372 SUPERTREND combinations...

  SUPERTREND batch complete: 485 stored, 5887 filtered, 0 failed
  SUPERTREND progress: 6372/6372 (100.0%)

======================================================================
Running KALMAN grid: 240 combinations
======================================================================
Processing KALMAN batch 1/1
  Combinations 1 to 240...

  Running vectorized backtest on 240 KALMAN combinations...

  KALMAN batch complete: 240 stored, 0 filtered, 0 failed
  KALMAN progress: 240/240 (100.0%)

======================================================================
Running RSI grid: 40 combinations
======================================================================
Processing RSI batch 1/1
  Combinations 1 to 40...
  Running vectorized backtest on 40 RSI combinations...

  RSI batch complete: 40 stored, 0 filtered, 0 failed
  RSI progress: 40/40 (100.0%)

======================================================================
Running ADX grid: 3360 combinations
======================================================================
Processing ADX batch 1/4
  Combinations 1 to 1000...

  Running vectorized backtest on 1000 ADX combinations...

  ADX batch complete: 979 stored, 21 filtered, 0 failed
  ADX progress: 1000/3360 (29.8%)

Processing ADX batch 2/4
  Combinations 1001 to 2000...

  Running vectorized backtest on 1000 ADX combinations...

  ADX batch complete: 1122 stored, 878 filtered, 0 failed
  ADX progress: 2000/3360 (59.5%)

Processing ADX batch 3/4
  Combinations 2001 to 3000...

  Running vectorized backtest on 1000 ADX combinations...

  ADX batch complete: 1122 stored, 1878 filtered, 0 failed
  ADX progress: 3000/3360 (89.3%)

Processing ADX batch 4/4
  Combinations 3001 to 3360...

  Running vectorized backtest on 360 ADX combinations...

  ADX batch complete: 1122 stored, 2238 filtered, 0 failed
  ADX progress: 3360/3360 (100.0%)

======================================================================
Running DONCHIAN grid: 50 combinations
======================================================================
Processing DONCHIAN batch 1/1
  Combinations 1 to 50...

  Running vectorized backtest on 50 DONCHIAN combinations...

  DONCHIAN batch complete: 47 stored, 3 filtered, 0 failed
  DONCHIAN progress: 50/50 (100.0%)

======================================================================
Running TRIX grid: 76 combinations
======================================================================
Processing TRIX batch 1/1
  Combinations 1 to 76...
  Running vectorized backtest on 76 TRIX combinations...

  TRIX batch complete: 19 stored, 57 filtered, 0 failed
  TRIX progress: 76/76 (100.0%)

======================================================================
Running VORTEX grid: 100 combinations
======================================================================
Processing VORTEX batch 1/1
  Combinations 1 to 100...

  Running vectorized backtest on 100 VORTEX combinations...

  VORTEX batch complete: 88 stored, 12 filtered, 0 failed
  VORTEX progress: 100/100 (100.0%)

======================================================================
Running ALMA grid: 38000 combinations
======================================================================
Processing ALMA batch 1/38
  Combinations 1 to 1000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 1000 stored, 0 filtered, 0 failed
  ALMA progress: 1000/38000 (2.6%)

Processing ALMA batch 2/38
  Combinations 1001 to 2000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 1998 stored, 2 filtered, 0 failed
  ALMA progress: 2000/38000 (5.3%)

Processing ALMA batch 3/38
  Combinations 2001 to 3000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 2985 stored, 15 filtered, 0 failed
  ALMA progress: 3000/38000 (7.9%)

Processing ALMA batch 4/38
  Combinations 3001 to 4000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 3945 stored, 55 filtered, 0 failed
  ALMA progress: 4000/38000 (10.5%)

Processing ALMA batch 5/38
  Combinations 4001 to 5000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 4895 stored, 105 filtered, 0 failed
  ALMA progress: 5000/38000 (13.2%)

Processing ALMA batch 6/38
  Combinations 5001 to 6000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 5828 stored, 172 filtered, 0 failed
  ALMA progress: 6000/38000 (15.8%)

Processing ALMA batch 7/38
  Combinations 6001 to 7000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 6758 stored, 242 filtered, 0 failed
  ALMA progress: 7000/38000 (18.4%)

Processing ALMA batch 8/38
  Combinations 7001 to 8000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 7689 stored, 311 filtered, 0 failed
  ALMA progress: 8000/38000 (21.1%)

Processing ALMA batch 9/38
  Combinations 8001 to 9000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 8630 stored, 370 filtered, 0 failed
  ALMA progress: 9000/38000 (23.7%)

Processing ALMA batch 10/38
  Combinations 9001 to 10000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 9558 stored, 442 filtered, 0 failed
  ALMA progress: 10000/38000 (26.3%)

Processing ALMA batch 11/38
  Combinations 10001 to 11000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 10498 stored, 502 filtered, 0 failed
  ALMA progress: 11000/38000 (28.9%)

Processing ALMA batch 12/38
  Combinations 11001 to 12000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 11425 stored, 575 filtered, 0 failed
  ALMA progress: 12000/38000 (31.6%)

Processing ALMA batch 13/38
  Combinations 12001 to 13000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 12338 stored, 662 filtered, 0 failed
  ALMA progress: 13000/38000 (34.2%)

Processing ALMA batch 14/38
  Combinations 13001 to 14000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 13250 stored, 750 filtered, 0 failed
  ALMA progress: 14000/38000 (36.8%)

Processing ALMA batch 15/38
  Combinations 14001 to 15000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 14156 stored, 844 filtered, 0 failed
  ALMA progress: 15000/38000 (39.5%)

Processing ALMA batch 16/38
  Combinations 15001 to 16000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 15070 stored, 930 filtered, 0 failed
  ALMA progress: 16000/38000 (42.1%)

Processing ALMA batch 17/38
  Combinations 16001 to 17000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 15981 stored, 1019 filtered, 0 failed
  ALMA progress: 17000/38000 (44.7%)

Processing ALMA batch 18/38
  Combinations 17001 to 18000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 16897 stored, 1103 filtered, 0 failed
  ALMA progress: 18000/38000 (47.4%)

Processing ALMA batch 19/38
  Combinations 18001 to 19000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 17809 stored, 1191 filtered, 0 failed
  ALMA progress: 19000/38000 (50.0%)

Processing ALMA batch 20/38
  Combinations 19001 to 20000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 18719 stored, 1281 filtered, 0 failed
  ALMA progress: 20000/38000 (52.6%)

Processing ALMA batch 21/38
  Combinations 20001 to 21000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 19646 stored, 1354 filtered, 0 failed
  ALMA progress: 21000/38000 (55.3%)

Processing ALMA batch 22/38
  Combinations 21001 to 22000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 20567 stored, 1433 filtered, 0 failed
  ALMA progress: 22000/38000 (57.9%)

Processing ALMA batch 23/38
  Combinations 22001 to 23000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 21469 stored, 1531 filtered, 0 failed
  ALMA progress: 23000/38000 (60.5%)

Processing ALMA batch 24/38
  Combinations 23001 to 24000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 22302 stored, 1698 filtered, 0 failed
  ALMA progress: 24000/38000 (63.2%)

Processing ALMA batch 25/38
  Combinations 24001 to 25000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 23113 stored, 1887 filtered, 0 failed
  ALMA progress: 25000/38000 (65.8%)

Processing ALMA batch 26/38
  Combinations 25001 to 26000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 23911 stored, 2089 filtered, 0 failed
  ALMA progress: 26000/38000 (68.4%)

Processing ALMA batch 27/38
  Combinations 26001 to 27000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 24688 stored, 2312 filtered, 0 failed
  ALMA progress: 27000/38000 (71.1%)

Processing ALMA batch 28/38
  Combinations 27001 to 28000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 25442 stored, 2558 filtered, 0 failed
  ALMA progress: 28000/38000 (73.7%)

Processing ALMA batch 29/38
  Combinations 28001 to 29000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 26181 stored, 2819 filtered, 0 failed
  ALMA progress: 29000/38000 (76.3%)

Processing ALMA batch 30/38
  Combinations 29001 to 30000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 26913 stored, 3087 filtered, 0 failed
  ALMA progress: 30000/38000 (78.9%)

Processing ALMA batch 31/38
  Combinations 30001 to 31000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 27644 stored, 3356 filtered, 0 failed
  ALMA progress: 31000/38000 (81.6%)

Processing ALMA batch 32/38
  Combinations 31001 to 32000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 28345 stored, 3655 filtered, 0 failed
  ALMA progress: 32000/38000 (84.2%)

Processing ALMA batch 33/38
  Combinations 32001 to 33000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 29019 stored, 3981 filtered, 0 failed
  ALMA progress: 33000/38000 (86.8%)

Processing ALMA batch 34/38
  Combinations 33001 to 34000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 29663 stored, 4337 filtered, 0 failed
  ALMA progress: 34000/38000 (89.5%)

Processing ALMA batch 35/38
  Combinations 34001 to 35000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 30278 stored, 4722 filtered, 0 failed
  ALMA progress: 35000/38000 (92.1%)

Processing ALMA batch 36/38
  Combinations 35001 to 36000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 30874 stored, 5126 filtered, 0 failed
  ALMA progress: 36000/38000 (94.7%)

Processing ALMA batch 37/38
  Combinations 36001 to 37000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 31469 stored, 5531 filtered, 0 failed
  ALMA progress: 37000/38000 (97.4%)

Processing ALMA batch 38/38
  Combinations 37001 to 38000...

  Running vectorized backtest on 1000 ALMA combinations...

  ALMA batch complete: 32077 stored, 5923 filtered, 0 failed
  ALMA progress: 38000/38000 (100.0%)

======================================================================
MULTI-INDICATOR GRID SEARCH COMPLETED!
======================================================================
Total combinations attempted: 378754
Stored after filters: 232314
Filtered by trade frequency: 146440
Failed: 0
Stored-result rate: 61.3%

Results stored in 'grid_search_results' (232314 entries)

======================================================================
TOP 5 IN-SAMPLE RESULTS BY INDICATOR
======================================================================

Triple EMA - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------

#1 - EMA(5,112,150)
   Sharpe Ratio:      0.934
   Total Return:      371.37%
   Annualized Return: 35.06%
   Max Drawdown:      -35.78%
   Win Rate:          62.5%
   Profit Factor:     10.88
   Total Trades:      16 (3.1/year)

#2 - EMA(5,112,148)
   Sharpe Ratio:      0.930
   Total Return:      365.64%
   Annualized Return: 34.74%
   Max Drawdown:      -35.78%
   Win Rate:          58.8%
   Profit Factor:     10.25
   Total Trades:      17 (3.3/year)

#3 - EMA(5,112,149)
   Sharpe Ratio:      0.930
   Total Return:      365.64%
   Annualized Return: 34.74%
   Max Drawdown:      -35.78%
   Win Rate:          58.8%
   Profit Factor:     10.25
   Total Trades:      17 (3.3/year)

#4 - EMA(4,117,125)
   Sharpe Ratio:      0.928
   Total Return:      367.01%
   Annualized Return: 34.82%
   Max Drawdown:      -35.78%
   Win Rate:          60.0%
   Profit Factor:     7.57
   Total Trades:      15 (2.9/year)

#5 - EMA(4,117,126)
   Sharpe Ratio:      0.928
   Total Return:      367.01%
   Annualized Return: 34.82%
   Max Drawdown:      -35.78%
   Win Rate:          60.0%
   Profit Factor:     7.57
   Total Trades:      15 (2.9/year)

MACD - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------

#1 - MACD(12,68,79)
   Sharpe Ratio:      0.724
   Total Return:      207.55%
   Annualized Return: 24.33%
   Max Drawdown:      -48.49%
   Win Rate:          50.0%
   Profit Factor:     3.87
   Total Trades:      14 (2.7/year)

#2 - MACD(12,69,78)
   Sharpe Ratio:      0.724
   Total Return:      207.55%
   Annualized Return: 24.33%
   Max Drawdown:      -48.49%
   Win Rate:          50.0%
   Profit Factor:     3.87
   Total Trades:      14 (2.7/year)

#3 - MACD(12,60,96)
   Sharpe Ratio:      0.718
   Total Return:      203.46%
   Annualized Return: 24.01%
   Max Drawdown:      -48.49%
   Win Rate:          53.3%
   Profit Factor:     3.55
   Total Trades:      15 (2.9/year)

#4 - MACD(12,60,97)
   Sharpe Ratio:      0.718
   Total Return:      203.46%
   Annualized Return: 24.01%
   Max Drawdown:      -48.49%
   Win Rate:          53.3%
   Profit Factor:     3.55
   Total Trades:      15 (2.9/year)

#5 - MACD(12,60,98)
   Sharpe Ratio:      0.718
   Total Return:      203.46%
   Annualized Return: 24.01%
   Max Drawdown:      -48.49%
   Win Rate:          53.3%
   Profit Factor:     3.55
   Total Trades:      15 (2.9/year)

AROON - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------

#1 - AROON(22)
   Sharpe Ratio:      0.796
   Total Return:      247.27%
   Annualized Return: 27.29%
   Max Drawdown:      -45.23%
   Win Rate:          47.8%
   Profit Factor:     2.88
   Total Trades:      23 (4.5/year)

#2 - AROON(18)
   Sharpe Ratio:      0.790
   Total Return:      267.01%
   Annualized Return: 28.66%
   Max Drawdown:      -52.25%
   Win Rate:          54.8%
   Profit Factor:     2.51
   Total Trades:      31 (6.0/year)

#3 - AROON(21)
   Sharpe Ratio:      0.722
   Total Return:      198.45%
   Annualized Return: 23.61%
   Max Drawdown:      -52.13%
   Win Rate:          52.2%
   Profit Factor:     2.56
   Total Trades:      23 (4.5/year)

#4 - AROON(23)
   Sharpe Ratio:      0.706
   Total Return:      179.76%
   Annualized Return: 22.07%
   Max Drawdown:      -49.07%
   Win Rate:          61.9%
   Profit Factor:     2.50
   Total Trades:      21 (4.1/year)

#5 - AROON(19)
   Sharpe Ratio:      0.673
   Total Return:      170.66%
   Annualized Return: 21.29%
   Max Drawdown:      -57.10%
   Win Rate:          53.8%
   Profit Factor:     2.16
   Total Trades:      26 (5.0/year)

STC - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------

#1 - STC(38,99,23)
   Sharpe Ratio:      0.964
   Total Return:      433.72%
   Annualized Return: 38.35%
   Max Drawdown:      -41.62%
   Win Rate:          52.9%
   Profit Factor:     4.20
   Total Trades:      17 (3.3/year)

#2 - STC(47,81,23)
   Sharpe Ratio:      0.925
   Total Return:      387.21%
   Annualized Return: 35.93%
   Max Drawdown:      -42.90%
   Win Rate:          52.9%
   Profit Factor:     4.03
   Total Trades:      17 (3.3/year)

#3 - STC(49,78,23)
   Sharpe Ratio:      0.924
   Total Return:      386.92%
   Annualized Return: 35.91%
   Max Drawdown:      -42.90%
   Win Rate:          58.8%
   Profit Factor:     3.99
   Total Trades:      17 (3.3/year)

#4 - STC(35,99,24)
   Sharpe Ratio:      0.921
   Total Return:      383.65%
   Annualized Return: 35.74%
   Max Drawdown:      -42.09%
   Win Rate:          43.8%
   Profit Factor:     4.32
   Total Trades:      16 (3.1/year)

#5 - STC(44,73,23)
   Sharpe Ratio:      0.909
   Total Return:      377.21%
   Annualized Return: 35.38%
   Max Drawdown:      -41.62%
   Win Rate:          50.0%
   Profit Factor:     4.07
   Total Trades:      18 (3.5/year)

KAMA - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------

#1 - KAMA(10,7,94)
   Sharpe Ratio:      0.807
   Total Return:      260.20%
   Annualized Return: 28.20%
   Max Drawdown:      -41.34%
   Win Rate:          44.4%
   Profit Factor:     4.12
   Total Trades:      27 (5.2/year)

#2 - KAMA(10,7,95)
   Sharpe Ratio:      0.807
   Total Return:      260.20%
   Annualized Return: 28.20%
   Max Drawdown:      -41.34%
   Win Rate:          44.4%
   Profit Factor:     4.12
   Total Trades:      27 (5.2/year)

#3 - KAMA(10,7,96)
   Sharpe Ratio:      0.807
   Total Return:      260.20%
   Annualized Return: 28.20%
   Max Drawdown:      -41.34%
   Win Rate:          44.4%
   Profit Factor:     4.12
   Total Trades:      27 (5.2/year)

#4 - KAMA(10,7,97)
   Sharpe Ratio:      0.807
   Total Return:      260.20%
   Annualized Return: 28.20%
   Max Drawdown:      -41.34%
   Win Rate:          44.4%
   Profit Factor:     4.12
   Total Trades:      27 (5.2/year)

#5 - KAMA(10,7,98)
   Sharpe Ratio:      0.807
   Total Return:      260.20%
   Annualized Return: 28.20%
   Max Drawdown:      -41.34%
   Win Rate:          44.4%
   Profit Factor:     4.12
   Total Trades:      27 (5.2/year)

SUPERTREND - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------

#1 - SUPERTREND(ATR=88,Factor=3)
   Sharpe Ratio:      0.852
   Total Return:      317.49%
   Annualized Return: 31.92%
   Max Drawdown:      -49.56%
   Win Rate:          40.9%
   Profit Factor:     3.25
   Total Trades:      22 (4.3/year)

#2 - SUPERTREND(ATR=87,Factor=3)
   Sharpe Ratio:      0.814
   Total Return:      284.46%
   Annualized Return: 29.83%
   Max Drawdown:      -49.56%
   Win Rate:          39.1%
   Profit Factor:     3.05
   Total Trades:      23 (4.5/year)

#3 - SUPERTREND(ATR=89,Factor=3)
   Sharpe Ratio:      0.808
   Total Return:      276.20%
   Annualized Return: 29.28%
   Max Drawdown:      -49.56%
   Win Rate:          43.5%
   Profit Factor:     2.62
   Total Trades:      23 (4.5/year)

#4 - SUPERTREND(ATR=91,Factor=3)
   Sharpe Ratio:      0.808
   Total Return:      276.20%
   Annualized Return: 29.28%
   Max Drawdown:      -49.56%
   Win Rate:          43.5%
   Profit Factor:     2.62
   Total Trades:      23 (4.5/year)

#5 - SUPERTREND(ATR=4,Factor=2)
   Sharpe Ratio:      0.804
   Total Return:      256.68%
   Annualized Return: 27.95%
   Max Drawdown:      -54.38%
   Win Rate:          54.5%
   Profit Factor:     2.32
   Total Trades:      33 (6.4/year)

KALMAN - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------

#1 - KALMAN(Q=1,R=157)
   Sharpe Ratio:      0.851
   Total Return:      299.86%
   Annualized Return: 30.82%
   Max Drawdown:      -47.60%
   Win Rate:          52.6%
   Profit Factor:     2.23
   Total Trades:      57 (11.0/year)

#2 - KALMAN(Q=1,R=158)
   Sharpe Ratio:      0.851
   Total Return:      299.86%
   Annualized Return: 30.82%
   Max Drawdown:      -47.60%
   Win Rate:          52.6%
   Profit Factor:     2.23
   Total Trades:      57 (11.0/year)

#3 - KALMAN(Q=1,R=159)
   Sharpe Ratio:      0.851
   Total Return:      299.86%
   Annualized Return: 30.82%
   Max Drawdown:      -47.60%
   Win Rate:          52.6%
   Profit Factor:     2.23
   Total Trades:      57 (11.0/year)

#4 - KALMAN(Q=1,R=154)
   Sharpe Ratio:      0.823
   Total Return:      275.18%
   Annualized Return: 29.22%
   Max Drawdown:      -47.60%
   Win Rate:          53.4%
   Profit Factor:     2.18
   Total Trades:      58 (11.2/year)

#5 - KALMAN(Q=1,R=155)
   Sharpe Ratio:      0.823
   Total Return:      275.18%
   Annualized Return: 29.22%
   Max Drawdown:      -47.60%
   Win Rate:          53.4%
   Profit Factor:     2.18
   Total Trades:      58 (11.2/year)

RSI - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------

#1 - RSI(71)
   Sharpe Ratio:      0.781
   Total Return:      245.80%
   Annualized Return: 27.19%
   Max Drawdown:      -42.05%
   Win Rate:          48.1%
   Profit Factor:     4.10
   Total Trades:      27 (5.2/year)

#2 - RSI(72)
   Sharpe Ratio:      0.779
   Total Return:      243.84%
   Annualized Return: 27.05%
   Max Drawdown:      -42.05%
   Win Rate:          48.3%
   Profit Factor:     4.00
   Total Trades:      29 (5.6/year)

#3 - RSI(73)
   Sharpe Ratio:      0.779
   Total Return:      243.38%
   Annualized Return: 27.02%
   Max Drawdown:      -42.05%
   Win Rate:          48.3%
   Profit Factor:     4.00
   Total Trades:      29 (5.6/year)

#4 - RSI(74)
   Sharpe Ratio:      0.769
   Total Return:      236.08%
   Annualized Return: 26.49%
   Max Drawdown:      -43.28%
   Win Rate:          44.8%
   Profit Factor:     3.90
   Total Trades:      29 (5.6/year)

#5 - RSI(75)
   Sharpe Ratio:      0.749
   Total Return:      222.41%
   Annualized Return: 25.47%
   Max Drawdown:      -40.62%
   Win Rate:          44.4%
   Profit Factor:     4.09
   Total Trades:      27 (5.2/year)

ADX - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------

#1 - ADX(DI=21,Smooth=31)
   Sharpe Ratio:      1.170
   Total Return:      717.24%
   Annualized Return: 50.26%
   Max Drawdown:      -40.89%
   Win Rate:          75.0%
   Profit Factor:     21.69
   Total Trades:      12 (2.3/year)

#2 - ADX(DI=21,Smooth=32)
   Sharpe Ratio:      1.170
   Total Return:      717.24%
   Annualized Return: 50.26%
   Max Drawdown:      -40.89%
   Win Rate:          75.0%
   Profit Factor:     21.69
   Total Trades:      12 (2.3/year)

#3 - ADX(DI=21,Smooth=33)
   Sharpe Ratio:      1.170
   Total Return:      717.24%
   Annualized Return: 50.26%
   Max Drawdown:      -40.89%
   Win Rate:          75.0%
   Profit Factor:     21.69
   Total Trades:      12 (2.3/year)

#4 - ADX(DI=18,Smooth=36)
   Sharpe Ratio:      1.087
   Total Return:      554.01%
   Annualized Return: 43.91%
   Max Drawdown:      -50.10%
   Win Rate:          78.6%
   Profit Factor:     9.89
   Total Trades:      14 (2.7/year)

#5 - ADX(DI=18,Smooth=37)
   Sharpe Ratio:      1.087
   Total Return:      554.01%
   Annualized Return: 43.91%
   Max Drawdown:      -50.10%
   Win Rate:          78.6%
   Profit Factor:     9.89
   Total Trades:      14 (2.7/year)

DONCHIAN - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------

#1 - DONCHIAN(22)
   Sharpe Ratio:      0.602
   Total Return:      119.73%
   Annualized Return: 16.49%
   Max Drawdown:      -41.52%
   Win Rate:          50.0%
   Profit Factor:     2.17
   Total Trades:      22 (4.3/year)

#2 - DONCHIAN(23)
   Sharpe Ratio:      0.552
   Total Return:      98.76%
   Annualized Return: 14.24%
   Max Drawdown:      -40.41%
   Win Rate:          52.4%
   Profit Factor:     2.08
   Total Trades:      21 (4.1/year)

#3 - DONCHIAN(26)
   Sharpe Ratio:      0.547
   Total Return:      93.06%
   Annualized Return: 13.60%
   Max Drawdown:      -35.99%
   Win Rate:          44.4%
   Profit Factor:     2.10
   Total Trades:      18 (3.5/year)

#4 - DONCHIAN(27)
   Sharpe Ratio:      0.542
   Total Return:      91.05%
   Annualized Return: 13.37%
   Max Drawdown:      -32.46%
   Win Rate:          44.4%
   Profit Factor:     2.08
   Total Trades:      18 (3.5/year)

#5 - DONCHIAN(24)
   Sharpe Ratio:      0.488
   Total Return:      76.57%
   Annualized Return: 11.65%
   Max Drawdown:      -40.42%
   Win Rate:          47.6%
   Profit Factor:     1.91
   Total Trades:      21 (4.1/year)

TRIX - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------

#1 - TRIX(6)
   Sharpe Ratio:      0.769
   Total Return:      242.75%
   Annualized Return: 26.97%
   Max Drawdown:      -59.62%
   Win Rate:          51.7%
   Profit Factor:     2.53
   Total Trades:      29 (5.6/year)

#2 - TRIX(5)
   Sharpe Ratio:      0.724
   Total Return:      219.90%
   Annualized Return: 25.28%
   Max Drawdown:      -59.25%
   Win Rate:          50.0%
   Profit Factor:     2.08
   Total Trades:      40 (7.8/year)

#3 - TRIX(7)
   Sharpe Ratio:      0.711
   Total Return:      202.18%
   Annualized Return: 23.91%
   Max Drawdown:      -55.81%
   Win Rate:          44.0%
   Profit Factor:     2.32
   Total Trades:      25 (4.8/year)

#4 - TRIX(8)
   Sharpe Ratio:      0.679
   Total Return:      182.62%
   Annualized Return: 22.31%
   Max Drawdown:      -58.16%
   Win Rate:          52.2%
   Profit Factor:     2.57
   Total Trades:      23 (4.5/year)

#5 - TRIX(4)
   Sharpe Ratio:      0.556
   Total Return:      115.39%
   Annualized Return: 16.04%
   Max Drawdown:      -61.95%
   Win Rate:          51.9%
   Profit Factor:     1.59
   Total Trades:      54 (10.5/year)

VORTEX - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------

#1 - VORTEX(136)
   Sharpe Ratio:      0.684
   Total Return:      198.12%
   Annualized Return: 23.58%
   Max Drawdown:      -62.09%
   Win Rate:          53.8%
   Profit Factor:     4.57
   Total Trades:      13 (2.5/year)

#2 - VORTEX(135)
   Sharpe Ratio:      0.588
   Total Return:      135.00%
   Annualized Return: 18.01%
   Max Drawdown:      -62.09%
   Win Rate:          45.5%
   Profit Factor:     3.58
   Total Trades:      11 (2.1/year)

#3 - VORTEX(115)
   Sharpe Ratio:      0.586
   Total Return:      131.72%
   Annualized Return: 17.69%
   Max Drawdown:      -62.09%
   Win Rate:          58.3%
   Profit Factor:     3.42
   Total Trades:      12 (2.3/year)

#4 - VORTEX(133)
   Sharpe Ratio:      0.584
   Total Return:      131.74%
   Annualized Return: 17.69%
   Max Drawdown:      -62.09%
   Win Rate:          66.7%
   Profit Factor:     3.59
   Total Trades:      12 (2.3/year)

#5 - VORTEX(131)
   Sharpe Ratio:      0.579
   Total Return:      128.87%
   Annualized Return: 17.41%
   Max Drawdown:      -62.09%
   Win Rate:          53.8%
   Profit Factor:     3.72
   Total Trades:      13 (2.5/year)

ALMA - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------

#1 - ALMA(2,99,0.10,3)
   Sharpe Ratio:      0.786
   Total Return:      256.99%
   Annualized Return: 27.98%
   Max Drawdown:      -48.14%
   Win Rate:          76.9%
   Profit Factor:     16.39
   Total Trades:      13 (2.5/year)

#2 - ALMA(2,98,0.18,7)
   Sharpe Ratio:      0.767
   Total Return:      251.82%
   Annualized Return: 27.62%
   Max Drawdown:      -48.14%
   Win Rate:          75.0%
   Profit Factor:     14.11
   Total Trades:      16 (3.1/year)

#3 - ALMA(2,97,0.18,7)
   Sharpe Ratio:      0.754
   Total Return:      240.64%
   Annualized Return: 26.82%
   Max Drawdown:      -48.14%
   Win Rate:          75.0%
   Profit Factor:     18.34
   Total Trades:      16 (3.1/year)

#4 - ALMA(2,99,0.12,3)
   Sharpe Ratio:      0.752
   Total Return:      231.12%
   Annualized Return: 26.12%
   Max Drawdown:      -48.14%
   Win Rate:          64.3%
   Profit Factor:     6.77
   Total Trades:      14 (2.7/year)

#5 - ALMA(2,98,0.10,3)
   Sharpe Ratio:      0.751
   Total Return:      230.09%
   Annualized Return: 26.05%
   Max Drawdown:      -48.14%
   Win Rate:          64.3%
   Profit Factor:     6.70
   Total Trades:      14 (2.7/year)

======================================================================

In [11]:
# Analyze Multi-Indicator Grid Search Results

# Convert results to DataFrame for analysis
results_df = pd.DataFrame(grid_search_results)

print("Grid Search Results Analysis")
print("=" * 50)
print(f"Total combinations tested after filters: {len(results_df)}")
print(f"Results shape: {results_df.shape}")

if results_df.empty:
    raise ValueError("No grid search results were produced. Run the grid search cell first.")

print("Results by indicator:")
print(results_df['indicator'].value_counts().to_string())

print_top_in_sample_by_indicator(results_df, top_n=5, include_summary=True)

print("\nAnalysis complete! Top in-sample results listed separately for each indicator.")

Grid Search Results Analysis
==================================================
Total combinations tested after filters: 232314
Results shape: (232314, 54)
Results by indicator:
indicator
MACD          110789
STC            58293
ALMA           32077
Triple EMA     21455
KAMA            7600
ADX             1122
SUPERTREND       485
KALMAN           240
VORTEX            88
AROON             59
DONCHIAN          47
RSI               40
TRIX              19

======================================================================
TOP 5 IN-SAMPLE RESULTS BY INDICATOR
======================================================================

Triple EMA - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------
In-sample summary:
   Stored combinations: 21455
   Best Sharpe Ratio: 0.934
   Best Total Return: 371.37%
   Average Total Return: 193.82%
   Smallest Max Drawdown: -35.78%
   Best Profit Factor: 13.15

#1 - EMA(5,112,150)
   Sharpe Ratio:      0.934
   Total Return:      371.37%
   Annualized Return: 35.06%
   Max Drawdown:      -35.78%
   Win Rate:          62.5%
   Profit Factor:     10.88
   Total Trades:      16 (3.1/year)

#2 - EMA(5,112,148)
   Sharpe Ratio:      0.930
   Total Return:      365.64%
   Annualized Return: 34.74%
   Max Drawdown:      -35.78%
   Win Rate:          58.8%
   Profit Factor:     10.25
   Total Trades:      17 (3.3/year)

#3 - EMA(5,112,149)
   Sharpe Ratio:      0.930
   Total Return:      365.64%
   Annualized Return: 34.74%
   Max Drawdown:      -35.78%
   Win Rate:          58.8%
   Profit Factor:     10.25
   Total Trades:      17 (3.3/year)

#4 - EMA(4,117,125)
   Sharpe Ratio:      0.928
   Total Return:      367.01%
   Annualized Return: 34.82%
   Max Drawdown:      -35.78%
   Win Rate:          60.0%
   Profit Factor:     7.57
   Total Trades:      15 (2.9/year)

#5 - EMA(4,117,126)
   Sharpe Ratio:      0.928
   Total Return:      367.01%
   Annualized Return: 34.82%
   Max Drawdown:      -35.78%
   Win Rate:          60.0%
   Profit Factor:     7.57
   Total Trades:      15 (2.9/year)

MACD - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------
In-sample summary:
   Stored combinations: 110789
   Best Sharpe Ratio: 0.724
   Best Total Return: 207.55%
   Average Total Return: 52.93%
   Smallest Max Drawdown: -46.95%
   Best Profit Factor: 4.48

#1 - MACD(12,68,79)
   Sharpe Ratio:      0.724
   Total Return:      207.55%
   Annualized Return: 24.33%
   Max Drawdown:      -48.49%
   Win Rate:          50.0%
   Profit Factor:     3.87
   Total Trades:      14 (2.7/year)

#2 - MACD(12,69,78)
   Sharpe Ratio:      0.724
   Total Return:      207.55%
   Annualized Return: 24.33%
   Max Drawdown:      -48.49%
   Win Rate:          50.0%
   Profit Factor:     3.87
   Total Trades:      14 (2.7/year)

#3 - MACD(12,60,96)
   Sharpe Ratio:      0.718
   Total Return:      203.46%
   Annualized Return: 24.01%
   Max Drawdown:      -48.49%
   Win Rate:          53.3%
   Profit Factor:     3.55
   Total Trades:      15 (2.9/year)

#4 - MACD(12,60,97)
   Sharpe Ratio:      0.718
   Total Return:      203.46%
   Annualized Return: 24.01%
   Max Drawdown:      -48.49%
   Win Rate:          53.3%
   Profit Factor:     3.55
   Total Trades:      15 (2.9/year)

#5 - MACD(12,60,98)
   Sharpe Ratio:      0.718
   Total Return:      203.46%
   Annualized Return: 24.01%
   Max Drawdown:      -48.49%
   Win Rate:          53.3%
   Profit Factor:     3.55
   Total Trades:      15 (2.9/year)

AROON - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------
In-sample summary:
   Stored combinations: 59
   Best Sharpe Ratio: 0.796
   Best Total Return: 267.01%
   Average Total Return: 31.54%
   Smallest Max Drawdown: -45.23%
   Best Profit Factor: 2.88

#1 - AROON(22)
   Sharpe Ratio:      0.796
   Total Return:      247.27%
   Annualized Return: 27.29%
   Max Drawdown:      -45.23%
   Win Rate:          47.8%
   Profit Factor:     2.88
   Total Trades:      23 (4.5/year)

#2 - AROON(18)
   Sharpe Ratio:      0.790
   Total Return:      267.01%
   Annualized Return: 28.66%
   Max Drawdown:      -52.25%
   Win Rate:          54.8%
   Profit Factor:     2.51
   Total Trades:      31 (6.0/year)

#3 - AROON(21)
   Sharpe Ratio:      0.722
   Total Return:      198.45%
   Annualized Return: 23.61%
   Max Drawdown:      -52.13%
   Win Rate:          52.2%
   Profit Factor:     2.56
   Total Trades:      23 (4.5/year)

#4 - AROON(23)
   Sharpe Ratio:      0.706
   Total Return:      179.76%
   Annualized Return: 22.07%
   Max Drawdown:      -49.07%
   Win Rate:          61.9%
   Profit Factor:     2.50
   Total Trades:      21 (4.1/year)

#5 - AROON(19)
   Sharpe Ratio:      0.673
   Total Return:      170.66%
   Annualized Return: 21.29%
   Max Drawdown:      -57.10%
   Win Rate:          53.8%
   Profit Factor:     2.16
   Total Trades:      26 (5.0/year)

STC - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------
In-sample summary:
   Stored combinations: 58293
   Best Sharpe Ratio: 0.964
   Best Total Return: 433.72%
   Average Total Return: 50.42%
   Smallest Max Drawdown: -41.62%
   Best Profit Factor: 4.32

#1 - STC(38,99,23)
   Sharpe Ratio:      0.964
   Total Return:      433.72%
   Annualized Return: 38.35%
   Max Drawdown:      -41.62%
   Win Rate:          52.9%
   Profit Factor:     4.20
   Total Trades:      17 (3.3/year)

#2 - STC(47,81,23)
   Sharpe Ratio:      0.925
   Total Return:      387.21%
   Annualized Return: 35.93%
   Max Drawdown:      -42.90%
   Win Rate:          52.9%
   Profit Factor:     4.03
   Total Trades:      17 (3.3/year)

#3 - STC(49,78,23)
   Sharpe Ratio:      0.924
   Total Return:      386.92%
   Annualized Return: 35.91%
   Max Drawdown:      -42.90%
   Win Rate:          58.8%
   Profit Factor:     3.99
   Total Trades:      17 (3.3/year)

#4 - STC(35,99,24)
   Sharpe Ratio:      0.921
   Total Return:      383.65%
   Annualized Return: 35.74%
   Max Drawdown:      -42.09%
   Win Rate:          43.8%
   Profit Factor:     4.32
   Total Trades:      16 (3.1/year)

#5 - STC(44,73,23)
   Sharpe Ratio:      0.909
   Total Return:      377.21%
   Annualized Return: 35.38%
   Max Drawdown:      -41.62%
   Win Rate:          50.0%
   Profit Factor:     4.07
   Total Trades:      18 (3.5/year)

KAMA - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------
In-sample summary:
   Stored combinations: 7600
   Best Sharpe Ratio: 0.807
   Best Total Return: 260.20%
   Average Total Return: 14.81%
   Smallest Max Drawdown: -35.87%
   Best Profit Factor: 4.48

#1 - KAMA(10,7,94)
   Sharpe Ratio:      0.807
   Total Return:      260.20%
   Annualized Return: 28.20%
   Max Drawdown:      -41.34%
   Win Rate:          44.4%
   Profit Factor:     4.12
   Total Trades:      27 (5.2/year)

#2 - KAMA(10,7,95)
   Sharpe Ratio:      0.807
   Total Return:      260.20%
   Annualized Return: 28.20%
   Max Drawdown:      -41.34%
   Win Rate:          44.4%
   Profit Factor:     4.12
   Total Trades:      27 (5.2/year)

#3 - KAMA(10,7,96)
   Sharpe Ratio:      0.807
   Total Return:      260.20%
   Annualized Return: 28.20%
   Max Drawdown:      -41.34%
   Win Rate:          44.4%
   Profit Factor:     4.12
   Total Trades:      27 (5.2/year)

#4 - KAMA(10,7,97)
   Sharpe Ratio:      0.807
   Total Return:      260.20%
   Annualized Return: 28.20%
   Max Drawdown:      -41.34%
   Win Rate:          44.4%
   Profit Factor:     4.12
   Total Trades:      27 (5.2/year)

#5 - KAMA(10,7,98)
   Sharpe Ratio:      0.807
   Total Return:      260.20%
   Annualized Return: 28.20%
   Max Drawdown:      -41.34%
   Win Rate:          44.4%
   Profit Factor:     4.12
   Total Trades:      27 (5.2/year)

SUPERTREND - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------
In-sample summary:
   Stored combinations: 485
   Best Sharpe Ratio: 0.852
   Best Total Return: 317.49%
   Average Total Return: 50.26%
   Smallest Max Drawdown: -37.19%
   Best Profit Factor: 3.25

#1 - SUPERTREND(ATR=88,Factor=3)
   Sharpe Ratio:      0.852
   Total Return:      317.49%
   Annualized Return: 31.92%
   Max Drawdown:      -49.56%
   Win Rate:          40.9%
   Profit Factor:     3.25
   Total Trades:      22 (4.3/year)

#2 - SUPERTREND(ATR=87,Factor=3)
   Sharpe Ratio:      0.814
   Total Return:      284.46%
   Annualized Return: 29.83%
   Max Drawdown:      -49.56%
   Win Rate:          39.1%
   Profit Factor:     3.05
   Total Trades:      23 (4.5/year)

#3 - SUPERTREND(ATR=89,Factor=3)
   Sharpe Ratio:      0.808
   Total Return:      276.20%
   Annualized Return: 29.28%
   Max Drawdown:      -49.56%
   Win Rate:          43.5%
   Profit Factor:     2.62
   Total Trades:      23 (4.5/year)

#4 - SUPERTREND(ATR=91,Factor=3)
   Sharpe Ratio:      0.808
   Total Return:      276.20%
   Annualized Return: 29.28%
   Max Drawdown:      -49.56%
   Win Rate:          43.5%
   Profit Factor:     2.62
   Total Trades:      23 (4.5/year)

#5 - SUPERTREND(ATR=4,Factor=2)
   Sharpe Ratio:      0.804
   Total Return:      256.68%
   Annualized Return: 27.95%
   Max Drawdown:      -54.38%
   Win Rate:          54.5%
   Profit Factor:     2.32
   Total Trades:      33 (6.4/year)

KALMAN - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------
In-sample summary:
   Stored combinations: 240
   Best Sharpe Ratio: 0.851
   Best Total Return: 299.86%
   Average Total Return: 117.01%
   Smallest Max Drawdown: -47.60%
   Best Profit Factor: 2.23

#1 - KALMAN(Q=1,R=157)
   Sharpe Ratio:      0.851
   Total Return:      299.86%
   Annualized Return: 30.82%
   Max Drawdown:      -47.60%
   Win Rate:          52.6%
   Profit Factor:     2.23
   Total Trades:      57 (11.0/year)

#2 - KALMAN(Q=1,R=158)
   Sharpe Ratio:      0.851
   Total Return:      299.86%
   Annualized Return: 30.82%
   Max Drawdown:      -47.60%
   Win Rate:          52.6%
   Profit Factor:     2.23
   Total Trades:      57 (11.0/year)

#3 - KALMAN(Q=1,R=159)
   Sharpe Ratio:      0.851
   Total Return:      299.86%
   Annualized Return: 30.82%
   Max Drawdown:      -47.60%
   Win Rate:          52.6%
   Profit Factor:     2.23
   Total Trades:      57 (11.0/year)

#4 - KALMAN(Q=1,R=154)
   Sharpe Ratio:      0.823
   Total Return:      275.18%
   Annualized Return: 29.22%
   Max Drawdown:      -47.60%
   Win Rate:          53.4%
   Profit Factor:     2.18
   Total Trades:      58 (11.2/year)

#5 - KALMAN(Q=1,R=155)
   Sharpe Ratio:      0.823
   Total Return:      275.18%
   Annualized Return: 29.22%
   Max Drawdown:      -47.60%
   Win Rate:          53.4%
   Profit Factor:     2.18
   Total Trades:      58 (11.2/year)

RSI - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------
In-sample summary:
   Stored combinations: 40
   Best Sharpe Ratio: 0.781
   Best Total Return: 245.80%
   Average Total Return: 124.86%
   Smallest Max Drawdown: -40.62%
   Best Profit Factor: 4.10

#1 - RSI(71)
   Sharpe Ratio:      0.781
   Total Return:      245.80%
   Annualized Return: 27.19%
   Max Drawdown:      -42.05%
   Win Rate:          48.1%
   Profit Factor:     4.10
   Total Trades:      27 (5.2/year)

#2 - RSI(72)
   Sharpe Ratio:      0.779
   Total Return:      243.84%
   Annualized Return: 27.05%
   Max Drawdown:      -42.05%
   Win Rate:          48.3%
   Profit Factor:     4.00
   Total Trades:      29 (5.6/year)

#3 - RSI(73)
   Sharpe Ratio:      0.779
   Total Return:      243.38%
   Annualized Return: 27.02%
   Max Drawdown:      -42.05%
   Win Rate:          48.3%
   Profit Factor:     4.00
   Total Trades:      29 (5.6/year)

#4 - RSI(74)
   Sharpe Ratio:      0.769
   Total Return:      236.08%
   Annualized Return: 26.49%
   Max Drawdown:      -43.28%
   Win Rate:          44.8%
   Profit Factor:     3.90
   Total Trades:      29 (5.6/year)

#5 - RSI(75)
   Sharpe Ratio:      0.749
   Total Return:      222.41%
   Annualized Return: 25.47%
   Max Drawdown:      -40.62%
   Win Rate:          44.4%
   Profit Factor:     4.09
   Total Trades:      27 (5.2/year)

ADX - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------
In-sample summary:
   Stored combinations: 1122
   Best Sharpe Ratio: 1.170
   Best Total Return: 717.24%
   Average Total Return: 121.00%
   Smallest Max Drawdown: -28.68%
   Best Profit Factor: 21.69

#1 - ADX(DI=21,Smooth=31)
   Sharpe Ratio:      1.170
   Total Return:      717.24%
   Annualized Return: 50.26%
   Max Drawdown:      -40.89%
   Win Rate:          75.0%
   Profit Factor:     21.69
   Total Trades:      12 (2.3/year)

#2 - ADX(DI=21,Smooth=32)
   Sharpe Ratio:      1.170
   Total Return:      717.24%
   Annualized Return: 50.26%
   Max Drawdown:      -40.89%
   Win Rate:          75.0%
   Profit Factor:     21.69
   Total Trades:      12 (2.3/year)

#3 - ADX(DI=21,Smooth=33)
   Sharpe Ratio:      1.170
   Total Return:      717.24%
   Annualized Return: 50.26%
   Max Drawdown:      -40.89%
   Win Rate:          75.0%
   Profit Factor:     21.69
   Total Trades:      12 (2.3/year)

#4 - ADX(DI=18,Smooth=36)
   Sharpe Ratio:      1.087
   Total Return:      554.01%
   Annualized Return: 43.91%
   Max Drawdown:      -50.10%
   Win Rate:          78.6%
   Profit Factor:     9.89
   Total Trades:      14 (2.7/year)

#5 - ADX(DI=18,Smooth=37)
   Sharpe Ratio:      1.087
   Total Return:      554.01%
   Annualized Return: 43.91%
   Max Drawdown:      -50.10%
   Win Rate:          78.6%
   Profit Factor:     9.89
   Total Trades:      14 (2.7/year)

DONCHIAN - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------
In-sample summary:
   Stored combinations: 47
   Best Sharpe Ratio: 0.602
   Best Total Return: 119.73%
   Average Total Return: 40.30%
   Smallest Max Drawdown: -32.46%
   Best Profit Factor: 2.30

#1 - DONCHIAN(22)
   Sharpe Ratio:      0.602
   Total Return:      119.73%
   Annualized Return: 16.49%
   Max Drawdown:      -41.52%
   Win Rate:          50.0%
   Profit Factor:     2.17
   Total Trades:      22 (4.3/year)

#2 - DONCHIAN(23)
   Sharpe Ratio:      0.552
   Total Return:      98.76%
   Annualized Return: 14.24%
   Max Drawdown:      -40.41%
   Win Rate:          52.4%
   Profit Factor:     2.08
   Total Trades:      21 (4.1/year)

#3 - DONCHIAN(26)
   Sharpe Ratio:      0.547
   Total Return:      93.06%
   Annualized Return: 13.60%
   Max Drawdown:      -35.99%
   Win Rate:          44.4%
   Profit Factor:     2.10
   Total Trades:      18 (3.5/year)

#4 - DONCHIAN(27)
   Sharpe Ratio:      0.542
   Total Return:      91.05%
   Annualized Return: 13.37%
   Max Drawdown:      -32.46%
   Win Rate:          44.4%
   Profit Factor:     2.08
   Total Trades:      18 (3.5/year)

#5 - DONCHIAN(24)
   Sharpe Ratio:      0.488
   Total Return:      76.57%
   Annualized Return: 11.65%
   Max Drawdown:      -40.42%
   Win Rate:          47.6%
   Profit Factor:     1.91
   Total Trades:      21 (4.1/year)

TRIX - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------
In-sample summary:
   Stored combinations: 19
   Best Sharpe Ratio: 0.769
   Best Total Return: 242.75%
   Average Total Return: 83.55%
   Smallest Max Drawdown: -49.68%
   Best Profit Factor: 2.57

#1 - TRIX(6)
   Sharpe Ratio:      0.769
   Total Return:      242.75%
   Annualized Return: 26.97%
   Max Drawdown:      -59.62%
   Win Rate:          51.7%
   Profit Factor:     2.53
   Total Trades:      29 (5.6/year)

#2 - TRIX(5)
   Sharpe Ratio:      0.724
   Total Return:      219.90%
   Annualized Return: 25.28%
   Max Drawdown:      -59.25%
   Win Rate:          50.0%
   Profit Factor:     2.08
   Total Trades:      40 (7.8/year)

#3 - TRIX(7)
   Sharpe Ratio:      0.711
   Total Return:      202.18%
   Annualized Return: 23.91%
   Max Drawdown:      -55.81%
   Win Rate:          44.0%
   Profit Factor:     2.32
   Total Trades:      25 (4.8/year)

#4 - TRIX(8)
   Sharpe Ratio:      0.679
   Total Return:      182.62%
   Annualized Return: 22.31%
   Max Drawdown:      -58.16%
   Win Rate:          52.2%
   Profit Factor:     2.57
   Total Trades:      23 (4.5/year)

#5 - TRIX(4)
   Sharpe Ratio:      0.556
   Total Return:      115.39%
   Annualized Return: 16.04%
   Max Drawdown:      -61.95%
   Win Rate:          51.9%
   Profit Factor:     1.59
   Total Trades:      54 (10.5/year)

VORTEX - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------
In-sample summary:
   Stored combinations: 88
   Best Sharpe Ratio: 0.684
   Best Total Return: 198.12%
   Average Total Return: 46.14%
   Smallest Max Drawdown: -48.14%
   Best Profit Factor: 4.57

#1 - VORTEX(136)
   Sharpe Ratio:      0.684
   Total Return:      198.12%
   Annualized Return: 23.58%
   Max Drawdown:      -62.09%
   Win Rate:          53.8%
   Profit Factor:     4.57
   Total Trades:      13 (2.5/year)

#2 - VORTEX(135)
   Sharpe Ratio:      0.588
   Total Return:      135.00%
   Annualized Return: 18.01%
   Max Drawdown:      -62.09%
   Win Rate:          45.5%
   Profit Factor:     3.58
   Total Trades:      11 (2.1/year)

#3 - VORTEX(115)
   Sharpe Ratio:      0.586
   Total Return:      131.72%
   Annualized Return: 17.69%
   Max Drawdown:      -62.09%
   Win Rate:          58.3%
   Profit Factor:     3.42
   Total Trades:      12 (2.3/year)

#4 - VORTEX(133)
   Sharpe Ratio:      0.584
   Total Return:      131.74%
   Annualized Return: 17.69%
   Max Drawdown:      -62.09%
   Win Rate:          66.7%
   Profit Factor:     3.59
   Total Trades:      12 (2.3/year)

#5 - VORTEX(131)
   Sharpe Ratio:      0.579
   Total Return:      128.87%
   Annualized Return: 17.41%
   Max Drawdown:      -62.09%
   Win Rate:          53.8%
   Profit Factor:     3.72
   Total Trades:      13 (2.5/year)

ALMA - Top 5 by In-Sample Sharpe Ratio
----------------------------------------------------------------------
In-sample summary:
   Stored combinations: 32077
   Best Sharpe Ratio: 0.786
   Best Total Return: 256.99%
   Average Total Return: -0.95%
   Smallest Max Drawdown: -35.78%
   Best Profit Factor: 34.61

#1 - ALMA(2,99,0.10,3)
   Sharpe Ratio:      0.786
   Total Return:      256.99%
   Annualized Return: 27.98%
   Max Drawdown:      -48.14%
   Win Rate:          76.9%
   Profit Factor:     16.39
   Total Trades:      13 (2.5/year)

#2 - ALMA(2,98,0.18,7)
   Sharpe Ratio:      0.767
   Total Return:      251.82%
   Annualized Return: 27.62%
   Max Drawdown:      -48.14%
   Win Rate:          75.0%
   Profit Factor:     14.11
   Total Trades:      16 (3.1/year)

#3 - ALMA(2,97,0.18,7)
   Sharpe Ratio:      0.754
   Total Return:      240.64%
   Annualized Return: 26.82%
   Max Drawdown:      -48.14%
   Win Rate:          75.0%
   Profit Factor:     18.34
   Total Trades:      16 (3.1/year)

#4 - ALMA(2,99,0.12,3)
   Sharpe Ratio:      0.752
   Total Return:      231.12%
   Annualized Return: 26.12%
   Max Drawdown:      -48.14%
   Win Rate:          64.3%
   Profit Factor:     6.77
   Total Trades:      14 (2.7/year)

#5 - ALMA(2,98,0.10,3)
   Sharpe Ratio:      0.751
   Total Return:      230.09%
   Annualized Return: 26.05%
   Max Drawdown:      -48.14%
   Win Rate:          64.3%
   Profit Factor:     6.70
   Total Trades:      14 (2.7/year)

======================================================================

Analysis complete! Top in-sample results listed separately for each indicator.

In [12]:
# TOP 5 OUT-OF-SAMPLE VALIDATION BY INDICATOR

oos_results_by_indicator = {}
oos_df_by_indicator = {}
oos_df_sorted = pd.DataFrame()  # compatibility: left empty; use oos_df_by_indicator

if "results_df" not in globals():
    raise ValueError("results_df is missing. Run the grid-search analysis cell first.")
if results_df.empty:
    print("No results to validate.")
elif "val_close" not in globals() or val_close is None or len(val_close) < 2:
    raise ValueError("val_close is missing or too short for OOS validation.")
else:
    print("=" * 90)
    print("TOP 5 OUT-OF-SAMPLE VALIDATION BY INDICATOR")
    print("=" * 90)
    print(f"Training Period: {train_close.index[0].date()} -> {train_close.index[-1].date()}")
    print(f"Validation Period: {val_close.index[0].date()} -> {val_close.index[-1].date()}")
    print("Each indicator is validated separately (no cross-indicator ranking).")
    print("Candidates: top 5 in-sample Sharpe per indicator (same metric as the IS table; tie notes below if applicable).")
    print("=" * 90)

    for indicator_name, indicator_results in results_df.groupby("indicator", sort=False):
        top_5_strategies = (
            indicator_results
            .dropna(subset=["sharpe_ratio"])
            .sort_values("sharpe_ratio", ascending=False)
            .head(5)
        )
        if top_5_strategies.empty:
            print(f"No valid in-sample results for {indicator_name}.")
            continue

        maybe_print_tied_is_sharpe_note(
            indicator_name,
            indicator_results,
            top_5_strategies["param_display"].tolist(),
            "OOS validation",
        )

        print("\n" + "=" * 90)
        print(f"{indicator_name} - TOP 5 IN-SAMPLE CANDIDATES ON OOS DATA")
        print("=" * 90)

        try:
            indicator_spec = get_active_indicator_spec(indicator_name)
        except KeyError as exc:
            print(f"Skipping {indicator_name}: {exc}")
            continue

        oos_results = []

        for is_rank, (_, strategy) in enumerate(top_5_strategies.iterrows(), 1):
            try:
                params = require_params_dict(strategy["params"], indicator_name)
                entries, exits = indicator_spec["build_signals"](val_close, params, shift_signals=True)
                pf_val = run_signal_backtest(val_close, entries, exits)

                oos_total_return = float(pf_val.total_return())
                oos_sharpe = float(pf_val.sharpe_ratio(freq=FREQ, year_freq=YEAR_FREQ))
                oos_max_drawdown = float(pf_val.max_drawdown())
                tstats = trade_stats_from_portfolio(pf_val)

                is_sharpe = float(strategy["sharpe_ratio"])
                is_return = float(strategy["total_return"])

                oos_results.append({
                    "IS_Rank": is_rank,
                    "Indicator": indicator_name,
                    "Strategy": strategy["param_display"],
                    "Params": params,
                    "IS_Sharpe": is_sharpe,
                    "IS_Return": is_return,
                    "IS_MaxDD": float(strategy["max_drawdown"]),
                    "IS_WinRate": float(strategy["win_rate"]),
                    "OOS_Sharpe": oos_sharpe,
                    "OOS_Return": oos_total_return,
                    "OOS_MaxDD": oos_max_drawdown,
                    "OOS_WinRate": tstats["win_rate_pct"],
                    "OOS_Trades": tstats["total_trades"],
                    "OOS_ProfitFactor": tstats["profit_factor"],
                    "Sharpe_Degradation": (
                        ((oos_sharpe - is_sharpe) / abs(is_sharpe) * 100)
                        if is_sharpe != 0 else np.nan
                    ),
                    "Return_Degradation": (
                        ((oos_total_return - is_return) / abs(is_return) * 100)
                        if is_return != 0 else np.nan
                    ),
                })
            except Exception as exc:
                print(f"  Skipping IS#{is_rank} {strategy.get('param_display', '?')}: {type(exc).__name__}: {exc}")
                continue

        if not oos_results:
            print(f"No successful OOS backtests for {indicator_name}.")
            continue

        oos_df_indicator = pd.DataFrame(oos_results)
        oos_df_indicator["OOS_Rank"] = (
            oos_df_indicator["OOS_Sharpe"]
            .rank(method="first", ascending=False)
            .astype(int)
        )
        oos_df_is_order = oos_df_indicator.sort_values("IS_Rank").reset_index(drop=True)

        oos_results_by_indicator[indicator_name] = oos_results
        oos_df_by_indicator[indicator_name] = oos_df_is_order

        print(f"\n{indicator_name} - OOS RESULTS (in-sample rank order)")
        print("-" * 90)
        for _, row in oos_df_is_order.iterrows():
            print(f"#{int(row['IS_Rank'])} - {row['Strategy']}")
            print(f"   In-Sample Sharpe:   {fmt_metric(row['IS_Sharpe'], '.3f')}")
            print(f"   OOS Sharpe Ratio:   {fmt_metric(row['OOS_Sharpe'], '.3f')}  (OOS rank #{int(row['OOS_Rank'])})")
            print(f"   OOS Return:         {fmt_metric(row['OOS_Return'], '.2%')}")
            print(f"   OOS Max Drawdown:   {fmt_metric(row['OOS_MaxDD'], '.2%')}")
            print(f"   OOS Win Rate:       {fmt_metric(row['OOS_WinRate'], '.1f', '%')}")
            print(f"   OOS Profit Factor:  {fmt_metric(row['OOS_ProfitFactor'], '.2f')}")
            print(f"   OOS Total Trades:   {int(row['OOS_Trades'])}")
            print(f"   Sharpe Degradation: {fmt_metric(row['Sharpe_Degradation'], '+.1f', '%')}\n")

        display_df = pd.DataFrame({
            "IS Rank": oos_df_is_order["IS_Rank"].astype(int),
            "OOS Rank": oos_df_is_order["OOS_Rank"].astype(int),
            "Strategy": oos_df_is_order["Strategy"],
            "IS Sharpe": oos_df_is_order["IS_Sharpe"].map(lambda x: fmt_metric(x, ".3f")),
            "OOS Sharpe": oos_df_is_order["OOS_Sharpe"].map(lambda x: fmt_metric(x, ".3f")),
            "Sharpe Delta %": oos_df_is_order["Sharpe_Degradation"].map(lambda x: fmt_metric(x, "+.1f", "%")),
            "IS Return": oos_df_is_order["IS_Return"].map(lambda x: fmt_metric(x, ".1%")),
            "OOS Return": oos_df_is_order["OOS_Return"].map(lambda x: fmt_metric(x, ".1%")),
            "Return Delta %": oos_df_is_order["Return_Degradation"].map(lambda x: fmt_metric(x, "+.1f", "%")),
            "OOS Trades": oos_df_is_order["OOS_Trades"].astype(int),
            "OOS WinRate": oos_df_is_order["OOS_WinRate"].map(lambda x: fmt_metric(x, ".1f", "%")),
            "OOS PF": oos_df_is_order["OOS_ProfitFactor"].map(lambda x: fmt_metric(x, ".2f")),
        })
        print(f"{indicator_name} - OOS COMPARISON TABLE (in-sample rank order)")
        print(display_df.to_string(index=False))

        best_oos = best_oos_row(oos_df_indicator)
        if best_oos is None:
            print(f"\nNo valid OOS Sharpe values for {indicator_name}.")
            continue

        print("\n" + "-" * 90)
        print(f"BEST OOS AMONG TOP-5 IS CANDIDATES: {indicator_name}")
        print("-" * 90)
        print(f"Strategy:              {best_oos['Strategy']}")
        print(f"In-Sample Rank:        #{int(best_oos['IS_Rank'])}")
        print(f"Out-of-Sample Rank:    #{int(best_oos['OOS_Rank'])}")
        print(f"OOS Sharpe Ratio:      {fmt_metric(best_oos['OOS_Sharpe'], '.3f')}")
        print(f"OOS Return:            {fmt_metric(best_oos['OOS_Return'], '.2%')}")
        print(f"OOS Max Drawdown:      {fmt_metric(best_oos['OOS_MaxDD'], '.2%')}")
        print(f"OOS Win Rate:          {fmt_metric(best_oos['OOS_WinRate'], '.1f', '%')}")
        print(f"OOS Profit Factor:     {fmt_metric(best_oos['OOS_ProfitFactor'], '.2f')}")
        print(f"OOS Total Trades:      {int(best_oos['OOS_Trades'])}")
        print(f"Sharpe Degradation:    {fmt_metric(best_oos['Sharpe_Degradation'], '+.1f', '%')}")

    print("\n" + "=" * 90)
    print("OOS validation complete for each indicator separately.")
    print("=" * 90)

==========================================================================================
TOP 5 OUT-OF-SAMPLE VALIDATION BY INDICATOR
==========================================================================================
Training Period: 2018-01-02 -> 2023-03-02
Validation Period: 2023-03-03 -> 2026-08-17
Each indicator is validated separately (no cross-indicator ranking).
Candidates: top 5 in-sample Sharpe per indicator (same metric as the IS table; tie notes below if applicable).
==========================================================================================

==========================================================================================
Triple EMA - TOP 5 IN-SAMPLE CANDIDATES ON OOS DATA
==========================================================================================

Triple EMA - OOS RESULTS (in-sample rank order)
------------------------------------------------------------------------------------------
#1 - EMA(5,112,150)
   In-Sample Sharpe:   0.934
   OOS Sharpe Ratio:   0.562  (OOS rank #4)
   OOS Return:         65.84%
   OOS Max Drawdown:   -44.64%
   OOS Win Rate:       40.0%
   OOS Profit Factor:  2.68
   OOS Total Trades:   10
   Sharpe Degradation: -39.8%

#2 - EMA(5,112,148)
   In-Sample Sharpe:   0.930
   OOS Sharpe Ratio:   0.585  (OOS rank #3)
   OOS Return:         71.35%
   OOS Max Drawdown:   -44.64%
   OOS Win Rate:       40.0%
   OOS Profit Factor:  2.93
   OOS Total Trades:   10
   Sharpe Degradation: -37.1%

#3 - EMA(5,112,149)
   In-Sample Sharpe:   0.930
   OOS Sharpe Ratio:   0.562  (OOS rank #5)
   OOS Return:         65.84%
   OOS Max Drawdown:   -44.64%
   OOS Win Rate:       40.0%
   OOS Profit Factor:  2.68
   OOS Total Trades:   10
   Sharpe Degradation: -39.6%

#4 - EMA(4,117,125)
   In-Sample Sharpe:   0.928
   OOS Sharpe Ratio:   0.653  (OOS rank #1)
   OOS Return:         89.60%
   OOS Max Drawdown:   -44.64%
   OOS Win Rate:       50.0%
   OOS Profit Factor:  3.47
   OOS Total Trades:   10
   Sharpe Degradation: -29.6%

#5 - EMA(4,117,129)
   In-Sample Sharpe:   0.928
   OOS Sharpe Ratio:   0.624  (OOS rank #2)
   OOS Return:         81.63%
   OOS Max Drawdown:   -44.64%
   OOS Win Rate:       40.0%
   OOS Profit Factor:  3.37
   OOS Total Trades:   10
   Sharpe Degradation: -32.8%

Triple EMA - OOS COMPARISON TABLE (in-sample rank order)
 IS Rank  OOS Rank       Strategy IS Sharpe OOS Sharpe Sharpe Delta % IS Return OOS Return Return Delta %  OOS Trades OOS WinRate OOS PF
       1         4 EMA(5,112,150)     0.934      0.562         -39.8%    371.4%      65.8%         -82.3%          10       40.0%   2.68
       2         3 EMA(5,112,148)     0.930      0.585         -37.1%    365.6%      71.4%         -80.5%          10       40.0%   2.93
       3         5 EMA(5,112,149)     0.930      0.562         -39.6%    365.6%      65.8%         -82.0%          10       40.0%   2.68
       4         1 EMA(4,117,125)     0.928      0.653         -29.6%    367.0%      89.6%         -75.6%          10       50.0%   3.47
       5         2 EMA(4,117,129)     0.928      0.624         -32.8%    367.0%      81.6%         -77.8%          10       40.0%   3.37

------------------------------------------------------------------------------------------
BEST OOS AMONG TOP-5 IS CANDIDATES: Triple EMA
------------------------------------------------------------------------------------------
Strategy:              EMA(4,117,125)
In-Sample Rank:        #4
Out-of-Sample Rank:    #1
OOS Sharpe Ratio:      0.653
OOS Return:            89.60%
OOS Max Drawdown:      -44.64%
OOS Win Rate:          50.0%
OOS Profit Factor:     3.47
OOS Total Trades:      10
Sharpe Degradation:    -29.6%
Note (OOS validation): MACD has multiple parameter sets tied at the best in-sample Sharpe (0.724). The in-sample top-5 table shows one valid tied set; this step used different tied equivalent(s): MACD(12,61,95)

==========================================================================================
MACD - TOP 5 IN-SAMPLE CANDIDATES ON OOS DATA
==========================================================================================

MACD - OOS RESULTS (in-sample rank order)
------------------------------------------------------------------------------------------
#1 - MACD(12,69,78)
   In-Sample Sharpe:   0.724
   OOS Sharpe Ratio:   1.203  (OOS rank #1)
   OOS Return:         233.71%
   OOS Max Drawdown:   -29.48%
   OOS Win Rate:       66.7%
   OOS Profit Factor:  11.02
   OOS Total Trades:   6
   Sharpe Degradation: +66.1%

#2 - MACD(12,68,79)
   In-Sample Sharpe:   0.724
   OOS Sharpe Ratio:   1.203  (OOS rank #2)
   OOS Return:         233.71%
   OOS Max Drawdown:   -29.48%
   OOS Win Rate:       66.7%
   OOS Profit Factor:  11.02
   OOS Total Trades:   6
   Sharpe Degradation: +66.1%

#3 - MACD(12,61,95)
   In-Sample Sharpe:   0.718
   OOS Sharpe Ratio:   1.127  (OOS rank #4)
   OOS Return:         206.25%
   OOS Max Drawdown:   -29.48%
   OOS Win Rate:       57.1%
   OOS Profit Factor:  7.91
   OOS Total Trades:   7
   Sharpe Degradation: +57.1%

#4 - MACD(12,60,96)
   In-Sample Sharpe:   0.718
   OOS Sharpe Ratio:   1.179  (OOS rank #3)
   OOS Return:         224.06%
   OOS Max Drawdown:   -29.48%
   OOS Win Rate:       66.7%
   OOS Profit Factor:  10.69
   OOS Total Trades:   6
   Sharpe Degradation: +64.3%

#5 - MACD(12,60,97)
   In-Sample Sharpe:   0.718
   OOS Sharpe Ratio:   1.127  (OOS rank #5)
   OOS Return:         206.25%
   OOS Max Drawdown:   -29.48%
   OOS Win Rate:       57.1%
   OOS Profit Factor:  7.91
   OOS Total Trades:   7
   Sharpe Degradation: +57.1%

MACD - OOS COMPARISON TABLE (in-sample rank order)
 IS Rank  OOS Rank       Strategy IS Sharpe OOS Sharpe Sharpe Delta % IS Return OOS Return Return Delta %  OOS Trades OOS WinRate OOS PF
       1         1 MACD(12,69,78)     0.724      1.203         +66.1%    207.5%     233.7%         +12.6%           6       66.7%  11.02
       2         2 MACD(12,68,79)     0.724      1.203         +66.1%    207.5%     233.7%         +12.6%           6       66.7%  11.02
       3         4 MACD(12,61,95)     0.718      1.127         +57.1%    203.5%     206.2%          +1.4%           7       57.1%   7.91
       4         3 MACD(12,60,96)     0.718      1.179         +64.3%    203.5%     224.1%         +10.1%           6       66.7%  10.69
       5         5 MACD(12,60,97)     0.718      1.127         +57.1%    203.5%     206.2%          +1.4%           7       57.1%   7.91

------------------------------------------------------------------------------------------
BEST OOS AMONG TOP-5 IS CANDIDATES: MACD
------------------------------------------------------------------------------------------
Strategy:              MACD(12,69,78)
In-Sample Rank:        #1
Out-of-Sample Rank:    #1
OOS Sharpe Ratio:      1.203
OOS Return:            233.71%
OOS Max Drawdown:      -29.48%
OOS Win Rate:          66.7%
OOS Profit Factor:     11.02
OOS Total Trades:      6
Sharpe Degradation:    +66.1%

==========================================================================================
AROON - TOP 5 IN-SAMPLE CANDIDATES ON OOS DATA
==========================================================================================

AROON - OOS RESULTS (in-sample rank order)
------------------------------------------------------------------------------------------
#1 - AROON(22)
   In-Sample Sharpe:   0.796
   OOS Sharpe Ratio:   0.868  (OOS rank #3)
   OOS Return:         130.46%
   OOS Max Drawdown:   -34.68%
   OOS Win Rate:       50.0%
   OOS Profit Factor:  3.31
   OOS Total Trades:   16
   Sharpe Degradation: +9.1%

#2 - AROON(18)
   In-Sample Sharpe:   0.790
   OOS Sharpe Ratio:   0.816  (OOS rank #4)
   OOS Return:         125.79%
   OOS Max Drawdown:   -35.83%
   OOS Win Rate:       43.5%
   OOS Profit Factor:  2.10
   OOS Total Trades:   23
   Sharpe Degradation: +3.3%

#3 - AROON(21)
   In-Sample Sharpe:   0.722
   OOS Sharpe Ratio:   0.986  (OOS rank #1)
   OOS Return:         181.09%
   OOS Max Drawdown:   -32.31%
   OOS Win Rate:       47.1%
   OOS Profit Factor:  3.45
   OOS Total Trades:   17
   Sharpe Degradation: +36.4%

#4 - AROON(23)
   In-Sample Sharpe:   0.706
   OOS Sharpe Ratio:   0.922  (OOS rank #2)
   OOS Return:         146.54%
   OOS Max Drawdown:   -35.79%
   OOS Win Rate:       50.0%
   OOS Profit Factor:  3.51
   OOS Total Trades:   16
   Sharpe Degradation: +30.6%

#5 - AROON(19)
   In-Sample Sharpe:   0.673
   OOS Sharpe Ratio:   0.771  (OOS rank #5)
   OOS Return:         112.91%
   OOS Max Drawdown:   -36.53%
   OOS Win Rate:       47.6%
   OOS Profit Factor:  2.10
   OOS Total Trades:   21
   Sharpe Degradation: +14.6%

AROON - OOS COMPARISON TABLE (in-sample rank order)
 IS Rank  OOS Rank  Strategy IS Sharpe OOS Sharpe Sharpe Delta % IS Return OOS Return Return Delta %  OOS Trades OOS WinRate OOS PF
       1         3 AROON(22)     0.796      0.868          +9.1%    247.3%     130.5%         -47.2%          16       50.0%   3.31
       2         4 AROON(18)     0.790      0.816          +3.3%    267.0%     125.8%         -52.9%          23       43.5%   2.10
       3         1 AROON(21)     0.722      0.986         +36.4%    198.4%     181.1%          -8.7%          17       47.1%   3.45
       4         2 AROON(23)     0.706      0.922         +30.6%    179.8%     146.5%         -18.5%          16       50.0%   3.51
       5         5 AROON(19)     0.673      0.771         +14.6%    170.7%     112.9%         -33.8%          21       47.6%   2.10

------------------------------------------------------------------------------------------
BEST OOS AMONG TOP-5 IS CANDIDATES: AROON
------------------------------------------------------------------------------------------
Strategy:              AROON(21)
In-Sample Rank:        #3
Out-of-Sample Rank:    #1
OOS Sharpe Ratio:      0.986
OOS Return:            181.09%
OOS Max Drawdown:      -32.31%
OOS Win Rate:          47.1%
OOS Profit Factor:     3.45
OOS Total Trades:      17
Sharpe Degradation:    +36.4%

==========================================================================================
STC - TOP 5 IN-SAMPLE CANDIDATES ON OOS DATA
==========================================================================================

STC - OOS RESULTS (in-sample rank order)
------------------------------------------------------------------------------------------
#1 - STC(38,99,23)
   In-Sample Sharpe:   0.964
   OOS Sharpe Ratio:   1.293  (OOS rank #1)
   OOS Return:         270.62%
   OOS Max Drawdown:   -27.99%
   OOS Win Rate:       50.0%
   OOS Profit Factor:  6.06
   OOS Total Trades:   10
   Sharpe Degradation: +34.1%

#2 - STC(47,81,23)
   In-Sample Sharpe:   0.925
   OOS Sharpe Ratio:   1.129  (OOS rank #5)
   OOS Return:         208.47%
   OOS Max Drawdown:   -32.36%
   OOS Win Rate:       62.5%
   OOS Profit Factor:  6.58
   OOS Total Trades:   8
   Sharpe Degradation: +22.1%

#3 - STC(49,78,23)
   In-Sample Sharpe:   0.924
   OOS Sharpe Ratio:   1.139  (OOS rank #4)
   OOS Return:         212.88%
   OOS Max Drawdown:   -32.36%
   OOS Win Rate:       62.5%
   OOS Profit Factor:  6.91
   OOS Total Trades:   8
   Sharpe Degradation: +23.3%

#4 - STC(35,99,24)
   In-Sample Sharpe:   0.921
   OOS Sharpe Ratio:   1.212  (OOS rank #3)
   OOS Return:         239.98%
   OOS Max Drawdown:   -27.99%
   OOS Win Rate:       62.5%
   OOS Profit Factor:  5.53
   OOS Total Trades:   8
   Sharpe Degradation: +31.6%

#5 - STC(44,73,23)
   In-Sample Sharpe:   0.909
   OOS Sharpe Ratio:   1.251  (OOS rank #2)
   OOS Return:         256.70%
   OOS Max Drawdown:   -27.99%
   OOS Win Rate:       50.0%
   OOS Profit Factor:  5.36
   OOS Total Trades:   10
   Sharpe Degradation: +37.6%

STC - OOS COMPARISON TABLE (in-sample rank order)
 IS Rank  OOS Rank      Strategy IS Sharpe OOS Sharpe Sharpe Delta % IS Return OOS Return Return Delta %  OOS Trades OOS WinRate OOS PF
       1         1 STC(38,99,23)     0.964      1.293         +34.1%    433.7%     270.6%         -37.6%          10       50.0%   6.06
       2         5 STC(47,81,23)     0.925      1.129         +22.1%    387.2%     208.5%         -46.2%           8       62.5%   6.58
       3         4 STC(49,78,23)     0.924      1.139         +23.3%    386.9%     212.9%         -45.0%           8       62.5%   6.91
       4         3 STC(35,99,24)     0.921      1.212         +31.6%    383.7%     240.0%         -37.4%           8       62.5%   5.53
       5         2 STC(44,73,23)     0.909      1.251         +37.6%    377.2%     256.7%         -31.9%          10       50.0%   5.36

------------------------------------------------------------------------------------------
BEST OOS AMONG TOP-5 IS CANDIDATES: STC
------------------------------------------------------------------------------------------
Strategy:              STC(38,99,23)
In-Sample Rank:        #1
Out-of-Sample Rank:    #1
OOS Sharpe Ratio:      1.293
OOS Return:            270.62%
OOS Max Drawdown:      -27.99%
OOS Win Rate:          50.0%
OOS Profit Factor:     6.06
OOS Total Trades:      10
Sharpe Degradation:    +34.1%
Note (OOS validation): KAMA has multiple parameter sets tied at the best in-sample Sharpe (0.807). The in-sample top-5 table shows one valid tied set; this step used different tied equivalent(s): KAMA(10,7,99)

==========================================================================================
KAMA - TOP 5 IN-SAMPLE CANDIDATES ON OOS DATA
==========================================================================================

KAMA - OOS RESULTS (in-sample rank order)
------------------------------------------------------------------------------------------
#1 - KAMA(10,7,97)
   In-Sample Sharpe:   0.807
   OOS Sharpe Ratio:   0.942  (OOS rank #2)
   OOS Return:         191.39%
   OOS Max Drawdown:   -35.32%
   OOS Win Rate:       43.8%
   OOS Profit Factor:  3.99
   OOS Total Trades:   16
   Sharpe Degradation: +16.8%

#2 - KAMA(10,7,96)
   In-Sample Sharpe:   0.807
   OOS Sharpe Ratio:   0.942  (OOS rank #3)
   OOS Return:         191.39%
   OOS Max Drawdown:   -35.32%
   OOS Win Rate:       43.8%
   OOS Profit Factor:  3.99
   OOS Total Trades:   16
   Sharpe Degradation: +16.8%

#3 - KAMA(10,7,95)
   In-Sample Sharpe:   0.807
   OOS Sharpe Ratio:   0.942  (OOS rank #4)
   OOS Return:         191.39%
   OOS Max Drawdown:   -35.32%
   OOS Win Rate:       43.8%
   OOS Profit Factor:  3.99
   OOS Total Trades:   16
   Sharpe Degradation: +16.8%

#4 - KAMA(10,7,94)
   In-Sample Sharpe:   0.807
   OOS Sharpe Ratio:   0.940  (OOS rank #5)
   OOS Return:         190.62%
   OOS Max Drawdown:   -35.49%
   OOS Win Rate:       43.8%
   OOS Profit Factor:  3.97
   OOS Total Trades:   16
   Sharpe Degradation: +16.5%

#5 - KAMA(10,7,99)
   In-Sample Sharpe:   0.807
   OOS Sharpe Ratio:   0.964  (OOS rank #1)
   OOS Return:         201.52%
   OOS Max Drawdown:   -35.32%
   OOS Win Rate:       40.0%
   OOS Profit Factor:  4.33
   OOS Total Trades:   15
   Sharpe Degradation: +19.6%

KAMA - OOS COMPARISON TABLE (in-sample rank order)
 IS Rank  OOS Rank      Strategy IS Sharpe OOS Sharpe Sharpe Delta % IS Return OOS Return Return Delta %  OOS Trades OOS WinRate OOS PF
       1         2 KAMA(10,7,97)     0.807      0.942         +16.8%    260.2%     191.4%         -26.4%          16       43.8%   3.99
       2         3 KAMA(10,7,96)     0.807      0.942         +16.8%    260.2%     191.4%         -26.4%          16       43.8%   3.99
       3         4 KAMA(10,7,95)     0.807      0.942         +16.8%    260.2%     191.4%         -26.4%          16       43.8%   3.99
       4         5 KAMA(10,7,94)     0.807      0.940         +16.5%    260.2%     190.6%         -26.7%          16       43.8%   3.97
       5         1 KAMA(10,7,99)     0.807      0.964         +19.6%    260.2%     201.5%         -22.6%          15       40.0%   4.33

------------------------------------------------------------------------------------------
BEST OOS AMONG TOP-5 IS CANDIDATES: KAMA
------------------------------------------------------------------------------------------
Strategy:              KAMA(10,7,99)
In-Sample Rank:        #5
Out-of-Sample Rank:    #1
OOS Sharpe Ratio:      0.964
OOS Return:            201.52%
OOS Max Drawdown:      -35.32%
OOS Win Rate:          40.0%
OOS Profit Factor:     4.33
OOS Total Trades:      15
Sharpe Degradation:    +19.6%

==========================================================================================
SUPERTREND - TOP 5 IN-SAMPLE CANDIDATES ON OOS DATA
==========================================================================================

SUPERTREND - OOS RESULTS (in-sample rank order)
------------------------------------------------------------------------------------------
#1 - SUPERTREND(ATR=88,Factor=3)
   In-Sample Sharpe:   0.852
   OOS Sharpe Ratio:   1.059  (OOS rank #3)
   OOS Return:         191.21%
   OOS Max Drawdown:   -26.28%
   OOS Win Rate:       42.9%
   OOS Profit Factor:  3.25
   OOS Total Trades:   14
   Sharpe Degradation: +24.3%

#2 - SUPERTREND(ATR=87,Factor=3)
   In-Sample Sharpe:   0.814
   OOS Sharpe Ratio:   1.059  (OOS rank #4)
   OOS Return:         191.21%
   OOS Max Drawdown:   -26.28%
   OOS Win Rate:       42.9%
   OOS Profit Factor:  3.25
   OOS Total Trades:   14
   Sharpe Degradation: +30.1%

#3 - SUPERTREND(ATR=89,Factor=3)
   In-Sample Sharpe:   0.808
   OOS Sharpe Ratio:   1.064  (OOS rank #1)
   OOS Return:         193.00%
   OOS Max Drawdown:   -26.28%
   OOS Win Rate:       42.9%
   OOS Profit Factor:  3.27
   OOS Total Trades:   14
   Sharpe Degradation: +31.7%

#4 - SUPERTREND(ATR=91,Factor=3)
   In-Sample Sharpe:   0.808
   OOS Sharpe Ratio:   1.063  (OOS rank #2)
   OOS Return:         192.76%
   OOS Max Drawdown:   -26.34%
   OOS Win Rate:       42.9%
   OOS Profit Factor:  3.27
   OOS Total Trades:   14
   Sharpe Degradation: +31.7%

#5 - SUPERTREND(ATR=4,Factor=2)
   In-Sample Sharpe:   0.804
   OOS Sharpe Ratio:   0.992  (OOS rank #5)
   OOS Return:         171.51%
   OOS Max Drawdown:   -39.46%
   OOS Win Rate:       36.0%
   OOS Profit Factor:  2.33
   OOS Total Trades:   25
   Sharpe Degradation: +23.4%

SUPERTREND - OOS COMPARISON TABLE (in-sample rank order)
 IS Rank  OOS Rank                    Strategy IS Sharpe OOS Sharpe Sharpe Delta % IS Return OOS Return Return Delta %  OOS Trades OOS WinRate OOS PF
       1         3 SUPERTREND(ATR=88,Factor=3)     0.852      1.059         +24.3%    317.5%     191.2%         -39.8%          14       42.9%   3.25
       2         4 SUPERTREND(ATR=87,Factor=3)     0.814      1.059         +30.1%    284.5%     191.2%         -32.8%          14       42.9%   3.25
       3         1 SUPERTREND(ATR=89,Factor=3)     0.808      1.064         +31.7%    276.2%     193.0%         -30.1%          14       42.9%   3.27
       4         2 SUPERTREND(ATR=91,Factor=3)     0.808      1.063         +31.7%    276.2%     192.8%         -30.2%          14       42.9%   3.27
       5         5  SUPERTREND(ATR=4,Factor=2)     0.804      0.992         +23.4%    256.7%     171.5%         -33.2%          25       36.0%   2.33

------------------------------------------------------------------------------------------
BEST OOS AMONG TOP-5 IS CANDIDATES: SUPERTREND
------------------------------------------------------------------------------------------
Strategy:              SUPERTREND(ATR=89,Factor=3)
In-Sample Rank:        #3
Out-of-Sample Rank:    #1
OOS Sharpe Ratio:      1.064
OOS Return:            193.00%
OOS Max Drawdown:      -26.28%
OOS Win Rate:          42.9%
OOS Profit Factor:     3.27
OOS Total Trades:      14
Sharpe Degradation:    +31.7%

==========================================================================================
KALMAN - TOP 5 IN-SAMPLE CANDIDATES ON OOS DATA
==========================================================================================

KALMAN - OOS RESULTS (in-sample rank order)
------------------------------------------------------------------------------------------
#1 - KALMAN(Q=1,R=159)
   In-Sample Sharpe:   0.851
   OOS Sharpe Ratio:   1.315  (OOS rank #1)
   OOS Return:         350.44%
   OOS Max Drawdown:   -34.73%
   OOS Win Rate:       45.8%
   OOS Profit Factor:  2.89
   OOS Total Trades:   48
   Sharpe Degradation: +54.5%

#2 - KALMAN(Q=1,R=157)
   In-Sample Sharpe:   0.851
   OOS Sharpe Ratio:   1.315  (OOS rank #2)
   OOS Return:         350.44%
   OOS Max Drawdown:   -34.73%
   OOS Win Rate:       45.8%
   OOS Profit Factor:  2.89
   OOS Total Trades:   48
   Sharpe Degradation: +54.5%

#3 - KALMAN(Q=1,R=158)
   In-Sample Sharpe:   0.851
   OOS Sharpe Ratio:   1.315  (OOS rank #3)
   OOS Return:         350.44%
   OOS Max Drawdown:   -34.73%
   OOS Win Rate:       45.8%
   OOS Profit Factor:  2.89
   OOS Total Trades:   48
   Sharpe Degradation: +54.5%

#4 - KALMAN(Q=1,R=154)
   In-Sample Sharpe:   0.823
   OOS Sharpe Ratio:   1.315  (OOS rank #4)
   OOS Return:         350.44%
   OOS Max Drawdown:   -34.73%
   OOS Win Rate:       45.8%
   OOS Profit Factor:  2.89
   OOS Total Trades:   48
   Sharpe Degradation: +59.8%

#5 - KALMAN(Q=1,R=155)
   In-Sample Sharpe:   0.823
   OOS Sharpe Ratio:   1.315  (OOS rank #5)
   OOS Return:         350.44%
   OOS Max Drawdown:   -34.73%
   OOS Win Rate:       45.8%
   OOS Profit Factor:  2.89
   OOS Total Trades:   48
   Sharpe Degradation: +59.8%

KALMAN - OOS COMPARISON TABLE (in-sample rank order)
 IS Rank  OOS Rank          Strategy IS Sharpe OOS Sharpe Sharpe Delta % IS Return OOS Return Return Delta %  OOS Trades OOS WinRate OOS PF
       1         1 KALMAN(Q=1,R=159)     0.851      1.315         +54.5%    299.9%     350.4%         +16.9%          48       45.8%   2.89
       2         2 KALMAN(Q=1,R=157)     0.851      1.315         +54.5%    299.9%     350.4%         +16.9%          48       45.8%   2.89
       3         3 KALMAN(Q=1,R=158)     0.851      1.315         +54.5%    299.9%     350.4%         +16.9%          48       45.8%   2.89
       4         4 KALMAN(Q=1,R=154)     0.823      1.315         +59.8%    275.2%     350.4%         +27.4%          48       45.8%   2.89
       5         5 KALMAN(Q=1,R=155)     0.823      1.315         +59.8%    275.2%     350.4%         +27.4%          48       45.8%   2.89

------------------------------------------------------------------------------------------
BEST OOS AMONG TOP-5 IS CANDIDATES: KALMAN
------------------------------------------------------------------------------------------
Strategy:              KALMAN(Q=1,R=159)
In-Sample Rank:        #1
Out-of-Sample Rank:    #1
OOS Sharpe Ratio:      1.315
OOS Return:            350.44%
OOS Max Drawdown:      -34.73%
OOS Win Rate:          45.8%
OOS Profit Factor:     2.89
OOS Total Trades:      48
Sharpe Degradation:    +54.5%

==========================================================================================
RSI - TOP 5 IN-SAMPLE CANDIDATES ON OOS DATA
==========================================================================================

RSI - OOS RESULTS (in-sample rank order)
------------------------------------------------------------------------------------------
#1 - RSI(71)
   In-Sample Sharpe:   0.781
   OOS Sharpe Ratio:   0.781  (OOS rank #5)
   OOS Return:         129.34%
   OOS Max Drawdown:   -39.73%
   OOS Win Rate:       46.2%
   OOS Profit Factor:  4.05
   OOS Total Trades:   13
   Sharpe Degradation: -0.1%

#2 - RSI(72)
   In-Sample Sharpe:   0.779
   OOS Sharpe Ratio:   0.853  (OOS rank #2)
   OOS Return:         155.94%
   OOS Max Drawdown:   -39.73%
   OOS Win Rate:       50.0%
   OOS Profit Factor:  5.57
   OOS Total Trades:   12
   Sharpe Degradation: +9.5%

#3 - RSI(73)
   In-Sample Sharpe:   0.779
   OOS Sharpe Ratio:   0.855  (OOS rank #1)
   OOS Return:         156.86%
   OOS Max Drawdown:   -39.73%
   OOS Win Rate:       53.8%
   OOS Profit Factor:  5.63
   OOS Total Trades:   13
   Sharpe Degradation: +9.8%

#4 - RSI(74)
   In-Sample Sharpe:   0.769
   OOS Sharpe Ratio:   0.808  (OOS rank #3)
   OOS Return:         140.37%
   OOS Max Drawdown:   -39.73%
   OOS Win Rate:       53.8%
   OOS Profit Factor:  4.29
   OOS Total Trades:   13
   Sharpe Degradation: +5.1%

#5 - RSI(75)
   In-Sample Sharpe:   0.749
   OOS Sharpe Ratio:   0.808  (OOS rank #4)
   OOS Return:         140.37%
   OOS Max Drawdown:   -39.73%
   OOS Win Rate:       53.8%
   OOS Profit Factor:  4.29
   OOS Total Trades:   13
   Sharpe Degradation: +8.0%

RSI - OOS COMPARISON TABLE (in-sample rank order)
 IS Rank  OOS Rank Strategy IS Sharpe OOS Sharpe Sharpe Delta % IS Return OOS Return Return Delta %  OOS Trades OOS WinRate OOS PF
       1         5  RSI(71)     0.781      0.781          -0.1%    245.8%     129.3%         -47.4%          13       46.2%   4.05
       2         2  RSI(72)     0.779      0.853          +9.5%    243.8%     155.9%         -36.1%          12       50.0%   5.57
       3         1  RSI(73)     0.779      0.855          +9.8%    243.4%     156.9%         -35.6%          13       53.8%   5.63
       4         3  RSI(74)     0.769      0.808          +5.1%    236.1%     140.4%         -40.5%          13       53.8%   4.29
       5         4  RSI(75)     0.749      0.808          +8.0%    222.4%     140.4%         -36.9%          13       53.8%   4.29

------------------------------------------------------------------------------------------
BEST OOS AMONG TOP-5 IS CANDIDATES: RSI
------------------------------------------------------------------------------------------
Strategy:              RSI(73)
In-Sample Rank:        #3
Out-of-Sample Rank:    #1
OOS Sharpe Ratio:      0.855
OOS Return:            156.86%
OOS Max Drawdown:      -39.73%
OOS Win Rate:          53.8%
OOS Profit Factor:     5.63
OOS Total Trades:      13
Sharpe Degradation:    +9.8%

==========================================================================================
ADX - TOP 5 IN-SAMPLE CANDIDATES ON OOS DATA
==========================================================================================

ADX - OOS RESULTS (in-sample rank order)
------------------------------------------------------------------------------------------
#1 - ADX(DI=21,Smooth=31)
   In-Sample Sharpe:   1.170
   OOS Sharpe Ratio:   0.971  (OOS rank #1)
   OOS Return:         124.47%
   OOS Max Drawdown:   -39.77%
   OOS Win Rate:       66.7%
   OOS Profit Factor:  12.54
   OOS Total Trades:   9
   Sharpe Degradation: -17.0%

#2 - ADX(DI=21,Smooth=33)
   In-Sample Sharpe:   1.170
   OOS Sharpe Ratio:   0.971  (OOS rank #2)
   OOS Return:         124.47%
   OOS Max Drawdown:   -39.77%
   OOS Win Rate:       66.7%
   OOS Profit Factor:  12.54
   OOS Total Trades:   9
   Sharpe Degradation: -17.0%

#3 - ADX(DI=21,Smooth=32)
   In-Sample Sharpe:   1.170
   OOS Sharpe Ratio:   0.971  (OOS rank #3)
   OOS Return:         124.47%
   OOS Max Drawdown:   -39.77%
   OOS Win Rate:       66.7%
   OOS Profit Factor:  12.54
   OOS Total Trades:   9
   Sharpe Degradation: -17.0%

#4 - ADX(DI=18,Smooth=36)
   In-Sample Sharpe:   1.087
   OOS Sharpe Ratio:   0.947  (OOS rank #4)
   OOS Return:         236.41%
   OOS Max Drawdown:   -58.04%
   OOS Win Rate:       70.0%
   OOS Profit Factor:  24.37
   OOS Total Trades:   10
   Sharpe Degradation: -12.9%

#5 - ADX(DI=18,Smooth=37)
   In-Sample Sharpe:   1.087
   OOS Sharpe Ratio:   0.947  (OOS rank #5)
   OOS Return:         236.41%
   OOS Max Drawdown:   -58.04%
   OOS Win Rate:       70.0%
   OOS Profit Factor:  24.37
   OOS Total Trades:   10
   Sharpe Degradation: -12.9%

ADX - OOS COMPARISON TABLE (in-sample rank order)
 IS Rank  OOS Rank             Strategy IS Sharpe OOS Sharpe Sharpe Delta % IS Return OOS Return Return Delta %  OOS Trades OOS WinRate OOS PF
       1         1 ADX(DI=21,Smooth=31)     1.170      0.971         -17.0%    717.2%     124.5%         -82.6%           9       66.7%  12.54
       2         2 ADX(DI=21,Smooth=33)     1.170      0.971         -17.0%    717.2%     124.5%         -82.6%           9       66.7%  12.54
       3         3 ADX(DI=21,Smooth=32)     1.170      0.971         -17.0%    717.2%     124.5%         -82.6%           9       66.7%  12.54
       4         4 ADX(DI=18,Smooth=36)     1.087      0.947         -12.9%    554.0%     236.4%         -57.3%          10       70.0%  24.37
       5         5 ADX(DI=18,Smooth=37)     1.087      0.947         -12.9%    554.0%     236.4%         -57.3%          10       70.0%  24.37

------------------------------------------------------------------------------------------
BEST OOS AMONG TOP-5 IS CANDIDATES: ADX
------------------------------------------------------------------------------------------
Strategy:              ADX(DI=21,Smooth=31)
In-Sample Rank:        #1
Out-of-Sample Rank:    #1
OOS Sharpe Ratio:      0.971
OOS Return:            124.47%
OOS Max Drawdown:      -39.77%
OOS Win Rate:          66.7%
OOS Profit Factor:     12.54
OOS Total Trades:      9
Sharpe Degradation:    -17.0%

==========================================================================================
DONCHIAN - TOP 5 IN-SAMPLE CANDIDATES ON OOS DATA
==========================================================================================

DONCHIAN - OOS RESULTS (in-sample rank order)
------------------------------------------------------------------------------------------
#1 - DONCHIAN(22)
   In-Sample Sharpe:   0.602
   OOS Sharpe Ratio:   0.962  (OOS rank #3)
   OOS Return:         129.94%
   OOS Max Drawdown:   -35.30%
   OOS Win Rate:       50.0%
   OOS Profit Factor:  3.04
   OOS Total Trades:   16
   Sharpe Degradation: +59.7%

#2 - DONCHIAN(23)
   In-Sample Sharpe:   0.552
   OOS Sharpe Ratio:   0.968  (OOS rank #2)
   OOS Return:         131.36%
   OOS Max Drawdown:   -35.30%
   OOS Win Rate:       50.0%
   OOS Profit Factor:  3.05
   OOS Total Trades:   16
   Sharpe Degradation: +75.3%

#3 - DONCHIAN(26)
   In-Sample Sharpe:   0.547
   OOS Sharpe Ratio:   0.883  (OOS rank #4)
   OOS Return:         114.32%
   OOS Max Drawdown:   -39.94%
   OOS Win Rate:       50.0%
   OOS Profit Factor:  2.88
   OOS Total Trades:   14
   Sharpe Degradation: +61.3%

#4 - DONCHIAN(27)
   In-Sample Sharpe:   0.542
   OOS Sharpe Ratio:   0.883  (OOS rank #5)
   OOS Return:         114.32%
   OOS Max Drawdown:   -39.94%
   OOS Win Rate:       50.0%
   OOS Profit Factor:  2.88
   OOS Total Trades:   14
   Sharpe Degradation: +62.8%

#5 - DONCHIAN(24)
   In-Sample Sharpe:   0.488
   OOS Sharpe Ratio:   1.002  (OOS rank #1)
   OOS Return:         140.58%
   OOS Max Drawdown:   -35.30%
   OOS Win Rate:       57.1%
   OOS Profit Factor:  3.35
   OOS Total Trades:   14
   Sharpe Degradation: +105.3%

DONCHIAN - OOS COMPARISON TABLE (in-sample rank order)
 IS Rank  OOS Rank     Strategy IS Sharpe OOS Sharpe Sharpe Delta % IS Return OOS Return Return Delta %  OOS Trades OOS WinRate OOS PF
       1         3 DONCHIAN(22)     0.602      0.962         +59.7%    119.7%     129.9%          +8.5%          16       50.0%   3.04
       2         2 DONCHIAN(23)     0.552      0.968         +75.3%     98.8%     131.4%         +33.0%          16       50.0%   3.05
       3         4 DONCHIAN(26)     0.547      0.883         +61.3%     93.1%     114.3%         +22.9%          14       50.0%   2.88
       4         5 DONCHIAN(27)     0.542      0.883         +62.8%     91.1%     114.3%         +25.6%          14       50.0%   2.88
       5         1 DONCHIAN(24)     0.488      1.002        +105.3%     76.6%     140.6%         +83.6%          14       57.1%   3.35

------------------------------------------------------------------------------------------
BEST OOS AMONG TOP-5 IS CANDIDATES: DONCHIAN
------------------------------------------------------------------------------------------
Strategy:              DONCHIAN(24)
In-Sample Rank:        #5
Out-of-Sample Rank:    #1
OOS Sharpe Ratio:      1.002
OOS Return:            140.58%
OOS Max Drawdown:      -35.30%
OOS Win Rate:          57.1%
OOS Profit Factor:     3.35
OOS Total Trades:      14
Sharpe Degradation:    +105.3%

==========================================================================================
TRIX - TOP 5 IN-SAMPLE CANDIDATES ON OOS DATA
==========================================================================================

TRIX - OOS RESULTS (in-sample rank order)
------------------------------------------------------------------------------------------
#1 - TRIX(6)
   In-Sample Sharpe:   0.769
   OOS Sharpe Ratio:   1.066  (OOS rank #2)
   OOS Return:         212.24%
   OOS Max Drawdown:   -32.21%
   OOS Win Rate:       44.0%
   OOS Profit Factor:  2.48
   OOS Total Trades:   25
   Sharpe Degradation: +38.7%

#2 - TRIX(5)
   In-Sample Sharpe:   0.724
   OOS Sharpe Ratio:   0.950  (OOS rank #4)
   OOS Return:         166.31%
   OOS Max Drawdown:   -38.96%
   OOS Win Rate:       37.5%
   OOS Profit Factor:  2.19
   OOS Total Trades:   32
   Sharpe Degradation: +31.2%

#3 - TRIX(7)
   In-Sample Sharpe:   0.711
   OOS Sharpe Ratio:   1.169  (OOS rank #1)
   OOS Return:         262.23%
   OOS Max Drawdown:   -35.98%
   OOS Win Rate:       47.6%
   OOS Profit Factor:  3.01
   OOS Total Trades:   21
   Sharpe Degradation: +64.4%

#4 - TRIX(8)
   In-Sample Sharpe:   0.679
   OOS Sharpe Ratio:   1.037  (OOS rank #3)
   OOS Return:         208.63%
   OOS Max Drawdown:   -44.29%
   OOS Win Rate:       52.6%
   OOS Profit Factor:  2.69
   OOS Total Trades:   19
   Sharpe Degradation: +52.7%

#5 - TRIX(4)
   In-Sample Sharpe:   0.556
   OOS Sharpe Ratio:   0.932  (OOS rank #5)
   OOS Return:         156.90%
   OOS Max Drawdown:   -37.60%
   OOS Win Rate:       45.2%
   OOS Profit Factor:  2.06
   OOS Total Trades:   42
   Sharpe Degradation: +67.5%

TRIX - OOS COMPARISON TABLE (in-sample rank order)
 IS Rank  OOS Rank Strategy IS Sharpe OOS Sharpe Sharpe Delta % IS Return OOS Return Return Delta %  OOS Trades OOS WinRate OOS PF
       1         2  TRIX(6)     0.769      1.066         +38.7%    242.7%     212.2%         -12.6%          25       44.0%   2.48
       2         4  TRIX(5)     0.724      0.950         +31.2%    219.9%     166.3%         -24.4%          32       37.5%   2.19
       3         1  TRIX(7)     0.711      1.169         +64.4%    202.2%     262.2%         +29.7%          21       47.6%   3.01
       4         3  TRIX(8)     0.679      1.037         +52.7%    182.6%     208.6%         +14.2%          19       52.6%   2.69
       5         5  TRIX(4)     0.556      0.932         +67.5%    115.4%     156.9%         +36.0%          42       45.2%   2.06

------------------------------------------------------------------------------------------
BEST OOS AMONG TOP-5 IS CANDIDATES: TRIX
------------------------------------------------------------------------------------------
Strategy:              TRIX(7)
In-Sample Rank:        #3
Out-of-Sample Rank:    #1
OOS Sharpe Ratio:      1.169
OOS Return:            262.23%
OOS Max Drawdown:      -35.98%
OOS Win Rate:          47.6%
OOS Profit Factor:     3.01
OOS Total Trades:      21
Sharpe Degradation:    +64.4%

==========================================================================================
VORTEX - TOP 5 IN-SAMPLE CANDIDATES ON OOS DATA
==========================================================================================

VORTEX - OOS RESULTS (in-sample rank order)
------------------------------------------------------------------------------------------
#1 - VORTEX(136)
   In-Sample Sharpe:   0.684
   OOS Sharpe Ratio:   0.231  (OOS rank #5)
   OOS Return:         6.36%
   OOS Max Drawdown:   -44.76%
   OOS Win Rate:       42.9%
   OOS Profit Factor:  0.50
   OOS Total Trades:   7
   Sharpe Degradation: -66.2%

#2 - VORTEX(135)
   In-Sample Sharpe:   0.588
   OOS Sharpe Ratio:   0.362  (OOS rank #4)
   OOS Return:         24.96%
   OOS Max Drawdown:   -46.54%
   OOS Win Rate:       27.3%
   OOS Profit Factor:  1.29
   OOS Total Trades:   11
   Sharpe Degradation: -38.5%

#3 - VORTEX(115)
   In-Sample Sharpe:   0.586
   OOS Sharpe Ratio:   0.593  (OOS rank #1)
   OOS Return:         74.51%
   OOS Max Drawdown:   -36.87%
   OOS Win Rate:       54.5%
   OOS Profit Factor:  5.27
   OOS Total Trades:   11
   Sharpe Degradation: +1.2%

#4 - VORTEX(133)
   In-Sample Sharpe:   0.584
   OOS Sharpe Ratio:   0.513  (OOS rank #3)
   OOS Return:         51.50%
   OOS Max Drawdown:   -35.18%
   OOS Win Rate:       50.0%
   OOS Profit Factor:  2.08
   OOS Total Trades:   12
   Sharpe Degradation: -12.2%

#5 - VORTEX(131)
   In-Sample Sharpe:   0.579
   OOS Sharpe Ratio:   0.562  (OOS rank #2)
   OOS Return:         61.06%
   OOS Max Drawdown:   -33.64%
   OOS Win Rate:       57.1%
   OOS Profit Factor:  2.03
   OOS Total Trades:   14
   Sharpe Degradation: -2.9%

VORTEX - OOS COMPARISON TABLE (in-sample rank order)
 IS Rank  OOS Rank    Strategy IS Sharpe OOS Sharpe Sharpe Delta % IS Return OOS Return Return Delta %  OOS Trades OOS WinRate OOS PF
       1         5 VORTEX(136)     0.684      0.231         -66.2%    198.1%       6.4%         -96.8%           7       42.9%   0.50
       2         4 VORTEX(135)     0.588      0.362         -38.5%    135.0%      25.0%         -81.5%          11       27.3%   1.29
       3         1 VORTEX(115)     0.586      0.593          +1.2%    131.7%      74.5%         -43.4%          11       54.5%   5.27
       4         3 VORTEX(133)     0.584      0.513         -12.2%    131.7%      51.5%         -60.9%          12       50.0%   2.08
       5         2 VORTEX(131)     0.579      0.562          -2.9%    128.9%      61.1%         -52.6%          14       57.1%   2.03

------------------------------------------------------------------------------------------
BEST OOS AMONG TOP-5 IS CANDIDATES: VORTEX
------------------------------------------------------------------------------------------
Strategy:              VORTEX(115)
In-Sample Rank:        #3
Out-of-Sample Rank:    #1
OOS Sharpe Ratio:      0.593
OOS Return:            74.51%
OOS Max Drawdown:      -36.87%
OOS Win Rate:          54.5%
OOS Profit Factor:     5.27
OOS Total Trades:      11
Sharpe Degradation:    +1.2%

==========================================================================================
ALMA - TOP 5 IN-SAMPLE CANDIDATES ON OOS DATA
==========================================================================================

ALMA - OOS RESULTS (in-sample rank order)
------------------------------------------------------------------------------------------
#1 - ALMA(2,99,0.10,3)
   In-Sample Sharpe:   0.786
   OOS Sharpe Ratio:   0.665  (OOS rank #1)
   OOS Return:         92.38%
   OOS Max Drawdown:   -43.11%
   OOS Win Rate:       50.0%
   OOS Profit Factor:  2.54
   OOS Total Trades:   10
   Sharpe Degradation: -15.3%

#2 - ALMA(2,98,0.18,7)
   In-Sample Sharpe:   0.767
   OOS Sharpe Ratio:   0.589  (OOS rank #4)
   OOS Return:         72.72%
   OOS Max Drawdown:   -46.71%
   OOS Win Rate:       58.3%
   OOS Profit Factor:  2.08
   OOS Total Trades:   12
   Sharpe Degradation: -23.2%

#3 - ALMA(2,97,0.18,7)
   In-Sample Sharpe:   0.754
   OOS Sharpe Ratio:   0.558  (OOS rank #5)
   OOS Return:         65.16%
   OOS Max Drawdown:   -47.76%
   OOS Win Rate:       46.7%
   OOS Profit Factor:  1.78
   OOS Total Trades:   15
   Sharpe Degradation: -25.9%

#4 - ALMA(2,99,0.12,3)
   In-Sample Sharpe:   0.752
   OOS Sharpe Ratio:   0.658  (OOS rank #2)
   OOS Return:         90.31%
   OOS Max Drawdown:   -42.34%
   OOS Win Rate:       54.5%
   OOS Profit Factor:  2.50
   OOS Total Trades:   11
   Sharpe Degradation: -12.5%

#5 - ALMA(2,98,0.10,3)
   In-Sample Sharpe:   0.751
   OOS Sharpe Ratio:   0.649  (OOS rank #3)
   OOS Return:         87.92%
   OOS Max Drawdown:   -42.34%
   OOS Win Rate:       40.0%
   OOS Profit Factor:  2.44
   OOS Total Trades:   10
   Sharpe Degradation: -13.5%

ALMA - OOS COMPARISON TABLE (in-sample rank order)
 IS Rank  OOS Rank          Strategy IS Sharpe OOS Sharpe Sharpe Delta % IS Return OOS Return Return Delta %  OOS Trades OOS WinRate OOS PF
       1         1 ALMA(2,99,0.10,3)     0.786      0.665         -15.3%    257.0%      92.4%         -64.1%          10       50.0%   2.54
       2         4 ALMA(2,98,0.18,7)     0.767      0.589         -23.2%    251.8%      72.7%         -71.1%          12       58.3%   2.08
       3         5 ALMA(2,97,0.18,7)     0.754      0.558         -25.9%    240.6%      65.2%         -72.9%          15       46.7%   1.78
       4         2 ALMA(2,99,0.12,3)     0.752      0.658         -12.5%    231.1%      90.3%         -60.9%          11       54.5%   2.50
       5         3 ALMA(2,98,0.10,3)     0.751      0.649         -13.5%    230.1%      87.9%         -61.8%          10       40.0%   2.44

------------------------------------------------------------------------------------------
BEST OOS AMONG TOP-5 IS CANDIDATES: ALMA
------------------------------------------------------------------------------------------
Strategy:              ALMA(2,99,0.10,3)
In-Sample Rank:        #1
Out-of-Sample Rank:    #1
OOS Sharpe Ratio:      0.665
OOS Return:            92.38%
OOS Max Drawdown:      -43.11%
OOS Win Rate:          50.0%
OOS Profit Factor:     2.54
OOS Total Trades:      10
Sharpe Degradation:    -15.3%

==========================================================================================
OOS validation complete for each indicator separately.
==========================================================================================

In [13]:
# FULL-SAMPLE EVALUATION BY INDICATOR

if "results_df" not in globals() or results_df.empty:
    raise ValueError("results_df is empty or missing. Run the grid search first.")

# Reuse the already-prepared full Close series (avoid re-parsing MultiIndex columns).
if "close" in globals() and close is not None and len(close) >= 2:
    full_close = close.astype(float).copy()
    full_close.name = TICKER
else:
    full_close = select_close_series(stock_data, TICKER).astype(float)
    full_close.name = TICKER

if len(full_close) < 2:
    raise ValueError("full_close is too short for full-sample evaluation.")

years = sample_years(full_close)
bh_total_return = (full_close.iloc[-1] / full_close.iloc[0]) - 1.0
bh_annualized = (1.0 + bh_total_return) ** (1.0 / years) - 1.0 if years > 0 else np.nan

full_sample_results_by_indicator = {}

print("=" * 90)
print("FULL-SAMPLE EVALUATION BY INDICATOR")
print("=" * 90)
print(f"Period: {full_close.index[0].date()} -> {full_close.index[-1].date()}")
print("Selection rule: OOS-best among top-5 IS when OOS results exist; else best IS Sharpe.")
print("=" * 90)

for indicator_name, indicator_results in results_df.groupby("indicator", sort=False):
    selection_source = "is"
    selected_params = None
    param_display = None
    is_sharpe_ref = np.nan
    oos_sharpe_ref = np.nan

    oos_df_ind = None
    if "oos_df_by_indicator" in globals():
        oos_df_ind = oos_df_by_indicator.get(indicator_name)

    if oos_df_ind is not None and not oos_df_ind.empty:
        best_oos = best_oos_row(oos_df_ind)
        if best_oos is None:
            print(f"\n{indicator_name}: no valid OOS Sharpe among top-5 IS candidates; falling back to best IS.")
        else:
            selected_params = require_params_dict(best_oos["Params"], indicator_name)
            param_display = best_oos["Strategy"]
            is_sharpe_ref = float(best_oos["IS_Sharpe"])
            oos_sharpe_ref = float(best_oos["OOS_Sharpe"])
            selection_source = "oos"
            maybe_print_tied_is_sharpe_note(
                indicator_name,
                indicator_results,
                [param_display],
                "full-sample selection",
            )

    if selected_params is None:
        best = best_is_row(indicator_results)
        if best is None:
            print(f"\n{indicator_name}: no valid in-sample results. Skipping.")
            continue
        selected_params = require_params_dict(best["params"], indicator_name)
        param_display = best["param_display"]
        is_sharpe_ref = float(best["sharpe_ratio"])
        selection_source = "is"

    try:
        best_spec = get_active_indicator_spec(indicator_name)
    except KeyError as exc:
        print(f"\n{indicator_name}: skipping full-sample ({exc})")
        continue

    try:
        entries_series, exits_series = best_spec["build_signals"](
            full_close, selected_params, shift_signals=True
        )
        pf_full = run_signal_backtest(full_close, entries_series, exits_series)
    except Exception as exc:
        print(f"\n{indicator_name}: full-sample backtest failed ({type(exc).__name__}: {exc})")
        continue

    full_total_return = float(pf_full.total_return())
    full_annualized_return = float(pf_full.annualized_return(freq=FREQ, year_freq=YEAR_FREQ))
    full_sharpe = float(pf_full.sharpe_ratio(freq=FREQ, year_freq=YEAR_FREQ))
    full_sortino = float(pf_full.sortino_ratio(freq=FREQ, year_freq=YEAR_FREQ))
    full_max_dd = float(pf_full.max_drawdown())
    full_vol = float(pf_full.annualized_volatility(freq=FREQ, year_freq=YEAR_FREQ))

    tstats = trade_stats_from_portfolio(pf_full)
    full_total_trades = tstats["total_trades"]
    full_trades_per_year = full_total_trades / years if years > 0 else np.nan

    full_sample_results_by_indicator[indicator_name] = {
        "params": selected_params,
        "param_display": param_display,
        "selection_source": selection_source,
        "is_sharpe": is_sharpe_ref,
        "oos_sharpe": oos_sharpe_ref,
        "total_return": full_total_return,
        "annualized_return": full_annualized_return,
        "sharpe": full_sharpe,
        "sortino": full_sortino,
        "max_drawdown": full_max_dd,
        "volatility": full_vol,
        "total_trades": full_total_trades,
        "trades_per_year": full_trades_per_year,
        "win_rate": tstats["win_rate_pct"],
        "profit_factor": tstats["profit_factor"],
        "expectancy": tstats["expectancy"],
        "avg_win_amount": tstats["avg_win"],
        "avg_loss_amount": tstats["avg_loss"],
        "portfolio": pf_full,
    }

    print("\n" + "=" * 90)
    print(f"FULL-SAMPLE: {indicator_name} {param_display}")
    print("=" * 90)
    print(f"Selection source: {selection_source}")
    print(f"In-Sample Sharpe (reference): {fmt_metric(is_sharpe_ref, '.3f')}")
    if selection_source == "oos":
        print(f"OOS Sharpe (selection): {fmt_metric(oos_sharpe_ref, '.3f')}")
    print("RETURN METRICS:")
    print(f"{'Total Return':<25} {fmt_metric(full_total_return, '.2%'):>10}")
    print(f"{'Annualized Return':<25} {fmt_metric(full_annualized_return, '.2%'):>10}")
    print("RISK-ADJUSTED:")
    print(f"{'Sharpe Ratio':<25} {fmt_metric(full_sharpe, '.3f'):>10}")
    print(f"{'Sortino Ratio':<25} {fmt_metric(full_sortino, '.3f'):>10}")
    print("RISK:")
    print(f"{'Max Drawdown':<25} {fmt_metric(full_max_dd, '.2%'):>10}")
    print(f"{'Volatility':<25} {fmt_metric(full_vol, '.2%'):>10}")
    print("TRADES:")
    print(f"{'Total Trades':<25} {full_total_trades:>10.0f}")
    print(f"{'Trades per Year':<25} {fmt_metric(full_trades_per_year, '.1f'):>10}")
    print(f"{'Win Rate %':<25} {fmt_metric(tstats['win_rate_pct'], '.1f'):>10}")
    print(f"{'Profit Factor':<25} {fmt_metric(tstats['profit_factor'], '.2f'):>10}")
    print(f"{'Expectancy':<25} {fmt_metric(tstats['expectancy'], '.4f'):>10}")
    print(f"{'Avg Win Amount':<25} {fmt_metric(tstats['avg_win'], '.4f'):>10}")
    print(f"{'Avg Loss Amount':<25} {fmt_metric(tstats['avg_loss'], '.4f'):>10}")
    print("BENCHMARK (BUY & HOLD):")
    print(f"{'Total Return':<25} {fmt_metric(bh_total_return, '.2%'):>10}")
    print(f"{'Annualized Return':<25} {fmt_metric(bh_annualized, '.2%'):>10}")

print("\n" + "=" * 90)
print("Full-sample evaluation complete for each indicator separately.")
print("=" * 90)

==========================================================================================
FULL-SAMPLE EVALUATION BY INDICATOR
==========================================================================================
Period: 2018-01-02 -> 2026-08-17
Selection rule: OOS-best among top-5 IS when OOS results exist; else best IS Sharpe.
==========================================================================================

==========================================================================================
FULL-SAMPLE: Triple EMA EMA(4,117,125)
==========================================================================================
Selection source: oos
In-Sample Sharpe (reference): 0.928
OOS Sharpe (selection): 0.653
RETURN METRICS:
Total Return                1156.09%
Annualized Return             34.22%
RISK-ADJUSTED:
Sharpe Ratio                   0.895
Sortino Ratio                  1.254
RISK:
Max Drawdown                 -44.64%
Volatility                    43.63%
TRADES:
Total Trades                      26
Trades per Year                  3.0
Win Rate %                      57.7
Profit Factor                   6.27
Expectancy                       n/a
Avg Win Amount                0.2584
Avg Loss Amount               0.0618
BENCHMARK (BUY & HOLD):
Total Return                     n/a
Annualized Return                n/a

==========================================================================================
FULL-SAMPLE: MACD MACD(12,69,78)
==========================================================================================
Selection source: oos
In-Sample Sharpe (reference): 0.724
OOS Sharpe (selection): 1.203
RETURN METRICS:
Total Return                1838.84%
Annualized Return             41.17%
RISK-ADJUSTED:
Sharpe Ratio                   1.045
Sortino Ratio                  1.507
RISK:
Max Drawdown                 -48.49%
Volatility                    41.20%
TRADES:
Total Trades                      21
Trades per Year                  2.4
Win Rate %                      52.4
Profit Factor                   6.85
Expectancy                    0.2022
Avg Win Amount                0.4520
Avg Loss Amount               0.0726
BENCHMARK (BUY & HOLD):
Total Return                     n/a
Annualized Return                n/a

==========================================================================================
FULL-SAMPLE: AROON AROON(21)
==========================================================================================
Selection source: oos
In-Sample Sharpe (reference): 0.722
OOS Sharpe (selection): 0.986
RETURN METRICS:
Total Return                 855.62%
Annualized Return             30.02%
RISK-ADJUSTED:
Sharpe Ratio                   0.856
Sortino Ratio                  1.211
RISK:
Max Drawdown                 -52.13%
Volatility                    40.20%
TRADES:
Total Trades                      41
Trades per Year                  4.8
Win Rate %                      51.2
Profit Factor                   2.94
Expectancy                       n/a
Avg Win Amount                0.2301
Avg Loss Amount               0.0864
BENCHMARK (BUY & HOLD):
Total Return                     n/a
Annualized Return                n/a

==========================================================================================
FULL-SAMPLE: STC STC(38,99,23)
==========================================================================================
Selection source: oos
In-Sample Sharpe (reference): 0.964
OOS Sharpe (selection): 1.293
RETURN METRICS:
Total Return                4012.68%
Annualized Return             54.07%
RISK-ADJUSTED:
Sharpe Ratio                   1.255
Sortino Ratio                  1.864
RISK:
Max Drawdown                 -41.62%
Volatility                    41.28%
TRADES:
Total Trades                      27
Trades per Year                  3.1
Win Rate %                      59.3
Profit Factor                   6.07
Expectancy                    0.1816
Avg Win Amount                0.3669
Avg Loss Amount               0.0879
BENCHMARK (BUY & HOLD):
Total Return                     n/a
Annualized Return                n/a

==========================================================================================
FULL-SAMPLE: KAMA KAMA(10,7,99)
==========================================================================================
Selection source: oos
In-Sample Sharpe (reference): 0.807
OOS Sharpe (selection): 0.964
RETURN METRICS:
Total Return                1017.14%
Annualized Return             32.40%
RISK-ADJUSTED:
Sharpe Ratio                   0.862
Sortino Ratio                  1.203
RISK:
Max Drawdown                 -41.34%
Volatility                    43.88%
TRADES:
Total Trades                      49
Trades per Year                  5.7
Win Rate %                      40.8
Profit Factor                   3.82
Expectancy                       n/a
Avg Win Amount                0.2156
Avg Loss Amount               0.0404
BENCHMARK (BUY & HOLD):
Total Return                     n/a
Annualized Return                n/a

==========================================================================================
FULL-SAMPLE: SUPERTREND SUPERTREND(ATR=89,Factor=3)
==========================================================================================
Selection source: oos
In-Sample Sharpe (reference): 0.808
OOS Sharpe (selection): 1.064
RETURN METRICS:
Total Return                2227.68%
Annualized Return             44.20%
RISK-ADJUSTED:
Sharpe Ratio                   1.083
Sortino Ratio                  1.560
RISK:
Max Drawdown                 -51.22%
Volatility                    42.05%
TRADES:
Total Trades                      36
Trades per Year                  4.2
Win Rate %                      44.4
Profit Factor                   3.52
Expectancy                       n/a
Avg Win Amount                0.3922
Avg Loss Amount               0.0938
BENCHMARK (BUY & HOLD):
Total Return                     n/a
Annualized Return                n/a

==========================================================================================
FULL-SAMPLE: KALMAN KALMAN(Q=1,R=159)
==========================================================================================
Selection source: oos
In-Sample Sharpe (reference): 0.851
OOS Sharpe (selection): 1.315
RETURN METRICS:
Total Return                1578.21%
Annualized Return             38.82%
RISK-ADJUSTED:
Sharpe Ratio                   1.007
Sortino Ratio                  1.445
RISK:
Max Drawdown                 -47.60%
Volatility                    40.99%
TRADES:
Total Trades                     107
Trades per Year                 12.4
Win Rate %                      48.6
Profit Factor                   2.42
Expectancy                       n/a
Avg Win Amount                0.1230
Avg Loss Amount               0.0489
BENCHMARK (BUY & HOLD):
Total Return                     n/a
Annualized Return                n/a

==========================================================================================
FULL-SAMPLE: RSI RSI(73)
==========================================================================================
Selection source: oos
In-Sample Sharpe (reference): 0.779
OOS Sharpe (selection): 0.855
RETURN METRICS:
Total Return                1146.42%
Annualized Return             34.10%
RISK-ADJUSTED:
Sharpe Ratio                   0.884
Sortino Ratio                  1.233
RISK:
Max Drawdown                 -42.05%
Volatility                    44.54%
TRADES:
Total Trades                      44
Trades per Year                  5.1
Win Rate %                      52.3
Profit Factor                   5.01
Expectancy                       n/a
Avg Win Amount                0.1729
Avg Loss Amount               0.0397
BENCHMARK (BUY & HOLD):
Total Return                     n/a
Annualized Return                n/a

==========================================================================================
FULL-SAMPLE: ADX ADX(DI=21,Smooth=31)
==========================================================================================
Selection source: oos
In-Sample Sharpe (reference): 1.170
OOS Sharpe (selection): 0.971
RETURN METRICS:
Total Return                3236.14%
Annualized Return             50.36%
RISK-ADJUSTED:
Sharpe Ratio                   1.235
Sortino Ratio                  1.807
RISK:
Max Drawdown                 -40.89%
Volatility                    39.35%
TRADES:
Total Trades                      21
Trades per Year                  2.4
Win Rate %                      71.4
Profit Factor                  21.98
Expectancy                       n/a
Avg Win Amount                0.3337
Avg Loss Amount               0.0456
BENCHMARK (BUY & HOLD):
Total Return                     n/a
Annualized Return                n/a

==========================================================================================
FULL-SAMPLE: DONCHIAN DONCHIAN(24)
==========================================================================================
Selection source: oos
In-Sample Sharpe (reference): 0.488
OOS Sharpe (selection): 1.002
RETURN METRICS:
Total Return                 287.08%
Annualized Return             17.05%
RISK-ADJUSTED:
Sharpe Ratio                   0.635
Sortino Ratio                  0.884
RISK:
Max Drawdown                 -40.42%
Volatility                    33.94%
TRADES:
Total Trades                      36
Trades per Year                  4.2
Win Rate %                      50.0
Profit Factor                   2.22
Expectancy                    0.0556
Avg Win Amount                0.2025
Avg Loss Amount               0.0913
BENCHMARK (BUY & HOLD):
Total Return                     n/a
Annualized Return                n/a

==========================================================================================
FULL-SAMPLE: TRIX TRIX(7)
==========================================================================================
Selection source: oos
In-Sample Sharpe (reference): 0.711
OOS Sharpe (selection): 1.169
RETURN METRICS:
Total Return                1033.72%
Annualized Return             32.63%
RISK-ADJUSTED:
Sharpe Ratio                   0.884
Sortino Ratio                  1.249
RISK:
Max Drawdown                 -55.81%
Volatility                    42.01%
TRADES:
Total Trades                      47
Trades per Year                  5.5
Win Rate %                      46.8
Profit Factor                   2.59
Expectancy                       n/a
Avg Win Amount                0.2764
Avg Loss Amount               0.0978
BENCHMARK (BUY & HOLD):
Total Return                     n/a
Annualized Return                n/a

==========================================================================================
FULL-SAMPLE: VORTEX VORTEX(115)
==========================================================================================
Selection source: oos
In-Sample Sharpe (reference): 0.586
OOS Sharpe (selection): 0.593
RETURN METRICS:
Total Return                 635.79%
Annualized Return             26.12%
RISK-ADJUSTED:
Sharpe Ratio                   0.729
Sortino Ratio                  1.010
RISK:
Max Drawdown                 -62.09%
Volatility                    47.75%
TRADES:
Total Trades                      24
Trades per Year                  2.8
Win Rate %                      58.3
Profit Factor                   5.16
Expectancy                       n/a
Avg Win Amount                0.2095
Avg Loss Amount               0.0631
BENCHMARK (BUY & HOLD):
Total Return                     n/a
Annualized Return                n/a

==========================================================================================
FULL-SAMPLE: ALMA ALMA(2,99,0.10,3)
==========================================================================================
Selection source: oos
In-Sample Sharpe (reference): 0.786
OOS Sharpe (selection): 0.665
RETURN METRICS:
Total Return                1034.30%
Annualized Return             32.63%
RISK-ADJUSTED:
Sharpe Ratio                   0.856
Sortino Ratio                  1.198
RISK:
Max Drawdown                 -48.14%
Volatility                    44.98%
TRADES:
Total Trades                      23
Trades per Year                  2.7
Win Rate %                      65.2
Profit Factor                   7.89
Expectancy                       n/a
Avg Win Amount                0.2149
Avg Loss Amount               0.0584
BENCHMARK (BUY & HOLD):
Total Return                     n/a
Annualized Return                n/a

==========================================================================================
Full-sample evaluation complete for each indicator separately.
==========================================================================================

In [14]:
# SAVE TOP IS / OOS / FULL-SAMPLE RESULTS BY INDICATOR

import os
import re


def _to_builtin(value):
    """Convert numpy scalars / nested containers to plain Python builtins."""
    if isinstance(value, dict):
        return {str(key): _to_builtin(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_to_builtin(item) for item in value]
    if isinstance(value, np.generic):
        return value.item()
    return value


def _stringify_mapping_cell(value):
    """Serialize dict-like param cells for json/parquet export (literal_eval-safe)."""
    if isinstance(value, dict):
        return str(_to_builtin(value))
    return value


def _require_positive_int(name, value):
    try:
        number = int(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{name} must be an integer >= 1; got {value!r}") from exc
    if number < 1:
        raise ValueError(f"{name} must be an integer >= 1; got {value!r}")
    return number


def _write_results_dataframe(export_df, filepath):
    """Write a results DataFrame to parquet or json based on filepath suffix."""
    if filepath is None or not str(filepath).strip():
        raise ValueError("filepath must be a non-empty path ending in .json or .parquet")

    path = str(filepath).strip()
    suffix = path.lower().rsplit(".", 1)[-1] if "." in path else ""
    if suffix not in {"parquet", "json"}:
        raise ValueError(f"Unsupported file format (use .parquet or .json): {filepath!r}")

    parent = os.path.dirname(path)
    if parent and not os.path.isdir(parent):
        raise FileNotFoundError(
            f"Parent directory does not exist for filepath={path!r}: {parent}"
        )

    try:
        if suffix == "parquet":
            export_df.to_parquet(path, index=False)
        else:
            # Ensure strict JSON: map +/-inf to null via NaN (version-safe).
            json_df = export_df.replace([np.inf, -np.inf], np.nan)
            json_df.to_json(path, orient="records", indent=2)
    except ImportError as exc:
        hint = "pip install pyarrow" if suffix == "parquet" else "pip install pandas"
        raise ImportError(
            f"Writing {suffix!r} requires a dependency that is not installed "
            f"({hint}). Original error: {exc}"
        ) from exc
    except ValueError as exc:
        raise ValueError(f"Failed to serialize results to {path!r}: {exc}") from exc
    except PermissionError as exc:
        raise PermissionError(
            f"Permission denied writing {path!r}. Close the file if it is open elsewhere "
            f"(e.g. Excel) and retry. Original error: {exc}"
        ) from exc
    except OSError as exc:
        raise OSError(f"Failed to write results to {path!r}: {exc}") from exc
    return path


def _collect_top_in_sample_by_indicator(results, top_n=5):
    """Top-N in-sample rows per indicator with normalized identity columns."""
    if not isinstance(results, pd.DataFrame):
        raise TypeError(f"results must be a pandas DataFrame; got {type(results).__name__}")
    if "displayed_is_top_n" not in globals():
        raise NameError("displayed_is_top_n is missing. Run the indicator-grid helper cell first.")

    top_n = _require_positive_int("top_n", top_n)
    required_columns = {
        "indicator",
        "params",
        "param_display",
        "sharpe_ratio",
        "total_return",
        "annualized_return",
        "max_drawdown",
        "win_rate",
        "profit_factor",
        "total_trades",
        "trades_per_year",
    }
    missing_columns = sorted(required_columns - set(results.columns))
    if missing_columns:
        raise KeyError(f"Missing required result columns: {missing_columns}")

    if results.empty:
        return None

    top_frames = []
    for indicator_name, indicator_results in results.groupby("indicator", sort=False):
        ranked = displayed_is_top_n(indicator_results, top_n)
        if ranked.empty:
            continue
        ranked = ranked.copy()
        ranked["rank"] = range(1, len(ranked) + 1)
        ranked["indicator"] = indicator_name
        ranked["params"] = ranked["params"].map(_stringify_mapping_cell)
        top_frames.append(ranked)

    if not top_frames:
        raise ValueError(
            "No in-sample rows to export: every indicator lacked a finite sharpe_ratio "
            "for displayed_is_top_n. Re-run the grid search cell."
        )

    return pd.concat(top_frames, ignore_index=True)


def _collect_top_oos_by_indicator(oos_df_by_indicator):
    """Top OOS rows per indicator with normalized identity columns."""
    if oos_df_by_indicator is None:
        return None
    if not isinstance(oos_df_by_indicator, dict):
        raise TypeError(
            "oos_df_by_indicator must be a dict of DataFrames; "
            f"got {type(oos_df_by_indicator).__name__}"
        )
    if not oos_df_by_indicator:
        return None

    required_after_rename = {"param_display", "params", "OOS_Sharpe"}
    frames = []
    for indicator_name, oos_df in oos_df_by_indicator.items():
        if oos_df is None:
            continue
        if not isinstance(oos_df, pd.DataFrame):
            raise TypeError(
                f"oos_df_by_indicator[{indicator_name!r}] must be a DataFrame; "
                f"got {type(oos_df).__name__}"
            )
        if oos_df.empty:
            continue

        frame = oos_df.copy()
        rename_map = {
            "Indicator": "indicator",
            "Strategy": "param_display",
            "Params": "params",
            "IS_Rank": "rank",
        }
        frame = frame.rename(columns={k: v for k, v in rename_map.items() if k in frame.columns})
        missing = sorted(required_after_rename - set(frame.columns))
        if missing:
            raise KeyError(
                f"oos_df_by_indicator[{indicator_name!r}] missing required columns "
                f"after normalize: {missing}"
            )
        frame["indicator"] = indicator_name
        frame["params"] = frame["params"].map(_stringify_mapping_cell)
        frames.append(frame)

    if not frames:
        return None
    return pd.concat(frames, ignore_index=True)


def _collect_full_sample_by_indicator(full_sample_results_by_indicator):
    """Full-sample rows per indicator with normalized identity columns."""
    if full_sample_results_by_indicator is None:
        return None
    if not isinstance(full_sample_results_by_indicator, dict):
        raise TypeError(
            "full_sample_results_by_indicator must be a dict; "
            f"got {type(full_sample_results_by_indicator).__name__}"
        )
    if not full_sample_results_by_indicator:
        return None

    required_keys = {"params", "param_display", "sharpe"}
    rows = []
    for indicator_name, info in full_sample_results_by_indicator.items():
        if not isinstance(info, dict):
            raise TypeError(
                f"full_sample_results_by_indicator[{indicator_name!r}] must be a dict; "
                f"got {type(info).__name__}"
            )
        missing_keys = sorted(required_keys - set(info))
        if missing_keys:
            raise KeyError(
                f"full_sample_results_by_indicator[{indicator_name!r}] "
                f"missing required keys: {missing_keys}"
            )
        row = {"indicator": indicator_name}
        for key, value in info.items():
            if key == "portfolio":
                continue
            row[key] = _stringify_mapping_cell(value)
        rows.append(row)

    if not rows:
        return None
    return pd.DataFrame(rows)


def save_notebook_results_by_indicator(
    results,
    oos_df_by_indicator,
    full_sample_results_by_indicator,
    filepath,
    top_n=5,
    require_all_stages=True,
):
    """Save top IS, top OOS, and full-sample results per indicator in one file.

    Rows are stacked with a leading `stage` column: 'is', 'oos', or 'full'.
    Identity columns are normalized to: indicator, rank, param_display, params.
    """
    top_n = _require_positive_int("top_n", top_n)
    stage_frames = {}

    is_df = _collect_top_in_sample_by_indicator(results, top_n=top_n)
    if is_df is not None and not is_df.empty:
        stage_frames["is"] = is_df.assign(stage="is")

    oos_df = _collect_top_oos_by_indicator(oos_df_by_indicator)
    if oos_df is not None and not oos_df.empty:
        stage_frames["oos"] = oos_df.assign(stage="oos")

    full_df = _collect_full_sample_by_indicator(full_sample_results_by_indicator)
    if full_df is not None and not full_df.empty:
        stage_frames["full"] = full_df.assign(stage="full")

    missing_stages = [name for name in ("is", "oos", "full") if name not in stage_frames]
    if missing_stages:
        message = f"Missing result stages for export: {missing_stages}"
        if require_all_stages or not stage_frames:
            raise ValueError(message)
        print(f"Warning: {message}")

    if not stage_frames:
        print("No notebook results to save.")
        return None

    # Put stage first, then shared identity columns when present.
    frames = []
    for stage_name in ("is", "oos", "full"):
        if stage_name not in stage_frames:
            continue
        frame = stage_frames[stage_name]
        leading = [
            col for col in ("stage", "indicator", "rank", "param_display", "params")
            if col in frame.columns
        ]
        ordered = leading + [col for col in frame.columns if col not in leading]
        frames.append(frame.loc[:, ordered])

    export_df = pd.concat(frames, ignore_index=True, sort=False)
    path = _write_results_dataframe(export_df, filepath)
    stage_counts = export_df["stage"].value_counts().to_dict()
    print(
        f"Saved notebook results by indicator to {path} "
        f"({len(export_df)} rows; stages={stage_counts})"
    )
    return export_df


_WINDOWS_RESERVED_NAMES = {
    "con", "prn", "aux", "nul",
    "com1", "com2", "com3", "com4", "com5", "com6", "com7", "com8", "com9",
    "lpt1", "lpt2", "lpt3", "lpt4", "lpt5", "lpt6", "lpt7", "lpt8", "lpt9",
}


def _ticker_results_slug(ticker):
    """Normalize TICKER into a safe filesystem slug for results filenames."""
    if ticker is None:
        raise ValueError("TICKER is missing or empty. Run the download cell first.")
    if not isinstance(ticker, str):
        ticker = str(ticker)
    text = ticker.strip()
    if not text:
        raise ValueError("TICKER is missing or empty. Run the download cell first.")

    slug = re.sub(r"[^a-z0-9]+", "_", text.lower())
    slug = re.sub(r"_+", "_", slug).strip("_")
    if not slug:
        raise ValueError(f"Could not build results filename from TICKER={ticker!r}")
    if slug in _WINDOWS_RESERVED_NAMES:
        slug = f"asset_{slug}"
    return slug


def _indicator_sweep_results_dir():
    """Return Indicator_sweep_results, creating it if it does not exist yet."""
    search = os.path.abspath(os.getcwd())
    for _ in range(6):
        candidate = os.path.join(search, "Indicator_sweep_results")
        if os.path.isdir(candidate):
            return candidate
        parent = os.path.dirname(search)
        if parent == search:
            break
        search = parent

    cwd = os.path.abspath(os.getcwd())
    if os.path.basename(cwd).lower() == "indicator_sweeps":
        results_dir = os.path.join(os.path.dirname(cwd), "Indicator_sweep_results")
    else:
        results_dir = os.path.join(cwd, "Indicator_sweep_results")
    try:
        os.makedirs(results_dir, exist_ok=True)
    except OSError as exc:
        raise OSError(
            f"Could not create results directory {results_dir!r}: {exc}"
        ) from exc
    return results_dir


def _results_filepath_for_ticker(ticker, file_format="json"):
    """Build the results path for the asset under test.

    Examples:
      BTC-USD -> Indicator_sweep_results/btc_usd_indicator_sweep_results.json
      QQQ     -> Indicator_sweep_results/qqq_indicator_sweep_results.json

    The results file itself is created/overwritten when results are written.
    """
    if not isinstance(file_format, str) or not file_format.strip():
        raise ValueError(f"file_format must be 'json' or 'parquet'; got {file_format!r}")
    fmt = file_format.strip().lower().lstrip(".")
    if fmt not in {"json", "parquet"}:
        raise ValueError(f"file_format must be 'json' or 'parquet'; got {file_format!r}")

    slug = _ticker_results_slug(ticker)
    filename = f"{slug}_indicator_sweep_results.{fmt}"
    if os.path.isabs(filename) or os.path.dirname(filename) not in ("", "."):
        raise ValueError(
            f"Refusing results filename outside the results directory: {filename!r}"
        )

    results_dir = os.path.abspath(_indicator_sweep_results_dir())
    filepath = os.path.abspath(os.path.join(results_dir, filename))
    if os.path.dirname(filepath) != results_dir:
        raise ValueError(
            f"Refusing results filepath outside Indicator_sweep_results: {filepath!r}"
        )

    if os.path.isfile(filepath):
        print(f"Using existing results file for {ticker}: {filepath}")
    elif os.path.exists(filepath):
        raise ValueError(f"Results path exists but is not a file: {filepath!r}")
    else:
        print(f"Will create results file for {ticker}: {filepath}")
    return filepath



if "results_df" not in globals() or not isinstance(results_df, pd.DataFrame):
    raise ValueError("results_df is missing or not a DataFrame. Run the grid-search analysis cell first.")
if results_df.empty:
    raise ValueError("results_df is empty. Run the grid search cell first.")
if "oos_df_by_indicator" not in globals() or not isinstance(oos_df_by_indicator, dict):
    raise ValueError("oos_df_by_indicator is missing or not a dict. Run the OOS validation cell first.")
if not oos_df_by_indicator:
    raise ValueError("oos_df_by_indicator is empty. Run the OOS validation cell first.")
if "full_sample_results_by_indicator" not in globals() or not isinstance(full_sample_results_by_indicator, dict):
    raise ValueError("full_sample_results_by_indicator is missing or not a dict. Run the full-sample cell first.")
if not full_sample_results_by_indicator:
    raise ValueError("full_sample_results_by_indicator is empty. Run the full-sample cell first.")

if "TICKER" not in globals() or not str(TICKER).strip():
    raise ValueError("TICKER is missing. Run the download cell first.")

results_filepath = _results_filepath_for_ticker(TICKER)

saved_notebook_results = save_notebook_results_by_indicator(
    results_df,
    oos_df_by_indicator,
    full_sample_results_by_indicator,
    filepath=results_filepath,
    top_n=5,
    require_all_stages=True,
)

Using existing results file for TQQQ: tqqq_indicator_sweep_results.json

Saved notebook results by indicator to tqqq_indicator_sweep_results.json (143 rows; stages={'is': 65, 'oos': 65, 'full': 13})

In [15]:
# STORE BEST STRATEGY PER INDICATOR FOR VISUALIZATIONS

best_by_indicator = {}

# Union of indicators seen in IS results and/or OOS tables.
indicator_names = []
if "results_df" in globals() and not results_df.empty:
    indicator_names = list(results_df.groupby("indicator", sort=False).groups.keys())
if "oos_df_by_indicator" in globals() and oos_df_by_indicator:
    for name in oos_df_by_indicator.keys():
        if name not in indicator_names:
            indicator_names.append(name)

if not indicator_names:
    print("No OOS or in-sample results available to store.")
else:
    for indicator_name in indicator_names:
        stored = None

        oos_df_ind = None
        if "oos_df_by_indicator" in globals() and oos_df_by_indicator:
            oos_df_ind = oos_df_by_indicator.get(indicator_name)

        if oos_df_ind is not None and not oos_df_ind.empty:
            best_oos = best_oos_row(oos_df_ind)
            if best_oos is not None:
                try:
                    params = require_params_dict(best_oos["Params"], indicator_name)
                    stored = {
                        "source": "oos",
                        "params": params,
                        "param_display": best_oos["Strategy"],
                        "is_sharpe": safe_float(best_oos.get("IS_Sharpe")),
                        "oos_sharpe": safe_float(best_oos.get("OOS_Sharpe")),
                        "full_sample_sharpe": np.nan,
                    }
                except (TypeError, KeyError, ValueError) as exc:
                    print(f"Skipping OOS store for {indicator_name}: {exc}")

        if stored is None and "results_df" in globals() and not results_df.empty:
            indicator_results = results_df[results_df["indicator"] == indicator_name]
            best_is = best_is_row(indicator_results)
            if best_is is not None:
                try:
                    params = require_params_dict(best_is["params"], indicator_name)
                    stored = {
                        "source": "is",
                        "params": params,
                        "param_display": best_is["param_display"],
                        "is_sharpe": safe_float(best_is.get("sharpe_ratio")),
                        "oos_sharpe": np.nan,
                        "full_sample_sharpe": np.nan,
                    }
                except (TypeError, KeyError, ValueError) as exc:
                    print(f"Skipping IS store for {indicator_name}: {exc}")

        if stored is None:
            print(f"No storable strategy found for {indicator_name}.")
            continue

        fs_result = None
        if "full_sample_results_by_indicator" in globals() and full_sample_results_by_indicator:
            fs_result = full_sample_results_by_indicator.get(indicator_name)
        if fs_result is not None:
            stored["full_sample_sharpe"] = safe_float(fs_result.get("sharpe"))

        best_by_indicator[indicator_name] = stored

print("Best strategy stored per indicator:")
for indicator_name, info in best_by_indicator.items():
    print(
        f"  {indicator_name}: {info['param_display']} "
        f"(source={info['source']}, IS Sharpe={fmt_metric(info['is_sharpe'], '.3f')})"
    )

# Cross-indicator ranking (best stored strategy per indicator, ranked by OOS Sharpe).
indicator_ranking_rows = []
for indicator_name, info in best_by_indicator.items():
    indicator_ranking_rows.append({
        "Indicator": indicator_name,
        "Strategy": info["param_display"],
        "Source": info["source"],
        "IS Sharpe": info["is_sharpe"],
        "OOS Sharpe": info["oos_sharpe"],
        "Full Sample Sharpe": info.get("full_sample_sharpe", np.nan),
    })

indicator_ranking_df = pd.DataFrame(indicator_ranking_rows)

if indicator_ranking_df.empty:
    print("\nNo indicators available for cross-indicator ranking.")
else:
    has_finite_oos = indicator_ranking_df["OOS Sharpe"].apply(
        lambda x: isinstance(x, (int, float)) and np.isfinite(x)
    ).any()

    indicator_ranking_df = (
        indicator_ranking_df
        .sort_values(["OOS Sharpe", "IS Sharpe"], ascending=[False, False], na_position="last")
        .reset_index(drop=True)
    )
    indicator_ranking_df.insert(0, "Rank", range(1, len(indicator_ranking_df) + 1))

    print("\n" + "=" * 90)
    print("INDICATOR RANKING (BEST STORED STRATEGY PER INDICATOR)")
    print("=" * 90)
    print("Ranking basis: OOS Sharpe (higher is better).")
    print("Each row uses that indicator's best stored strategy (OOS-best when available, else IS-best).")
    if not has_finite_oos:
        print("Warning: no finite OOS Sharpe values; table order is informational only.")
    if "full_sample_results_by_indicator" not in globals() or not full_sample_results_by_indicator:
        print("Warning: full-sample results missing; Full Sample Sharpe will show as n/a.")
    print("=" * 90)

    ranking_display_df = indicator_ranking_df.assign(
        **{
            "IS Sharpe": indicator_ranking_df["IS Sharpe"].map(lambda x: fmt_metric(x, ".3f")),
            "OOS Sharpe": indicator_ranking_df["OOS Sharpe"].map(lambda x: fmt_metric(x, ".3f")),
            "Full Sample Sharpe": indicator_ranking_df["Full Sample Sharpe"].map(lambda x: fmt_metric(x, ".3f")),
        }
    )[["Rank", "Indicator", "Strategy", "IS Sharpe", "OOS Sharpe", "Full Sample Sharpe"]]
    print(ranking_display_df.to_string(index=False))

    if has_finite_oos:
        best_ranked = indicator_ranking_df.iloc[0]
        print("\n" + "-" * 90)
        print(f"TOP RANKED INDICATOR: {best_ranked['Indicator']} ({best_ranked['Strategy']})")
        print(f"OOS Sharpe: {fmt_metric(best_ranked['OOS Sharpe'], '.3f')}")
        print(f"IS Sharpe: {fmt_metric(best_ranked['IS Sharpe'], '.3f')}")
        print(f"Full Sample Sharpe: {fmt_metric(best_ranked['Full Sample Sharpe'], '.3f')}")
    else:
        print("\nNo top-ranked indicator declared because OOS Sharpe is unavailable for all rows.")

# Compatibility for Triple-EMA-specific downstream cells.
if "Triple EMA" in best_by_indicator:
    BEST_INDICATOR = "Triple EMA"
    BEST_STRATEGY_LABEL = best_by_indicator["Triple EMA"]["param_display"]
    BEST_PARAMS = best_by_indicator["Triple EMA"]["params"]
    BEST_IS_SHARPE = best_by_indicator["Triple EMA"]["is_sharpe"]
    BEST_OOS_SHARPE = best_by_indicator["Triple EMA"]["oos_sharpe"]
    missing = [k for k in ("ema1_period", "ema2_period", "ema3_period") if k not in BEST_PARAMS]
    if missing:
        print(f"Triple EMA best params missing keys {missing}; downstream EMA defaults not set.")
        for name in ("BEST_EMA1", "BEST_EMA2", "BEST_EMA3"):
            if name in globals():
                del globals()[name]
    else:
        BEST_EMA1 = int(BEST_PARAMS["ema1_period"])
        BEST_EMA2 = int(BEST_PARAMS["ema2_period"])
        BEST_EMA3 = int(BEST_PARAMS["ema3_period"])
        print(f"\nDownstream Triple EMA defaults set to: EMA({BEST_EMA1}, {BEST_EMA2}, {BEST_EMA3})")
elif "BEST_EMA1" in globals():
    del BEST_EMA1, BEST_EMA2, BEST_EMA3

Best strategy stored per indicator:
  Triple EMA: EMA(4,117,125) (source=oos, IS Sharpe=0.928)
  MACD: MACD(12,69,78) (source=oos, IS Sharpe=0.724)
  AROON: AROON(21) (source=oos, IS Sharpe=0.722)
  STC: STC(38,99,23) (source=oos, IS Sharpe=0.964)
  KAMA: KAMA(10,7,99) (source=oos, IS Sharpe=0.807)
  SUPERTREND: SUPERTREND(ATR=89,Factor=3) (source=oos, IS Sharpe=0.808)
  KALMAN: KALMAN(Q=1,R=159) (source=oos, IS Sharpe=0.851)
  RSI: RSI(73) (source=oos, IS Sharpe=0.779)
  ADX: ADX(DI=21,Smooth=31) (source=oos, IS Sharpe=1.170)
  DONCHIAN: DONCHIAN(24) (source=oos, IS Sharpe=0.488)
  TRIX: TRIX(7) (source=oos, IS Sharpe=0.711)
  VORTEX: VORTEX(115) (source=oos, IS Sharpe=0.586)
  ALMA: ALMA(2,99,0.10,3) (source=oos, IS Sharpe=0.786)

==========================================================================================
INDICATOR RANKING (BEST STORED STRATEGY PER INDICATOR)
==========================================================================================
Ranking basis: OOS Sharpe (higher is better).
Each row uses that indicator's best stored strategy (OOS-best when available, else IS-best).
==========================================================================================
 Rank  Indicator                    Strategy IS Sharpe OOS Sharpe Full Sample Sharpe
    1     KALMAN           KALMAN(Q=1,R=159)     0.851      1.315              1.007
    2        STC               STC(38,99,23)     0.964      1.293              1.255
    3       MACD              MACD(12,69,78)     0.724      1.203              1.045
    4       TRIX                     TRIX(7)     0.711      1.169              0.884
    5 SUPERTREND SUPERTREND(ATR=89,Factor=3)     0.808      1.064              1.083
    6   DONCHIAN                DONCHIAN(24)     0.488      1.002              0.635
    7      AROON                   AROON(21)     0.722      0.986              0.856
    8        ADX        ADX(DI=21,Smooth=31)     1.170      0.971              1.235
    9       KAMA               KAMA(10,7,99)     0.807      0.964              0.862
   10        RSI                     RSI(73)     0.779      0.855              0.884
   11       ALMA           ALMA(2,99,0.10,3)     0.786      0.665              0.856
   12 Triple EMA              EMA(4,117,125)     0.928      0.653              0.895
   13     VORTEX                 VORTEX(115)     0.586      0.593              0.729

------------------------------------------------------------------------------------------
TOP RANKED INDICATOR: KALMAN (KALMAN(Q=1,R=159))
OOS Sharpe: 1.315
IS Sharpe: 0.851
Full Sample Sharpe: 1.007

Downstream Triple EMA defaults set to: EMA(4, 117, 125)

In [16]:
# FULL-SAMPLE ROLLING SHARPE + DRAWDOWNS - for all strategies

# Prefer stored per-indicator best strategies (OOS-best when available, else best IS).
strategies_to_plot = []
if "best_by_indicator" in globals() and best_by_indicator:
    for indicator_name, info in best_by_indicator.items():
        try:
            params = require_params_dict(info["params"], indicator_name)
        except (TypeError, KeyError, ValueError) as exc:
            print(f"{indicator_name}: skipping (invalid stored params: {exc})")
            continue
        strategies_to_plot.append((indicator_name, params, info["param_display"]))
elif "results_df" in globals() and not results_df.empty:
    for indicator_name, indicator_results in results_df.groupby("indicator", sort=False):
        best = best_is_row(indicator_results)
        if best is None:
            continue
        try:
            params = require_params_dict(best["params"], indicator_name)
        except (TypeError, KeyError, ValueError) as exc:
            print(f"{indicator_name}: skipping (invalid IS params: {exc})")
            continue
        strategies_to_plot.append((indicator_name, params, best["param_display"]))

if not strategies_to_plot:
    print("No results to visualize.")
elif "close" not in globals() or close is None or len(close) < 2:
    print("Close series missing or too short for rolling Sharpe / drawdown plots.")
else:
    # Reuse full-sample portfolios when available to avoid re-running identical backtests.
    fs_by_indicator = (
        full_sample_results_by_indicator
        if "full_sample_results_by_indicator" in globals() and full_sample_results_by_indicator
        else {}
    )
    # Window depends only on series length / annualization constants, so compute once.
    rolling_window = max(20, min(TRADING_DAYS_PER_YEAR, max(1, len(close) // 4)))

    for best_indicator, best_params, param_display in strategies_to_plot:
        best_label = f"{best_indicator} {param_display}"
        try:
            fs_result = fs_by_indicator.get(best_indicator)
            if fs_result is not None and fs_result.get("portfolio") is not None:
                pf_full = fs_result["portfolio"]
            else:
                best_spec = get_active_indicator_spec(best_indicator)
                entries_series, exits_series = best_spec["build_signals"](
                    close, best_params, shift_signals=True
                )
                pf_full = run_signal_backtest(close, entries_series, exits_series)

            ret = pf_full.returns()

            # 1) Rolling Sharpe (dynamic annualization window)
            if len(ret) > rolling_window:
                rolling_sharpe = ret.rolling(window=rolling_window).apply(
                    lambda x: (x.mean() * TRADING_DAYS_PER_YEAR) / (x.std() * np.sqrt(TRADING_DAYS_PER_YEAR)) if x.std() and x.std() != 0 else np.nan,
                    raw=False
                )

                plt.figure(figsize=(12, 5))
                plt.plot(rolling_sharpe.index, rolling_sharpe.values, linewidth=2, color='blue', alpha=0.85)
                plt.axhline(y=1.0, color='green', linestyle='--', alpha=0.6, label='Sharpe = 1.0')
                plt.axhline(y=0.5, color='orange', linestyle='--', alpha=0.6, label='Sharpe = 0.5')
                plt.axhline(y=0.0, color='red', linestyle='--', alpha=0.6, label='Sharpe = 0.0')
                plt.title(f'Rolling Sharpe (window={rolling_window}) - {best_label} Full Sample', fontsize=14, fontweight='bold')
                plt.xlabel('Date', fontsize=12)
                plt.ylabel('Rolling Sharpe Ratio', fontsize=12)
                plt.grid(True, alpha=0.3)
                plt.legend()
                plt.tight_layout()
                plt.show()
            else:
                print(f"Not enough data for rolling Sharpe calculation: {best_label}")

            # 2) Drawdowns (underwater)
            eq = (1 + ret).cumprod()
            peak = eq.cummax()
            dd = (eq - peak) / peak.replace(0, np.nan)

            fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8), sharex=True)

            ax1.plot(eq.index, (eq - 1) * 100, color='black', linewidth=1.5, label='Cumulative Return %')
            ax1.plot(peak.index, (peak - 1) * 100, color='green', linewidth=1.0, alpha=0.7, label='Peak %')
            ax1.fill_between(eq.index, (eq - 1) * 100, (peak - 1) * 100, color='red', alpha=0.25, label='Drawdown Area')
            ax1.set_title(f'Cumulative Returns & Drawdowns - {best_label} Full Sample', fontsize=14, fontweight='bold')
            ax1.set_ylabel('Return (%)', fontsize=12)
            ax1.grid(True, alpha=0.3)
            ax1.legend()

            ax2.fill_between(dd.index, dd * 100, 0, color='red', alpha=0.7, label='Drawdown %')
            ax2.plot(dd.index, dd * 100, color='darkred', linewidth=1)
            ax2.set_title('Underwater Chart (Drawdown from Peak)', fontsize=13)
            ax2.set_xlabel('Date', fontsize=12)
            ax2.set_ylabel('Drawdown (%)', fontsize=12)
            ax2.grid(True, alpha=0.3)
            ax2.legend()

            plt.tight_layout()
            plt.show()

            print(f"Rolling Sharpe and Drawdown analysis complete for: {best_label}")
        except Exception as exc:
            print(f"{best_label}: rolling Sharpe / drawdown failed ({type(exc).__name__}: {exc})")

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\4057478222.py:72: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\4057478222.py:100: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Rolling Sharpe and Drawdown analysis complete for: Triple EMA EMA(4,117,125)

Rolling Sharpe and Drawdown analysis complete for: MACD MACD(12,69,78)

Rolling Sharpe and Drawdown analysis complete for: AROON AROON(21)

Rolling Sharpe and Drawdown analysis complete for: STC STC(38,99,23)

Rolling Sharpe and Drawdown analysis complete for: KAMA KAMA(10,7,99)

Rolling Sharpe and Drawdown analysis complete for: SUPERTREND SUPERTREND(ATR=89,Factor=3)

Rolling Sharpe and Drawdown analysis complete for: KALMAN KALMAN(Q=1,R=159)

Rolling Sharpe and Drawdown analysis complete for: RSI RSI(73)

Rolling Sharpe and Drawdown analysis complete for: ADX ADX(DI=21,Smooth=31)

Rolling Sharpe and Drawdown analysis complete for: DONCHIAN DONCHIAN(24)

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\4057478222.py:61: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure(figsize=(12, 5))

Rolling Sharpe and Drawdown analysis complete for: TRIX TRIX(7)

Rolling Sharpe and Drawdown analysis complete for: VORTEX VORTEX(115)

Rolling Sharpe and Drawdown analysis complete for: ALMA ALMA(2,99,0.10,3)

In [17]:
# STEP 5C: VISUALS ONLY (Signals + Equity Curves) - for all strategies

def _params_match(stored_params, current_params):
    return isinstance(stored_params, dict) and stored_params == current_params


# Prefer stored per-indicator best strategies (OOS-best when available, else best IS).
strategies_to_plot = []
if "best_by_indicator" in globals() and best_by_indicator:
    for indicator_name, info in best_by_indicator.items():
        if "active_indicator_grids" in globals() and indicator_name not in active_indicator_grids:
            print(f"{indicator_name}: skipping (not in active_indicator_grids)")
            continue
        try:
            params = require_params_dict(info["params"], indicator_name)
            param_display = info.get("param_display")
            if not param_display:
                param_display = get_active_indicator_spec(indicator_name)["format_params"](params)
        except (TypeError, KeyError, ValueError) as exc:
            print(f"{indicator_name}: skipping (invalid stored params: {exc})")
            continue
        strategies_to_plot.append((indicator_name, params, param_display))
elif "results_df" in globals() and not results_df.empty:
    if "best_is_row" not in globals():
        print("best_is_row is not defined; run the grid-search setup cells first.")
    else:
        for indicator_name, indicator_results in results_df.groupby("indicator", sort=False):
            if "active_indicator_grids" in globals() and indicator_name not in active_indicator_grids:
                print(f"{indicator_name}: skipping (not in active_indicator_grids)")
                continue
            best = best_is_row(indicator_results)
            if best is None:
                continue
            try:
                params = require_params_dict(best["params"], indicator_name)
                param_display = best.get("param_display") or get_active_indicator_spec(indicator_name)["format_params"](params)
            except (TypeError, KeyError, ValueError) as exc:
                print(f"{indicator_name}: skipping (invalid IS params: {exc})")
                continue
            strategies_to_plot.append((indicator_name, params, param_display))

required_series = ("close", "train_close", "val_close")
missing_series = [name for name in required_series if name not in globals() or globals()[name] is None]

if not strategies_to_plot:
    print("No results to visualize.")
elif missing_series:
    print(f"Missing required price series: {', '.join(missing_series)}")
elif "split_idx" not in globals():
    print("split_idx is not defined; cannot build train/val equity curves.")
elif len(close) < 2:
    print("Close series too short for visualizations.")
elif len(train_close) < 1 or len(val_close) < 1:
    print(f"Train/val segments are empty: train={len(train_close)}, val={len(val_close)}")
elif split_idx <= 0 or split_idx >= len(close):
    print(f"Invalid split_idx={split_idx} for close length {len(close)}.")
elif len(train_close) != split_idx or len(val_close) != len(close) - split_idx:
    print(
        f"Train/val lengths do not match split_idx: "
        f"train={len(train_close)}, val={len(val_close)}, split_idx={split_idx}, close={len(close)}"
    )
else:
    fs_by_indicator = (
        full_sample_results_by_indicator
        if "full_sample_results_by_indicator" in globals() and full_sample_results_by_indicator
        else {}
    )

    for indicator_name, params, param_display in strategies_to_plot:
        best_label = f"{indicator_name} {param_display}"
        try:
            spec = get_active_indicator_spec(indicator_name)
            entries_series, exits_series = spec["build_signals"](close, params, shift_signals=True)

            if len(entries_series) != len(close) or len(exits_series) != len(close):
                raise ValueError(
                    f"Signal length mismatch: entries={len(entries_series)}, "
                    f"exits={len(exits_series)}, close={len(close)}"
                )

            entries_full = entries_series.to_numpy(dtype=bool)
            exits_full = exits_series.to_numpy(dtype=bool)
            entries_train = entries_full[:split_idx]
            exits_train = exits_full[:split_idx]
            entries_val = entries_full[split_idx:]
            exits_val = exits_full[split_idx:]

            if len(entries_train) != len(train_close) or len(entries_val) != len(val_close):
                raise ValueError("Train/val signal slices do not align with train_close/val_close.")

            # Reuse cached full-sample portfolio when params match; always run train/val backtests.
            fs_result = fs_by_indicator.get(indicator_name)
            if (
                fs_result is not None
                and fs_result.get("portfolio") is not None
                and _params_match(fs_result.get("params"), params)
            ):
                pf_full = fs_result["portfolio"]
            else:
                pf_full = run_signal_backtest(close, entries_full, exits_full)

            pf_train = run_signal_backtest(train_close, entries_train, exits_train)
            pf_val = run_signal_backtest(val_close, entries_val, exits_val)

            # 1) Price + indicator overlay + signals (full sample)
            fig, ax = plt.subplots(figsize=(14, 7))
            ax.plot(close.index, close.values, label='Close', color='black', linewidth=1.5, alpha=0.7)

            if indicator_name == "Triple EMA":
                ema1 = int(params["ema1_period"])
                ema2 = int(params["ema2_period"])
                ema3 = int(params["ema3_period"])
                ema1_full = get_ema_series(close, ema1)
                ema2_full = get_ema_series(close, ema2)
                ema3_full = get_ema_series(close, ema3)
                ax.plot(close.index, ema1_full.values, label=f'Fast EMA ({ema1})', color='blue', alpha=0.8, linewidth=1.2)
                ax.plot(close.index, ema2_full.values, label=f'Medium EMA ({ema2})', color='orange', alpha=0.8, linewidth=1.2)
                ax.plot(close.index, ema3_full.values, label=f'Slow EMA ({ema3})', color='purple', alpha=0.8, linewidth=1.2)

            buy_idx = close.index[entries_full]
            sell_idx = close.index[exits_full]
            ax.scatter(buy_idx, close.reindex(buy_idx).values, marker='^', color='green', s=80, label='Buy', zorder=5)
            ax.scatter(sell_idx, close.reindex(sell_idx).values, marker='v', color='red', s=80, label='Sell', zorder=5)

            ax.set_title(f'Best {param_display} - Full Sample Signals', fontsize=14, fontweight='bold')
            ax.set_xlabel('Date', fontsize=12)
            ax.set_ylabel('Price', fontsize=12)
            ax.grid(True, alpha=0.3)
            ax.legend(loc='best')
            plt.tight_layout()
            plt.show()

            # 2) Equity curves: train / val / full
            eq_full = (1 + pf_full.returns()).cumprod()
            eq_train = (1 + pf_train.returns()).cumprod()
            eq_val = (1 + pf_val.returns()).cumprod()

            fig, ax = plt.subplots(figsize=(14, 7))
            ax.plot(close.index, eq_full.values, label='Full Sample', color='black', linewidth=2)
            ax.plot(train_close.index, eq_train.values, label='Train (In-Sample)', color='blue', linewidth=1.5, alpha=0.8)
            ax.plot(val_close.index, eq_val.values, label='Validation (Out-of-Sample)', color='orange', linewidth=1.5, alpha=0.8)
            ax.axvline(x=train_close.index[-1], color='red', linestyle='--', alpha=0.5, label='Train/Val Split')

            ax.set_title(f'Best {param_display} - Equity Curves', fontsize=14, fontweight='bold')
            ax.set_xlabel('Date', fontsize=12)
            ax.set_ylabel('Cumulative Returns (normalized to 1)', fontsize=12)
            ax.grid(True, alpha=0.3)
            ax.legend(loc='best')
            plt.tight_layout()
            plt.show()

            print(f"Visualizations complete for: {best_label}")
        except Exception as exc:
            print(f"{best_label}: visualization failed ({type(exc).__name__}: {exc})")

Visualizations complete for: Triple EMA EMA(4,117,125)

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:131: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:150: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:131: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:150: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:131: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Visualizations complete for: MACD MACD(12,69,78)

Visualizations complete for: AROON AROON(21)
Visualizations complete for: STC STC(38,99,23)

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:150: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:131: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:150: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:131: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:150: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Visualizations complete for: KAMA KAMA(10,7,99)

Visualizations complete for: SUPERTREND SUPERTREND(ATR=89,Factor=3)

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:131: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:150: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:131: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:150: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:131: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Visualizations complete for: KALMAN KALMAN(Q=1,R=159)
Visualizations complete for: RSI RSI(73)

Visualizations complete for: ADX ADX(DI=21,Smooth=31)

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:150: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:131: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:150: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:131: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:150: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Visualizations complete for: DONCHIAN DONCHIAN(24)
Visualizations complete for: TRIX TRIX(7)

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:131: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:150: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:131: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:150: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:131: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Visualizations complete for: VORTEX VORTEX(115)
Visualizations complete for: ALMA ALMA(2,99,0.10,3)

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\2331449690.py:150: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [18]:
# FULL-SAMPLE TRADE-BY-TRADE RETURNS (BAR) + CUMULATIVE PER-TRADE EQUITY — ALL TRADESbt

# Reuse the same full Close series as full-sample evaluation (avoid re-parsing columns).
plot_close = None
if "close" in globals() and close is not None and len(close) >= 2:
    plot_close = close.astype(float).copy()
    plot_close.name = TICKER
elif "stock_data" in globals() and stock_data is not None and "TICKER" in globals():
    try:
        plot_close = select_close_series(stock_data, TICKER).astype(float)
        plot_close.name = TICKER
    except (KeyError, ValueError, TypeError) as exc:
        print(f"Could not resolve Close series from stock_data ({exc})")

# Prefer stored per-indicator best strategies (OOS-best when available, else best IS).
strategies_to_plot = []
if "best_by_indicator" in globals() and best_by_indicator:
    for indicator_name, info in best_by_indicator.items():
        try:
            params = require_params_dict(info.get("params"), indicator_name)
            param_display = info.get("param_display") or str(params)
        except (TypeError, KeyError, ValueError) as exc:
            print(f"{indicator_name}: skipping (invalid stored params: {exc})")
            continue
        strategies_to_plot.append((indicator_name, params, param_display))
elif "results_df" in globals() and not results_df.empty:
    if "best_is_row" not in globals():
        print("best_is_row helper missing. Run the grid-search cells first.")
    else:
        for indicator_name, indicator_results in results_df.groupby("indicator", sort=False):
            best = best_is_row(indicator_results)
            if best is None:
                continue
            try:
                params = require_params_dict(best["params"], indicator_name)
            except (TypeError, KeyError, ValueError) as exc:
                print(f"{indicator_name}: skipping (invalid IS params: {exc})")
                continue
            strategies_to_plot.append((indicator_name, params, best.get("param_display") or str(params)))

if not strategies_to_plot:
    print("No results to visualize.")
elif plot_close is None or len(plot_close) < 2:
    print("Close series missing or too short for trade-by-trade plots.")
else:
    fs_by_indicator = (
        full_sample_results_by_indicator
        if "full_sample_results_by_indicator" in globals() and full_sample_results_by_indicator
        else {}
    )

    if "_params_match" not in globals():
        def _params_match(stored_params, current_params):
            return isinstance(stored_params, dict) and stored_params == current_params

    for indicator_name, params, param_display in strategies_to_plot:
        best_label = f"{indicator_name} {param_display}"
        print("\n" + "=" * 90)
        print(f"FULL-SAMPLE TRADE-BY-TRADE ANALYSIS — {best_label}")
        print("=" * 90)

        try:
            fs_result = fs_by_indicator.get(indicator_name)
            if (
                fs_result is not None
                and fs_result.get("portfolio") is not None
                and _params_match(fs_result.get("params"), params)
            ):
                pf_full = fs_result["portfolio"]
            else:
                if fs_result is not None and not _params_match(fs_result.get("params"), params):
                    print(f"{best_label}: cached portfolio params differ; rebuilding backtest.")
                spec = get_active_indicator_spec(indicator_name)
                entries_series, exits_series = spec["build_signals"](
                    plot_close, params, shift_signals=True
                )
                if len(entries_series) != len(plot_close) or len(exits_series) != len(plot_close):
                    raise ValueError(
                        f"Signal length mismatch: entries={len(entries_series)}, "
                        f"exits={len(exits_series)}, close={len(plot_close)}"
                    )
                pf_full = run_signal_backtest(plot_close, entries_series, exits_series)

            trades = pf_full.trades
            trade_returns = (
                trades.returns.values
                if hasattr(trades.returns, "values")
                else np.asarray(trades.returns)
            )
            trade_returns = np.asarray(trade_returns, dtype=float).ravel()
            bad_mask = ~np.isfinite(trade_returns)
            if np.any(bad_mask):
                print(
                    f"{best_label}: Dropping {int(bad_mask.sum())} trade(s) with non-finite returns."
                )
                trade_returns = trade_returns[~bad_mask]

            if trade_returns.size == 0:
                print(f"{best_label}: No trades to plot.")
                continue

            winning_trades = trade_returns[trade_returns > 0]
            losing_trades = trade_returns[trade_returns < 0]
            total_trades = int(trade_returns.size)
            win_count = int(winning_trades.size)
            loss_count = int(losing_trades.size)
            win_rate = (win_count / total_trades * 100.0) if total_trades > 0 else 0.0

            avg_win_pct = (winning_trades.mean() * 100.0) if win_count > 0 else 0.0
            avg_loss_pct = (losing_trades.mean() * 100.0) if loss_count > 0 else 0.0
            max_win_pct = (winning_trades.max() * 100.0) if win_count > 0 else 0.0
            max_loss_pct = (losing_trades.min() * 100.0) if loss_count > 0 else 0.0

            print(f"Total trades plotted: {total_trades}")
            print(f"Win Rate: {win_rate:.1f}% ({win_count}W / {loss_count}L)")
            print(f"Avg Win: {avg_win_pct:.2f}% | Avg Loss: {avg_loss_pct:.2f}%")
            print(f"Max Win: {max_win_pct:.2f}% | Max Loss: {max_loss_pct:.2f}%")

            equity_per_trade = np.cumprod(1.0 + trade_returns)

            x = np.arange(1, trade_returns.size + 1)
            fig, axes = plt.subplots(2, 1, figsize=(14, 9), sharex=False)

            colors = np.where(trade_returns >= 0, "green", "red")
            axes[0].bar(x, trade_returns * 100.0, color=colors, alpha=0.85, width=0.8)
            axes[0].axhline(0, color="black", linewidth=1, alpha=0.6)

            stats_text = (
                f"Win Rate: {win_rate:.1f}% ({win_count}W/{loss_count}L)\n"
                f"Avg Win: {avg_win_pct:.2f}% | Avg Loss: {avg_loss_pct:.2f}%\n"
                f"Max Win: {max_win_pct:.2f}% | Max Loss: {max_loss_pct:.2f}%"
            )
            axes[0].text(
                0.02,
                0.98,
                stats_text,
                transform=axes[0].transAxes,
                fontsize=10,
                verticalalignment="top",
                bbox=dict(boxstyle="round", facecolor="wheat", alpha=0.8),
            )
            axes[0].set_title(
                f"Per-Trade Returns (%) - {best_label} Full Sample",
                fontsize=13,
                fontweight="bold",
            )
            axes[0].set_ylabel("Return (%)")
            axes[0].grid(True, alpha=0.3)

            axes[1].plot(x, equity_per_trade, color="black", linewidth=2)
            axes[1].set_title("Cumulative Equity per Trade (Trade Domain)", fontsize=13)
            axes[1].set_xlabel("Trade #")
            axes[1].set_ylabel("Equity (x)")
            axes[1].grid(True, alpha=0.3)

            plt.tight_layout()
            plt.show()

            print(f"Trade-by-trade analysis complete for: {best_label}")
        except KeyError as exc:
            print(f"{best_label}: unknown indicator ({exc})")
        except ValueError as exc:
            print(f"{best_label}: invalid data/signals ({exc})")
        except Exception as exc:
            print(f"{best_label}: trade-by-trade plot failed ({type(exc).__name__}: {exc})")

==========================================================================================
FULL-SAMPLE TRADE-BY-TRADE ANALYSIS — Triple EMA EMA(4,117,125)
==========================================================================================
Triple EMA EMA(4,117,125): Dropping 1 trade(s) with non-finite returns.
Total trades plotted: 25
Win Rate: 60.0% (15W / 10L)
Avg Win: 25.84% | Avg Loss: -6.18%
Max Win: 123.02% | Max Loss: -12.52%

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\124681817.py:157: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Trade-by-trade analysis complete for: Triple EMA EMA(4,117,125)

==========================================================================================
FULL-SAMPLE TRADE-BY-TRADE ANALYSIS — MACD MACD(12,69,78)
==========================================================================================
Total trades plotted: 21
Win Rate: 52.4% (11W / 10L)
Avg Win: 45.20% | Avg Loss: -7.26%
Max Win: 123.79% | Max Loss: -15.90%
Trade-by-trade analysis complete for: MACD MACD(12,69,78)

==========================================================================================
FULL-SAMPLE TRADE-BY-TRADE ANALYSIS — AROON AROON(21)
==========================================================================================
AROON AROON(21): Dropping 1 trade(s) with non-finite returns.
Total trades plotted: 40
Win Rate: 52.5% (21W / 19L)
Avg Win: 23.01% | Avg Loss: -8.64%
Max Win: 102.66% | Max Loss: -22.71%
Trade-by-trade analysis complete for: AROON AROON(21)

==========================================================================================
FULL-SAMPLE TRADE-BY-TRADE ANALYSIS — STC STC(38,99,23)
==========================================================================================
Total trades plotted: 27
Win Rate: 59.3% (16W / 11L)
Avg Win: 36.69% | Avg Loss: -8.79%
Max Win: 102.52% | Max Loss: -24.79%

Trade-by-trade analysis complete for: STC STC(38,99,23)

==========================================================================================
FULL-SAMPLE TRADE-BY-TRADE ANALYSIS — KAMA KAMA(10,7,99)
==========================================================================================
KAMA KAMA(10,7,99): Dropping 1 trade(s) with non-finite returns.
Total trades plotted: 48
Win Rate: 41.7% (20W / 28L)
Avg Win: 21.56% | Avg Loss: -4.04%
Max Win: 117.74% | Max Loss: -10.25%

Trade-by-trade analysis complete for: KAMA KAMA(10,7,99)

==========================================================================================
FULL-SAMPLE TRADE-BY-TRADE ANALYSIS — SUPERTREND SUPERTREND(ATR=89,Factor=3)
==========================================================================================
SUPERTREND SUPERTREND(ATR=89,Factor=3): Dropping 1 trade(s) with non-finite returns.
Total trades plotted: 35
Win Rate: 45.7% (16W / 19L)
Avg Win: 39.22% | Avg Loss: -9.38%
Max Win: 92.19% | Max Loss: -15.17%
Trade-by-trade analysis complete for: SUPERTREND SUPERTREND(ATR=89,Factor=3)

==========================================================================================
FULL-SAMPLE TRADE-BY-TRADE ANALYSIS — KALMAN KALMAN(Q=1,R=159)
==========================================================================================
KALMAN KALMAN(Q=1,R=159): Dropping 1 trade(s) with non-finite returns.
Total trades plotted: 106
Win Rate: 49.1% (52W / 54L)
Avg Win: 12.30% | Avg Loss: -4.89%
Max Win: 80.03% | Max Loss: -14.82%

Trade-by-trade analysis complete for: KALMAN KALMAN(Q=1,R=159)

==========================================================================================
FULL-SAMPLE TRADE-BY-TRADE ANALYSIS — RSI RSI(73)
==========================================================================================
RSI RSI(73): Dropping 1 trade(s) with non-finite returns.
Total trades plotted: 43
Win Rate: 53.5% (23W / 20L)
Avg Win: 17.29% | Avg Loss: -3.97%
Max Win: 129.43% | Max Loss: -8.39%
Trade-by-trade analysis complete for: RSI RSI(73)

==========================================================================================
FULL-SAMPLE TRADE-BY-TRADE ANALYSIS — ADX ADX(DI=21,Smooth=31)
==========================================================================================
ADX ADX(DI=21,Smooth=31): Dropping 1 trade(s) with non-finite returns.
Total trades plotted: 20
Win Rate: 75.0% (15W / 5L)
Avg Win: 33.37% | Avg Loss: -4.56%
Max Win: 138.33% | Max Loss: -6.78%
Trade-by-trade analysis complete for: ADX ADX(DI=21,Smooth=31)

==========================================================================================
FULL-SAMPLE TRADE-BY-TRADE ANALYSIS — DONCHIAN DONCHIAN(24)
==========================================================================================
Total trades plotted: 36
Win Rate: 50.0% (18W / 18L)
Avg Win: 20.25% | Avg Loss: -9.13%
Max Win: 81.93% | Max Loss: -18.26%
Trade-by-trade analysis complete for: DONCHIAN DONCHIAN(24)

==========================================================================================
FULL-SAMPLE TRADE-BY-TRADE ANALYSIS — TRIX TRIX(7)
==========================================================================================
TRIX TRIX(7): Dropping 1 trade(s) with non-finite returns.
Total trades plotted: 46
Win Rate: 47.8% (22W / 24L)
Avg Win: 27.64% | Avg Loss: -9.78%
Max Win: 122.24% | Max Loss: -27.88%

Trade-by-trade analysis complete for: TRIX TRIX(7)

==========================================================================================
FULL-SAMPLE TRADE-BY-TRADE ANALYSIS — VORTEX VORTEX(115)
==========================================================================================
VORTEX VORTEX(115): Dropping 1 trade(s) with non-finite returns.
Total trades plotted: 23
Win Rate: 60.9% (14W / 9L)
Avg Win: 20.95% | Avg Loss: -6.31%
Max Win: 82.00% | Max Loss: -15.86%
Trade-by-trade analysis complete for: VORTEX VORTEX(115)

==========================================================================================
FULL-SAMPLE TRADE-BY-TRADE ANALYSIS — ALMA ALMA(2,99,0.10,3)
==========================================================================================
ALMA ALMA(2,99,0.10,3): Dropping 1 trade(s) with non-finite returns.
Total trades plotted: 22
Win Rate: 68.2% (15W / 7L)
Avg Win: 21.49% | Avg Loss: -5.84%
Max Win: 112.01% | Max Loss: -12.58%
Trade-by-trade analysis complete for: ALMA ALMA(2,99,0.10,3)

In [19]:
# COMPACT PARAMETER SENSITIVITY ANALYSIS - HEATMAPS ONLY

from IPython.display import HTML, display
from matplotlib.ticker import PercentFormatter

# Keep the combined sensitivity charts and summaries expanded in notebook output.
display(HTML("""
<style>
.jp-OutputArea-output.jp-OutputArea-executeResult,
.jp-OutputArea-output.jp-OutputArea-displayData,
.jp-OutputArea-output.jp-OutputArea-stdout,
.output_scroll,
.output_subarea {
    max-height: none !important;
    height: auto !important;
    overflow-y: visible !important;
}
</style>
"""))

# ALMA has 4 grid params; sensitivity varies fast/slow/offset and holds sigma fixed at the base.
_ALMA_SENSITIVITY_FIXED = {}


def validate_alma_sensitivity_params(fast_length, slow_length, offset):
    sigma = _ALMA_SENSITIVITY_FIXED.get("alma_sigma")
    if sigma is None:
        raise ValueError(
            "ALMA sensitivity sigma is not set. Resolve the base strategy first."
        )
    fast_length, slow_length, offset, _sigma = validate_alma_crossover_params(
        fast_length, slow_length, offset, sigma
    )
    return fast_length, slow_length, offset


def build_alma_sensitivity_signals(close_series, params, shift_signals=True):
    full_params = dict(params)
    if "alma_sigma" not in full_params:
        sigma = _ALMA_SENSITIVITY_FIXED.get("alma_sigma")
        if sigma is None:
            raise ValueError(
                "ALMA sensitivity sigma is not set. Resolve the base strategy first."
            )
        full_params["alma_sigma"] = sigma
    return build_alma_signals(close_series, full_params, shift_signals=shift_signals)


INDICATOR_SENSITIVITY_SPECS = {
    "Triple EMA": {
        "param_keys": ("ema1_period", "ema2_period", "ema3_period"),
        "param_grid_sources": ("ema1_periods", "ema2_periods", "ema3_periods"),
        "range_mins": (2, 3, 4),
        "summary_title": "EMA SENSITIVITY SUMMARY",
        "base_label_fmt": "EMA({},{},{})",
        "base_missing_msg": "Base EMA combination missing from sensitivity results.",
        "validate_combo": validate_triple_ema_params,
        "build_signals": build_triple_ema_signals,
        "param_specs": [
            {"name": "EMA1", "col": "ema1", "xlabel": "EMA1 Period", "title": "EMA1 (Fast)"},
            {"name": "EMA2", "col": "ema2", "xlabel": "EMA2 Period", "title": "EMA2 (Medium)"},
            {"name": "EMA3", "col": "ema3", "xlabel": "EMA3 Period", "title": "EMA3 (Slow)"},
        ],
    },
    "MACD": {
        "param_keys": ("macd_fast_period", "macd_slow_period", "macd_signal_period"),
        "param_grid_sources": ("macd_fast_periods", "macd_slow_periods", "macd_signal_periods"),
        "range_mins": (2, 3, 2),
        "summary_title": "MACD SENSITIVITY SUMMARY",
        "base_label_fmt": "MACD({},{},{})",
        "base_missing_msg": "Base MACD combination missing from sensitivity results.",
        "validate_combo": validate_macd_params,
        "build_signals": build_macd_signals,
        "param_specs": [
            {"name": "MACD Fast", "col": "ema1", "xlabel": "MACD Fast Period", "title": "MACD Fast"},
            {"name": "MACD Slow", "col": "ema2", "xlabel": "MACD Slow Period", "title": "MACD Slow"},
            {"name": "MACD Signal", "col": "ema3", "xlabel": "MACD Signal Period", "title": "MACD Signal"},
        ],
    },
    "AROON": {
        "param_keys": ("aroon_timeperiod", "aroon_timeperiod", "aroon_timeperiod"),
        "param_grid_sources": ("aroon_timeperiods", "aroon_timeperiods", "aroon_timeperiods"),
        "range_mins": (2, 2, 2),
        "summary_title": "AROON SENSITIVITY SUMMARY",
        "base_label_fmt": "AROON({})",
        "base_missing_msg": "Base AROON combination missing from sensitivity results.",
        "validate_combo": validate_aroon_sensitivity_params,
        "build_signals": build_aroon_signals,
        "format_base_label": lambda timeperiod, _a, _b: f"AROON({timeperiod})",
        "param_specs": [
            {"name": "AROON Timeperiod", "col": "ema1", "xlabel": "AROON Timeperiod", "title": "AROON Timeperiod"},
        ],
        "vary_axes": [
            {"dim": 0, "grid_index": 0, "sync": {1: "value", 2: "value"}},
        ],
    },
    "STC": {
        "param_keys": ("stc_ema_short_period", "stc_ema_long_period", "stc_cycle_period"),
        "param_grid_sources": ("stc_ema_short_periods", "stc_ema_long_periods", "stc_cycle_periods"),
        "range_mins": (2, 3, 2),
        "summary_title": "STC SENSITIVITY SUMMARY",
        "base_label_fmt": "STC({},{},{})",
        "base_missing_msg": "Base STC combination missing from sensitivity results.",
        "validate_combo": validate_stc_params,
        "build_signals": build_stc_signals,
        "param_specs": [
            {"name": "STC EMA Short", "col": "ema1", "xlabel": "STC EMA Short Period", "title": "STC EMA Short"},
            {"name": "STC EMA Long", "col": "ema2", "xlabel": "STC EMA Long Period", "title": "STC EMA Long"},
            {"name": "STC Cycle", "col": "ema3", "xlabel": "STC Cycle Period", "title": "STC Cycle Period"},
        ],
    },
    "KAMA": {
        "param_keys": ("kama_period", "kama_fast_ema_constant", "kama_slow_ema_constant"),
        "param_grid_sources": ("kama_periods", "kama_fast_ema_constants", "kama_slow_ema_constants"),
        "range_mins": (2, 2, 2),
        "summary_title": "KAMA SENSITIVITY SUMMARY",
        "base_label_fmt": "KAMA({},{},{})",
        "base_missing_msg": "Base KAMA combination missing from sensitivity results.",
        "validate_combo": validate_kama_params,
        "build_signals": build_kama_signals,
        "param_specs": [
            {"name": "KAMA Period", "col": "ema1", "xlabel": "KAMA Period", "title": "KAMA Period"},
            {"name": "KAMA Fast EMA", "col": "ema2", "xlabel": "KAMA Fastest EMA Constant", "title": "KAMA Fastest EMA Constant"},
            {"name": "KAMA Slow EMA", "col": "ema3", "xlabel": "KAMA Slowest EMA Constant", "title": "KAMA Slowest EMA Constant"},
        ],
    },
    "SUPERTREND": {
        "param_keys": ("supertrend_atr_length", "supertrend_factor", "supertrend_factor"),
        "param_grid_sources": ("supertrend_atr_lengths", "supertrend_factors", "supertrend_factors"),
        "range_mins": (2, 1, 1),
        "summary_title": "SUPERTREND SENSITIVITY SUMMARY",
        "base_label_fmt": "SUPERTREND(ATR={},Factor={})",
        "base_missing_msg": "Base SUPERTREND combination missing from sensitivity results.",
        "validate_combo": validate_supertrend_sensitivity_params,
        "build_signals": build_supertrend_signals,
        "format_base_label": lambda atr_length, factor, _anchor: f"SUPERTREND(ATR={atr_length},Factor={factor})",
        "param_specs": [
            {"name": "SUPERTREND ATR Length", "col": "ema1", "xlabel": "ATR Length", "title": "SUPERTREND ATR Length"},
            {"name": "SUPERTREND Factor", "col": "ema2", "xlabel": "Factor / Multiplier", "title": "SUPERTREND Factor"},
        ],
        "vary_axes": [
            {"dim": 0, "grid_index": 0, "sync": {2: "dim1"}},
            {"dim": 1, "grid_index": 1, "sync": {2: "value"}},
        ],
    },
    "KALMAN": {
        "param_keys": ("kalman_process_noise", "kalman_measurement_noise", "kalman_measurement_noise"),
        "param_grid_sources": ("kalman_process_noise_values", "kalman_measurement_noise_values", "kalman_measurement_noise_values"),
        "range_mins": (1, 1, 1),
        "summary_title": "KALMAN SENSITIVITY SUMMARY",
        "base_label_fmt": "KALMAN(Q={},R={})",
        "base_missing_msg": "Base KALMAN combination missing from sensitivity results.",
        "validate_combo": validate_kalman_sensitivity_params,
        "build_signals": build_kalman_signals,
        "format_base_label": lambda process_noise, measurement_noise, _anchor: f"KALMAN(Q={process_noise},R={measurement_noise})",
        "param_specs": [
            {"name": "KALMAN Process Noise Q", "col": "ema1", "xlabel": "Process Noise (Q)", "title": "KALMAN Process Noise (Q)"},
            {"name": "KALMAN Measurement Noise R", "col": "ema2", "xlabel": "Measurement Noise (R)", "title": "KALMAN Measurement Noise (R)"},
        ],
        "vary_axes": [
            {"dim": 0, "grid_index": 0, "sync": {2: "dim1"}},
            {"dim": 1, "grid_index": 1, "sync": {2: "value"}},
        ],
    },
    "RSI": {
        "param_keys": ("rsi_timeperiod", "rsi_timeperiod", "rsi_timeperiod"),
        "param_grid_sources": ("rsi_timeperiods", "rsi_timeperiods", "rsi_timeperiods"),
        "range_mins": (2, 2, 2),
        "summary_title": "RSI SENSITIVITY SUMMARY",
        "base_label_fmt": "RSI({})",
        "base_missing_msg": "Base RSI combination missing from sensitivity results.",
        "validate_combo": validate_rsi_sensitivity_params,
        "build_signals": build_rsi_signals,
        "format_base_label": lambda timeperiod, _a, _b: f"RSI({timeperiod})",
        "param_specs": [
            {"name": "RSI Timeperiod", "col": "ema1", "xlabel": "RSI Timeperiod", "title": "RSI Timeperiod"},
        ],
        "vary_axes": [
            {"dim": 0, "grid_index": 0, "sync": {1: "value", 2: "value"}},
        ],
    },
    "ADX": {
        "param_keys": ("adx_di_length", "adx_smoothing_timeperiod", "adx_smoothing_timeperiod"),
        "param_grid_sources": ("adx_di_lengths", "adx_smoothing_timeperiods", "adx_smoothing_timeperiods"),
        "range_mins": (2, 2, 2),
        "summary_title": "ADX SENSITIVITY SUMMARY",
        "base_label_fmt": "ADX(DI={},Smooth={})",
        "base_missing_msg": "Base ADX combination missing from sensitivity results.",
        "validate_combo": validate_adx_sensitivity_params,
        "build_signals": build_adx_signals,
        "format_base_label": lambda di_length, adx_smoothing, _anchor: f"ADX(DI={di_length},Smooth={adx_smoothing})",
        "param_specs": [
            {"name": "ADX DI Length", "col": "ema1", "xlabel": "DI Length", "title": "ADX DI Length"},
            {"name": "ADX Smoothing", "col": "ema2", "xlabel": "ADX Smoothing Timeperiod", "title": "ADX Smoothing Timeperiod"},
        ],
        "vary_axes": [
            {"dim": 0, "grid_index": 0, "sync": {2: "dim1"}},
            {"dim": 1, "grid_index": 1, "sync": {2: "value"}},
        ],
    },
    "DONCHIAN": {
        "param_keys": ("donchian_timeperiod", "donchian_timeperiod", "donchian_timeperiod"),
        "param_grid_sources": ("donchian_timeperiods", "donchian_timeperiods", "donchian_timeperiods"),
        "range_mins": (2, 2, 2),
        "summary_title": "DONCHIAN SENSITIVITY SUMMARY",
        "base_label_fmt": "DONCHIAN({})",
        "base_missing_msg": "Base DONCHIAN combination missing from sensitivity results.",
        "validate_combo": validate_donchian_sensitivity_params,
        "build_signals": build_donchian_signals,
        "format_base_label": lambda timeperiod, _a, _b: f"DONCHIAN({timeperiod})",
        "param_specs": [
            {"name": "DONCHIAN Timeperiod", "col": "ema1", "xlabel": "DONCHIAN Timeperiod", "title": "DONCHIAN Timeperiod"},
        ],
        "vary_axes": [
            {"dim": 0, "grid_index": 0, "sync": {1: "value", 2: "value"}},
        ],
    },
    "TRIX": {
        "param_keys": ("trix_timeperiod", "trix_timeperiod", "trix_timeperiod"),
        "param_grid_sources": ("trix_timeperiods", "trix_timeperiods", "trix_timeperiods"),
        "range_mins": (2, 2, 2),
        "summary_title": "TRIX SENSITIVITY SUMMARY",
        "base_label_fmt": "TRIX({})",
        "base_missing_msg": "Base TRIX combination missing from sensitivity results.",
        "validate_combo": validate_trix_sensitivity_params,
        "build_signals": build_trix_signals,
        "format_base_label": lambda timeperiod, _a, _b: f"TRIX({timeperiod})",
        "param_specs": [
            {"name": "TRIX Timeperiod", "col": "ema1", "xlabel": "TRIX Timeperiod", "title": "TRIX Timeperiod"},
        ],
        "vary_axes": [
            {"dim": 0, "grid_index": 0, "sync": {1: "value", 2: "value"}},
        ],
    },
    "VORTEX": {
        "param_keys": ("vortex_timeperiod", "vortex_timeperiod", "vortex_timeperiod"),
        "param_grid_sources": ("vortex_timeperiods", "vortex_timeperiods", "vortex_timeperiods"),
        "range_mins": (2, 2, 2),
        "summary_title": "VORTEX SENSITIVITY SUMMARY",
        "base_label_fmt": "VORTEX({})",
        "base_missing_msg": "Base VORTEX combination missing from sensitivity results.",
        "validate_combo": validate_vortex_sensitivity_params,
        "build_signals": build_vortex_signals,
        "format_base_label": lambda timeperiod, _a, _b: f"VORTEX({timeperiod})",
        "param_specs": [
            {"name": "VORTEX Timeperiod", "col": "ema1", "xlabel": "VORTEX Timeperiod", "title": "VORTEX Timeperiod"},
        ],
        "vary_axes": [
            {"dim": 0, "grid_index": 0, "sync": {1: "value", 2: "value"}},
        ],
    },
    "ALMA": {
        "param_keys": ("alma_fast_length", "alma_slow_length", "alma_offset"),
        "param_grid_sources": ("alma_fast_lengths", "alma_slow_lengths", "alma_offsets"),
        "range_mins": (2, 3, 0),
        "summary_title": "ALMA SENSITIVITY SUMMARY",
        "base_label_fmt": "ALMA(fast={},slow={},offset={})",
        "base_missing_msg": "Base ALMA combination missing from sensitivity results.",
        "validate_combo": validate_alma_sensitivity_params,
        "build_signals": build_alma_sensitivity_signals,
        "format_base_label": lambda fast_length, slow_length, offset: (
            f"ALMA(fast={fast_length},slow={slow_length},"
            f"offset={offset / 100:.2f},sigma={_ALMA_SENSITIVITY_FIXED.get('alma_sigma', '?')})"
        ),
        "fixed_from_base_keys": ("alma_sigma",),
        "fixed_param_store": _ALMA_SENSITIVITY_FIXED,
        "param_specs": [
            {"name": "ALMA Fast Length", "col": "ema1", "xlabel": "ALMA Fast Length", "title": "ALMA Fast Length"},
            {"name": "ALMA Slow Length", "col": "ema2", "xlabel": "ALMA Slow Length", "title": "ALMA Slow Length"},
            {"name": "ALMA Offset", "col": "ema3", "xlabel": "ALMA Offset (hundredths)", "title": "ALMA Offset"},
        ],
    },
}


_SENSITIVITY_GRID_CACHE = {}


def resolve_param_grid(source_name):
    if source_name in _SENSITIVITY_GRID_CACHE:
        return _SENSITIVITY_GRID_CACHE[source_name]

    grid_values = globals().get(source_name)
    if grid_values is None:
        raise KeyError(f"Missing grid definition: {source_name}")
    if not hasattr(grid_values, "__iter__") or isinstance(grid_values, (str, bytes)):
        raise TypeError(f"Grid definition {source_name} must be an iterable of numbers")
    try:
        grid = [int(value) for value in grid_values]
    except (TypeError, ValueError) as exc:
        raise ValueError(f"Grid definition {source_name} contains non-integer values") from exc
    if not grid:
        raise ValueError(f"Grid definition {source_name} is empty")

    _SENSITIVITY_GRID_CACHE[source_name] = grid
    return grid


def resolve_sensitivity_param_grids(spec):
    grids = [resolve_param_grid(source_name) for source_name in spec["param_grid_sources"]]
    return grids[: len(spec["param_specs"])]


def grid_index_for_base(grid_values, base_value):
    if not grid_values:
        raise ValueError("Cannot locate base value on an empty grid")
    base_value = int(base_value)
    try:
        return grid_values.index(base_value)
    except ValueError:
        return min(range(len(grid_values)), key=lambda idx: abs(grid_values[idx] - base_value))


def grid_window_values(grid_values, base_value, window_steps=15):
    """Return grid-tested values within ±window_steps of base on the search grid."""
    idx = grid_index_for_base(grid_values, base_value)
    lo = max(0, idx - window_steps)
    hi = min(len(grid_values), idx + window_steps + 1)
    return grid_values[lo:hi]


def grid_step_size(grid_values):
    if len(grid_values) < 2:
        return 1
    positive_steps = [b - a for a, b in zip(grid_values, grid_values[1:]) if b > a]
    return min(positive_steps) if positive_steps else 1


def set_grid_aligned_xticks(ax, param_values, grid_values=None):
    ticks = sorted({int(value) for value in param_values if pd.notna(value)})
    if not ticks:
        return
    if len(ticks) > 20:
        step = grid_step_size(grid_values) if grid_values else grid_step_size(ticks)
        tick_stride = max(1, len(ticks) // 15)
        tick_step = step * tick_stride
        ticks = [tick for tick in ticks if (tick - ticks[0]) % tick_step == 0]
    ax.set_xticks(ticks)
    if len(ticks) > 12:
        ax.tick_params(axis="x", rotation=45)


def make_sensitivity_combo(bases, vary_dim, value, sync_rules=None):
    combo = list(bases)
    combo[vary_dim] = int(value)
    for target_dim, rule in (sync_rules or {}).items():
        if rule == "value":
            combo[target_dim] = int(value)
        elif rule == "dim1":
            combo[target_dim] = combo[1]
        elif rule == "base":
            combo[target_dim] = bases[target_dim]
    return tuple(combo)


def default_vary_axes(spec):
    return [
        {"dim": idx, "grid_index": idx, "sync": {}}
        for idx in range(len(spec["param_specs"]))
    ]


def variation_mask_for_axis(sens_df, axis, bases):
    mask = pd.Series(True, index=sens_df.index)
    vary_dim = axis["dim"]
    param_cols = ("ema1", "ema2", "ema3")

    for dim, col in enumerate(param_cols):
        if dim == vary_dim or dim in axis.get("sync", {}):
            continue
        mask &= sens_df[col] == bases[dim]

    for target_dim, rule in axis.get("sync", {}).items():
        col = param_cols[target_dim]
        if rule == "value":
            mask &= sens_df[col] == sens_df[param_cols[vary_dim]]
        elif rule == "dim1":
            mask &= sens_df[col] == sens_df["ema2"]
        elif rule == "base":
            mask &= sens_df[col] == bases[target_dim]

    return mask


def build_variation_sets(sens_df, bases, spec):
    vary_axes = spec.get("vary_axes") or default_vary_axes(spec)
    param_cols = ("ema1", "ema2", "ema3")
    variation_sets = []
    for axis in vary_axes:
        vary_col = param_cols[axis["dim"]]
        mask = variation_mask_for_axis(sens_df, axis, bases)
        variation_sets.append(sens_df[mask].copy().sort_values(vary_col))
    return variation_sets


def pct_delta(values, base_value):
    """Return percentage delta from a finite, non-zero base value."""
    if pd.isna(base_value) or not np.isfinite(base_value) or base_value == 0:
        return np.nan
    return ((values - base_value) / abs(base_value) * 100)


def drawdown_pct_delta(values, base_value):
    """Return percentage delta in drawdown magnitude, where positive means deeper drawdown."""
    if pd.isna(base_value) or not np.isfinite(base_value) or base_value == 0:
        return np.nan
    return ((values.abs() - abs(base_value)) / abs(base_value) * 100)


def max_abs_finite(values):
    finite_values = pd.to_numeric(values, errors='coerce').replace([np.inf, -np.inf], np.nan).dropna()
    return finite_values.abs().max() if not finite_values.empty else np.nan


def count_delta(values, base_value):
    """Return absolute count delta from a finite base value."""
    if pd.isna(base_value) or not np.isfinite(base_value):
        return np.nan
    return values - base_value


def neighbor_variations(variations, param_col, base_param, grid_values):
    """Keep only the base value and its immediate neighbors on the search grid."""
    if variations.empty:
        return variations
    idx = grid_index_for_base(grid_values, base_param)
    neighbor_values = {
        grid_values[j]
        for j in (idx - 1, idx, idx + 1)
        if 0 <= j < len(grid_values)
    }
    param_values = pd.to_numeric(variations[param_col], errors="coerce").dropna().astype(int)
    return variations.loc[param_values.index[param_values.isin(neighbor_values)]]


def is_finite_number(value):
    return pd.notna(value) and np.isfinite(value)


def directional_delta_colors(delta_values):
    colors = []
    for x in pd.to_numeric(delta_values, errors='coerce'):
        if not is_finite_number(x):
            colors.append('gray')
        elif x < -10:
            colors.append('red')
        elif x < 0:
            colors.append('orange')
        elif x < 10:
            colors.append('lightgreen')
        else:
            colors.append('darkgreen')
    return colors


def absolute_delta_colors(delta_values):
    colors = []
    for x in pd.to_numeric(delta_values, errors='coerce'):
        if not is_finite_number(x):
            colors.append('gray')
        elif abs(x) > 40:
            colors.append('red')
        elif abs(x) > 20:
            colors.append('orange')
        elif abs(x) > 10:
            colors.append('lightgreen')
        else:
            colors.append('darkgreen')
    return colors


def add_base_line(ax, base_value, label):
    if is_finite_number(base_value):
        ax.axhline(base_value, color='black', linewidth=1.5, alpha=0.7, label=label)


def prefer_finite(evaluated, stored):
    """Prefer sensitivity-evaluated metric; fall back to stored when non-finite."""
    if is_finite_number(evaluated):
        return evaluated
    if is_finite_number(stored):
        return stored
    return np.nan


def note_if_reference_differs(kind, evaluated, stored):
    if (
        is_finite_number(evaluated)
        and is_finite_number(stored)
        and abs(evaluated - stored) > 1e-6
    ):
        print(
            f"Note: using sensitivity-evaluated {kind} Sharpe {evaluated:.3f} "
            f"for reference line (stored/grid Sharpe was {stored:.3f})."
        )
    elif is_finite_number(stored) and not is_finite_number(evaluated):
        print(
            f"Note: sensitivity-evaluated {kind} Sharpe was non-finite; "
            f"falling back to stored/grid Sharpe {stored:.3f}."
        )


def extract_base_metrics(base_row):
    """Pull base reference metrics safely from the evaluated sensitivity row."""
    required = (
        'is_sharpe', 'oos_sharpe',
        'is_trades', 'oos_trades',
        'is_volatility', 'oos_volatility',
        'is_maxdd', 'oos_maxdd',
    )
    missing = [col for col in required if col not in base_row.index]
    if missing:
        raise KeyError(f"sensitivity base row missing columns: {', '.join(missing)}")

    def _trades(col):
        value = safe_float(base_row[col])
        return int(value) if is_finite_number(value) else np.nan

    return {
        'is_sharpe': safe_float(base_row['is_sharpe']),
        'oos_sharpe': safe_float(base_row['oos_sharpe']),
        'is_trades': _trades('is_trades'),
        'oos_trades': _trades('oos_trades'),
        'is_volatility': safe_float(base_row['is_volatility']),
        'oos_volatility': safe_float(base_row['oos_volatility']),
        'is_maxdd': safe_float(base_row['is_maxdd']),
        'oos_maxdd': safe_float(base_row['oos_maxdd']),
    }


def portfolio_metrics_with_prefix(pf, prefix):
    """Shared IS/OOS metric extraction to avoid duplicated Portfolio calls."""
    return {
        f"{prefix}_sharpe": safe_float(pf.sharpe_ratio(freq=FREQ, year_freq=YEAR_FREQ)),
        f"{prefix}_return": safe_float(pf.total_return()),
        f"{prefix}_maxdd": safe_float(pf.max_drawdown()),
        f"{prefix}_volatility": safe_float(pf.annualized_volatility(freq=FREQ, year_freq=YEAR_FREQ)),
        f"{prefix}_trades": len(pf.trades),
    }


def eval_indicator_combo_both(e1: int, e2: int, e3: int, spec) -> dict:
    """Evaluate one already-validated parameter combo on IS and OOS."""
    params = dict(zip(spec['param_keys'], (e1, e2, e3)))

    e_is, x_is = spec['build_signals'](train_close, params, shift_signals=True)
    pf_is = run_signal_backtest(train_close, e_is, x_is)

    e_oos, x_oos = spec['build_signals'](val_close, params, shift_signals=True)
    pf_oos = run_signal_backtest(val_close, e_oos, x_oos)

    return {
        'ema1': e1,
        'ema2': e2,
        'ema3': e3,
        **portfolio_metrics_with_prefix(pf_is, 'is'),
        **portfolio_metrics_with_prefix(pf_oos, 'oos'),
    }


def plot_trade_values(ax, variations, param_spec, base_params, title, value_col, delta_col, base_value, grid_values=None):
    colors = absolute_delta_colors(variations[delta_col])
    ax.bar(variations[param_spec['col']], variations[value_col], color=colors, edgecolor='black', linewidth=0.5)
    add_base_line(ax, base_value, f'Base trades={base_value:.0f}')
    ax.axvline(
        base_params[param_spec['col']], color='blue', linestyle='--', linewidth=2.5, alpha=0.7,
        label=f'Base={base_params[param_spec["col"]]}'
    )
    ax.set_xlabel(param_spec['xlabel'], fontsize=11, fontweight='bold')
    ax.set_ylabel('Total Trades', fontsize=11, fontweight='bold')
    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.grid(axis='y', alpha=0.3)
    ax.legend(fontsize=10, loc='upper right')
    set_grid_aligned_xticks(ax, variations[param_spec['col']], grid_values)


def plot_volatility_values(ax, variations, param_spec, base_params, title, value_col, delta_col, base_value, grid_values=None):
    colors = absolute_delta_colors(variations[delta_col])
    ax.bar(variations[param_spec['col']], variations[value_col], color=colors, edgecolor='black', linewidth=0.5)
    add_base_line(ax, base_value, f'Base vol={base_value:.2%}')
    ax.axvline(
        base_params[param_spec['col']], color='blue', linestyle='--', linewidth=2.5, alpha=0.7,
        label=f'Base={base_params[param_spec["col"]]}'
    )
    ax.set_xlabel(param_spec['xlabel'], fontsize=11, fontweight='bold')
    ax.set_ylabel('Volatility', fontsize=11, fontweight='bold')
    ax.yaxis.set_major_formatter(PercentFormatter(1.0))
    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.grid(axis='y', alpha=0.3)
    ax.legend(fontsize=10, loc='upper right')
    set_grid_aligned_xticks(ax, variations[param_spec['col']], grid_values)


def plot_maxdd_values(ax, variations, param_spec, base_params, title, value_col, delta_col, base_value, grid_values=None):
    colors = absolute_delta_colors(variations[delta_col])
    ax.bar(variations[param_spec['col']], variations[value_col], color=colors, edgecolor='black', linewidth=0.5)
    add_base_line(ax, base_value, f'Base max DD={base_value:.2%}')
    ax.axvline(
        base_params[param_spec['col']], color='blue', linestyle='--', linewidth=2.5, alpha=0.7,
        label=f'Base={base_params[param_spec["col"]]}'
    )
    ax.set_xlabel(param_spec['xlabel'], fontsize=11, fontweight='bold')
    ax.set_ylabel('Max Drawdown', fontsize=11, fontweight='bold')
    ax.yaxis.set_major_formatter(PercentFormatter(1.0))
    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.grid(axis='y', alpha=0.3)
    ax.legend(fontsize=10, loc='upper right')
    set_grid_aligned_xticks(ax, variations[param_spec['col']], grid_values)


def sensitivity_prerequisites_ok():
    required = (
        'train_close',
        'val_close',
        'FREQ',
        'YEAR_FREQ',
        'run_signal_backtest',
        'require_params_dict',
        'best_is_row',
        'safe_float',
    )
    missing = [name for name in required if name not in globals()]
    if missing:
        print(f"Missing prerequisites for sensitivity analysis: {', '.join(missing)}")
        return False
    if getattr(train_close, 'empty', len(train_close) == 0):
        print("train_close is empty; cannot run sensitivity analysis.")
        return False
    if getattr(val_close, 'empty', len(val_close) == 0):
        print("val_close is empty; cannot run sensitivity analysis.")
        return False
    return True


def resolve_sensitivity_indicators():
    candidates = []
    if 'active_indicator_names' in globals() and active_indicator_names:
        candidates = list(active_indicator_names)
    elif 'best_by_indicator' in globals() and best_by_indicator:
        candidates = list(best_by_indicator.keys())
    elif 'results_df' in globals() and not results_df.empty:
        candidates = list(results_df.groupby('indicator', sort=False).groups.keys())

    return [name for name in candidates if name in INDICATOR_SENSITIVITY_SPECS]


def resolve_indicator_base(indicator_name, spec):
    try:
        fixed_store = spec.get("fixed_param_store")
        fixed_keys = tuple(spec.get("fixed_from_base_keys") or ())
        # Prevent stale fixed values from a prior indicator/run leaking forward.
        if fixed_store is not None:
            fixed_store.clear()

        if 'best_by_indicator' in globals() and indicator_name in best_by_indicator:
            info = best_by_indicator[indicator_name]
            params = require_params_dict(info['params'], indicator_name)
            if fixed_store is not None:
                for key in fixed_keys:
                    if key not in params:
                        raise KeyError(f"{indicator_name} base params missing fixed key: {key}")
                    fixed_store[key] = int(params[key])
            p1, p2, p3 = (int(params[key]) for key in spec['param_keys'])
            return p1, p2, p3, safe_float(info['is_sharpe']), safe_float(info['oos_sharpe'])

        if 'results_df' not in globals() or results_df.empty:
            return None

        indicator_results = results_df[results_df['indicator'] == indicator_name]
        best = best_is_row(indicator_results)
        if best is None:
            return None

        if fixed_store is not None:
            for key in fixed_keys:
                if key not in best:
                    raise KeyError(f"{indicator_name} base results missing fixed key: {key}")
                fixed_store[key] = int(best[key])
        p1, p2, p3 = (int(best[key]) for key in spec['param_keys'])
        return p1, p2, p3, safe_float(best['sharpe_ratio']), np.nan
    except (KeyError, TypeError, ValueError) as exc:
        print(f"Could not resolve base parameters for {indicator_name}: {exc}")
        return None



def build_sensitivity_combos(p1_base, p2_base, p3_base, spec, param_grids):
    window_steps = spec.get("neighbor_window", 15)
    bases = (int(p1_base), int(p2_base), int(p3_base))
    vary_axes = spec.get("vary_axes") or default_vary_axes(spec)

    raw_combos = []
    for axis in vary_axes:
        dim = axis["dim"]
        grid_idx = axis.get("grid_index", dim)
        if grid_idx >= len(param_grids):
            continue
        grid = param_grids[grid_idx]
        for value in grid_window_values(grid, bases[dim], window_steps):
            raw_combos.append(make_sensitivity_combo(bases, dim, value, axis.get("sync")))

    raw_combos = list(dict.fromkeys(raw_combos))
    all_combos = []
    for combo in raw_combos:
        try:
            all_combos.append(spec['validate_combo'](*combo))
        except ValueError:
            pass
    return all_combos


def run_indicator_sensitivity_analysis(indicator_name):
    spec = INDICATOR_SENSITIVITY_SPECS.get(indicator_name)
    if spec is None:
        print(f"Skipping {indicator_name}: no sensitivity spec defined for this indicator.")
        return
    base_info = resolve_indicator_base(indicator_name, spec)
    if base_info is None:
        print(f"Skipping {indicator_name}: no results available for parameter sensitivity analysis.")
        return

    p1_base, p2_base, p3_base, base_is_sharpe, base_oos_sharpe = base_info
    bases = [int(p1_base), int(p2_base), int(p3_base)]

    try:
        # Snap all 3 sensitivity slots onto their full grid sources so the exact
        # base combo is always among evaluated rows (avoids wasted runs then skip).
        full_grids = [resolve_param_grid(name) for name in spec["param_grid_sources"]]
        param_grids = full_grids[: len(spec["param_specs"])]
    except (KeyError, TypeError, ValueError) as exc:
        print(f"Skipping {indicator_name}: {exc}")
        return

    for dim_idx, grid_values in enumerate(full_grids):
        if bases[dim_idx] not in grid_values:
            snapped = grid_values[grid_index_for_base(grid_values, bases[dim_idx])]
            print(
                f"Note: {indicator_name} base parameter dim {dim_idx}={bases[dim_idx]} "
                f"is not on the search grid; snapping to nearest grid value {snapped}."
            )
            bases[dim_idx] = int(snapped)

    try:
        bases = list(spec["validate_combo"](*bases))
    except ValueError as exc:
        print(f"Skipping {indicator_name}: snapped base params are invalid ({bases}): {exc}")
        return

    p1_base, p2_base, p3_base = (int(bases[0]), int(bases[1]), int(bases[2]))
    bases = (p1_base, p2_base, p3_base)

    format_base_label = spec.get('format_base_label')
    if callable(format_base_label):
        base_label = format_base_label(p1_base, p2_base, p3_base)
    else:
        base_label = spec['base_label_fmt'].format(p1_base, p2_base, p3_base)

    print("\n" + "=" * 90)
    print(f"🔬 PARAMETER SENSITIVITY ANALYSIS - {indicator_name} - Base: {base_label}")

    all_combos = build_sensitivity_combos(p1_base, p2_base, p3_base, spec, param_grids)
    if not all_combos:
        print(f"Skipping {indicator_name}: no valid sensitivity combinations were generated.")
        return

    print(f"\n🔄 Testing {len(all_combos)} parameter variations...")

    rows = []
    failed_sensitivity_combos = []
    for combo in all_combos:
        try:
            rows.append(eval_indicator_combo_both(*combo, spec))
        except Exception as exc:
            failed_sensitivity_combos.append((combo, str(exc)))

    if failed_sensitivity_combos:
        first_failed_combo, first_error = failed_sensitivity_combos[0]
        print(
            f"⚠️ Skipped {len(failed_sensitivity_combos)} failed sensitivity variation(s). "
            f"First failure: {first_failed_combo} -> {first_error[:120]}"
        )

    if not rows:
        print(f"❌ No sensitivity results computed for {indicator_name}.")
        return

    sens_df = pd.DataFrame(rows)
    variation_sets = build_variation_sets(sens_df, bases, spec)
    base_params = {'ema1': p1_base, 'ema2': p2_base, 'ema3': p3_base}

    base_trade_row = sens_df[(sens_df['ema1'] == p1_base) & (sens_df['ema2'] == p2_base) & (sens_df['ema3'] == p3_base)]
    if base_trade_row.empty:
        print(f"Skipping {indicator_name}: {spec['base_missing_msg']}")
        return
    if len(base_trade_row) > 1:
        print(
            f"Note: {indicator_name} matched {len(base_trade_row)} base rows; "
            "using the first evaluated match for reference metrics."
        )

    # Reference line + deltas must use the same metrics as the bars (evaluated),
    # not the stored grid/CSV Sharpes which can differ after re-evaluation.
    stored_is_sharpe, stored_oos_sharpe = base_is_sharpe, base_oos_sharpe
    try:
        base_metrics = extract_base_metrics(base_trade_row.iloc[0])
    except (KeyError, TypeError, ValueError) as exc:
        print(f"Skipping {indicator_name}: could not read base metrics ({exc})")
        return

    evaluated_is_sharpe = base_metrics['is_sharpe']
    evaluated_oos_sharpe = base_metrics['oos_sharpe']
    note_if_reference_differs('IS', evaluated_is_sharpe, stored_is_sharpe)
    note_if_reference_differs('OOS', evaluated_oos_sharpe, stored_oos_sharpe)
    base_is_sharpe = prefer_finite(evaluated_is_sharpe, stored_is_sharpe)
    base_oos_sharpe = prefer_finite(evaluated_oos_sharpe, stored_oos_sharpe)

    if is_finite_number(base_is_sharpe) and is_finite_number(base_oos_sharpe):
        print(f"IS Sharpe: {base_is_sharpe:.3f} | OOS Sharpe: {base_oos_sharpe:.3f}")
    elif is_finite_number(base_is_sharpe):
        print(f"IS Sharpe: {base_is_sharpe:.3f}")
    else:
        print("IS Sharpe: n/a")

    has_valid_oos_sharpe = is_finite_number(base_oos_sharpe)
    base_is_trades = base_metrics['is_trades']
    base_oos_trades = base_metrics['oos_trades']
    base_is_volatility = base_metrics['is_volatility']
    base_oos_volatility = base_metrics['oos_volatility']
    base_is_maxdd = base_metrics['is_maxdd']
    base_oos_maxdd = base_metrics['oos_maxdd']

    for variations in variation_sets:
        variations['is_sharpe_delta'] = pct_delta(variations['is_sharpe'], base_is_sharpe)
        variations['oos_sharpe_delta'] = (
            pct_delta(variations['oos_sharpe'], base_oos_sharpe)
            if has_valid_oos_sharpe else np.nan
        )
        variations['is_trades_delta'] = pct_delta(variations['is_trades'], base_is_trades)
        variations['oos_trades_delta'] = pct_delta(variations['oos_trades'], base_oos_trades)
        variations['is_trades_count_delta'] = count_delta(variations['is_trades'], base_is_trades)
        variations['oos_trades_count_delta'] = count_delta(variations['oos_trades'], base_oos_trades)
        variations['is_volatility_delta'] = pct_delta(variations['is_volatility'], base_is_volatility)
        variations['oos_volatility_delta'] = pct_delta(variations['oos_volatility'], base_oos_volatility)
        variations['is_maxdd_delta'] = drawdown_pct_delta(variations['is_maxdd'], base_is_maxdd)
        variations['oos_maxdd_delta'] = drawdown_pct_delta(variations['oos_maxdd'], base_oos_maxdd)

    n_params = len(spec['param_specs'])
    n_cols = max(n_params, 1)
    fig_w = max(6.5 * n_cols, 8)

    def _new_sensitivity_figure(title):
        fig, axes = plt.subplots(2, n_cols, figsize=(fig_w, 10), squeeze=False)
        fig.suptitle(title, fontsize=16, fontweight='bold')
        if not has_valid_oos_sharpe:
            for col_idx in range(n_cols):
                axes[1, col_idx].set_visible(False)
        return fig, axes

    fig, axes = _new_sensitivity_figure(
        f'Parameter Sensitivity Analysis - {indicator_name} - Base: {base_label}'
    )

    for col_idx, (param_spec, variations, grid_values) in enumerate(zip(spec['param_specs'], variation_sets, param_grids)):
        if variations.empty:
            axes[0, col_idx].set_title(f"{param_spec['title']} - In-Sample (no data)", fontsize=12, fontweight='bold')
            continue
        colors_is = directional_delta_colors(variations['is_sharpe_delta'])
        axes[0, col_idx].bar(
            variations[param_spec['col']], variations['is_sharpe'],
            color=colors_is, edgecolor='black', linewidth=0.5
        )
        add_base_line(axes[0, col_idx], base_is_sharpe, f'Base Sharpe={base_is_sharpe:.3f}')
        axes[0, col_idx].axvline(
            base_params[param_spec['col']], color='blue', linestyle='--', linewidth=2.5, alpha=0.7,
            label=f'Base={base_params[param_spec["col"]]}'
        )
        axes[0, col_idx].set_xlabel(param_spec['xlabel'], fontsize=11, fontweight='bold')
        axes[0, col_idx].set_ylabel('Sharpe Ratio', fontsize=11, fontweight='bold')
        axes[0, col_idx].set_title(f"{param_spec['title']} - In-Sample", fontsize=12, fontweight='bold')
        axes[0, col_idx].grid(axis='y', alpha=0.3)
        axes[0, col_idx].legend(fontsize=10, loc='upper right')
        set_grid_aligned_xticks(axes[0, col_idx], variations[param_spec['col']], grid_values)

        if has_valid_oos_sharpe:
            colors_oos = directional_delta_colors(variations['oos_sharpe_delta'])
            axes[1, col_idx].bar(
                variations[param_spec['col']], variations['oos_sharpe'],
                color=colors_oos, edgecolor='black', linewidth=0.5
            )
            add_base_line(axes[1, col_idx], base_oos_sharpe, f'Base Sharpe={base_oos_sharpe:.3f}')
            axes[1, col_idx].axvline(
                base_params[param_spec['col']], color='blue', linestyle='--', linewidth=2.5, alpha=0.7,
                label=f'Base={base_params[param_spec["col"]]}'
            )
            axes[1, col_idx].set_xlabel(param_spec['xlabel'], fontsize=11, fontweight='bold')
            axes[1, col_idx].set_ylabel('Sharpe Ratio', fontsize=11, fontweight='bold')
            axes[1, col_idx].set_title(f"{param_spec['title']} - Out-of-Sample", fontsize=12, fontweight='bold')
            axes[1, col_idx].grid(axis='y', alpha=0.3)
            axes[1, col_idx].legend(fontsize=10, loc='upper right')
            set_grid_aligned_xticks(axes[1, col_idx], variations[param_spec['col']], grid_values)

    plt.tight_layout()
    plt.show()

    fig_trades, trade_axes = _new_sensitivity_figure(
        f'Total Trades Sensitivity Analysis - {indicator_name} - Base: {base_label}'
    )

    for col_idx, (param_spec, variations, grid_values) in enumerate(zip(spec['param_specs'], variation_sets, param_grids)):
        if variations.empty:
            trade_axes[0, col_idx].set_title(f"{param_spec['title']} - In-Sample Trades (no data)", fontsize=12, fontweight='bold')
            continue
        plot_trade_values(
            trade_axes[0, col_idx], variations, param_spec, base_params,
            f"{param_spec['title']} - In-Sample Trades", 'is_trades', 'is_trades_delta', base_is_trades, grid_values
        )
        if has_valid_oos_sharpe:
            plot_trade_values(
                trade_axes[1, col_idx], variations, param_spec, base_params,
                f"{param_spec['title']} - Out-of-Sample Trades", 'oos_trades', 'oos_trades_delta', base_oos_trades, grid_values
            )

    plt.tight_layout()
    plt.show()

    fig_vol, vol_axes = _new_sensitivity_figure(
        f'Volatility Sensitivity Analysis - {indicator_name} - Base: {base_label}'
    )

    for col_idx, (param_spec, variations, grid_values) in enumerate(zip(spec['param_specs'], variation_sets, param_grids)):
        if variations.empty:
            vol_axes[0, col_idx].set_title(f"{param_spec['title']} - In-Sample Volatility (no data)", fontsize=12, fontweight='bold')
            continue
        plot_volatility_values(
            vol_axes[0, col_idx], variations, param_spec, base_params,
            f"{param_spec['title']} - In-Sample Volatility", 'is_volatility', 'is_volatility_delta', base_is_volatility, grid_values
        )
        if has_valid_oos_sharpe:
            plot_volatility_values(
                vol_axes[1, col_idx], variations, param_spec, base_params,
                f"{param_spec['title']} - Out-of-Sample Volatility", 'oos_volatility', 'oos_volatility_delta', base_oos_volatility, grid_values
            )

    plt.tight_layout()
    plt.show()

    fig_maxdd, maxdd_axes = _new_sensitivity_figure(
        f'Max Drawdown Sensitivity Analysis - {indicator_name} - Base: {base_label}'
    )

    for col_idx, (param_spec, variations, grid_values) in enumerate(zip(spec['param_specs'], variation_sets, param_grids)):
        if variations.empty:
            maxdd_axes[0, col_idx].set_title(f"{param_spec['title']} - In-Sample Max Drawdown (no data)", fontsize=12, fontweight='bold')
            continue
        plot_maxdd_values(
            maxdd_axes[0, col_idx], variations, param_spec, base_params,
            f"{param_spec['title']} - In-Sample Max Drawdown", 'is_maxdd', 'is_maxdd_delta', base_is_maxdd, grid_values
        )
        if has_valid_oos_sharpe:
            plot_maxdd_values(
                maxdd_axes[1, col_idx], variations, param_spec, base_params,
                f"{param_spec['title']} - Out-of-Sample Max Drawdown", 'oos_maxdd', 'oos_maxdd_delta', base_oos_maxdd, grid_values
            )

    plt.tight_layout()
    plt.show()

    print(f"\n📋 {spec['summary_title']}")
    print("=" * 80)

    ema_summary_data = []
    trades_summary_data = []
    volatility_summary_data = []
    maxdd_summary_data = []

    for param_spec, variations, grid_values in zip(spec['param_specs'], variation_sets, param_grids):
        if variations.empty:
            ema_summary_data.append({
                'Parameter': param_spec['name'],
                'IS Range': 'N/A',
                'IS Max Δ%': 'N/A',
                'OOS Range': 'N/A',
                'OOS Max Δ%': 'N/A',
                'Sensitivity': 'N/A',
            })
            trades_summary_data.append({
                'Parameter': param_spec['name'],
                'IS Trades': 'N/A',
                'IS Trades Max Δ%': 'N/A',
                'IS Trades Max Δ': 'N/A',
                'OOS Trades': 'N/A',
                'OOS Trades Max Δ%': 'N/A',
                'OOS Trades Max Δ': 'N/A',
                'Neighbor Trade Robustness': 'N/A',
            })
            volatility_summary_data.append({
                'Parameter': param_spec['name'],
                'IS Volatility': 'N/A',
                'IS Volatility Max Δ%': 'N/A',
                'OOS Volatility': 'N/A',
                'OOS Volatility Max Δ%': 'N/A',
                'Neighbor Volatility Robustness': 'N/A',
            })
            maxdd_summary_data.append({
                'Parameter': param_spec['name'],
                'IS Max Drawdown': 'N/A',
                'IS Max Drawdown Max Δ%': 'N/A',
                'OOS Max Drawdown': 'N/A',
                'OOS Max Drawdown Max Δ%': 'N/A',
                'Neighbor Max Drawdown Robustness': 'N/A',
            })
            continue

        param_col = param_spec['col']
        base_param = base_params[param_col]
        neighbor_rows = neighbor_variations(variations, param_col, base_param, grid_values)

        is_trades_max_delta = max_abs_finite(variations['is_trades_delta'])
        oos_trades_max_delta = max_abs_finite(variations['oos_trades_delta'])
        is_trades_max_count_delta = max_abs_finite(variations['is_trades_count_delta'])
        oos_trades_max_count_delta = max_abs_finite(variations['oos_trades_count_delta'])
        is_trades_neighbor_delta = max_abs_finite(neighbor_rows['is_trades_delta'])
        oos_trades_neighbor_delta = max_abs_finite(neighbor_rows['oos_trades_delta'])
        trade_neighbor_delta_values = [x for x in [is_trades_neighbor_delta, oos_trades_neighbor_delta] if not pd.isna(x)]
        max_trade_neighbor_delta = max(trade_neighbor_delta_values) if trade_neighbor_delta_values else np.nan
        is_volatility_max_delta = max_abs_finite(variations['is_volatility_delta'])
        oos_volatility_max_delta = max_abs_finite(variations['oos_volatility_delta'])
        is_volatility_neighbor_delta = max_abs_finite(neighbor_rows['is_volatility_delta'])
        oos_volatility_neighbor_delta = max_abs_finite(neighbor_rows['oos_volatility_delta'])
        volatility_neighbor_delta_values = [x for x in [is_volatility_neighbor_delta, oos_volatility_neighbor_delta] if not pd.isna(x)]
        max_volatility_neighbor_delta = max(volatility_neighbor_delta_values) if volatility_neighbor_delta_values else np.nan
        is_maxdd_max_delta = max_abs_finite(variations['is_maxdd_delta'])
        oos_maxdd_max_delta = max_abs_finite(variations['oos_maxdd_delta'])
        is_maxdd_neighbor_delta = max_abs_finite(neighbor_rows['is_maxdd_delta'])
        oos_maxdd_neighbor_delta = max_abs_finite(neighbor_rows['oos_maxdd_delta'])
        maxdd_neighbor_delta_values = [x for x in [is_maxdd_neighbor_delta, oos_maxdd_neighbor_delta] if not pd.isna(x)]
        max_maxdd_neighbor_delta = max(maxdd_neighbor_delta_values) if maxdd_neighbor_delta_values else np.nan

        ema_summary_data.append({
            'Parameter': param_spec['name'],
            'IS Range': f"{variations['is_sharpe'].min():.3f} - {variations['is_sharpe'].max():.3f}",
            'IS Max Δ%': f"{variations['is_sharpe_delta'].min():.1f}%",
            'OOS Range': f"{variations['oos_sharpe'].min():.3f} - {variations['oos_sharpe'].max():.3f}" if has_valid_oos_sharpe else 'N/A',
            'OOS Max Δ%': f"{variations['oos_sharpe_delta'].min():.1f}%" if has_valid_oos_sharpe and 'oos_sharpe_delta' in variations else 'N/A',
            'Sensitivity': '⚠️ HIGH' if abs(variations['is_sharpe_delta'].min()) > 40 else '✅ LOW'
        })
        trades_summary_data.append({
            'Parameter': param_spec['name'],
            'IS Trades': f"{variations['is_trades'].min():.0f} - {variations['is_trades'].max():.0f}",
            'IS Trades Max Δ%': f"{is_trades_max_delta:.1f}%" if not pd.isna(is_trades_max_delta) else 'N/A',
            'IS Trades Max Δ': f"{is_trades_max_count_delta:.0f}" if not pd.isna(is_trades_max_count_delta) else 'N/A',
            'OOS Trades': f"{variations['oos_trades'].min():.0f} - {variations['oos_trades'].max():.0f}",
            'OOS Trades Max Δ%': f"{oos_trades_max_delta:.1f}%" if not pd.isna(oos_trades_max_delta) else 'N/A',
            'OOS Trades Max Δ': f"{oos_trades_max_count_delta:.0f}" if not pd.isna(oos_trades_max_count_delta) else 'N/A',
            'Neighbor Trade Robustness': 'N/A' if pd.isna(max_trade_neighbor_delta) else ('⚠️ HIGH' if max_trade_neighbor_delta > 40 else '✅ LOW')
        })
        volatility_summary_data.append({
            'Parameter': param_spec['name'],
            'IS Volatility': f"{variations['is_volatility'].min():.2%} - {variations['is_volatility'].max():.2%}",
            'IS Volatility Max Δ%': f"{is_volatility_max_delta:.1f}%" if not pd.isna(is_volatility_max_delta) else 'N/A',
            'OOS Volatility': f"{variations['oos_volatility'].min():.2%} - {variations['oos_volatility'].max():.2%}",
            'OOS Volatility Max Δ%': f"{oos_volatility_max_delta:.1f}%" if not pd.isna(oos_volatility_max_delta) else 'N/A',
            'Neighbor Volatility Robustness': 'N/A' if pd.isna(max_volatility_neighbor_delta) else ('⚠️ HIGH' if max_volatility_neighbor_delta > 40 else '✅ LOW')
        })
        maxdd_summary_data.append({
            'Parameter': param_spec['name'],
            'IS Max Drawdown': f"{variations['is_maxdd'].min():.2%} - {variations['is_maxdd'].max():.2%}",
            'IS Max Drawdown Max Δ%': f"{is_maxdd_max_delta:.1f}%" if not pd.isna(is_maxdd_max_delta) else 'N/A',
            'OOS Max Drawdown': f"{variations['oos_maxdd'].min():.2%} - {variations['oos_maxdd'].max():.2%}",
            'OOS Max Drawdown Max Δ%': f"{oos_maxdd_max_delta:.1f}%" if not pd.isna(oos_maxdd_max_delta) else 'N/A',
            'Neighbor Max Drawdown Robustness': 'N/A' if pd.isna(max_maxdd_neighbor_delta) else ('⚠️ HIGH' if max_maxdd_neighbor_delta > 40 else '✅ LOW')
        })

    ema_summary_df = pd.DataFrame(ema_summary_data)
    print(ema_summary_df.to_string(index=False))

    print("\n\n")
    print("📋 TOTAL TRADES SENSITIVITY SUMMARY")
    print("=" * 80)
    trades_summary_df = pd.DataFrame(trades_summary_data)
    print(trades_summary_df.to_string(index=False))

    print("\n\n")
    print("📋 VOLATILITY SENSITIVITY SUMMARY")
    print("=" * 80)
    volatility_summary_df = pd.DataFrame(volatility_summary_data)
    print(volatility_summary_df.to_string(index=False))

    print("\n\n\n")
    print("📋 MAX DRAWDOWN SENSITIVITY SUMMARY")
    print("=" * 80)
    maxdd_summary_df = pd.DataFrame(maxdd_summary_data)
    print(maxdd_summary_df.to_string(index=False))

    print(f"\n✅ {indicator_name} sensitivity analysis complete! Green = Robust, Red = Fragile")


if 'results_df' not in globals() or results_df.empty:
    print("No results available for sensitivity analysis.")
elif not sensitivity_prerequisites_ok():
    pass
else:
    sensitivity_indicators = resolve_sensitivity_indicators()
    if not sensitivity_indicators:
        print("No indicators available for sensitivity analysis.")
    else:
        for indicator_name in sensitivity_indicators:
            try:
                run_indicator_sensitivity_analysis(indicator_name)
            except Exception as exc:
                print(f"❌ Sensitivity analysis failed for {indicator_name}: {exc}")

==========================================================================================
🔬 PARAMETER SENSITIVITY ANALYSIS - Triple EMA - Base: EMA(4,117,125)

🔄 Testing 49 parameter variations...

IS Sharpe: 0.928 | OOS Sharpe: 0.653

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:903: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:924: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:945: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:966: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

📋 EMA SENSITIVITY SUMMARY
================================================================================
Parameter      IS Range IS Max Δ%     OOS Range OOS Max Δ% Sensitivity
     EMA1 0.655 - 0.928    -29.4% 0.531 - 0.653     -18.7%       ✅ LOW
     EMA2 0.687 - 0.928    -26.0% 0.620 - 0.762      -5.1%       ✅ LOW
     EMA3 0.855 - 0.928     -7.9% 0.624 - 0.715      -4.6%       ✅ LOW



📋 TOTAL TRADES SENSITIVITY SUMMARY
================================================================================
Parameter IS Trades IS Trades Max Δ% IS Trades Max Δ OOS Trades OOS Trades Max Δ% OOS Trades Max Δ Neighbor Trade Robustness
     EMA1    7 - 15            53.3%               8     7 - 10             30.0%                3                     ✅ LOW
     EMA2   13 - 19            26.7%               4     9 - 12             20.0%                2                     ✅ LOW
     EMA3   15 - 17            13.3%               2    10 - 11             10.0%                1                     ✅ LOW



📋 VOLATILITY SENSITIVITY SUMMARY
================================================================================
Parameter   IS Volatility IS Volatility Max Δ%  OOS Volatility OOS Volatility Max Δ% Neighbor Volatility Robustness
     EMA1 41.67% - 44.02%                 5.7% 42.27% - 43.29%                  2.4%                          ✅ LOW
     EMA2 40.74% - 41.88%                 2.2% 41.68% - 42.82%                  1.4%                          ✅ LOW
     EMA3 41.21% - 41.67%                 1.1% 42.12% - 42.35%                  0.4%                          ✅ LOW




📋 MAX DRAWDOWN SENSITIVITY SUMMARY
================================================================================
Parameter   IS Max Drawdown IS Max Drawdown Max Δ%  OOS Max Drawdown OOS Max Drawdown Max Δ% Neighbor Max Drawdown Robustness
     EMA1 -50.20% - -35.78%                  40.3% -48.66% - -44.64%                    9.0%                            ✅ LOW
     EMA2 -44.17% - -35.78%                  23.5% -49.13% - -34.78%                   22.1%                            ✅ LOW
     EMA3 -36.70% - -35.78%                   2.6% -44.64% - -43.89%                    1.7%                            ✅ LOW

✅ Triple EMA sensitivity analysis complete! Green = Robust, Red = Fragile

==========================================================================================
🔬 PARAMETER SENSITIVITY ANALYSIS - MACD - Base: MACD(12,69,78)

🔄 Testing 72 parameter variations...

IS Sharpe: 0.724 | OOS Sharpe: 1.203

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:903: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:924: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:945: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:966: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

📋 MACD SENSITIVITY SUMMARY
================================================================================
  Parameter      IS Range IS Max Δ%     OOS Range OOS Max Δ% Sensitivity
  MACD Fast 0.382 - 0.724    -47.3% 0.822 - 1.203     -31.6%     ⚠️ HIGH
  MACD Slow 0.399 - 0.724    -45.0% 1.076 - 1.204     -10.5%     ⚠️ HIGH
MACD Signal 0.389 - 0.724    -46.3% 1.076 - 1.216     -10.5%     ⚠️ HIGH



📋 TOTAL TRADES SENSITIVITY SUMMARY
================================================================================
  Parameter IS Trades IS Trades Max Δ% IS Trades Max Δ OOS Trades OOS Trades Max Δ% OOS Trades Max Δ Neighbor Trade Robustness
  MACD Fast   12 - 17            21.4%               3      6 - 8             33.3%                2                     ✅ LOW
  MACD Slow   14 - 17            21.4%               3      6 - 8             33.3%                2                     ✅ LOW
MACD Signal   14 - 17            21.4%               3      6 - 8             33.3%                2                     ✅ LOW



📋 VOLATILITY SENSITIVITY SUMMARY
================================================================================
  Parameter   IS Volatility IS Volatility Max Δ%  OOS Volatility OOS Volatility Max Δ% Neighbor Volatility Robustness
  MACD Fast 41.25% - 43.69%                 3.9% 33.23% - 34.30%                  2.1%                          ✅ LOW
  MACD Slow 42.70% - 43.81%                 2.1% 33.62% - 34.35%                  1.2%                          ✅ LOW
MACD Signal 42.70% - 43.99%                 2.5% 33.58% - 34.31%                  1.1%                          ✅ LOW




📋 MAX DRAWDOWN SENSITIVITY SUMMARY
================================================================================
  Parameter   IS Max Drawdown IS Max Drawdown Max Δ%  OOS Max Drawdown OOS Max Drawdown Max Δ% Neighbor Max Drawdown Robustness
  MACD Fast -68.75% - -48.49%                  41.8% -36.15% - -26.19%                   22.6%                            ✅ LOW
  MACD Slow -61.31% - -48.49%                  26.4% -30.00% - -27.99%                    5.1%                            ✅ LOW
MACD Signal -63.09% - -48.49%                  30.1% -30.00% - -27.67%                    6.1%                            ✅ LOW

✅ MACD sensitivity analysis complete! Green = Robust, Red = Fragile

==========================================================================================
🔬 PARAMETER SENSITIVITY ANALYSIS - AROON - Base: AROON(21)

🔄 Testing 31 parameter variations...

IS Sharpe: 0.722 | OOS Sharpe: 0.986

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:903: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:924: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:945: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:966: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

📋 AROON SENSITIVITY SUMMARY
================================================================================
       Parameter      IS Range IS Max Δ%     OOS Range OOS Max Δ% Sensitivity
AROON Timeperiod 0.072 - 0.796    -90.0% 0.454 - 1.171     -53.9%     ⚠️ HIGH



📋 TOTAL TRADES SENSITIVITY SUMMARY
================================================================================
       Parameter IS Trades IS Trades Max Δ% IS Trades Max Δ OOS Trades OOS Trades Max Δ% OOS Trades Max Δ Neighbor Trade Robustness
AROON Timeperiod   16 - 81           252.2%              58     8 - 54            217.6%               37                     ✅ LOW



📋 VOLATILITY SENSITIVITY SUMMARY
================================================================================
       Parameter   IS Volatility IS Volatility Max Δ%  OOS Volatility OOS Volatility Max Δ% Neighbor Volatility Robustness
AROON Timeperiod 39.37% - 45.26%                 9.9% 33.84% - 37.91%                 10.4%                          ✅ LOW




📋 MAX DRAWDOWN SENSITIVITY SUMMARY
================================================================================
       Parameter   IS Max Drawdown IS Max Drawdown Max Δ%  OOS Max Drawdown OOS Max Drawdown Max Δ% Neighbor Max Drawdown Robustness
AROON Timeperiod -75.19% - -45.23%                  44.2% -58.77% - -25.15%                   81.9%                            ✅ LOW

✅ AROON sensitivity analysis complete! Green = Robust, Red = Fragile

==========================================================================================
🔬 PARAMETER SENSITIVITY ANALYSIS - STC - Base: STC(38,99,23)

🔄 Testing 60 parameter variations...

IS Sharpe: 0.964 | OOS Sharpe: 1.293

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:903: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:924: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:945: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:966: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

📋 STC SENSITIVITY SUMMARY
================================================================================
    Parameter      IS Range IS Max Δ%     OOS Range OOS Max Δ% Sensitivity
STC EMA Short 0.332 - 0.964    -65.6% 1.005 - 1.380     -22.3%     ⚠️ HIGH
 STC EMA Long 0.744 - 0.964    -22.9% 1.174 - 1.293      -9.3%       ✅ LOW
    STC Cycle 0.183 - 0.964    -81.1% 0.878 - 1.303     -32.1%     ⚠️ HIGH



📋 TOTAL TRADES SENSITIVITY SUMMARY
================================================================================
    Parameter IS Trades IS Trades Max Δ% IS Trades Max Δ OOS Trades OOS Trades Max Δ% OOS Trades Max Δ Neighbor Trade Robustness
STC EMA Short   15 - 21            23.5%               4     7 - 15             50.0%                5                     ✅ LOW
 STC EMA Long   17 - 19            11.8%               2     9 - 10             10.0%                1                     ✅ LOW
    STC Cycle   12 - 22            29.4%               5     7 - 13             30.0%                3                     ✅ LOW



📋 VOLATILITY SENSITIVITY SUMMARY
================================================================================
    Parameter   IS Volatility IS Volatility Max Δ%  OOS Volatility OOS Volatility Max Δ% Neighbor Volatility Robustness
STC EMA Short 42.79% - 46.34%                 6.5% 33.27% - 34.46%                  1.9%                          ✅ LOW
 STC EMA Long 43.53% - 44.05%                 1.2% 33.93% - 34.52%                  1.8%                          ✅ LOW
    STC Cycle 43.53% - 45.82%                 5.3% 32.77% - 36.45%                  7.4%                          ✅ LOW




📋 MAX DRAWDOWN SENSITIVITY SUMMARY
================================================================================
    Parameter   IS Max Drawdown IS Max Drawdown Max Δ%  OOS Max Drawdown OOS Max Drawdown Max Δ% Neighbor Max Drawdown Robustness
STC EMA Short -59.77% - -41.62%                  43.6% -34.79% - -25.24%                   24.3%                            ✅ LOW
 STC EMA Long -42.32% - -41.62%                   1.7% -27.99% - -25.24%                    9.8%                            ✅ LOW
    STC Cycle -80.56% - -41.62%                  93.6% -40.23% - -25.51%                   43.7%                            ✅ LOW

✅ STC sensitivity analysis complete! Green = Robust, Red = Fragile

==========================================================================================
🔬 PARAMETER SENSITIVITY ANALYSIS - KAMA - Base: KAMA(10,7,99)

🔄 Testing 40 parameter variations...

IS Sharpe: 0.807 | OOS Sharpe: 0.964

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:903: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:924: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:945: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:966: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

📋 KAMA SENSITIVITY SUMMARY
================================================================================
    Parameter       IS Range IS Max Δ%     OOS Range OOS Max Δ% Sensitivity
  KAMA Period  0.264 - 0.807    -67.3% 0.583 - 0.964     -39.6%     ⚠️ HIGH
KAMA Fast EMA -0.075 - 0.807   -109.3% 0.618 - 1.122     -35.9%     ⚠️ HIGH
KAMA Slow EMA  0.696 - 0.807    -13.7% 0.918 - 0.965      -4.8%       ✅ LOW



📋 TOTAL TRADES SENSITIVITY SUMMARY
================================================================================
    Parameter IS Trades IS Trades Max Δ% IS Trades Max Δ OOS Trades OOS Trades Max Δ% OOS Trades Max Δ Neighbor Trade Robustness
  KAMA Period   22 - 41            51.9%              14    10 - 20             33.3%                5                   ⚠️ HIGH
KAMA Fast EMA   23 - 80           196.3%              53     1 - 58            286.7%               43                     ✅ LOW
KAMA Slow EMA   27 - 29             7.4%               2    15 - 18             20.0%                3                     ✅ LOW



📋 VOLATILITY SENSITIVITY SUMMARY
================================================================================
    Parameter   IS Volatility IS Volatility Max Δ%  OOS Volatility OOS Volatility Max Δ% Neighbor Volatility Robustness
  KAMA Period 39.59% - 46.78%                12.0% 40.30% - 50.11%                 16.9%                          ✅ LOW
KAMA Fast EMA 35.99% - 53.39%                27.8% 32.81% - 46.86%                 23.5%                          ✅ LOW
KAMA Slow EMA 41.19% - 41.78%                 1.4% 42.82% - 43.36%                  1.1%                          ✅ LOW




📋 MAX DRAWDOWN SENSITIVITY SUMMARY
================================================================================
    Parameter   IS Max Drawdown IS Max Drawdown Max Δ%  OOS Max Drawdown OOS Max Drawdown Max Δ% Neighbor Max Drawdown Robustness
  KAMA Period -53.18% - -41.34%                  28.7% -43.72% - -33.38%                   23.8%                            ✅ LOW
KAMA Fast EMA -79.97% - -36.81%                  93.5% -43.62% - -29.89%                   23.5%                            ✅ LOW
KAMA Slow EMA -41.34% - -41.34%                   0.0% -35.49% - -35.32%                    0.5%                            ✅ LOW

✅ KAMA sensitivity analysis complete! Green = Robust, Red = Fragile

==========================================================================================
🔬 PARAMETER SENSITIVITY ANALYSIS - SUPERTREND - Base: SUPERTREND(ATR=89,Factor=3)

🔄 Testing 48 parameter variations...

IS Sharpe: 0.808 | OOS Sharpe: 1.064

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:903: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:924: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:945: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:966: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

📋 SUPERTREND SENSITIVITY SUMMARY
================================================================================
            Parameter       IS Range IS Max Δ%      OOS Range OOS Max Δ% Sensitivity
SUPERTREND ATR Length  0.653 - 0.852    -19.2%  0.988 - 1.176      -7.1%       ✅ LOW
    SUPERTREND Factor -0.053 - 0.808   -106.5% -0.241 - 1.081    -122.6%     ⚠️ HIGH



📋 TOTAL TRADES SENSITIVITY SUMMARY
================================================================================
            Parameter IS Trades IS Trades Max Δ% IS Trades Max Δ OOS Trades OOS Trades Max Δ% OOS Trades Max Δ Neighbor Trade Robustness
SUPERTREND ATR Length   22 - 24             4.3%               1    14 - 15              7.1%                1                     ✅ LOW
    SUPERTREND Factor    1 - 82           256.5%              59     1 - 59            321.4%               45                   ⚠️ HIGH



📋 VOLATILITY SENSITIVITY SUMMARY
================================================================================
            Parameter   IS Volatility IS Volatility Max Δ%  OOS Volatility OOS Volatility Max Δ% Neighbor Volatility Robustness
SUPERTREND ATR Length 42.49% - 44.35%                 2.9% 35.04% - 36.70%                  4.1%                          ✅ LOW
    SUPERTREND Factor 35.02% - 48.86%                20.0% 29.50% - 41.23%                 16.9%                          ✅ LOW




📋 MAX DRAWDOWN SENSITIVITY SUMMARY
================================================================================
            Parameter   IS Max Drawdown IS Max Drawdown Max Δ%  OOS Max Drawdown OOS Max Drawdown Max Δ% Neighbor Max Drawdown Robustness
SUPERTREND ATR Length -56.75% - -49.56%                  14.5% -33.13% - -26.28%                   26.1%                            ✅ LOW
    SUPERTREND Factor -85.76% - -36.02%                  73.0% -65.65% - -26.28%                  149.8%                          ⚠️ HIGH

✅ SUPERTREND sensitivity analysis complete! Green = Robust, Red = Fragile

==========================================================================================
🔬 PARAMETER SENSITIVITY ANALYSIS - KALMAN - Base: KALMAN(Q=1,R=159)

🔄 Testing 19 parameter variations...

IS Sharpe: 0.851 | OOS Sharpe: 1.315

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:903: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:924: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:945: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:966: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

📋 KALMAN SENSITIVITY SUMMARY
================================================================================
                 Parameter      IS Range IS Max Δ%     OOS Range OOS Max Δ% Sensitivity
    KALMAN Process Noise Q 0.438 - 0.851    -48.5% 1.044 - 1.315     -20.6%     ⚠️ HIGH
KALMAN Measurement Noise R 0.704 - 0.851    -17.2% 1.314 - 1.324      -0.0%       ✅ LOW



📋 TOTAL TRADES SENSITIVITY SUMMARY
================================================================================
                 Parameter IS Trades IS Trades Max Δ% IS Trades Max Δ OOS Trades OOS Trades Max Δ% OOS Trades Max Δ Neighbor Trade Robustness
    KALMAN Process Noise Q   57 - 91            59.6%              34    48 - 72             50.0%               24                     ✅ LOW
KALMAN Measurement Noise R   57 - 61             7.0%               4    48 - 48              0.0%                0                     ✅ LOW



📋 VOLATILITY SENSITIVITY SUMMARY
================================================================================
                 Parameter   IS Volatility IS Volatility Max Δ%  OOS Volatility OOS Volatility Max Δ% Neighbor Volatility Robustness
    KALMAN Process Noise Q 42.09% - 44.54%                 5.8% 38.39% - 39.16%                  2.0%                          ✅ LOW
KALMAN Measurement Noise R 41.92% - 42.09%                 0.4% 39.16% - 39.16%                  0.0%                          ✅ LOW




📋 MAX DRAWDOWN SENSITIVITY SUMMARY
================================================================================
                 Parameter   IS Max Drawdown IS Max Drawdown Max Δ%  OOS Max Drawdown OOS Max Drawdown Max Δ% Neighbor Max Drawdown Robustness
    KALMAN Process Noise Q -75.00% - -47.60%                  57.6% -34.73% - -33.25%                    4.2%                          ⚠️ HIGH
KALMAN Measurement Noise R -51.06% - -47.60%                   7.3% -34.73% - -34.73%                    0.0%                            ✅ LOW

✅ KALMAN sensitivity analysis complete! Green = Robust, Red = Fragile

==========================================================================================
🔬 PARAMETER SENSITIVITY ANALYSIS - RSI - Base: RSI(73)

🔄 Testing 22 parameter variations...

IS Sharpe: 0.779 | OOS Sharpe: 0.855

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:903: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:924: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:945: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:966: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

📋 RSI SENSITIVITY SUMMARY
================================================================================
     Parameter      IS Range IS Max Δ%     OOS Range OOS Max Δ% Sensitivity
RSI Timeperiod 0.541 - 0.781    -30.5% 0.741 - 0.985     -13.4%       ✅ LOW



📋 TOTAL TRADES SENSITIVITY SUMMARY
================================================================================
     Parameter IS Trades IS Trades Max Δ% IS Trades Max Δ OOS Trades OOS Trades Max Δ% OOS Trades Max Δ Neighbor Trade Robustness
RSI Timeperiod   24 - 35            20.7%               6    12 - 20             53.8%                7                     ✅ LOW



📋 VOLATILITY SENSITIVITY SUMMARY
================================================================================
     Parameter   IS Volatility IS Volatility Max Δ%  OOS Volatility OOS Volatility Max Δ% Neighbor Volatility Robustness
RSI Timeperiod 42.05% - 43.61%                 2.6% 41.12% - 43.38%                  4.3%                          ✅ LOW




📋 MAX DRAWDOWN SENSITIVITY SUMMARY
================================================================================
     Parameter   IS Max Drawdown IS Max Drawdown Max Δ%  OOS Max Drawdown OOS Max Drawdown Max Δ% Neighbor Max Drawdown Robustness
RSI Timeperiod -49.09% - -40.62%                  16.7% -39.73% - -30.00%                   24.5%                            ✅ LOW

✅ RSI sensitivity analysis complete! Green = Robust, Red = Fragile

==========================================================================================
🔬 PARAMETER SENSITIVITY ANALYSIS - ADX - Base: ADX(DI=21,Smooth=31)

🔄 Testing 57 parameter variations...

IS Sharpe: 1.170 | OOS Sharpe: 0.971

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:903: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:924: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:945: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:966: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

📋 ADX SENSITIVITY SUMMARY
================================================================================
    Parameter       IS Range IS Max Δ%     OOS Range OOS Max Δ% Sensitivity
ADX DI Length -0.596 - 1.170   -151.0% 0.671 - 1.412     -30.9%     ⚠️ HIGH
ADX Smoothing  0.346 - 1.170    -70.4% 0.705 - 1.205     -27.4%     ⚠️ HIGH



📋 TOTAL TRADES SENSITIVITY SUMMARY
================================================================================
    Parameter IS Trades IS Trades Max Δ% IS Trades Max Δ OOS Trades OOS Trades Max Δ% OOS Trades Max Δ Neighbor Trade Robustness
ADX DI Length    0 - 90           650.0%              78     1 - 61            577.8%               52                     ✅ LOW
ADX Smoothing    9 - 13            25.0%               3     7 - 10             22.2%                2                     ✅ LOW



📋 VOLATILITY SENSITIVITY SUMMARY
================================================================================
    Parameter   IS Volatility IS Volatility Max Δ%  OOS Volatility OOS Volatility Max Δ% Neighbor Volatility Robustness
ADX DI Length  0.00% - 45.10%               100.0% 25.15% - 56.71%                100.1%                          ✅ LOW
ADX Smoothing 22.28% - 42.69%                47.8% 25.18% - 45.27%                 59.7%                          ✅ LOW




📋 MAX DRAWDOWN SENSITIVITY SUMMARY
================================================================================
    Parameter   IS Max Drawdown IS Max Drawdown Max Δ%  OOS Max Drawdown OOS Max Drawdown Max Δ% Neighbor Max Drawdown Robustness
ADX DI Length   -65.73% - 0.00%                 100.0% -65.87% - -23.11%                   65.6%                          ⚠️ HIGH
ADX Smoothing -61.27% - -40.89%                  49.9% -58.04% - -23.11%                   45.9%                            ✅ LOW

✅ ADX sensitivity analysis complete! Green = Robust, Red = Fragile

==========================================================================================
🔬 PARAMETER SENSITIVITY ANALYSIS - DONCHIAN - Base: DONCHIAN(24)

🔄 Testing 30 parameter variations...

IS Sharpe: 0.488 | OOS Sharpe: 1.002

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:903: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:924: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:945: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:966: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

📋 DONCHIAN SENSITIVITY SUMMARY
================================================================================
          Parameter      IS Range IS Max Δ%     OOS Range OOS Max Δ% Sensitivity
DONCHIAN Timeperiod 0.133 - 0.602    -72.7% 0.616 - 1.378     -38.6%     ⚠️ HIGH



📋 TOTAL TRADES SENSITIVITY SUMMARY
================================================================================
          Parameter IS Trades IS Trades Max Δ% IS Trades Max Δ OOS Trades OOS Trades Max Δ% OOS Trades Max Δ Neighbor Trade Robustness
DONCHIAN Timeperiod   15 - 49           133.3%              28     9 - 32            128.6%               18                     ✅ LOW



📋 VOLATILITY SENSITIVITY SUMMARY
================================================================================
          Parameter   IS Volatility IS Volatility Max Δ%  OOS Volatility OOS Volatility Max Δ% Neighbor Volatility Robustness
DONCHIAN Timeperiod 32.49% - 36.89%                 9.9% 29.52% - 32.91%                  9.6%                          ✅ LOW




📋 MAX DRAWDOWN SENSITIVITY SUMMARY
================================================================================
          Parameter   IS Max Drawdown IS Max Drawdown Max Δ%  OOS Max Drawdown OOS Max Drawdown Max Δ% Neighbor Max Drawdown Robustness
DONCHIAN Timeperiod -63.15% - -32.46%                  56.2% -49.57% - -22.44%                   40.4%                            ✅ LOW

✅ DONCHIAN sensitivity analysis complete! Green = Robust, Red = Fragile

==========================================================================================
🔬 PARAMETER SENSITIVITY ANALYSIS - TRIX - Base: TRIX(7)

🔄 Testing 19 parameter variations...

IS Sharpe: 0.711 | OOS Sharpe: 1.169

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:903: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:924: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:945: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:966: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

📋 TRIX SENSITIVITY SUMMARY
================================================================================
      Parameter      IS Range IS Max Δ%     OOS Range OOS Max Δ% Sensitivity
TRIX Timeperiod 0.188 - 0.769    -73.5% 0.444 - 1.169     -62.0%     ⚠️ HIGH



📋 TOTAL TRADES SENSITIVITY SUMMARY
================================================================================
      Parameter IS Trades IS Trades Max Δ% IS Trades Max Δ OOS Trades OOS Trades Max Δ% OOS Trades Max Δ Neighbor Trade Robustness
TRIX Timeperiod   11 - 54           116.0%              29     5 - 42            100.0%               21                     ✅ LOW



📋 VOLATILITY SENSITIVITY SUMMARY
================================================================================
      Parameter   IS Volatility IS Volatility Max Δ%  OOS Volatility OOS Volatility Max Δ% Neighbor Volatility Robustness
TRIX Timeperiod 43.43% - 48.36%                10.4% 36.75% - 40.94%                  6.7%                          ✅ LOW




📋 MAX DRAWDOWN SENSITIVITY SUMMARY
================================================================================
      Parameter   IS Max Drawdown IS Max Drawdown Max Δ%  OOS Max Drawdown OOS Max Drawdown Max Δ% Neighbor Max Drawdown Robustness
TRIX Timeperiod -67.50% - -49.68%                  20.9% -44.29% - -29.88%                   23.1%                            ✅ LOW

✅ TRIX sensitivity analysis complete! Green = Robust, Red = Fragile

==========================================================================================
🔬 PARAMETER SENSITIVITY ANALYSIS - VORTEX - Base: VORTEX(115)

🔄 Testing 31 parameter variations...

IS Sharpe: 0.586 | OOS Sharpe: 0.593

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:903: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:924: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:945: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:966: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

📋 VORTEX SENSITIVITY SUMMARY
================================================================================
        Parameter      IS Range IS Max Δ%     OOS Range OOS Max Δ% Sensitivity
VORTEX Timeperiod 0.328 - 0.654    -44.0% 0.136 - 0.909     -77.1%     ⚠️ HIGH



📋 TOTAL TRADES SENSITIVITY SUMMARY
================================================================================
        Parameter IS Trades IS Trades Max Δ% IS Trades Max Δ OOS Trades OOS Trades Max Δ% OOS Trades Max Δ Neighbor Trade Robustness
VORTEX Timeperiod    6 - 23            91.7%              11     7 - 15             36.4%                4                     ✅ LOW



📋 VOLATILITY SENSITIVITY SUMMARY
================================================================================
        Parameter   IS Volatility IS Volatility Max Δ%  OOS Volatility OOS Volatility Max Δ% Neighbor Volatility Robustness
VORTEX Timeperiod 45.39% - 48.97%                 3.9% 35.44% - 43.30%                 17.6%                          ✅ LOW




📋 MAX DRAWDOWN SENSITIVITY SUMMARY
================================================================================
        Parameter   IS Max Drawdown IS Max Drawdown Max Δ%  OOS Max Drawdown OOS Max Drawdown Max Δ% Neighbor Max Drawdown Robustness
VORTEX Timeperiod -66.83% - -62.09%                   7.6% -50.56% - -33.64%                   37.1%                            ✅ LOW

✅ VORTEX sensitivity analysis complete! Green = Robust, Red = Fragile

==========================================================================================
🔬 PARAMETER SENSITIVITY ANALYSIS - ALMA - Base: ALMA(fast=2,slow=99,offset=0.10,sigma=3)

🔄 Testing 35 parameter variations...

IS Sharpe: 0.786 | OOS Sharpe: 0.665

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:903: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:924: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

📋 ALMA SENSITIVITY SUMMARY
================================================================================
       Parameter      IS Range IS Max Δ%     OOS Range OOS Max Δ% Sensitivity
ALMA Fast Length 0.192 - 0.786    -75.6% 0.607 - 0.771      -8.8%     ⚠️ HIGH
ALMA Slow Length 0.162 - 0.786    -79.4% 0.381 - 0.665     -42.8%     ⚠️ HIGH
     ALMA Offset 0.618 - 0.786    -21.4% 0.601 - 0.687      -9.6%       ✅ LOW



📋 TOTAL TRADES SENSITIVITY SUMMARY
================================================================================
       Parameter IS Trades IS Trades Max Δ% IS Trades Max Δ OOS Trades OOS Trades Max Δ% OOS Trades Max Δ Neighbor Trade Robustness
ALMA Fast Length    8 - 13            38.5%               5     6 - 10             40.0%                4                     ✅ LOW
ALMA Slow Length   12 - 23            76.9%              10    10 - 14             40.0%                4                     ✅ LOW
     ALMA Offset   13 - 17            30.8%               4    10 - 11             10.0%                1                     ✅ LOW



📋 VOLATILITY SENSITIVITY SUMMARY
================================================================================
       Parameter   IS Volatility IS Volatility Max Δ%  OOS Volatility OOS Volatility Max Δ% Neighbor Volatility Robustness
ALMA Fast Length 43.81% - 53.67%                22.5% 41.87% - 43.65%                  4.3%                          ✅ LOW
ALMA Slow Length 43.78% - 45.15%                 3.0% 40.47% - 41.87%                  3.4%                          ✅ LOW
     ALMA Offset 43.07% - 43.89%                 1.7% 41.58% - 41.87%                  0.7%                          ✅ LOW




📋 MAX DRAWDOWN SENSITIVITY SUMMARY
================================================================================
       Parameter   IS Max Drawdown IS Max Drawdown Max Δ%  OOS Max Drawdown OOS Max Drawdown Max Δ% Neighbor Max Drawdown Robustness
ALMA Fast Length -73.15% - -48.14%                  52.0% -48.78% - -37.37%                   13.3%                            ✅ LOW
ALMA Slow Length -52.96% - -42.86%                  11.0% -46.13% - -42.34%                    7.0%                            ✅ LOW
     ALMA Offset -48.14% - -42.86%                  11.0% -43.64% - -42.34%                    1.8%                            ✅ LOW

✅ ALMA sensitivity analysis complete! Green = Robust, Red = Fragile

C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:945: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\j_jon\AppData\Local\Temp\ipykernel_11484\3376849503.py:966: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()